### ISSUE TITLE
Mismatch in theme directories between rofi and rofi-theme-selector

### ISSUE THREAD

**Issue by hnefatl** [davatorium/rofi#1000]
##  Version

1.5.2 (but present in the current master head)

## Configuration

https://gist.github.com/hnefatl/684490247a6c9c175cbdb55d10f86334

## Launch Command

`rofi -theme $foo -show run` (anything with `-theme`).

## Steps to reproduce

* Run `rofi-theme-selector`, note that it prints "Checking themes in: /home/foo/.config/**rofi/themes**" and that `test` is an available theme.
* Put a simple theme in `$XDG_CONFIG_DIR/rofi/themes/`, eg:
  `echo "#window { fullscreen: true; }' > ~/.config/rofi/themes/test.rasi`
* Run `rofi -theme test.rasi -show run`, 

## What behaviour you see

* `rofi` displays "failed to open theme: /home/foo/test.rasi".

## What behaviour you expect to see

* `rofi` to open normally, using the given theme.

## Description

`rofi-theme-selector` reads themes from `$XDG_CONFIG_DIR/rofi/themes` ([source](https://github.com/davatorium/rofi/blob/eece00bad67ad64ee33f8490fd56adc585dc484b/script/rofi-theme-selector#L75)), but `rofi` only checks `$XDG_CONFIG_DIR/rofi` ([source](https://github.com/davatorium/rofi/blob/eece00bad67ad64ee33f8490fd56adc585dc484b/source/helper.c#L1041)).

**Comment by DaveDavenport** [comment]
thanks.
