### ISSUE TITLE
Run commands with gnome-terminal

### ISSUE THREAD

**Issue by Kabouik** [davatorium/rofi#1003]
## Version

Version: 1.5.3

## Configuration

[Output of `rofi -help`](https://gist.github.com/Kabouik/879d7c18eda4afad87365f7aefce3066)

## Launch Command

`rofi -show run -font "Fira Code 9" -theme-str '#window {width: 20%; height: 40%; anchor: southwest; location: southwest;}'`

## Steps to reproduce

- Try to run a command (*e.g.*, `cal`) with `rofi` and `gnome-terminal` using the default configuration and hit `Shift+Return` to run it in a new terminal.

## What behaviour you see

- The new terminal will only show up for a fraction of a second, likely because of an issue with `gnome-terminal`.

## What behaviour you expect to see

- A new terminal should open and show the output of the command.

## Solution

- Mimicking `rofi`'s behavior directly in terminal by running `gnome-terminal -e cal` will allow checking what the error is:

```bash
mathieu@solus-desktop ~ $ gnome-terminal -e cal
# Option “-e” is deprecated and might be removed in a later version of gnome-terminal.
# Use “-- ” to terminate the options and put the command line to execute after it.
# _g_io_module_get_default: Found default implementation gvfs (GDaemonVfs) for ‘gio-vfs’
# _g_io_module_get_default: Found default implementation dconf (DConfSettingsBackend) for ‘gsettings-backend’
# watch_fast: "/org/gnome/terminal/legacy/" (establishing: 0, active: 0)
# unwatch_fast: "/org/gnome/terminal/legacy/" (active: 0, establishing: 1)
# watch_established: "/org/gnome/terminal/legacy/" (establishing: 0)
```

Customizing `rofi`'s config file to add `rofi.run-shell-command:	{terminal} -- bash -c "{cmd}; bash"` solves the issue. Note that I used `--` instead of `-e` as argument for `gnome-terminal`, because the latter is deprecated.

This is definitely caused by `gnome-terminal`, but maybe the default `rofi` configuration should take that into account when running on a system with `gnome-terminal` because this will probably not change and the default `{terminal} -e {cmd}` will never work with `gnome-terminal`.

**Comment by DaveDavenport** [comment]
I won't add terminal specific hacks into rofi. Problem is that there are to many.
You can fix it by updating rofi his config.

if gnome-terminal  is no longer compatible it should be taken out of rofi-sensible-terminal.

**Comment by Kabouik** [comment]
Not adding hacks for every terminal sounds reasonable. I wanted at least to give details about the issue so that the solution for `rofi` is written somewhere and can be found with a search.

**Comment by DaveDavenport** [comment]
Thanks for reporting and the info!. Should make a wiki page out of it.
