### ISSUE TITLE
Missing support for legacy configurations. Are the updates that break configurations necessary?

### ISSUE THREAD

**Issue by da-edra** [davatorium/rofi#1004]
## Version

Output of `rofi -v`
Version: 1.5.4

## Configuration

Output of `rofi -help` (in a [gist](https://gist.github.com/da-edra/e9bfe3dbba0594ed4d75d682496668ac))

## Launch Command

The commandline used to launch **rofi**
rofi -show drun

## Steps to reproduce

* Step 1: Spend some time updating your previously working but now broken configuration to the new way Rofi wants things.
* Step 2: Enjoy a working configuration for a couple of days.
* Step 3: Update Rofi, realize everything is broke *again* and you have to spend more time to update your previously working config *again*
* Step 4: Update again, go back to step 1.

## What behaviour you see

* - It's pretty frequent for Rofi to have updates that break my previous configuration because some things are now named different and some small things changed and have to be done a different way.

## What behaviour you expect to see

* - For Rofi to be able to work with a configuration that was working before the update so we don't have to spend a lot of time updating our confiurations so often, or a commnd to update my previous configuration to the new schema.

**Comment by DaveDavenport** [comment]
what broke?  there has been one small break in the last few release (sidebar to mode-switcher)

**Comment by DaveDavenport** [comment]
I find this a very frustrating bug report.. There are *no* examples what so ever given. It is a rant.

Frustrating me more is that I do try to take care not to break things, if you look at the code base, you will see a decent amount of code in there that is purely there to convert old config formats to new one and to allow old config options still behave next to the new improved ones.
This actually takes effort to keep.

Some config breakage is unavoidable, a lot of features are added/improved (on request) or old 'experimental code becomes stable and needs cleaning. These are mentioned in the release notes.  If you don't care about these.  Don't update.

**Comment by da-edra** [comment]
Sorry if it was seen as a rant, it was not my intention.
