### ISSUE TITLE
Tiny Icons on HiDPI

### ISSUE THREAD

**Issue by BilLOPGVkPPn8z0JGJhgiAGNo9YAqpk5ruChl0F** [davatorium/rofi#1005]
:exclamation:
First read the [guidelines](https://github.com/DaveDavenport/rofi/blob/next/.github/CONTRIBUTING.md)!
This is not optional for any report/question. People must be able to understand the full context of the report when reading it, at any time.
If you feel like you “just have a simple question”, please consider you’re wrong and still fill the full report.
Any report missing these informations will be labeled as “Incomplete Report - Please follow the guidelines” and may not be answered in a timely fashion.
:exclamation:

## Version
`Version: 1.5.4-13-g85279323 (makepkg)`

## Configuration
https://gist.github.com/BilLOPGVkPPn8z0JGJhgiAGNo9YAqpk5ruChl0F/af1a3ee7945ae4f46a470d8c95b0ca79

## Launch Command
`rofi -show drun`

## Steps to reproduce

* `rofi -show drun`

## What behaviour you see

* tiny icons

## What behaviour you expect to see

* normal sized icons

I have a hidpi display and had no issues with the icon size until updating a month ago. I do not know exactly at which version this change ocurred.

**Comment by DaveDavenport** [comment]
Thanks this indeed changed and this was not taken into account.

**Comment by DaveDavenport** [comment]
On latest git can you try running rofi with this extra commandline argument and see if that helps?
```
 -theme-str 'element-icon { size: 1.2ch;}'
``

**Comment by BilLOPGVkPPn8z0JGJhgiAGNo9YAqpk5ruChl0F** [comment]
Yeah that fixes it.

**Comment by DaveDavenport** [comment]
I will add the fix.

**Comment by DaveDavenport** [comment]
fix should be in.
