### ISSUE TITLE
Disable cursor blinking

### ISSUE THREAD

**Issue by astier** [davatorium/rofi#1006]
## Version

1.5.4

## Configuration

https://gist.github.com/astier/fa5016ccf21982060b85d26295394885

## Launch Command

`rofi -show run`

## Steps to reproduce

* Run `rofi -show run`

## What behaviour you see

* Cursor is blinking

## What behaviour you expect to see

* Cursor is not blinking. An option to disable cursor-blinking would be nice. My reason is just for aesthetics.

**Comment by DaveDavenport** [comment]
Cursor should be blinking.  it blinks for me. (1Hz).

**Comment by DaveDavenport** [comment]
Added theme option to disable blinking:
```
rofi -show run -theme-str 'entry {blink:false;}'
```

**Comment by georgeabr** [comment]
Can you add a full config example with cursor blink disabled?
And how to pass the config file to rofi?

**Comment by DaveDavenport** [comment]
I don't make a release for every feature request. You need to use git, or wait until a new release.

**Comment by georgeabr** [comment]
I used rofi-git in arch, with your command, and cursor blink was disabled.
Perhaps you could do another release in the next weeks. It would be much appreciated. Thanks.

**Comment by DaveDavenport** [comment]
no

**Comment by astier** [comment]
I guess his point was that he thought he is in fact using the git version because usually git-versions in the aur like the aur-package rofi-git are usually pretty much up to date with git.

**Comment by DaveDavenport** [comment]
I cannot say, I know nothing about archlinux.
