### ISSUE TITLE
rofi show many unknow applications that not exist in /usr/share/applications

### ISSUE THREAD

**Issue by lubocheng** [davatorium/rofi#1009]
## Version

Version: 1.3.1

## Configuration

https://gist.github.com/lubocheng/5fb77148993548cda52d1f7d3e44d68d

## Launch Command
run rofi in i3wm as below(my system is Deepin 15.11):
`bindsym $mod+d exec --no-startup-id "rofi -modi drun -show drun"`

## Steps to reproduce
just run as Launch Command
## What behaviour you see
i see many many unknow applications shown in rofi list, and can't know why
i tried to printscreen, but find that i can't get a screenshot because my `deepin-screenshot` app won't  run with rofi at the same time in i3wm :disappointed: 
## What behaviour you expect to see
just show applications list in /usr/share/applications

**Comment by sardemff7** [comment]
You can use the built-in screenshot feature, `Alt-Shift-S`, it will store the image in your (XDG) Pictures directory.

However, the `.desktop` file specification is about `/usr/share/applications` **and** the user counterpart `~/.local/share/applications` where stuff like Wine tends to put a loooot of files, I would recommend checking it for stuff you want to remove.

**Comment by lubocheng** [comment]
@sardemff7 many thanks, I am too stupid to find the unknow *.desktop are store in:
`/usr/share/applications/screensavers`
![rofi-2019-09-01-1535](https://user-images.githubusercontent.com/3746672/64073442-89486e00-ccd0-11e9-84b0-7cb0726b83d6.png)
![深度截图_选择区域_20190901154202](https://user-images.githubusercontent.com/3746672/64073446-936a6c80-ccd0-11e9-930b-3c1a33c5c4de.png)
