### ISSUE TITLE
rofi won't launch any application

### ISSUE THREAD

**Issue by Harmen9816** [davatorium/rofi#1011]
rofi version - 1.5.4-17-git-c3caa20d (next)

Anytime I try and open any application with rofi I get the error Failed to execute: 'application name' 
Error: 'Failed to execute child process
"application name" (File name too long)'
and if I launch rofi from my terminal like rofi -show run or rofi -show drun and try and open an application I get the 'error ** (process:15283): WARNING **: 10:52:40.711: Failed to open file: No such file or directory'

If I try and open an application with dmenu or just straight from my terminal that works perfectly fine it's just rofi wont open anything.

**Comment by DaveDavenport** [comment]
That error is thrown by glib function `g_spawn_async`.
Can you provide more information (see guidelines), to see if we can debug this?

**Comment by Harmen9816** [comment]
I don't know how to reproduce this error rofi went from working perfectly fine to not wanting to open anything I didn't change anything I even tried completely removing rofi and then reinstalling it.

Here is my rofi config in my Xresources I don't think it will help but here you go.
!! rofi

!! Enable extended coloring
rofi.color-enabled:   true

!! Settings
rofi.dpi:             96
rofi.modi:            run,drun,window
rofi.font:            Tamzen 10
rofi.width:           20
rofi.lines:           4

rofi.separator-style: solid
rofi.hide-scrollbar:  true
rofi.matching:        fuzzy
rofi.bw:              1
rofi.padding:         15
rofi.line-margin:     6

!!                    bg       bd       sp
rofi.color-window:    #1d1f21, #1d1f21, #1d1f21

!!                    bg       fg       bg-2     hl-bg    hl-fg
rofi.color-normal:    #1d1f21, #c5c8c6, #1d1f21, #373b41, #c5c8c6
rofi.color-active:    #1d1f21, #c5c8c6, #1d1f21, #373b41, #c5c8c6
rofi.color-urgent:    #1d1f21, #cc6666, #1d1f21, #373b41, #cc6666

**Comment by DaveDavenport** [comment]
What distribution?

**Comment by DaveDavenport** [comment]
can you also paste your environment?

**Comment by Harmen9816** [comment]
Kali 2019.3
Kernel 5.2.0-kali2-amd64

CAML_LD_LIBRARY_PATH=/home/ajhp99/.opam/default/lib/stublibs:Updated by package ocaml
COLORTERM=truecolor
DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
DESKTOP_SESSION=bspwm
DISPLAY=:0
EDITOR=vim
GDMSESSION=bspwm
GPG_AGENT_INFO=/run/user/1000/gnupg/S.gpg-agent:0:1
HOME=/home/ajhp99
LANG=en_US.utf8
LC_ALL=en_US.UTF-8
LOGNAME=ajhp99
LS_COLORS=
OCAML_TOPLEVEL_PATH=/home/ajhp99/.opam/default/lib/toplevel
OMF_CONFIG=/home/ajhp99/.config/omf
OMF_PATH=/home/ajhp99/.local/share/omf
OPAMNOENVNOTICE=true
OPAM_SWITCH_PREFIX=/home/ajhp99/.opam/default
PATH=/home/ajhp99/.local/bin/ /home/ajhp99/.local/bin/:/home/ajhp99/.local/bin/:/home/ajhp99/.opam/default/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
PWD=/home/ajhp99
QT_ACCESSIBILITY=1
SHELL=/usr/bin/fish
SHLVL=3
SPOTIFY_CLIENT_ID=1ca862700a944751b8b9aa3fd0902978
SPOTIFY_CLIENT_SECRET=17ac60b8363b4946afc8087b3a3cb51f
SSH_AGENT_PID=944
SSH_AUTH_SOCK=/tmp/ssh-91h3XTKwHEdJ/agent.911
TERM=xterm-256color
TILIX_ID=f0dcf89b-0735-42e2-89f5-0b82eaa86599
USER=ajhp99
VTE_VERSION=5002
XAUTHORITY=/home/ajhp99/.Xauthority
XDG_GREETER_DATA_DIR=/var/lib/lightdm/data/ajhp99
XDG_RUNTIME_DIR=/run/user/1000
XDG_SEAT=seat0
XDG_SEAT_PATH=/org/freedesktop/DisplayManager/Seat0
XDG_SESSION_CLASS=user
XDG_SESSION_DESKTOP=bspwm
XDG_SESSION_ID=2
XDG_SESSION_PATH=/org/freedesktop/DisplayManager/Session0
XDG_SESSION_TYPE=x11
XDG_VTNR=7
_JAVA_AWT_WM_NONREPARENTING=1
fish_user_paths=/home/ajhp99/.local/bin/

**Comment by Harmen9816** [comment]
Never mind I found out how to fix it, it has nothing to do with rofi I have to fix $PATH and it should be working again. Thank you for helping.

**Comment by DaveDavenport** [comment]
happy to hear it is all working again...
