### ISSUE TITLE
bitmap fonts displaying illegibly

### ISSUE THREAD

**Issue by leshow** [davatorium/rofi#1012]
## Version

Output of `rofi -v`
```
~ 1m 10s
❯ rofi -v
Version: 1.5.4
```

## Configuration

Output of `rofi -help` [here](https://gist.github.com/leshow/445cfc6987ef796ad40fa696556832e8)

## Launch Command

The commandline used to launch **rofi**

```rofi -modi drun -show drun```

## Steps to reproduce

Use any bitmap font (so far as I can tell)

and the display looks like this:
![rofi_fudged](https://user-images.githubusercontent.com/1128302/64303390-e43ec700-cf55-11e9-973c-9c67371f9ef6.png)

I used the exact same font for years. I had in my rofi config.

```
rofi.font:      Tamzen 11
```
(maybe 12 but I've tried multiple sizes and neither works).

fc-match confirms I have that font available:
```
❯ fc-match "Tamzen"
Tamzen6x12r.bdf: "Tamzen" "Regular"
```
I use arch, a few months ago all of a sudden I rebooted and rofi displayed like it does above whenever I launched it. After fiddling around I realized I could get it to work by using a non bitmap font, but any bitmap font I selected displayed like it does above. 

Is this some kind of regression in rofi? I was quite attached to my bitmap font.

**Comment by DaveDavenport** [comment]
The font rendering in rofi has not changed in the past years.
Can you see if another pango based tool (gedit is normally a good test) renders the font correctly?

**Comment by leshow** [comment]
I fired up gedit, but it can't find tamzen. There are other fonts in the list whos names I can't see that are rendering like the rofi image is though.

You're saying it's likely because of some pango update I pulled in?

**Comment by DaveDavenport** [comment]
Would be my guess.

**Comment by leshow** [comment]
This issue is indeed on the arch forums and is fairly common, I haven't found a good workaround yet. Others are using a ttf version of tamzen but it still renders very ugly when I use it. I'll close since this isn't a rofi issue

**Comment by DaveDavenport** [comment]
Thanks for letting me know.

**Comment by ksevelyar** [comment]
In case this will be helpful for someone:

You can use .otb bitmap fonts with new Pango. You can just put them to `~/.local/share/fonts`

![2020-05-12-21-52-46-region](https://user-images.githubusercontent.com/725959/81733606-f553b680-949a-11ea-83f5-e2cc4fa0eed4.png)
![2020-05-12-19-48-20](https://user-images.githubusercontent.com/725959/81733652-0ac8e080-949b-11ea-9ac5-0b538e290b84.png)

You can convert your fonts with FontForge.

**Comment by Saladaa** [comment]
Setting the font to a bitmap font, such as Cozette or Terminus (both OTB fonts), results in invisible characters on my system. I have tried various font sizes and pixel sizes, none of which worked. I am not getting the empty boxes detailed in the OP, they are just invisible, I can type and run applications but no visible text. Rofi gives no error when running regarding the config. Using an OTF font or TTF works fine.

Running `pango-list | grep Cozette` and `pango-list | grep Terminus` both return the fonts, so pango is recognizing them, `fc-match` for both returns the correct font. Am I missing something or is this a bug (or potentially something wrong with my font config)? I've had Terminus installed for some time, however I installed Cozette only today to check if it would work. The fonts are in `~/.local/share/fonts` as well as in the global font directories (`fc-list` does identify them in both places).

**Comment by Saladaa** [comment]
It magically started working, no idea why, just randomly set it to `terminus` again and the font was working, same with `cozette` font. I did uninstall `nerd fonts` today and ran `fc-cache --really-force -v`, however I already did that before so I don't know why it helped this time. Very pleased though :)

**Comment by DaveDavenport** [comment]
happy to hear it is working now :smile:

**Comment by itshaydendev** [comment]
Ah, thanks!
