### ISSUE TITLE
Is it possible to output custom input even with matches?

### ISSUE THREAD

**Issue by harrisonthorne** [davatorium/rofi#1014]
## Version

Output of `rofi -v`

```
Version: 1.5.4
```

## Configuration

[rofi -help](https://gist.github.com/harrisonthorne/dd38be1f833f6ce431f2ca8c863ffb99)

## Launch Command

```
rofi -dmenu -no-auto-select -no-sort -no-show-match -tokenize -regex -p "..." -mesg "..."
```

This command is launched from a program I'm writing in Go. Lines are piped in to stdin from the program.

## Steps to reproduce

* Open rofi with this command:

```
echo -e "Item 1\nBullet 2\nLine 3" | rofi -dmenu -no-auto-select -no-sort -no-show-match -tokenize -regex
```

* Type "Item", see that "Item 1" is automatically selected without manual intervention
* Press Enter

## What behaviour you see

* "Item 1" is printed to stdout.

## What behaviour you expect to see

* "Item" to be printed to stdout.

Is it possible to prefer manual (custom) entry over the first selected entry in dmenu mode? Like an option to require manual selection of the entries listed and the possibility of having nothing selected at all (in which case manual input is used)?

**Comment by DaveDavenport** [comment]
Yes, there is a keybinding for that. please see manpage.  
```
* `Ctrl-Enter`: Use entered text as a command (in `ssh/run modi`)
```

**Comment by harrisonthorne** [comment]
Perfect! Thank you!
