### ISSUE TITLE
[dmenu] Allow a non-selectable row for column headers

### ISSUE THREAD

**Issue by process0** [davatorium/rofi#1016]
Currently using rofi Version 1.5.1.

The dmenu option can accept tabular data, which in turn, rofi displays as columns and rows.  It believe it would be useful to have support for an optional non-selectable fixed row for column headers when handling tabular data.  This could be placed under message bar (such as the extra message bar), where the data in the extra message bar is aligned with the columns beneath it.

My particular use case where I see this fit is extracting information from TaskWarrior and displaying it in rofi.  A user could have many entries and scrolling further down the list, the fixed non-selectable headers row would stay under message bar. 

```
ID Age Project Tag  Due Description  Urg 
 3 3h  Test    test 2d  Testing  9.39
 2 3h  Test    none 1d  Finish me 8.95
```

**Comment by DaveDavenport** [comment]
I think this is now possible using the theme engine.   You can add a widget with the extra text above the listview.

With the tabstop support on textbox you can even make sure it aligns property.
