### ISSUE TITLE
Missing libnkutils source files in release 1.5.4 archives

### ISSUE THREAD

**Issue by VinceCOT** [davatorium/rofi#1018]
##  Version

rofi 1.5.4

## Steps to reproduce

* Download releases 1.5.4 :

https://github.com/davatorium/rofi/releases/download/1.5.4/rofi-1.5.4.tar.gz
https://github.com/davatorium/rofi/releases/download/1.5.4/rofi-1.5.4.tar.xz

* Extract and go to subprojects/libkutils/src

* Compare source file list with the corresponding repo tree  :

https://github.com/sardemff7/libnkutils/tree/6164bacaef10031ce77380499cfad2ae818ab6b0/src

* Or use the attached Dockerfile to reproduce the build failure.
[Dockerfile.txt](https://github.com/davatorium/rofi/files/3681748/Dockerfile.txt)

## What behaviour you see

* Some sources files are missing  :

git-version.c (required by meson)
xdg-theme-example.c (required by meson)
token-example.c (not required)

* Meson setup build failed :

$ meson setup build

subprojects/libnkutils/meson.build:117:4: ERROR:  File src/git-version.c does not exist.
subprojects/libnkutils/meson.build:192:4: ERROR:  File src/xdg-theme-example.c does not exist.

## What behaviour you expect to see

* Sources files existing and meson setup build command success.

**Comment by sardemff7** [comment]
I don’t think I will fix this one. Use a (full) git clone at the correct tag, or the Autotools build from the archive.

Hopefully for the next release I will have libnkutils split as a standalone library with nice packages for almost everyone, and no more Autotools/Meson hiccup.

**Comment by VinceCOT** [comment]
Hi @sardemff7, yes absolutely I understand but it was more for adding information on this little issue and sharing it because I didn't find something about this one. Great idea to split the library in a package it would be really cool. Do you plan to do the same process with the libgwater too ?  By the way, I discover this project recently and this is a very good one nice job guys ! Otherwise just for information what is the relation between these projects (rofi / libnkutils & libgwater) and why they are separate ?

**Comment by sardemff7** [comment]
Yeah sorry, thanks for the report.

libgwater has a really different scope and each part is even smaller, merely some boilerplate code. It also needs much less maintenance and creating packages that would not require everybody to have all the deps installed isn’t worth the effort IMO.

libnkutils started small, grew a bit, just enough for bug fixes to be harder to ship in its submodule-static form, so I think it’s time to make it a shared library for good.

As for their relation to rofi, they’re projects I started to share some effort between a few other projects of mine, and some stuff happened to be useful for rofi too so when I helped, I just used them.
The submodule-static design was so people wouldn’t have to go through all kind of issues to find the libraries on their system, or need to build them separately. It worked well for a time, but now I have some packaging setup in place that would balance this, so here we are. :-)

**Comment by VinceCOT** [comment]
Yes no problem and thank you very much for all the details I understand better the context on this project :) I'll keep a close eye on it and it's gonna to be great with the packaging setup ;) I wish you well for the next ! (feel free to keep open or close this issue)
