### ISSUE TITLE
Use prompt as placeholder in entry input field

### ISSUE THREAD

**Issue by Spindlyskit** [davatorium/rofi#1020]
## Version

Output of `rofi -v`
```
Version: 1.5.4-26-gaeecf34c (makepkg)
```
## Description
Ability to show prompt as a html input-like placeholder so that the prompt will appear in the entry with a different color to normal input and disappear when any text is inputted. You can see many examples of this across the internet in the majority of input fields. I have attached an example image from github.
![23-10-2019-screenshot](https://user-images.githubusercontent.com/12555442/67381303-9de40c80-f583-11e9-9456-b759bc10b262.png)

## Use case
This would be useful for anyone who prefers the aesthetic. My main use case would be in dmenu mode since the prompt is often used to give additional context however the default style of the prompt does not look good with some themes.

**Comment by DaveDavenport** [comment]
![rofi-2019-10-23-1312-00000](https://user-images.githubusercontent.com/406245/67387223-be699200-f596-11e9-9683-528139eb2556.png)

You can already do a lot with the current theme format. (see attached screenshot). where the prompt is on the right and looks to be in bg of textbox.

In dmenu there is an option to pass an additional message to the user using the "-mesg" option.

That said, it is an interesting option and will consider it.

**Comment by ilovecookieee** [comment]
This is definitely nice to have.

**Comment by DaveDavenport** [comment]
![rofi-2019-12-26-1424-00000](https://user-images.githubusercontent.com/406245/71477679-8a575b00-27eb-11ea-96fb-ada506f63a87.png)
