### ISSUE TITLE
rofi -dmenu -select fails for inputs containing a hyphen

### ISSUE THREAD

**Issue by LiteracyFanatic** [davatorium/rofi#1021]
## Version

```
$ rofi -v
Version: 1.5.4
```

## Configuration

https://gist.github.com/LiteracyFanatic/40f6d3ae7d1b60ff3cdf8818b5098d3b

## Launch Command

```
echo -e 'abc\ndef - ghi\njkl' | rofi -dmenu -select 'def - hgi'
```

## Steps to reproduce

Run `rofi` in `-dmenu` mode with a `-select` flag containing a hyphen.

## What behaviour you see

The item with the dash is not selected.

## What behaviour you expect to see

The item passed to `-select` is selected.

**Comment by DaveDavenport** [comment]
Related to #937 I suspect. -select uses the normal matching code.
