### ISSUE TITLE
Pango markup is matched in search box

### ISSUE THREAD

**Issue by andrei-a-papou** [davatorium/rofi#1023]
## Version

Version: 1.5.4

## Configuration

No user configuration at all.

## Launch Command

`echo -e '<span color="red">one</span>\n<span color="blue">two</span>\n' | rofi -p TEST -dmenu -markup-rows`

## Steps to reproduce

* run the above command
* type _span_ into the search box

## What behaviour you see

* both items are matched due to Pango markup

![rofi-span-problem](https://user-images.githubusercontent.com/30468319/68085379-74639480-fe51-11e9-9bec-e71d8f1f3bfb.png)

## What behaviour you expect to see

* no items should be matched

**Comment by DaveDavenport** [comment]
It currently does it. I never implemented parsing of it, because I was worried about performance issues. Should investigates this.

**Comment by andrei-a-papou** [comment]
I see. I just assumed it's a bug since the drun mode doesn't have this problem. Hopefully, fixing it for dmenu mode won't cause a performance hit.

I'm building a custom rofi-based app for JIRA, and it loads 1,000+ JIRA issues into rofi, all with Pango markup (colored arrows to indicate issue priorities, and more). 

Would be willing to load-test any code that fixes this problem.

**Comment by DaveDavenport** [comment]
in drun the markup is added on display..   in dmenu it is the input and I don't have the original without markup.

It will be a performance hit, question is just how big.

**Comment by DaveDavenport** [comment]
Seems I fixed this a while back.

**Comment by andrei-a-papou** [comment]
thank you, seems to work well!

**Comment by DaveDavenport** [comment]
Thanks for confirming.
