### ISSUE TITLE
[dmenu] allow non-selectable separators

### ISSUE THREAD

**Issue by andrei-a-papou** [davatorium/rofi#1024]
## Version

Version: 1.5.4

## Configuration

No user configuration at all.

## Launch Command

```
sep="$(seq -s "─" 0 66 | sed 's/[0-9]//g')"
echo -e "one\ntwo\n$sep\napples\noranges\n$sep\nquit" | rofi -p "Pick the right action" -dmenu

```
## Use Case

When building CLI rofi-driven menu apps, it is sometimes very useful to separate groups of actions using separators to:
* improve the UX
* enhance readability
* indicate grouping

Currently, one has to resort to fake separators (see the above example), but this has disadvantages:

* No easy way to calculate separator width
* The separator is needlessly selectable, which is not so good for UX
* One has to handle the case when the user presses Enter on a selected separator
* One cannot set the separator color in the theme; the separator should be dimmer than the surrounding text, but fake separators _are_ text and so inherit the same foreground color.

Possible solutions:
* a single special character (like the horizontal box-drawing character in the above example) could be treated as a separator and extended to the right width
* a special string such as `<separator>` could be treated in the same way 

Thank you for considering this feature. Rofi is an amazing tool I rely on daily.

**Comment by DaveDavenport** [comment]
In the current design I could make it impossible to 'activate' an item, selecting the item (e.g. having it highlighted) is going to be very hard to disable. 

I will think about this, as it currently doe not  fully fit the design of rofi.

**Comment by andrei-a-papou** [comment]
@DaveDavenport I think even disabling the activation would be a step forward, eliminating the need to needlessly handle the activation event in rofi scripts.

Also, native separators would auto-adjust to rofi window's width.

Anyway, thanks for considering it, I hope it gets implemented.

**Comment by andrei-a-papou** [comment]
@DaveDavenport This is good news, I'll build from GitHub and test it soon!

**Comment by Yodzorah** [comment]
It would still be nice to make an item impossible to highlight. (Actually, I would say, it's a must-have for custom menus.) Any chance the design has changed enough for the past year that the feature is more likely to be implemented?
