### ISSUE TITLE
`-markup-rows` for mode scripts

### ISSUE THREAD

**Issue by fdw** [davatorium/rofi#1027]
#Version
1.5.4

As far as I can see, when calling `rofi` with a custom mode `-markup-rows` does not result in the entries being styled, even though they contain the necessary markup.

**Comment by DaveDavenport** [comment]
'markup-rows' is supported, but not as a commandline option.
Because if you have multiple modi? what command line option should apply to what mode.

**Comment by DaveDavenport** [comment]
To enable it send:
```
 "\x00markup-rowsx1ftrue\n"
```

**Comment by fdw** [comment]
Ah, I see. Thank you very much!

**Comment by fdw** [comment]
Is there something similar for custom keyboard shortcuts?

**Comment by DaveDavenport** [comment]
No.
Just:
* message
* prompt
* markup-rows
* urgent
* active

**Comment by fdw** [comment]
Thank you :)
