### ISSUE TITLE
An unexpected thin space may appear on the right of the window

### ISSUE THREAD

**Issue by roipoussiere** [davatorium/rofi#1029]
An unexpected thin space may appear on the right of the window, even with padding, margin and border set to 0. This space is displayed or not, and is 1px or 2px wide, depending of some parameters like number of columns, borders widths, etc.

## Version

1.5.4

## Configuration

Unnecessary because using -no-config and -no-plugins options

## Launch Command

```
echo 'a|b|c' | rofi -sep '|' -dmenu -theme-str 'window,mainbox,listview,element {padding: 0; margin: 0; border: 0;} inputbar { enabled: false;} listview { scrollbar: false; spacing: 10;} window {background-color: red; border: 7;}' -lines 1 -columns 3 -width 150 -no-config -no-plugins
```

## Steps to reproduce

Run the command above.

## What behaviour you see

![2019-11-15_23-11-1573856877](https://user-images.githubusercontent.com/1665542/68980185-054a5080-0800-11ea-8785-74c8e3073ad5.jpg)

## What behaviour you expect to see

no red line on the right

**Comment by DaveDavenport** [comment]
because the pixe(s)l is/are left..

border
150-2*7=136
spacing
136-20=116
element would be 38px. floor(116/3)
that would leave 2 spare pixels.

**Comment by roipoussiere** [comment]
> Change width to 148.

The width may be calculated if number is <100.

Is it possible to reduce the window size to fit the dimentions in order to avoid this line (ie. add the space *after* the external border instead of between the right element and the border?

**Comment by DaveDavenport** [comment]
>  The width may be calculated if number is <100.

I don't understand? What do you mean with this?

>Is it possible to reduce the window size to fit the dimentions in order to avoid this line (ie. add the  space after the external border instead of between the right element and the border)?

This will not work with how the ui is build up out of widgets.  You set a specific width, margins and border.. this decides what width the listview widget has,   then it just depends on spacing/margins/etc. set in listview.  You need to use full pixels or you get very weird drawing issues, so this is inevitable.

**Comment by roipoussiere** [comment]
> > The width may be calculated if number is <100.
>
> I don't understand? What do you mean with this?

I mean that if I set `50`, the window width will be calculated according to the monitor size. So _changing width_ is not a solution, because the effective window size may depend on the user's monitor.

If there is a space at `50` and I avoid it by changing to `51`, other users may see the space on their monitor if it has a different size.

> This will not work with how the ui is build up out of widgets. You set a specific width, margins and border.. this decides what width the listview widget has, then it just depends on spacing/margins/etc. set in listview.

Current simplified pseudo code (at least what I guess):

```py
window_size = config.window_size # ie. 200
element_size = floor(config.window_size / config.nb_columns) # ie. floor(200/3) = floor(66.67) = 66
```

The annoying space that I mention can be calculated: 

```py
annoying_space = config.window_size - (element_size * config.nb_columns) # ie. 200 - 66*3 = 200-198 = 2
```

But instead, the actual window size could be calculated _before_ rendering it, **based on the element_size**:

```py
element_size = floor(config.window_size / config.nb_columns) # ie. floor(200/3) = floor(66.67) = 66
window_size = config.element_size * config.nb_columns # ie. 66*3 = 198
```

Based on these new values, `annoying_space` is always 0.

**Comment by DaveDavenport** [comment]
So you would get a window that slightly resizes when you filter down the list (as that can change the number of columns).
I also see an issue with full-screen windows.

**Comment by roipoussiere** [comment]
Ok, I understand better now.

An other solution: distribute the remaining pixels in the separators. So separators size may not be equal, but it's less annoying than an additional unwanted space.

**Comment by DaveDavenport** [comment]
quick hack can you try?
```patch
diff --git a/source/widgets/listview.c b/source/widgets/listview.c
index 88007013..814196bd 100644
--- a/source/widgets/listview.c
+++ b/source/widgets/listview.c
@@ -404,8 +404,19 @@ static void listview_draw ( widget *wid, cairo_t *draw )
                 width -= widget_get_width ( WIDGET ( lv->scrollbar ) );
             }
             unsigned int element_width = ( width ) / lv->cur_columns;
+
+            int d = lv->widget.w - (element_width+spacing_hori)*(lv->cur_columns-1)-element_width;
+            float diff = d/(float)lv->cur_columns;
+            if ( diff >= lv->cur_columns ){
+                spacing_hori+=1;
+                d -= lv->cur_columns;
+            }
             for ( unsigned int i = 0; i < max; i++ ) {
                 unsigned int ex = left_offset + ( ( i ) / lv->max_rows ) * ( element_width + spacing_hori );
+
+                if ( (i)/lv->max_rows == (lv->cur_columns-1) ) {
+                    ex+=d;
+                }
                 if ( lv->reverse ) {
                     unsigned int ey = wid->h - ( widget_padding_get_bottom ( wid ) + ( ( i ) % lv->max_rows ) * ( lv->element_height + spacing_vert ) ) - lv->element_height;
                     widget_move ( WIDGET(lv->boxes[i].box), ex, ey);
```

**Comment by DaveDavenport** [comment]
should be fixed

**Comment by roipoussiere** [comment]
Thanks! I will check on v1.6 when released.
