### ISSUE TITLE
WHY DOES ROFI REQUIRE I3?

### ISSUE THREAD

**Issue by lewisde** [davatorium/rofi#1031]
Different distros, binary or source, build or install rofi and I also get i3.

WHY????

**Comment by DaveDavenport** [comment]
it does not, what distro do, is out of my power.

Btw.. shouting and not following guidelines will not solve anything.

**Comment by DaveDavenport** [comment]
For debian/ubuntu:
> Package: rofi
> Version: 1.5.4-1
> Priority: optional
> Section: x11
> Maintainer: Jason Pleau <jason@jpleau.ca>
> Installed-Size: 566 kB
> Depends: libc6 (>= 2.27), libcairo2 (>= 1.6.4-5~), libglib2.0-0 (>= 2.35.9), libpango-1.0-0 (>= 1.22.0), libpangocairo-1.0-0 (>= 1.22.0), librsvg2-2 (>= 2.14.4), libstartup-notification0 (>= 0.11), libxcb-ewmh2 (>= 0.4.1), libxcb-icccm4 (>= 0.4.1), libxcb-randr0 (>= 1.12), libxcb-util0 (>= 0.3.8), libxcb-xinerama0, libxcb-xkb1, libxcb-xrm0 (>= 0.0.0), libxcb1, libxkbcommon-x11-0 (>= 0.5.0), libxkbcommon0 (>= 0.7.0)
>
