### ISSUE TITLE
Highlight color not updated when selection changes

### ISSUE THREAD

**Issue by nathanchere** [davatorium/rofi#1032]
## Version

1.5.4

## Configuration

https://gist.github.com/nathanchere/48a99ed5ff8bacbaa278b64a626f108d

## Launch Command

`rofi -show run`

## Steps to reproduce

Type something to filter the run commands. Highlight is applied as expected. Then move the selection up/down.

## What behaviour you see

The highlight is not updated. For example if `element normal` has highlight set to red `element selected` has highlight set to blue, it appears as expected when first typing. But when moving the selection up/down, newly selected items still show their highlight in red while the item which was selected while typing still shows highlighted characters in blue.

## What behaviour you expect to see

Highlight styling to update when moving selection

**Comment by DaveDavenport** [comment]
This is currently not supported no. 
This should be:
a.) fixed
or
b.) better documented.

Thx.

**Comment by DaveDavenport** [comment]
hopefully won't slow it down to much
