### ISSUE TITLE
Highlight color doesn't handle alpha value

### ISSUE THREAD

**Issue by nathanchere** [davatorium/rofi#1033]
## Version

1.5.4

## Configuration

https://gist.github.com/nathanchere/48a99ed5ff8bacbaa278b64a626f108d

## Launch Command

`rofi -show run`

## Steps to reproduce

Set a highlight style to something like `rgba(255,255,255,50%)`.

## What behaviour you see

The highlight colour displays opaque white.

## What behaviour you expect to see

Highlighted text rendered in 50% opacity white.

**Comment by DaveDavenport** [comment]
should be fixed in git.
