### ISSUE TITLE
Long message in dmenu mode hides other layout components

### ISSUE THREAD

**Issue by mihalea** [davatorium/rofi#1034]
## Version

Version: 1.5.4

## Configuration

https://gist.github.com/mihalea/b6d7919744dec8a587e22479c47f9469

## Launch Command
```
echo "aaa\nbbb\nccc\nddd" | rofi -dmenu -mesg "This is a long text that doesnt work" -theme theme.rasi

echo "aaa\nbbb\nccc\nddd" | rofi -dmenu -mesg "This is a long text" -theme theme.rasi
```
## Steps to reproduce

* Step 1: Download the following [theme.rasi](https://gist.github.com/mihalea/d44ed5fd5ea36d94e6016c526c44be49)
* Step 2: Launch rofi in dmenu mode using the first command
* Step 3: Launch rofi again using the second command

## What behaviour you see

The only differences between the two should be the different text, however the prompt and the list view are invisible, with just the message showing in the first instance, while the second instance has all of them visible.

Screenshot of first command:
![2019-11-20-13:28:44](https://user-images.githubusercontent.com/10897160/69226546-c3236500-0b99-11ea-9e6f-e19f4cda2556.png)

Screenshot of second command:
![2019-11-20-13:39:18](https://user-images.githubusercontent.com/10897160/69227448-3e394b00-0b9b-11ea-87cc-6575b8e79696.png)

## What behaviour you expect to see

The prompt, list view and message should be visible in both instances. Changing the length of the text shouldn't have such an effect on the other components.

**Comment by DaveDavenport** [comment]
![rofi-2019-11-20-1122-00001](https://user-images.githubusercontent.com/406245/69230737-21dfe300-0b88-11ea-8233-95ae786bb721.png)

works for me.

You might have more in your configuration. Can you  do a `rofi -theme theme.rasi -dump-theme` and post that?

**Comment by mihalea** [comment]
Here's the output of `rofi -theme theme.rasi -dump-theme`. 
There doesn't seem to be anything wrong with it.
https://gist.github.com/mihalea/b6d7919744dec8a587e22479c47f9469#file-dump-theme

However running `rofi -dmenu -theme theme.rasi -dump-theme` seems to contain a lot more than expected.
https://gist.github.com/mihalea/b6d7919744dec8a587e22479c47f9469#file-dump-theme-dmenu

Assumming that you ran the command with the `-dmenu` flag, it's leading me to think that there's an issue with my installation, so I am going to investigate further. I am running rofi on Manjaro Linux, so there may be something to it.

**Comment by mihalea** [comment]
Building from source the latest version seems to have fixed the issue. This issue can now be closed.

**Comment by DaveDavenport** [comment]
Great to hear! thanks for testing it!
