### ISSUE TITLE
Remove auto completion in obtrusive style

### ISSUE THREAD

**Issue by Shamaoke** [davatorium/rofi#1035]
Rofi always run the first history match of inputted command regardless of whether it's what a user wants or not. For example, if a user wants to run `atn 5` and the history contains `atn 25` and `atn 15`, there's no way to run the command exactly as it was typed — the first history match will always run.

![Rofi obtrusive autocompletion](https://live.staticflickr.com/65535/49095114911_5ec3e1c119_o.png)

Re-implement the auto completion behavior, so that the command runs exactly as it was typed if a history entry wasn't explicitly selected.

**Comment by DaveDavenport** [comment]
Duplicate: #1014

**Comment by DaveDavenport** [comment]
The base idea behind rofi is to select from a list, to help you select, you can type to filter. There is no autocompleting.
