### ISSUE TITLE
Rofi ignores new 'config.rasi' file and uses old style format 'config' file

### ISSUE THREAD

**Issue by gugutz** [davatorium/rofi#1036]
## Version

Version: 1.5.4

## Configuration

https://gist.github.com/gugutz/61de0a65f9a1268c233a0938ad7a2b27

## Launch Command

i3 line on my config for launching rofi:

`bindsym $mod+d exec rofi -show run`

## Steps to reproduce

* `rofi -dump-config > ~/.config/rofi/config.rasi`
* run `rofi-theme-selector`
* confirm a theme with `Alt-a`
* run `rofi -h`

## What behaviour you see

- output shows rofi is still using the old 'config' file (~/.config/rofi/config)
- rofi saves the newly selected theme as Xresources style config format on ~/.config/rofi/config and ignores the config.rasi file located in the same folder.

## What behaviour you expect to see

- `rofi -h` showing the `~/.config/rofi/config.rasi` being used
- `rofi-theme-selector` changing the newly selected theme on the correct `~/.config/rofi/config.rasi` file instead of  the old format in `~/.config/rofi/config` file

**Comment by DaveDavenport** [comment]
That should not be possible as it does this in psuedo code:

 if file exists  rasi_config:
   parse_rasi_config
else
  parse_old_config
fi.


So if the file exists and is a regular file, it should work.

**Comment by gugutz** [comment]
Im so sorry. It was entirely my fault. I save the config in another file and had forgotten to update symlink in the `~/.config/rofi` folder to contain the .rasi extension
