### ISSUE TITLE
Repeatedly launching/exiting rofi creates a running instance that doesn't have a window

### ISSUE THREAD

**Issue by sqd** [davatorium/rofi#1037]
## Version

Output of `rofi -v`: `Version: 1.5.4`

## Configuration

Output of `rofi -help` (in a [gist](https://gist.github.com/sqd/7362d93a68f7055c4225f412b8284026))

## Launch Command

`bindsym $mod+d exec rofi -show drun`

## Steps to reproduce

* Launch rofi and press escape to close it quickly.
* Repeat a dozen times.

## What behaviour you see

* A rofi instance is created but doesn't show the window. (can see it in `ps aux` and it is the same as `/run/user/1000/rofi.pid`). The state is `Sl` (interruptible sleep, is multi-threaded)
* Also my input control/command key got hijacked. I have to press escape again to close it and regain control.
* Meanwhile new rofi can't be launched, giving
```
(process:23392): Helper-WARNING **: 23:32:07.050: Failed to set lock on pidfile: Rofi already running?

(process:23392): Helper-WARNING **: 23:32:07.050: Got error: -1 Socket operation on non-socket
```

**Comment by sqd** [comment]
Looks very much like https://github.com/davatorium/rofi/issues/959

**Comment by DaveDavenport** [comment]
Tried to reproduce on 4 machines, but failed. might need some help getting this one pinned down.

**Comment by sqd** [comment]
Should I run a debug-log enabled version of rofi? (I'm working around this issue by `pkill rofi` before starting it for now)

**Comment by DaveDavenport** [comment]
Can you describe your setup? it seems you are using wayland?

**Comment by sqd** [comment]
Yes, I'm using rofi with sway on Fedora 31 (even though I was pretty sure I had the same problem on an Archlinux machine I had). I have an external HDMI monitor but I force rofi to appear on the laptop's builtin display.

**Comment by DaveDavenport** [comment]
I don't support wayland, or Xwayland.. to many weird  issues with it.
I spend an hour trying to figure out how this issue could happen, I cannot see it.

I have been unable to reproduce this on X11.

**Comment by sqd** [comment]
I see. It could be helpful to put that into README so people would know.

I'll try to figure it out when I have time. Thanks Dave!
