### ISSUE TITLE
Rounded corner with compositor

### ISSUE THREAD

**Issue by mustaqimM** [davatorium/rofi#1039]
:exclamation:
First read the [guidelines](https://github.com/DaveDavenport/rofi/blob/next/.github/CONTRIBUTING.md)!
This is not optional for any report/question. People must be able to understand the full context of the report when reading it, at any time.
If you feel like you “just have a simple question”, please consider you’re wrong and still fill the full report.
Any report missing these informations will be labeled as “Incomplete Report - Please follow the guidelines” and may not be answered in a timely fashion.
:exclamation:

## Version

Output of `rofi -v`
Version: 1.5.4

## Configuration

`rofi -help`
https://gist.github.com/mustaqimM/314edcbe3f88dc1ea91653d071ec7abf
`compton.conf`
https://gist.github.com/mustaqimM/91d56c92b1eaa02cd602308afdf46f72

## Launch Command

`rofi -config ~/.config/rofi/config -show combi`

## Steps to reproduce

* Launch rofi

## What behaviour you see

* Corners are still visible

![corner](https://user-images.githubusercontent.com/24436622/70687698-cf39a880-1ca7-11ea-8482-f3175955eecf.png)

![2019-12-12_08-12](https://user-images.githubusercontent.com/24436622/70687661-b630f780-1ca7-11ea-8869-7bdfbb9dc7df.png)

## What behaviour you expect to see

* Rounded corners

**Comment by DaveDavenport** [comment]
That is a compton issue. Disable shadow on the rofi window.
