### ISSUE TITLE
Cache the parsed desktop entries

### ISSUE THREAD

**Issue by fctorial** [davatorium/rofi#1040]
## Version

Output of `rofi -v`

Version: 1.5.4

## Configuration

Output of `rofi -help` (in a [gist](https://gist.github.com/))
https://gist.github.com/fctorial/2d65499bb29e0f120e5ea48e0e84d7a4

## Launch Command

The commandline used to launch **rofi**

rofi -show drun

Would it be possible to cache whatever data structure rofi stores the parsed application entries in, and update it at startup if the application directories have changed? This might solve some of the slow startup issues.

**Comment by DaveDavenport** [comment]
Please give a timing log.  More recently most slowness was caused by pango/fontconfig.

**Comment by DaveDavenport** [comment]
For me:
```
(process:17570): Dialogs.DRun-DEBUG: 20:03:04.254
........
(process:17570): Dialogs.DRun-DEBUG: 20:03:04.275
.....

takes around 21ms.

**Comment by fctorial** [comment]
This is the output of `strace -c rofi -show drun`:
https://gist.github.com/fctorial/8490a6f38e26156b2fb2129f2213fe90

Subsequent runs are fast for me as well, but it's slow if .desktop files aren't cached, like in this issue:
https://github.com/davatorium/rofi/issues/898

**Comment by DaveDavenport** [comment]
please see [wiki](https://github.com/davatorium/rofi/wiki/Debugging-Rofi#timing-traces) for timing trace.

I thought about adding a cache, but I haven't had systems where it was noticable.  Even low end arm systems with filesystem on nfs/slow sd card. I might give it a stab.

**Comment by DaveDavenport** [comment]
Added optional cache.
