### ISSUE TITLE
'-sep' option for script modi

### ISSUE THREAD

**Issue by vredesbyyrd** [davatorium/rofi#1041]
## Version

1.5.4-1

## Launch Command

`rofi -modi "ffh:/home/clu/experiments/fire-hist/ffh.lua" -show ffh -async-pre-read 30 -eh 2 -sep '^'`

## Steps to reproduce

* run rofi

## What behaviour you see

* Since '-sep' is dmenu specific, option is ignored. 

## What behaviour you expect to see

With rofi in dmenu mode, you can use the `-sep` and `-eh` options to display a single selection across a multiple lines, e.g `echo -en "a\nb^c\nd" | rofi -dmenu -sep '^' -eh 2`. IMO, this can be a nice way to display data. I do this for a firefox tab switcher script. 

![rofi-2019-12-12-1609-00000](https://user-images.githubusercontent.com/22080838/70754019-c8d51c00-1cfb-11ea-85d5-d0d6f37f01f5.png)

I have been wanting to display information this way but with modi scripts rather than `-dmenu`.  I do not think its possible at the moment, maybe programmatically in the script itself but I have not had any success yet. 

Could the `-sep` option or a similar function be added to mode scripts?   

Thanks for your time.

**Comment by DaveDavenport** [comment]
How is that going to work if you have multiple script modi that require different 'sep'.

**Comment by vredesbyyrd** [comment]
> How is that going to work if you have multiple script modi that require different 'sep'.

I asked myself that after posting this. The best I could think of is an option similar to `-display-{mode} string`. With my previous launch command example...

`rofi -modi "window,run,ffh:/home/clu/experiments/fire-hist/ffh.lua" -show ffh -separator-ffh "^"`

Although it would have the same function as the dmenu option `-sep` maybe a distinct name to differentiate it makes sense,  `-delimiter-(mode) string`?  

I assume I am overlooking important considerations and perhaps this level of control should be left for `-dmenu` or _c_ plugins. There are just certain use cases where I prefer the mode scripts over -dmenu.

**Comment by DaveDavenport** [comment]
Added option to change delimiter in script mode.

**Comment by vredesbyyrd** [comment]
Right on, thank you for implementing this. I only tested it briefly and all seems to work well.  When time abides I have a script in mind that will utilize this option so I'll test more than. 

Much appreciated, closing.
