### ISSUE TITLE
emojis dont show up

### ISSUE THREAD

**Issue by grenzionky** [davatorium/rofi#1042]
## Version

Rofi Version: 1.5.4

## Configuration

[gist](https://gist.github.com/grenzionky/d6243e7cb7562071795791c5fd30bf8a/)

```
OS: Manjaro Linux x86_64 
Kernel: 5.3.15-1-MANJARO 
WM: awesome 
```

## Launch Command

```
echo -e "\U1F62C GRIMACING FACE\n😄 SMILING FACE WITH OPEN MOUTH AND SMILING EYES" | rofi -dmenu
```

## What behaviour you see

* emojis dont show in rofi, while they do work in all other programs on my computer

![image](https://user-images.githubusercontent.com/13357949/70765713-9215fa80-1d29-11ea-903f-5165503e3842.png)

## What behaviour you expect to see

* i expect to see emojis show up as usual

## other

doing just `echo -e "\U1F62C\n😄"` *does* work

![image](https://user-images.githubusercontent.com/13357949/70765728-9b9f6280-1d29-11ea-96e4-77dbf2ed36a4.png)

I haven't set the font to anything in my ~/.config/rofi/config

Even when i do set the font to an emoji font, the emojis still dont show up:

`echo -e "\U1F62C GRIMACING FACE\n😄 SMILING FACE WITH OPEN MOUTH AND SMILING EYES" | rofi -dmenu -font 'Noto Color Emoji 12'`
![image](https://user-images.githubusercontent.com/13357949/70811555-cde5aa00-1d93-11ea-8325-8c9f35ec79b4.png)

`echo -e "\U1F62C GRIMACING FACE\n😄 SMILING FACE WITH OPEN MOUTH AND SMILING EYES" | rofi -dmenu -font 'JoyPixels 12'`
![image](https://user-images.githubusercontent.com/13357949/70811589-e3f36a80-1d93-11ea-994a-54008ffef6e0.png)

I know its a real font, cuz ① all the emoji on my computer use JoyPixels (emojione) as the emoji font, and ② ↓
![image](https://user-images.githubusercontent.com/13357949/70811705-24eb7f00-1d94-11ea-9f19-34812d2e1e62.png)

**Comment by DaveDavenport** [comment]
Pick a font that supports the emojis.  The default is just whatever resolves 'mono 12'..

**Comment by grenzionky** [comment]
i shudve put that in the original post your right. i just edited the post saying that even when i set the font to an emoji font, it still doesnt show

**Comment by DaveDavenport** [comment]
Still think it could be your font setup. I don't realy handle fonts in rofi, this is done by pango.

![rofi-2019-12-13-1750-00000](https://user-images.githubusercontent.com/406245/70817105-24250e00-1dd1-11ea-8bc7-57f688ba689e.png)
