### ISSUE TITLE
[REQUEST] Flatpak support

### ISSUE THREAD

**Issue by ishan9299** [davatorium/rofi#1044]
Cant launch the flatpak apps using rofi 
According to arch wiki if launchers scans for 
**~/.local/share/flatpak/exports/share/applications
/var/lib/flatpak/exports/share/applications**
flatpak apps will be visible
Version 1.5.4

**Comment by DaveDavenport** [comment]
No change should be required:

- If there are executables, add it to you PATH,
- if it contains desktop files, add it to the right XDG environment variable.

**Comment by DaveDavenport** [comment]
https://www.reddit.com/r/qtools/comments/ebdymq/flatpak_support_in_rofi/
