### ISSUE TITLE
Render root background instead of windows on transparent rofi

### ISSUE THREAD

**Issue by xcbdz** [davatorium/rofi#1045]
I've been searching for this quite a while now. I just want to know how to display the desktop/root background instead of clients behind a transparent-background rofi. I use this [config](https://pastebin.com/36eAUG3R) and this when I call it `rofi -show drun -theme ${HOME}/.config/rofi/rofi.rasi` Sorry if this is a noob question. I'm fairly new to linux and I just stole that config. Thanks in advanced!

**Comment by sardemff7** [comment]
See the man page for `rofi-theme`, under `window`, property `transparency`. Using `"background"` should work.
