### ISSUE TITLE
[BUG] Rofi ignores padding from config.rasi when loading a theme.rasi

### ISSUE THREAD

**Issue by LeLobster** [davatorium/rofi#1046]
##  Version

Output of `rofi -v`

Version: 1.5.4

## Configuration

Output of `rofi -help` (in a [gist](https://gist.github.com/))

https://gist.github.com/LeLobster/ea8c4b2bade0b51555dc672b70d62ee3#file-rofi-help-L17

## Launch Command

`rofi -show run`

## Steps to reproduce

- Step 1
Have a config.rasi file without all color related properties, but specify a
`theme: "theme.rasi"` which would hold colors etc. (below was my theme.rasi just for testing)
```
* {
  background: #140a21;
  foreground: #c4c1c7;
}
```
- Step 2
Launch rofi

## What behaviour you see
Rofi ignores padding specified in the config.rasi even though nothing regarding padding is specified in the theme file  
Once i comment out the `theme: "theme.rasi"` line in the config the padding gets applied again as expected

## What behaviour you expect to see
Every property specified in the config.rasi should be applied

**Additional details:**
I understand the reasoning behind it because themeing would mostly be done by the theme.rasi file, but if there is no padding specified shouldn't it just listen to the main config?  
if this is *intended* behaviour feel free to close this issue, but it seemed like something Id report.
Thanks

**Comment by sardemff7** [comment]
It is intended, theming information in the configuration part is only there as a backward compatibility feature.
Applying a theme is supposed to be a deterministic operation, so all values are reset to their defaults before that.

To override theme values, you can use the `@theme "theme"` syntax to load a theme, then add any theming you would like after that line. (Or even better, use `@theme "parent-theme"` in your theme file, to avoid any theming in your configuration file.)

**Comment by LeLobster** [comment]
yeah I expected something like that to be the reason, fair enough
> To override theme values

Do you mean i.e. specifying `@theme "theme2"` in the `theme.rasi` file and then being able to use `theme2.rasi` to override any of those values in theme.rasi?  
If so, that's interesting. I hadn't though of that, I'll try it in a bit

**Comment by DaveDavenport** [comment]
See the rofi-theme manpage, it describes how multiple files and entries are handled.
