### ISSUE TITLE
[BUG] Cannot pipe rofi into rofi

### ISSUE THREAD

**Issue by SicariusNoctis** [davatorium/rofi#1048]
## Version

```
Version: 1.5.4-17-gc3caa20d (makepkg)
```

## Steps to reproduce

```bash
echo "test" | rofi -dmenu -p "1" | rofi -dmenu -p "2"
```

## What behaviour you see

Undefined behavior due to race condition. Sometimes window "1" appears, and other times window "2" appears.

Also generates the following warnings:

```bash
(process:2974422): Helper-WARNING **: 17:16:30.666: Failed to set lock on pidfile: Rofi already running?

(process:2974422): Helper-WARNING **: 17:16:30.666: Got error: -1 Socket operation on non-socket
```

## What behaviour you expect to see

Opening window "1" then window "2" in succession.

**Comment by DaveDavenport** [comment]
This is not a bug, but intended behavior. Multiple concurrent rofi are not supported.

What is the actual use case for this?

**Comment by SicariusNoctis** [comment]
The intended use case was using rofi for input, doing some arbitrary action, then running rofi again on the results.

```bash
rofi -dmenu | xargs ls | rofi -dmenu
```

In retrospect, it probably makes more sense to just split that into multiple lines, since pipes run concurrently rather than in sequence.
