### ISSUE TITLE
[request] Use POSIX/GNU command line argument syntax

### ISSUE THREAD

**Issue by sirtomato999** [davatorium/rofi#1049]
This one is pretty simple. An example: `rofi -show run`
With the POSIX standard, it would be `rofi --show run`.

You can find standard [here](https://www.gnu.org/software/libc/manual/html_node/Argument-Syntax.html), but the double-dash is really the main point.

This is better because it would allow for stacking of single-letter arguments, and it would just follow the standard that most other applications use.

**Comment by DaveDavenport** [comment]
Not going to change the commandline options now. (The amount of complaints would be insane)

Current format was inherited from the tool `rofi` originates from (simpleswitcher). A lot of X related tools use this style, I always suspected it was copied from those.
