### ISSUE TITLE
[BUG] Config file never loads any changes

### ISSUE THREAD

**Issue by MtotheM1337** [davatorium/rofi#1051]
## Version

Version: 1.5.4

## Configuration

```
Configuration {
...
/*    font: "Terminus (TTF) 9";*/
...
}
```

## Launch Command

`rofi -show run`

## Steps to reproduce

Generate config with `rofi -dump-config > ~/.config/rofi/config`
Run rofi normally `rofi -show <mode>` or specifically specify the config file. 
`rofi -show <mode> -config /path/to/config`

## What behaviour you see

None of the settings from the config file apply, regardless of which i set.
All settings are default.

## What behaviour you expect to see

I expected it to read my configurations from the config file.
When i run `rofi -h` it indicates that it has recognized it.
```
Configuration file: /home/mtothem/.config/rofi/config
```
Even if i explicitly specify the config file using `-config` none of the changes apply.
```
rofi -show run -config ~/.config/rofi/config
```

Having the `.rasi` extension makes no difference either.

I saw there is already a closed issue about this specific problem. but it was never addressed.
https://github.com/davatorium/rofi/issues/758

**Comment by DaveDavenport** [comment]
The `-dump-config` option is for the new 'rasi'  format, and needs to be stored in ~/.config/rofi/config.rasi.
To generate the old config, use `rofi -dump-xresources`.

**Comment by DaveDavenport** [comment]
See remark in the **Configuration** section of the manpage:


> **TIP**: To get a template config file run: `rofi -dump-xresources > rofi-example.config`.                        
> **NOTE**: In version 1.4.0 we support configuration in a new format, a config for this can be generated by: `rofi 
> -dump-config > config.rasi`                                                                                       
> **NOTE**: If you want to use the new configuration format, the config file should be named `config.rasi`.

**Comment by MtotheM1337** [comment]
> See remark in the **Configuration** section of the manpage:
> 
> > **TIP**: To get a template config file run: `rofi -dump-xresources > rofi-example.config`.
> > **NOTE**: In version 1.4.0 we support configuration in a new format, a config for this can be generated by: `rofi  -dump-config > config.rasi`
> > **NOTE**: If you want to use the new configuration format, the config file should be named `config.rasi`.

> The `-dump-config` option is for the new 'rasi' format, and needs to be stored in ~/.config/rofi/config.rasi.
> To generate the old config, use `rofi -dump-xresources`.

Neither the old format nor new actually gets loaded by the program. This is the issue.

### New format
```
# Correct config file path
[nashandra ~]$ rofi -config ~/.config/rofi/config.rasi -h | grep "Configuration"
      Configuration file: /home/mtothem/.config/rofi/config.rasi

# Contents of config file
[nashandra ~]$ cat ~/.config/rofi/config.rasi | grep font
/*    font: "Terminus (TTF) 32";*/

# Rofi uses defaults despite there being custom values set in the config file
[nashandra ~]$ rofi -config ~/.config/rofi/config.rasi -h | grep font -A 1
    -font [string]                          Font to use
        mono 12 (Default)
```
### Old format
```
# Correct config file path
[nashandra ~]$ rofi -config ~/.config/rofi/rofi.config -h | grep "Configuration"
      Configuration file: /home/mtothem/.config/rofi/rofi.config

# Contents of config file
[nashandra ~]$ cat ~/.config/rofi/rofi.config | grep font
! rofi.font:                           Fira Code 32

# Rofi uses defaults despite there being custom values set in the config file
[nashandra ~]$ rofi -config ~/.config/rofi/rofi.config -h | grep font -A 1
    -font [string]                          Font to use
        mono 12 (Default)
```

**Comment by DaveDavenport** [comment]
> /*    font: "Terminus (TTF) 32";*/
and

> ! rofi.font:                           Fira Code 32

Are both commented out.  It will not load a commented line.

**Comment by MtotheM1337** [comment]
> > /*    font: "Terminus (TTF) 32";*/
> 
> and
> 
> > ! rofi.font:                           Fira Code 32
> 
> Are both commented out. It will not load a commented line.

You are absolutely correct. i'm sorry for my stupidity. i thought it was part of the config syntax.

**Comment by DaveDavenport** [comment]
Happy to hear it is working.
