### ISSUE TITLE
[REQUEST] Ability to disable bold and underline highlighting for search matches

### ISSUE THREAD

**Issue by mvrozanti** [davatorium/rofi#1053]
**Describe the feature**
- A clear description of the feature you want added.
  - Title says it all

- If the feature involves replacement of current functionality, how the new
  functionality is better?
  - The highlighted text is both bold and underlined. That's aesthetically redundant. The user should be able to choose to use the default (both), one of those, or no text highlighting at all.

- If the feature is implemented in another application, include:
  - I looked for this feature in `dmenu`, but I have failed to find it.

- If possible try to explain how you would expect to use feature:
  For example, should it be a configuration option or a hot-key. 
  - Obviously, a configuration option. Something like:
```
    match-highlight-font-weight: bold;
    match-highlight-font-decoration: underline;

    match-highlight-font-weight: none;
    match-highlight-font-decoration: underline;

    match-highlight-font-weight: bold;
    match-highlight-font-decoration: none;

    match-highlight-font-weight: none;
    match-highlight-font-decoration: none;
```

**When reporting a feature request include the following information:**
- Rofi version:
  - `Version: 1.5.4`

This is a duplicate of #515.

**Comment by DaveDavenport** [comment]
The highlighting style can already be modified and disabled. 

```
rofi  -show drun -no-config -theme-str 'element { highlight: none; }'
```

**Comment by mvrozanti** [comment]
Whoops, sorry about that.
