### ISSUE TITLE
[REQUEST] Plasma Activities detection

### ISSUE THREAD

**Issue by dkazantzas** [davatorium/rofi#1056]
I use Rofi with KDE and I notice that, Rofi does not detect Plasma activities. This results to window modi showing all windows regardless of the activity they reside in. My Rofi version is 1.5.4

The functionality I expect is that, when in window modi, Rofi should show only the windows that reside on the current activity. I think that the option to do this could be passed as a flag when running Rofi

**Comment by DaveDavenport** [comment]
What are plasma activities? 
 
Rofi shows the windows that the window manager says that exist.
windowcd will filter on current desktop.

I have no idea what activities are and how the window manager makes them known.  Is there a standard for this?

**Comment by dkazantzas** [comment]
Plasma activities are like extensions to virtual desktops. From [documentation](https://userbase.kde.org/Plasma#Activities).

> A user likes web comics so they add their favorite web comics via the comics widget. The user now has a full desktop activity dedicated to their favorite web comics. Now the user is happy with the web comics, but the user now has to go to work, so the user creates an activity with the folder view widgets set to the folders of the projects the user is currently working on. After work the user goes home and works on a side project of writing romance novels. The user always gains inspiration by looking at pictures of the user's significant other. The user now creates a new Activity but now puts pictures frame widgets with pictures of the user's significant other. The user also has a folder view of the romance novel project folder. Now no matter what the user is doing the user has a custom tailored activity to match it. 

I have no idea about a standard, but I think that the libraries provided by KDE give a way to make them known

**Comment by DaveDavenport** [comment]
I am not going to make rofi depend on KDE libraries. I think that would break with its goal.

If people want this, it can be added using a separate plugin .
