### ISSUE TITLE
[BUG] not possible to select an item after 7dcc3f4 in script mode

### ISSUE THREAD

**Issue by cinghiopinghio** [davatorium/rofi#1057]
## Version

Output of `rofi -v`: Version: `1.5.4-63-geb12ff23` (makepkg)

## Configuration

Output of `rofi -help` [gist](https://gist.github.com/cinghiopinghio/94944a5dba3e833cab4b4bd1eed48418)

## Launch Command

`rofi -modi thismodi:./Examples/test_script_mode.sh -show thismodi`

This is the script example shipped with rofi.

## Steps to reproduce

- launch the above command
- enter <enter> on any item

## What behaviour you see

- nothing

## What behaviour you expect to see

- the item get selected and echoed to the same script

**Additional details:**

- This issue is introduced by commit: 7dcc3f4

**Please do not submit reports related to wayland, see
[here](https://github.com/DaveDavenport/rofi/wiki/Wayland) for more
information.**

**Comment by DaveDavenport** [comment]
odd, works fine for me.

**Comment by DaveDavenport** [comment]
Can you test git, should be fixed.

**Comment by cinghiopinghio** [comment]
Good, it does work now. Thanks

**Comment by DaveDavenport** [comment]
thanks for reporting back.
