### ISSUE TITLE
rofi.kb-mode-next is not working with custom modis

### ISSUE THREAD

**Issue by ortango** [davatorium/rofi#1059]
## Version

Version: 1.5.4-64-g03775378 (makepkg)

## Configuration

[rofi -h](https://gist.githubusercontent.com/ortango/3a95d8a01d04c60a1e58034244ae93c3/raw/3a22818489ddbb75651556302c9d07c4437094f1/rofi.log)

## Launch Command

`rofi -modi "custom1:script.sh,run,custom2:script.sh arg,ssh" -show custom1`

## Steps to reproduce

run the command and try to navigate the modi's

## What behaviour you see

if the shown modi is a custom one then kb-mode-next doesn't work. if it is a builtin mode than navigation works fine. kb-mode-previous seem to work fine either way.

## What behaviour you expect to see

normally the next modi regardless of builtin or custom would be displayed

**Additional details:**
this started a few commits ago, it is not new from todays commit (it was introduced at or around the time bug #1057 was introduced)

**Comment by DaveDavenport** [comment]
should be fixed.

**Comment by ortango** [comment]
wow. yep, thanks.
