### ISSUE TITLE
window-match-fields specification seemingly unused by Rofi

### ISSUE THREAD

**Issue by kgilmer** [davatorium/rofi#1062]
## Version

Output of `rofi -v`
`Version: 1.5.4`

## Configuration

Output of `rofi -help`: 
https://gist.github.com/kgilmer/23e63b621656456e440271de5205422a

## Launch Command

`rofi -window-match-fields title -show window`

## Steps to reproduce

- Launch Rofi in window mode, specifying only title column.

## What behaviour you see

- Display in window mode does not change regardless of any `window-match-fields` value.  If I specify an invalid value (`asdf`), get a warning so it appears that Rofi is parsing the parameter but does not seem to have any effect.

## What behaviour you expect to see

- Output of window list should only include title, not the default "all"

**Additional details:**

I've tried both specifying `window-match-fields` on both command line and via Xresources.  Neither seem to produce any change in Rofi's behaviour.

```bash
$ ./rofi -dump-Xresources | grep window-match
rofi.window-match-fields:            name
```

**Comment by DaveDavenport** [comment]
are you talking about matching or displaying?

To modify what is shown, use : `window-format` option.

**Comment by kgilmer** [comment]
Oh, I misunderstood the the intention of `window-match-fields`.  Works as expected.  Thank you for your time!

**Comment by DaveDavenport** [comment]
np. happy this works.
