### ISSUE TITLE
Program gets launched without accessing environment variable

### ISSUE THREAD

**Issue by nkakouros** [davatorium/rofi#1065]
First, I have gone through the shell environment issues and I think mine is a bit different.

I am trying to run Viber on a HiDPI screen. For Viber to scale correctly the `QT_DEVICE_PIXEL_RATIO` env variable needs to be set to 2. I set this variable in an `/etc/profile.d/` script.

After I log into my system and open a bash terminal, if I type `echo $QT_DEVICE_PIXEL_RATIO`, `2` is returned as expected. Also, if I type `viber` in bash, Viber is launched scaled correctly.

If I do, still in bash,:

```
rofi -show run -run-command "bash -c 'echo $QT_DEVICE_PIXEL_RATIO'"
```

`2` is again printer correctly.

Now, if I run `rofi -show run` (still in bash) and launch 'viber' from there, Viber is not launched correctly, probably due to the environment variable not being there.

If I do:

```
rofi -show run -run-command "bash -c 'viber'"
rofi -show run -run-command "bash -c 'QT_DEVICE_PIXEL_RATIO=2 viber'"
rofi -show run -run-command "bash -c 'env QT_DEVICE_PIXEL_RATIO=2 viber'"
```

or use `{cmd}` instead of `viber` in the three commands above, Viber is still not scaled correctly. 

To test this further, I created a script under `/usr/bin/qqq` containing:

```
echo $QT_DEVICE_PIXEL_RATIO
```

and then used `rofi -run show` to launch it. `2` shows as expected.

Do you have any insight to share on the above that could help me find out what is wrong with launching Viber from rofi?

**Comment by sardemff7** [comment]
Please fill **all** the information requested, it is important for future reference.

First :
```
rofi -show run -run-command "bash -c 'echo $QT_DEVICE_PIXEL_RATIO'"
```
is wrong: the `"` will not protect the `$` so the variable is expanded *before* even running rofi. So it doesn’t test what you think it’s testing, and makes the results of the other tests unreliable for comparison.

Your last test seems to work, but your script is incomplete, you didn’t put the shebang (or it doesn’t have one which probably falls back to some system default we don’t know about).

AFAIK, rofi doesn’t remove any env, so I would suspect bash first here. Again, “an `/etc/profile.d/` script” doesn’t say much. I could assume you mean a script with only `export QT_DEVICE_PIXEL_RATIO=2` but you could have some extra logic in there (like a condition on the screen you use or whatever, though that would be the wrong place).

**Comment by nkakouros** [comment]
After playing a bit more with it, I think it is a Qt or Viber issue.
