### ISSUE TITLE
[REQUEST] Append arguments to drun modi when modifier is pressed

### ISSUE THREAD

**Issue by Kabouik** [davatorium/rofi#1067]
### Description
Add a config option to set custom arguments to be used when launching an application from drun with `modifier + Return`.

### Rationale
When using Rofi with a tiling WM, it would be useful to be able to append arguments to applications launched from the drun modi. For instance, `--name XXX` would allow setting a class name "XXX" to any GTK application (I think), and this class could then be used by the WM to apply special rules to corresponding windows (_i.e_, run them in floating mode).

### Example
Let's say running something from the drun modi with the `Shift` modifier appends custom characters, which could be configured in the rofi config. One could set the custom arguments to `--name floating` to launch applications with the `floating` instance, and then make a rule in i3 to automatically display these applications in floating mode with the following in the i3 config: `for_window [instance="floating"] floating enable`.

Applications executed the regular way (without `Shift` modifier) would preserve their default instance and therefore be displayed in tiling mode.

### What would be necessary
- Config option to set custom arguments for drun modi
- Config option to set a modifier key to use these arguments (_i.e._, `Shift`)

### Rofi version
Version: 1.5.4

**Comment by Kabouik** [comment]
Sorry, I elaborated.

**Comment by vdegenne** [comment]
Any news about this feature, that would be very useful in fact

**Comment by DaveDavenport** [comment]
wouldn't it be better to update the desktop file? this would be more inline with how the desktop-file system work, and should work across launchers.

copy the desktop file in `~/.local/share/applications/` and modify the Exec line.

**Comment by Kabouik** [comment]
Thanks for your reply @DaveDavenport. I don't think modifying the desktop files would solve the issue, as I didn't want to permanently alter the flags or arguments when running particular programs, but instead be able to use generic flags or arguments on multiple programs _only when the modifier is used_. I'm sorry if I just am missing something.

**Comment by DaveDavenport** [comment]
Closing this one. If you want variations of your program in drun use the facilities provided by the desktop file system. 
You can define multiple 'actions' in a desktop file and rofi does support these when enabled.
