### ISSUE TITLE
'-eh' option ignored

### ISSUE THREAD

**Issue by vredesbyyrd** [davatorium/rofi#1069]
## output of rofi -v

Version: 1.5.4-72-gf8c3d694

## Launch Command

`echo -en "a\nb\x0fc\nd" | rofi -dmenu -sep '\x0f' -eh 2 `

## Steps to reproduce

* run above command on commit >= 618d1396eefea6ea26d954e44015c1fa422801f3

## What behavior you see

* Line height option ignored

![rofi-2020-03-15-2014-00000](https://user-images.githubusercontent.com/22080838/76715535-c8815e00-66fa-11ea-9002-4edaa6158925.png)

## What behavior you expect to see

![rofi-2020-03-15-2026-00000](https://user-images.githubusercontent.com/22080838/76715671-5c532a00-66fb-11ea-9299-1df2403ee68c.png)

## Additional info

Beginning with 618d1396eefea6ea26d954e44015c1fa422801f3 the `-eh` option seems to be ignored.

I built the latest commit to take advantage of the newly add jpg support :)  but noticed that "multi-line output" via `-eh` no longer works. 

Thanks for your time.

**Comment by DaveDavenport** [comment]
Yeah, that needs to be fixed.   Thanks. (did not know people used this option :-D).

**Comment by vredesbyyrd** [comment]
For a few scripts of mine I have found it the best way to display information. In conjunction with markup it can be useful when trying to pack a lot of data in a small area, imo. e,g a little buku frontend

![rofi-2020-03-16-1409-00001](https://user-images.githubusercontent.com/22080838/76793029-4775a580-6792-11ea-8b9c-bb311044a653.png)

**Comment by blueForestIcarus** [comment]
I can't seem to figure out if rofi supports multiline entries of different heights. I'd like to be able to make '|' my separator and have line height based on the number of lines.

**Comment by DaveDavenport** [comment]
@blueForestIcarus please follow the guidelines and do not hijack issues.

**Comment by DaveDavenport** [comment]
can you test last commit?

**Comment by vredesbyyrd** [comment]
My one observation is it appears that `if -eh > 1, height = -eh + 1` ? Sorry for the pseudo code. 

Prior to commit 618d1396eefea6ea26d954e44015c1fa422801f3

![rofi-2020-03-29-1611-00000](https://user-images.githubusercontent.com/22080838/77861372-3d17ca80-71da-11ea-8a10-65e5dab5a4c7.png)

Latest commit ca067234ff70ffc17b820233dd958fd6ec699587

![rofi-2020-03-29-1605-00000](https://user-images.githubusercontent.com/22080838/77861433-7e0fdf00-71da-11ea-834f-ed36bea46444.png)

Is it possible to vertically align to `0.5` so that the lines content is centered?  No luck through theming. 

Thanks for the fix.

**Comment by DaveDavenport** [comment]
you can center using the theme (it has vertical/horizontal align option).

can you actually give the command you use? this way its hard to check.

**Comment by DaveDavenport** [comment]
missed a -1.. hope it is ok now..

**Comment by DaveDavenport** [comment]
add `echo -en "a\nb\x0fc\nd" | rofi -dmenu -sep '\x0f' -eh 2 ` to align.

**Comment by vredesbyyrd** [comment]
Rebuilt and it looks right on, so that fixed it. Appreciate the fix and guidance. Closing.
