### ISSUE TITLE
Build Failure [BUG] 

### ISSUE THREAD

**Issue by yoruba-codigy** [davatorium/rofi#1070]
## Please Help

I Cloned Rofi And Wanted And Ran The configure script

## Output

checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking for flex... flex
checking lex output file root... lex.yy
checking lex library... -lfl
checking whether yytext is a pointer... yes
checking for bison... bison -y
checking for a sed that does not truncate output... /usr/bin/sed
checking for grep that handles long lines and -e... /usr/bin/grep
checking for gawk... gawk
checking for flex version... 2.6.4
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking whether make sets $(MAKE)... yes
checking whether make supports the include directive... yes (GNU style)
checking whether make supports nested variables... yes
checking dependency style of gcc... none
checking whether make supports nested variables... (cached) yes
checking whether we are using the GNU C compiler... (cached) yes
checking whether gcc accepts -g... (cached) yes
checking for gcc option to accept ISO C89... (cached) none needed
checking whether gcc understands -c and -o together... (cached) yes
checking for gcc option to accept ISO C99... none needed
checking how to run the C preprocessor... gcc -E
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking minix/config.h usability... no
checking minix/config.h presence... no
checking for minix/config.h... no
checking whether it is safe to define __EXTENSIONS__... yes
checking for ranlib... ranlib
checking for ar... ar
checking the archiver (ar) interface... ar
checking for getline... yes
checking for open... yes
checking for sysconf... yes
checking for strtok_r... yes
checking for flock... yes
checking for ftruncate... yes
checking for fcntl... yes
checking for setlocale... yes
checking for atexit... yes
checking for glob... yes
checking for strchrnul... yes
checking math.h usability... yes
checking math.h presence... yes
checking for math.h... yes
checking for library containing floor... -lm
checking for library containing ceil... none required
checking sysexits.h usability... yes
checking sysexits.h presence... yes
checking for sysexits.h... yes
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
../configure: line 5995: syntax error near unexpected token ->bindings'
../configure: line 5995: NK_INIT(bindings xdg-theme)'

## System 
Terminal Emulator: qterminal
OS: Kali Linux
Shell: Zsh

**Comment by DaveDavenport** [comment]
Please follow the build instructions as described in the INSTALL file:
https://github.com/davatorium/rofi/blob/next/INSTALL.md#install-a-checkout-from-git

It sounds like you did not do a recursive checkout.
