### ISSUE TITLE
[BUG] Icons - bad rendering

### ISSUE THREAD

**Issue by vtnpp** [davatorium/rofi#1073]
## Version

```
rofi -v
Version: 1.5.4
```

## Configuration

```
rofi -help
```
[Gist](https://gist.github.com/vtnpp/3c53eb12d15ffc2c1867c0995c22a658)

## Launch Command

```
rofi -show drun
```

## Steps to reproduce

1. Use [My config.rasi](https://gist.github.com/vtnpp/1617d565cd8c957b290dd742d8085c2c)
2. Install `papirus-icon-theme`
3. Launch rofi: `rofi -show drun`

## What behaviour you see

- Icons look somewhat washed-out/blurry

![rofi_icons_blurred](https://user-images.githubusercontent.com/59181811/77122502-102b2100-6a3e-11ea-8ff7-affd4b691e61.png)

## What behaviour you expect to see

- Wish the icons would look clear, like on this screenshot (from another user).

![rofi_icons_ok](https://user-images.githubusercontent.com/59181811/77122505-115c4e00-6a3e-11ea-9fc2-405b11edbae1.png)

Notice how different the GIMP icon looks between the two screenshots, since this is the only one in common. The difference is still pretty noticeable for other icons though.

I'm using Arch Linux + bspwm for info.

Any idea?

**Comment by vtnpp** [comment]
Ok, I fixed it by switching to [`rofi-git`<sup>AUR</sup>](https://aur.archlinux.org/packages/rofi-git/) and adding:

```
element-icon {
    size: 18;
    border: 0px;
}
```

to `config.rasi`. Turns out `size` value has to match any of those from `Papirus-Dark` icons (`/usr/share/icons/Papirus-Dark`) such as 16x16 ; 18x18, 22x22 etc., otherwise the icons will render just bad.

- Before:
![screen_rofi_before](https://user-images.githubusercontent.com/59181811/77122502-102b2100-6a3e-11ea-8ff7-affd4b691e61.png)

- After:
![screen_rofi_after](https://user-images.githubusercontent.com/59181811/77184499-38636000-6ad0-11ea-834a-ce79cd7f5634.png)

**Comment by DaveDavenport** [comment]
It will request the closest icon and scale it to the size.   This will result in some fuzzy icons.
