### ISSUE TITLE
[REQUEST] variable multiline items

### ISSUE THREAD

**Issue by blueForestIcarus** [davatorium/rofi#1076]
I can't seem to figure out whether or not rofi supports multiline entries of different heights. I'd like to be able to make '|' my separator and have line height based on the number of lines.

Is there any way to do variable height multiline? I put this as a feature request because it doesn't seem like this is supported, but I've seen conflicting information on forums. If there is a way to do this it could be better documented.

**Comment by DaveDavenport** [comment]
There is no support for having entries with different heights .
It is also something I consider to be out of the scope of rofi. For two reasons:
* It breaks the simple interface of rofi. The interface and placing of the content won't be consistent anymore and will vary with scrolling. If this is required? is a simple selection menu still the right tool for the job?
* Having a variable number of visible entries, would require a significant increase in complexity of the underlying code. More code and complex code will increase maintenance, and I currently have very little time to work on rofi as it is.

**Comment by jgonsior** [comment]
I'd like to have multiline items as well to achieve something like [Alfred](https://www.alfredapp.com/media/pages/home/search.jpg) looks like.

**Comment by DaveDavenport** [comment]
(fixed number of lines per) multi-line rows have been possible for a long time .

**Comment by jgonsior** [comment]
Oh, perfect! I can't find the right configuration options - where do I look for multi-line rows?

**Comment by DaveDavenport** [comment]
`-eh` element height (in lines of text.)

**Comment by jgonsior** [comment]
Thanks! Now the last question - how do I get -drun-display-format to work such that a line break is inserted?
I've tried `rofi -show drun -modi drun -drun-display-format "{name}\n\r{generic}" -eh 2` but the line breaks are ignored and just displayed.

**Comment by jgonsior** [comment]
So I think the problems lies in the parsing of the pango format string as `\n` is ignored there, and <br> f. e. does not work.
When using something like `echo "a\nb|c\nd|e\nf" | rofi -sep '|' -dmenu -eh 2` the newline `\n` results in a multiline entry, but when using `rofi -show drun -modi drun -drun-display-format "{name}\n{generic}" -eh 2` it gets displayed in a single line with `\n` in between.

**Comment by DaveDavenport** [comment]
That is because you are not passing a a newline. 
```
rofi -show drun -modi drun -drun-display-format "{name}
{generic}" -eh 2
```
will work.

**Comment by sardemff7** [comment]
Tip: shells support the `$'\n'` syntax if you need to add a specific character literally, i.e. `rofi -show drun -modi drun -drun-display-format "{name}"$'\n'"{generic}" -eh 2`

**Comment by DaveDavenport** [comment]
I am closing this one as the original issue is never fixed.
