### ISSUE TITLE
[REQUEST] Disable Super+number to execute 

### ISSUE THREAD

**Issue by JoshuaJChan** [davatorium/rofi#1078]
I am using Openbox with rofi. I start up rofi using Super+F2, but if I want to switch workspaces(e.g. 3rd workspace), so I press Super+3 right after. What this actually does is execute the 3rd command on the rofi dropdown menu, which is not what I want. One time, I've made a mistake by executing poweroff. Is it possible to disable this keybinding?

**Comment by carnager** [comment]
`rofi -show run -kb-select-2 ""`
