### ISSUE TITLE
Add `-combi-default-mode` option

### ISSUE THREAD

**Issue by danjenson** [davatorium/rofi#1084]
Can we implement `--combi-default-mode {run,ssh,...}`, which will execute when combi mode has no direct match? On execution, it checks if there is a default and if so uses that to try to execute the arguments. I find this super useful because I wrote a script that allows me to type stuff like `chrome 3` and it will fuzzy match the `google-chrome-stable` binary and then run `bsprc desktop -f ^3 && google-chrome-stable` (opens chrome in desktop 3). It would be awesome to just run `chrome 3` instead of `!r chrome 3` in rofi and hand it off to this script running via `-run-command`. Tl;dr this provides a default mode when there are no filter matches and makes running a command more ergonomic.

Here is an example usage:
```
  rofi \                                                                            
    -run-command "/home/$USER/.config/rofi/run.sh \{cmd\}" \      
    -show combi \                                                                   
    -modi combi \
    -combi-default-mode run  # uses `run` mode when no matches in rofi
```

**Comment by danjenson** [comment]
I added example usage, I'm not sure what else you're looking for. This was in a previous task and I was asked to open a new issue -- it's not implemented yet AFAIK.

**Comment by DaveDavenport** [comment]
Similar to: #813

**Comment by DaveDavenport** [comment]
This applies to versions <= 1.5.4 as of posting.

**Comment by DaveDavenport** [comment]
From 011908e1ffda06d09c9f163867cb6a7d68fd6c20 uses first modi if there is no direct match to handle input.
