### ISSUE TITLE
[REQUEST]  From rofi launcher to edit certain file by keybinding.

### ISSUE THREAD

**Issue by thepenguinthatwants** [davatorium/rofi#1085]
```
rofi -v
Version: 1.5.4

```

I use i3wm and I have some bash scripts that opens up a list of stuff by piping cat sed and rofi to list files to easily open certain files.

The problem is that sometimes I want to edit the lists or files.
Is there possibility to add into rofi that it allows using keybindings ctrl-e to edit certain file after opening the rofi launcher?

**Comment by carnager** [comment]
```#!/usr/bin/bash

main () {
    menu="$(echo -e "1\n2\n3\n4\n" | rofi -dmenu -kb-move-end "" -kb-custom-1 "Control-e")"
    exit_status=$?

    case "${exit_status}" in
        "10") echo "Control+e has been pressed" ;;
        "0") exit ;;
         *) : ;;
    esac
}

main
```

`-kb-move-end ""` is needed, because there already exists a keybind for this. This will disable it.
each `kb-custom-n` returns a different exit code, starting from 10.
