### ISSUE TITLE
[BUG] Escaping % char in desktop files Exec doesn't work

### ISSUE THREAD

**Issue by Kiblyn11** [davatorium/rofi#1087]
## Version

```                 
Version: 1.5.4
```

## Configuration

https://gist.github.com/Kiblyn11/6a3bf9839e9643951bfd6ea609702000
Config file in .config/rofi is blank

## Launch Command

```
rofi -combi-modi window,drun -show combi -modi combi
```

## Steps to reproduce

- Have a desktop file with an escaped percent (%%) in Exec=
Example: `Exec= env G_TLS_GNUTLS_PRIORITY=NORMAL:%%COMPAT:+VERS-TLS1.0 evolution %U`
- Launch rofi
- Launch this desktop file

## What behaviour you see

Running rofi with debug messages:
```
Dialogs.DRun-WARNING **: 15:22:21.816: Invalid field code in Exec line: env G_TLS_GNUTLS_PRIORITY=NORMAL:%%COMPAT:+VERS-TLS1.0 evolution %U.
```

## What behaviour you expect to see

According to specification, using double percent should escape the percent and not be considered a field.  So it should consider %%COMPAT to not be a field and perform the exec command as so:
```
env G_TLS_GNUTLS_PRIORITY=NORMAL:%COMPAT:+VERS-TLS1.0 evolution %U
```

Specification: https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html
"Field codes consist of the percentage character ("%") followed by an alpha character. Literal percentage characters must be escaped as %%."

**Comment by DaveDavenport** [comment]
If I have a double %% I don't get ` Invalid field code in Exec line:` .  If I look at the code, the replacement regex does not match %%. (so it will output %%COMPAT.) 

I will fix this, but not sure why you get that message.. (if there is not a double %% as in your actual example, I do get the error, but that is correct.).

**Comment by DaveDavenport** [comment]
Can you test git?

Now:
```
Parsed into command: env G_TLS_GNUTLS_PRIORITY=NORMAL:%%COMPAT:+VERS-TLS1.0 evolution %U into env G_TLS_GNUTLS_PRIORITY=NORMAL:%COMPAT:+VERS-TLS1.0 evolution .
```

**Comment by Kiblyn11** [comment]
My bad I pasted the wrong command in my example in 'Steps to reproduce'.
This is the line causing me trouble:
`Exec= env G_TLS_GNUTLS_PRIORITY=NORMAL:%%COMPAT:+VERS-TLS1.0 evolution %U`

**Comment by Kiblyn11** [comment]
Trying 
`Exec=env G_TLS_GNUTLS_PRIORITY=NORMAL:%COMPAT:+VERS-TLS1.0 evolution %U`
instead of
`Exec=env G_TLS_GNUTLS_PRIORITY=NORMAL:%%COMPAT:+VERS-TLS1.0 evolution %U`
Gives me this in logs
```
Dialogs.DRun-WARNING **: 20:59:34.737: Invalid field code in Exec line: env G_TLS_GNUTLS_PRIORITY=NORMAL:%COMPAT:+VERS-TLS1.0 evolution %U.
```

**Comment by Kiblyn11** [comment]
I created a gist with a simplified corresponding desktop file triggering the error.
https://gist.github.com/Kiblyn11/84386920355696afd706db15592bdcd1

**Comment by DaveDavenport** [comment]
did you try git?

**Comment by Kiblyn11** [comment]
My mistake, no.
So I just did it and there is no problem on latest git revision.

**Comment by DaveDavenport** [comment]
thx.
