### ISSUE TITLE
Ability to combine distances in rofi theme files [REQUEST] 

### ISSUE THREAD

**Issue by 9las** [davatorium/rofi#1088]
I would like to be able to combine distances in rofi theme files. Specifically I would like to be able to subtract/add {Real}% and {Integer}px. E.g. 100%-37px. That way I would e.g. be able to set polybar height to some fixed value in pixels (37px in this case) and let the rofi window fill the rest of the monitor. This way the polybar would always have the same height no matter the monitor and the rofi window would take up the remaining height.

Polybar does have this [function](https://github.com/polybar/polybar/wiki/Configuration) (look under the bar settings width and height).

I have tried to make the polybar window fill up the remaining height of the monitor by setting the height of the window to 100% and the margin to 37px 0 px 0 px, but then i get a visible outline around the invisible margin of the window, which I do not want.

Rofi version: 1.5.4

**Comment by DaveDavenport** [comment]
made a first implementation on the i1088 branch.

It is not done, one of the biggest limitations is that there needs to be spaces around the (math)  + and -.

and if you dump theme, it is not yet printed.

**Comment by DaveDavenport** [comment]
A good suggestion from @sardemff7 , I will probably make it work with css format.
https://www.w3schools.com/cssref/func_calc.asp

**Comment by DaveDavenport** [comment]
Implemented the `calc()`.

**Comment by 9las** [comment]
Awesome!
