### ISSUE TITLE
[BUG] Rofi doesn't show the placeholder

### ISSUE THREAD

**Issue by dlasagno** [davatorium/rofi#1090]
## Version

`1.5.4`

## Configuration

No configuration: used `-no-config` option when launching rofi.

## Launch Command

`rofi -no-config -theme-str 'entry { placeholder: "type to filter"; placeholder-color: grey;}' -show combi`

## Steps to reproduce

- Launch the above command

## What behaviour you see

- The entry box is empty

## What behaviour you expect to see

- The entry box should display the specified placeholder

**Additional details:**
![image](https://user-images.githubusercontent.com/25227413/79635481-7c01c600-8171-11ea-8fe6-184f7c259017.png)

**Comment by DaveDavenport** [comment]
This feature is not in 1.5.4.
