### ISSUE TITLE
[REQUEST] Support plugin-path in configuration files

### ISSUE THREAD

**Issue by jluttine** [davatorium/rofi#1091]
**Describe the feature**

The plugin path can be given as a command line argument, but based on `rofi -dump-xresources`, it cannot be set in the configuration file. It would be great if it could be because then a system admin could set the default plugin path in the system-wide default configuration file (e.g., `/etc/rofi.conf`) without needing to compile rofi with different compile-time flags (which is much more difficult task to perform and maintain). Also, I would have expected all command line options (or as many as possible) to be configurable also in the configuration file.

Also, in some systems like NixOS, each package is installed in its own unique store path (e.g., `/nix/store/l8xrdpa9a13a1gcc0gwpjlcgi34r69vv-rofi-1.5.4`), so the plug-ins need to be installed under some other store paths and those paths aren't known when rofi itself is built (because rofi might be a dependency of those plug-ins). In that case, the system-wide default plug-in location can be set only after rofi has been already built and then the configuration file would be a natural place to put such default plug-in path definitions.

And finally, a user might want to install plug-ins in their home directory. Then it would be nice if the user could set that plug-in path in the configuration file `XDG_USER_CONFIG_DIR/rofi/config` without needing to always give the flag `-plugin-path` when calling rofi.

**When reporting a feature request include the following information:**

```
$ rofi -v
Version: 1.5.4
```

**Comment by jluttine** [comment]
Perhaps #1096 should be preffered over this one? I don't know. I'd be happy with either solution.

**Comment by DaveDavenport** [comment]
Is an environment variable now.

**Comment by jluttine** [comment]
Wow, thanks a lot, this is superb! :ok_hand:
