### ISSUE TITLE
[REQUEST] Improved support for repeated CLI options

### ISSUE THREAD

**Issue by jluttine** [davatorium/rofi#1092]
**Describe the feature**

If given a same CLI option multiple times, rofi seems to take into account only the first occurrence and ignore the other occurrences:

```
$ cat rofi-1.conf
rofi.width: 90

$ cat rofi-2.conf
rofi.columns: 2

$ rofi -show drun -modi drun -config rofi-1.conf -config rofi-2.conf
```

The outcome is that rofi opens 90% wide but not with two columns. So, clearly rofi only takes into account the first `-config` option occurrence.

However, it would good if instead rofi either:

a. took into account the last occurrence or
b. took into account them all by merging them.

A few reasons why I would prefer either a or b compared to the current behavior:

- If I define `alias rofi=rofi -config=~/my-rofi.conf`, I cannot overwrite that command-line option anymore with `rofi -config ~/other.conf` which feels counter-intuitive.
- Similarly, if rofi is wrapped so that some default command-line arguments are passed, those cannot be overwritten. Especially, because the plugin-path cannot be even defined in the configuration file, it needs to be defined as a command-line argument, so wrapping/alias sounds like a natural solution.
- As far as I understand (but I may be wrong), it's a typical behavior in Linux tools.

I don't see any reason/usecase why the first occurrence should be preferred, but I might be missing something.

**When reporting a feature request include the following information:**

```
$ rofi -v
Version: 1.5.4
```

**Comment by DaveDavenport** [comment]
changing this would break rofi behavior with the past.  I would like to avoid this.
(it behaved like this before I forked it.).

**Comment by jluttine** [comment]
Does something really rely on the current behavior? That sounds really weird. What usecase am I not understanding?

Also, this reminds me of https://xkcd.com/1172/ :smile:

**Comment by jluttine** [comment]
I think option (b) would be quite awesome for options that can be merged - like config files. One could use a bit modular approach to define the configuration and then do `rofi -config base.conf -config desktopenvironment.conf -config personal.conf` to have hierarchical or topic-divided configuration files. Sounds quite powerful to me.

**Comment by jluttine** [comment]
Ok, seems that POSIX accepts any kind of interpretation: "Options may be supplied in any order, or appear multiple times. The interpretation is left up to the particular application program." https://www.gnu.org/software/libc/manual/html_node/Argument-Syntax.html

So, at least the current behavior or any of those I suggest are all equally ok in terms of POSIX standard, if I understand correctly.

**Comment by DaveDavenport** [comment]
I am not going to change this. Everytime I change behaviour I get a lot of complaints in emails and on the issue tracker.. 

Also, If you always pass an option, put it in the config file. Don't pass it in an alias (yes you can load another config file from the config file).

**Comment by jluttine** [comment]
Ok, I understand. Just for the record: as mentioned, for instance, `-plugin-path` cannot be set in the configuration file so it needs to be passed as a command-line argument every time. Then, aliasing/wrapping becomes quite natural a solution.

Oh, nice that one can import config files in other config files. I couldn't find any information about this (probably just not looking for the right keywords). How can it be done in `rofi.conf` and where is it documented?

**Comment by jluttine** [comment]
I made another request that actually solves my usecase in a much better way: #1096.

**Comment by jluttine** [comment]
By the way, this behavior is different from how dmenu works:

```
printf "foo\nbar\n" | dmenu -p "Prompt A" -p "Prompt B"
printf "foo\nbar\n" | rofi -dmenu -p "Prompt A" -p "Prompt B"
```

dmenu shows "Prompt B" but rofi shows "Prompt A". Probably not a big deal, but just thought I'd mention now that I happened to discover this difference.
