### ISSUE TITLE
Window previews.

### ISSUE THREAD

**Issue by m-kru** [davatorium/rofi#1094]
Is there any way to get window previews in rofi window switch mode? I have realized, that switching windows in tiling windows managers, when the window I am looking for is not on the current work space, takes me much more time than for example in Cinnamon where I have the windows previews.
The human brain is able to acquire and process much more information by looking at the picture than by reading the text. Assuming the same exposure time.

**Comment by DaveDavenport** [comment]
Option `-window-thumbnail` exists.  If an image can be grabbed it shows it.

**Comment by m-kru** [comment]
@DaveDavenport How to run it? I can't find any information in the manual or help.

**Comment by m-kru** [comment]
Ok, look like Arch has not updated rofi package for quite long. I have to do manual install.

**Comment by m-kru** [comment]
@DaveDavenport what do you mean by 

> If an image can be grabbed it shows it.

I have set this option to true, and there is no effect in bspwm.

**Comment by sardemff7** [comment]
Read carefully, he said “If an image can be grabbed it shows it.”
The implementation asks the X server for an image, so it depends whether the window is mapped and has content. I may need a compositor in some cases and with some WMs. This has nothing to do with rofi.
