### ISSUE TITLE
how to get rofi switch window work on dwm?

### ISSUE THREAD

**Issue by lyjdwh** [davatorium/rofi#1095]
# Version

Version: 1.5.4

## Configuration

the default configuration

## Environment

manjaro dwm-6.2

## Launch Command

rofi -show window

## Steps to reproduce

- rofi -show window
- choose a window and enter

## What behaviour you see

it doesn't switch window

## What behaviour you expect to see

switch window

**Comment by DaveDavenport** [comment]
Rofi uses [EWMH](https://en.wikipedia.org/wiki/Extended_Window_Manager_Hints)  to switch between windows.  Does DWM implement this?

**Comment by DaveDavenport** [comment]
This is what rofi calls:
```c
xcb_ewmh_request_change_active_window
```

**Comment by lyjdwh** [comment]
It seems DWM doesn't support EWMH.
Thanks for your help!

**Comment by alesandar** [comment]
@lyjdwh, you could use this patches, in order to achieve what you want:
- https://dwm.suckless.org/patches/ewmhtags
- https://dwm.suckless.org/patches/focusonnetactive/

**Comment by lyjdwh** [comment]
@alesandar it really works, thanks!

**Comment by alesandar** [comment]
You're welcome. It was not necessary to patch ewmhtags, but you're already looking for EWMH support and it might be useful if you decide to use polybar or anything similar in the future. However, you may find focusonnetactive a little bit obtrusive, because popup windows may also change your current view.

**Comment by LanderMoerkerke** [comment]
Nice solution, is it possible to see the tag number or something similar just like in i3wm?
