### ISSUE TITLE
Ordering of results doesn't make sense (even with Levenshtein enabled)

### ISSUE THREAD

**Issue by farzadmf** [davatorium/rofi#1100]
## Version

Version: 1.5.4

## Configuration

[https://gist.github.com/farzadmf/af6f84b98b104598f4a3af4d9a4b6958](https://gist.github.com/farzadmf/af6f84b98b104598f4a3af4d9a4b6958)

## Launch Command

`rofi -theme purple -matching fuzzy -show drun -modi run,drun,ssh,window -drun-show-actions`

## Steps to reproduce

- Launch `rofi`; I'm using `i3` and my shortcut key is `Shift+$mod+d`
- Type `vscode`

## What behaviour you see
Screenshot:
![rofi-2020-04-20-1700-00000](https://user-images.githubusercontent.com/5768792/79799519-8e723000-8328-11ea-95c7-35032e2e3393.png)

As you can see in the screenshot, the first match is, surprisingly, `Buka`, which does not contain even a single character of `vscode`!

I also use shortcut `Alt + Grave` to enable Levenshtein sort, but this is what I see:
![rofi-2020-04-20-1702-00000](https://user-images.githubusercontent.com/5768792/79799674-dabd7000-8328-11ea-8ac6-2af4a050922e.png)

## What behaviour you expect to see

I expect the sorting to better match the underlines I see in the menu. In the menu being shown, there are underlines under **V**isual **S**tudio etc., but the order of results doesn't make sense for me

**Comment by DaveDavenport** [comment]
I agree this example is confusing. DRun matches invisible fields,  you can tweak what it matches/displays using the drun configuration options.

**Comment by DaveDavenport** [comment]
See:
`-drun-match-fields [string]             Desktop entry fields to match in drun`
and
`	-drun-display-format [string]           DRUN format string. (Supports: generic,name,comment,exec,categories)`

**Comment by farzadmf** [comment]
Thank you @DaveDavenport for your very quick replay, changing `-drun-match-fields` seems to greatly improve what I see.

Now my launch command is this:
```
rofi -theme purple -matching fuzzy -show drun -modi run,drun,ssh,window 
  -drun-show-actions -drun-match-fields name,generic,categories
```

Do you think I'd be missing out on results with this setting?

**Comment by DaveDavenport** [comment]
That is what I mostly use. seems good enough.

**Comment by MaskRay** [comment]
https://github.com/MaskRay/ccls/blob/master/src/fuzzy_match.cc has a simple fuzzy searching implementation and it works pretty well in practice.

I thought about contributing it but rofi grabs mouse/keyboard so it is really difficult to debug.

```
cgdb --args Debug/rofi -dmenu -sort -matching fuzzy -input /tmp/p/ctags/tags
r
# My mouse/keyboard is locked. I have to switch to a virtual console to kill gdb.
```
