### ISSUE TITLE
[REQUEST] Support no custom entries in script mode

### ISSUE THREAD

**Issue by jluttine** [davatorium/rofi#1101]
I already mentioned this idea in IRC, but here's a bit more detailed explanation.

To understand what I'm after, run `rofi -show drun -modi drun` and type some gibberish in the input field until all application are filtered out from the list. Now, press Enter. Nothing happens. The gibberish text doesn't disappear, the list stays filtered out, nothing happened. Perfect! Drun doesn't accept custom entries so it's not possible to choose such. I'd like this to be possible in script mode too.

In script mode, there are some mode options that can be passed in this way: `echo -en "\0prompt\x1fChange prompt\n"`. There's no possibility to pass `no-custom` option in this way. Therefore, it is not possible (or at least easy) to write a script that wouldn't accept custom entries. There is the environment variable `ROFI_RETV=2` to tell the script that a custom entry was selected but this isn't quite the same as not accepting it in the first place. Here's why:

1. The script gets the gibberish text as the argument, so if it's a multi-stage script called potentially multiple times, the script cannot know which stage it was in without keeping some state handling in a file (or elsewhere).

2. Even if the script would magically know where it was and could continue from there, the input field gets emptied, that is, the gibberish disappears. This is different from how `-no-custom` works.

Consider the following simple script which lets the user first select either `letter` or `number` and then gives a list of letters or numbers, respectively:

```
#!/usr/bin/env bash

if [ -z "$@" ]
then
        echo "letter"
        echo "number"
        exit 0
fi

if [ x"$@" = x"letter" ]
then
        echo "alpha"
        echo "beta"
        exit 0
fi

if [ x"$@" = x"number" ]
then
        echo "one"
        echo "two"
        exit 0
fi
```

Now, consider that at some stage (either at the first question or the following), the user inputs some gibberish `asdfghjkl`. When the script receives this input, the script cannot know, for which question this answer was to, so the script cannot show that question again. Perhaps the only sensible things would be to just quit, raise an error or show the first question. None of these is equivalent to just not allowing custom entries in the first place. And as I said, even if the script did some internal book keeping with files and then could determine which question it was showing and show it again, the rofi input field would anyway get emptied.

So, I'd suggest adding support for not accepting custom entries in script mode by doing something like `echo -en "\0no-custom\x1f\n"`(you know better what would be good). Anyway, the point is that one could set the option with those `\0` and `\x1f` magic.

As a natural follow-up question: Are there other options that are supported by rofi but not in script mode, but it would make sense to add support? I'm not sure about these, but here are the ones I thought could work and make sense:

- `-select`
- `-password`
- `-multi-select`

Requested info:

```
$ rofi -v
Version: 1.5.4-dev
```

**Comment by DaveDavenport** [comment]
Implemented `no-custom`

**Comment by jluttine** [comment]
@DaveDavenport Thanks a lot, works perfectly! :ok_hand: :gem:

**Comment by DaveDavenport** [comment]
These are currently not (easily) implementable for script mode:
```
    -select
    -password
    -multi-select
```
