### ISSUE TITLE
[BUG] Installation: make error regarding resources.xml

### ISSUE THREAD

**Issue by andradei** [davatorium/rofi#1102]
## Steps to reproduce

- Downloaded version 1.5.4 (latest) from [release page](https://github.com/davatorium/rofi/releases)
- Following the wiki for installation to build and install manually
- After doing `mkdir build && cd build/ && ../configure`
- I ran `make` (with and without `sudo`)
- Got:

```
../script/get_git_rev.sh .. ./gitconfig.h
make[1]: Entering directory '/home/andradei/Dropbox/os_config/programs/rofi-1.5.4/build'
../script/get_git_rev.sh .. ./gitconfig.h
make[1]: Leaving directory '/home/andradei/Dropbox/os_config/programs/rofi-1.5.4/build'
mkdir -p ./resources/
../resources/resources.xml  --generate-source --target=resources/resources.c --sourcedir=..
/bin/bash: ../resources/resources.xml: Permission denied
make: *** [Makefile:5118: resources/resources.c] Error 126
```
- Ran `chmod +x ../resources/resources.xml` to solve that problem
- Ran `make` again (with and without `sudo`)

## What behaviour you see

- Got this error:

```
../script/get_git_rev.sh .. ./gitconfig.h
make[1]: Entering directory '/home/andradei/Dropbox/os_config/programs/rofi-1.5.4/build'
../script/get_git_rev.sh .. ./gitconfig.h
make[1]: Leaving directory '/home/andradei/Dropbox/os_config/programs/rofi-1.5.4/build'
mkdir -p ./resources/
../resources/resources.xml  --generate-source --target=resources/resources.c --sourcedir=..
../resources/resources.xml: line 1: syntax error near unexpected token `newline'
../resources/resources.xml: line 1: `<?xml version="1.0" encoding="UTF-8"?>'
make: *** [Makefile:5118: resources/resources.c] Error 2
```

## What behaviour you expect to see

- `resources/resources.xml` would be parsed correctly so the installation can go on

**Additional details:**
- none

**Comment by DaveDavenport** [comment]
Do you have `glib-compile-resources` installed?

**Comment by andradei** [comment]
`glib-compile-resources` was already installed.
I was missing `libglib2.0-dev` (Ubuntu) and the installation went further, now I have a different error. I'm closing this issue and will open a new one for the other error.

Thank you.
