### ISSUE TITLE
Floating window is always the first one on the rofi window list

### ISSUE THREAD

**Issue by m-kru** [davatorium/rofi#1103]
I have realized, that if you have any window in floating state (BSPWM), it will always appears as the first one the `rofi -show window` list. I do not know if this is a feature or a bug. If it is a feature I would like to get to know what is the idea behind this. It breaks user experience in my opinion, as I would like to have all windows sorted in access history order.

**Comment by DaveDavenport** [comment]
Rofi uses the order as set by the window manager. The ' history'  order is not available, so cannot be used.

Next time, do **not** delete the template, but fill in the requested information and follow the guidelines..
