### ISSUE TITLE
[BUG] Installation can't find xkbcommon on Pop!_OS (Ubuntu)

### ISSUE THREAD

**Issue by andradei** [davatorium/rofi#1104]
## Version

Error during installation

## Steps to reproduce

- Installed `libxkbcommon-dev` (version 0.8.4-1, same for `libxkbcommon-x11-dev`)
- Follow [documentation steps](https://github.com/davatorium/rofi/blob/next/INSTALL.md#install-from-a-release)
- Error appear during the `../configure` step:

## What behaviour you see

```
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking for flex... flex
checking lex output file root... lex.yy
checking lex library... -lfl
checking whether yytext is a pointer... yes
checking for bison... bison -y
checking for a sed that does not truncate output... /home/linuxbrew/.linuxbrew/bin/sed
checking for grep that handles long lines and -e... /usr/bin/grep
checking for gawk... gawk
checking for flex version... 2.6.4
checking for a BSD-compatible install... /home/linuxbrew/.linuxbrew/bin/ginstall -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /home/linuxbrew/.linuxbrew/bin/gmkdir -p
checking whether make sets $(MAKE)... yes
checking for style of include used by make... GNU
checking whether make supports nested variables... yes
checking dependency style of gcc... gcc3
checking whether make supports nested variables... (cached) yes
checking whether we are using the GNU C compiler... (cached) yes
checking whether gcc accepts -g... (cached) yes
checking for gcc option to accept ISO C89... (cached) none needed
checking whether gcc understands -c and -o together... (cached) yes
checking for gcc option to accept ISO C99... none needed
checking how to run the C preprocessor... gcc -E
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking minix/config.h usability... no
checking minix/config.h presence... no
checking for minix/config.h... no
checking whether it is safe to define __EXTENSIONS__... yes
checking for ranlib... ranlib
checking for ar... ar
checking the archiver (ar) interface... ar
checking for getline... yes
checking for open... yes
checking for sysconf... yes
checking for strtok_r... yes
checking for flock... yes
checking for ftruncate... yes
checking for fcntl... yes
checking for setlocale... yes
checking for atexit... yes
checking for glob... yes
checking math.h usability... yes
checking math.h presence... yes
checking for math.h... yes
checking for library containing floor... -lm
checking for library containing ceil... none required
checking sysexits.h usability... yes
checking sysexits.h presence... yes
checking for sysexits.h... yes
checking for pkg-config... /home/linuxbrew/.linuxbrew/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for _NKUTILS_INTERNAL_XKBCOMMON... no
configure: error: Package requirements (xkbcommon >= 0.4.1) were not met:

No package 'xkbcommon' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables _NKUTILS_INTERNAL_XKBCOMMON_CFLAGS
and _NKUTILS_INTERNAL_XKBCOMMON_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
```

## What behaviour you expect to see

The installation would find `xkbcommon` I installed in the first step listed above

**Additional details:**
- none

**Comment by andradei** [comment]
Also, `pkg-config` is installed and on PATH

**Comment by DaveDavenport** [comment]
It feels like something is off  with your install, this should work and worked for others.
I also do not understand how in your previous issue you been able to 'make'  if configure does not finish because of xbcommon.

Can you execute:
```
pkg-config --version  xkbcommon
```

**Comment by andradei** [comment]
```
$ pkg-config --version  xkbcommon
0.29.2
```

**Comment by andradei** [comment]
> I also do not understand how in your previous issue you been able to 'make' if configure does not finish because of xbcommon.

This also confused me.

**Comment by DaveDavenport** [comment]
sorry, stupid mistake on my part.

```
pkg-config --modversion xkbcommon
```

**Comment by andradei** [comment]
```
$ pkg-config --modversion xkbcommon
Package xkbcommon was not found in the pkg-config search path.
Perhaps you should add the directory containing `xkbcommon.pc'
to the PKG_CONFIG_PATH environment variable
No package 'xkbcommon' found
```

I'll need to check where xkbcommon was intalled and set `PKG_CONFIG_PATH` then, right?

**Comment by andradei** [comment]
Running `dpkg -L libxkbcommon-dev` shows me that `xkbcommon.pc` is in the following directory:

`/usr/lib/x86_64-linux-gnu/pkgconfig`

**Comment by DaveDavenport** [comment]
Normally it should look there. 

What distro are you on?

**Comment by andradei** [comment]
Pop!_OS 19.04.

But I'm running custom tools (lightdm, bspwm, polybar) instead of its gnome ones. Maybe that's why... I don't know, I'm still learning.

**Comment by DaveDavenport** [comment]
Not sure what is wrong. Most ubuntu/debian based system have this set correct.
You can try doing
```
 PKG_CONFIG_PATH=/usr/lib/x86_64-linux-gnu/pkgconfig ./configure 
```
But you likely run into other issues.

Does it not have a rofi package in its repository?

**Comment by andradei** [comment]
I did set `PKG_CONFIG_PATH` and run into another issue later in the installation.

> Does it not have a rofi package in its repository?

I'd like to use the newest released version (1.5.4) instead of what's in the ppa.

```
$ sudo apt info rofi
Package: rofi
Version: 1.5.1-1
...
```

**Comment by andradei** [comment]
The problem might be that I have `pkg-config` installed by linuxbrew.

So I got two installations:

```
$ which pkg-config
/home/linuxbrew/.linuxbrew/bin/pkg-config
```

and

```
$ sudo which pkg-config
/usr/bin/pkg-config
```

**Comment by andradei** [comment]
Yeah... that was the issue, I was running:

```
../configure --disable-check
sudo make
sudo make install
```

but had to run all commands with sudo to I'd use the same tools for configuration and installation:

```
sudo ../configure --disable-check
sudo make
sudo make install
```

**Comment by DaveDavenport** [comment]
happy it worked, but normally you don't have to run sudo for configure and make.

**Comment by sardemff7** [comment]
Precision: you **must never** compile anything as root.

In this case, just fix your PATH to block linuxbrew executables from being selected.

**Comment by andradei** [comment]
@sardemff7 Well, this a little out of the scope for the issue.

But I am a noob on linux, just now I'm learning how it properly functions under the hood. So I'll take his chance to ask:

What would you suggest? Cause I'd like to avoid `sudo` at all costs if possible.

I've thought about putting `linuxbrew` later in my PATH, but I'd lose access to the newest versions of some tools like `git`, `curl`, `vim`, `tmux` and `openssl` to name a few.

Maybe if I'd used a rolling release distro I'd be always on the bleeding edge without the need for `linuxbrew`, but I don't have the time nor the heart to do that right now. Yet, if that's one of the best solutions, I'd plan on it once I have time.

**Comment by sardemff7** [comment]
I this **specific** case I would say: drop the linuxbrew part of `PATH`, because they are just tools. Then point `pkg-config` to the linuxbrew libraries *as an extra* using `PKG_CONFIG_PATH=/home/linuxbrew/.linuxbrew/lib/pkgconfig`.
I’m not saying drop the `PATH` part for good, just for the time of the build.

**Comment by andradei** [comment]
Gotcha, I'll try it, thanks!
