### ISSUE TITLE
[REQUEST] Script-mode: Pass '-eh' and '-show-icons' properties internally

### ISSUE THREAD

**Issue by vredesbyyrd** [davatorium/rofi#1108]
- Rofi version: 1.5.4-82-gc1ac4804 (makepkg)

**Describe the feature**

In script mode, some properties can be passed like: 

`echo -en "\0markup-rows\x1ftrue"`,  for _markup_, 

`echo -en "\x00delim\x1f\\x1\n"` for _delimiter_, which was recently implemented with aa07b8ef9475032634492f42a4f568c01fc47763. 

This is a feature request to pass a couple more options this way. Specifically, it would be cool to set these internally:  _line height_ (`-eh` flag), and whether or not _icons_ should be displayed (`-show-icons` flag) 

**Example use case:**

I have two mpd scripts - one designed for browsing by different categories, the other for making 'full text' queries. Ideally, they would be started on the same command line so you could toggle between the two modes with `-kb-mode-next` / `-kb-mode-previous`. 

`rofi -modi "Browse-db:mpd-modi.lua, Query-db:query-mpd-modi.lua" -show Browse-db`

Currently this cannot be done if each mode requires a different line height and only one uses icons. 

**Browse-mode:**

![rofi-2020-04-27-1601-00000](https://user-images.githubusercontent.com/22080838/80422082-1e712600-88a3-11ea-8ccd-9bf31732744a.png)

**Query-mode:** 

![rofi-2020-04-27-1434-00000](https://user-images.githubusercontent.com/22080838/80422753-59c02480-88a4-11ea-9a87-77c26a0ffa90.png)

**Browse-mode:** (with correct line height / no icons)

![rofi-2020-04-27-1437-00000](https://user-images.githubusercontent.com/22080838/80423083-ebc82d00-88a4-11ea-8b6a-72727783e038.png)

For `-show-icons` perhaps `"\0show-icons\x1ftrue"`. For `-eh`, no recommendation. You would know better than me anyway. Not sure its even possible to implement these properties this way, but figured it worth a request. 

Thanks for your time.

**Comment by DaveDavenport** [comment]
Both options are not specific to a mode, but instance wide.  It would be illogical to set them from a single mode. 

Show icons is a theming options, and `-eh` is a regrettable hack left over from the past that is still in search of a better solution.
