### ISSUE TITLE
[BUG] failed to set locale

### ISSUE THREAD

**Issue by pmatos** [davatorium/rofi#1109]
## Version

1.5.4

## Configuration

`(process:16401): Rofi-WARNING **: 08:49:22.608: Failed to set locale.`

## Launch Command
`rofi -help`

## Steps to reproduce

- run `rofi -help`

## What behaviour you see

- Error `(process:16401): Rofi-WARNING **: 08:49:22.608: Failed to set locale.`

## What behaviour you expect to see

- help

**Additional details:**

I have the exact same setup on my laptop, also running arch linux and same rofi version but I have no problems there.
An strace shows on my newly configured PC (where it does *not* work) shows:
```
openat(AT_FDCWD, "/usr/lib/locale/en_GB.UTF-8/LC_IDENTIFICATION", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/locale/en_GB.utf8/LC_IDENTIFICATION", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/locale/en_GB/LC_IDENTIFICATION", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/locale/en.UTF-8/LC_IDENTIFICATION", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/locale/en.utf8/LC_IDENTIFICATION", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/locale/en/LC_IDENTIFICATION", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
```

On my laptop, where all works, the directory prefix is `/usr/share/locale`, not `/usr/lib/locale`. Where is `rofi` getting these from?

**Comment by DaveDavenport** [comment]
This is not an issue with rofi, but with your locale setup. This seems to be a common problem on ArchLinux setups.

I have no knowledge about archlinux, please check their support. A search points me to [this](https://wiki.archlinux.org/index.php/Locale).
