### ISSUE TITLE
[BUG] programs installed via snap aren't showing

### ISSUE THREAD

**Issue by andradei** [davatorium/rofi#1111]
## Version

Version: 1.5.4

## Configuration

 [gist](https://gist.github.com/andradei/b3aabd1ae0f863c53e0904fcfb40a14d)

## Launch Command

`rofi -show drun`

## Steps to reproduce

- Install snaps: `sudo snap install codium --classic` or `sudo snap install nvim --edge --classic`
- Run `rofi -show drun` or `rofi -show run`

## What behaviour you see

- Programs installed via `sudo snap install` won't show unless I run `sudo rofi ...` which isn't ideal

## What behaviour you expect to see

- Since the programs are installed on `/snap/bin/`, and that is on my `$PATH`, I'd like to see them displayed by rofi without `sudo`

**Additional details:**
- Running Lubuntu 20.04 on Virtualbox 6.2 (latest)

**Comment by DaveDavenport** [comment]
RUN mode looks in $PATH.

DRUN follows the XDG spec for finding desktop files (this does not use $PATH at all).  If it cannot find your snap applications when run as user, it means your XDG settings as user do not include them.

**Comment by andradei** [comment]
I added `XDG_DATA_HOME=/snap/bin:/home/andradei/.local/share` to my profile. `rofi -show run` shows snap packages now, but `rofi -show drun` still doesn't show them.

That's seems to have the opposite effect of what you mentioned. I was expecting to see `snap` programs in `drun`, not `run`

**Comment by andradei** [comment]
If other beginners like me get to this issue, there are 3 things I wanted to point out (and a solution):

1. `XDG_DATA_HOME` is supposed to have only one path, for multiple paths, use `XDG_DATA_DIRS` (read the [spec](https://specifications.freedesktop.org/basedir-spec/latest/ar01s03.html))
2. On `zsh` setting environment variables in `.zshenv` instead of `.zshrc` is preferred. This fixed my `rofi -show run` which now show my snap packages
3. The program I'm trying to see via `rofi -show drun`, namely `VSCodium` has a Ubuntu-specific `codium.desktop` file, and since I'm using `bspwm` and a custom environment, I think `rofi` can't find the `.desktop` file, or it can't read that thing correctly since is references things I don't have like Unity and some environment variables like `${SNAP}`

So I uninstalled it (`sudo snap remove --purge codium`) and installed from their [official website](https://vscodium.com/).

**Comment by DaveDavenport** [comment]
> I added `XDG_DATA_HOME=/snap/bin:/home/andradei/.local/share` to my profile. `rofi -show run` 

run looks in $PATH..
For drun,   XDG_DATA_HOME should not contain bin directories.
I think it should have: /var/lib/snapd/desktop

**Comment by andradei** [comment]
Yeah, I tried to clarify on my previous post that `run` didn't pick up `$PATH` until I put it on `.zshenv`, don't ask me why 😅 

Thanks for clarifying the `XDG_DATA_DIRS` part. But I installed VSCodium from their ppa and now it works without setting it.

Thanks again, rofi is one of the best tools I have on my system.
