### ISSUE TITLE
Rofi clear deleted binaries 

### ISSUE THREAD

**Issue by strogiyotec** [davatorium/rofi#1117]
Good day, this command `rofi -show drun` detects deleted binaries and as a result can't open them . I found similar problem here https://github.com/davatorium/rofi/issues/466 as I understand rofi should delete binary from history if it can't be opened but it doesn't 

Rofi version
`Version: 1.5.4`

The binary is: Advanced Rest Client . This is the output when I try to open this app through rofi's menu 
`
Error failed to execute child process /opt/google/chrome/google-chrome
`
Google chrome was deleted from my laptop and I don't have folder '/opt/google'

**Comment by DaveDavenport** [comment]
drun does not detect binaries, it looks for .desktop files. If the desktop file is still there, it will still show it.

**Comment by DaveDavenport** [comment]
(look in ~/.local/share/applications/   it might be placed there,  otherwise see wiki on how to get more debug output from rofi to help pinpoint the file)

**Comment by strogiyotec** [comment]
Got it , yes I have unused files in this directory, thank you for fast response
