### ISSUE TITLE
[REQUEST] More flexibility with layouts (CONCEPT)

### ISSUE THREAD

**Issue by busybox11** [davatorium/rofi#1118]
Hey,
I wanted to create a Spotify menu for rofi.
Thing is, it has a special layout, which is not possible with rofi.
It also relies on using pictures on fields, which is not possible too, I think.
Here is the concept : 
<img width="1366" alt="Spotify-rofi@2x" src="https://user-images.githubusercontent.com/29630035/81274555-bfed3a00-9050-11ea-92c3-7fc06e6aad1d.png">
([Dribbble](https://dribbble.com/shots/11281833-Spotify-for-rofi))

Would it be possible to implement those features ?
If it's not, how can I make this menu ?

Regards,
busybox

(Version: 1.5.4)

**Comment by DaveDavenport** [comment]
I think this is out of scope for rofi. 

[this](https://gtk.org/) might be more what you are looking for.
