### ISSUE TITLE
[BUG] Filter applied to on pre-markup-escaped text

### ISSUE THREAD

**Issue by johnbeard** [davatorium/rofi#1128]
## Version
Version: 1.5.4

## Configuration

https://gist.github.com/johnbeard/e33811266f7b3086b325fa004206f04e

## Launch Command

    echo "&amp;" | rofi -dmenu -markup-rows

## Steps to reproduce

- Observe the list contains the post-Pango-escaped string "&"
- Type "amp"

## What behaviour you see

- The list still contains "&"

## What behaviour you expect to see

- The list should be empty, as "amp" doesn't match "&"

**Comment by DaveDavenport** [comment]
This has been fixed in git, and will be in next release.

**Comment by DaveDavenport** [comment]
duplicate: #1023
