### ISSUE TITLE
[REQUEST] Unicode symbols as icons

### ISSUE THREAD

**Issue by jluttine** [davatorium/rofi#1132]
(This is is a feature request. If you feel that this idea doesn't fit Rofi roadmap, feel free to close.)

**Describe the feature**

Icon support is a great feature in rofi. Especially for theming, it allows the theme to define whether the icon and the text should be horizontally side-by-side or vertically text below the icon. Also, the theme can control the size of the icon and the text independently of each other. Nice!

However, it'd be nice to be able to use Unicode symbols as icons. For instance, with Nerdfonts, there's a huge collection of various symbols/icons available: https://www.nerdfonts.com/cheat-sheet. In addition to large selection, the symbols get colored similarly as the text (e.g., fg and bg color might be swapped when an entry is highlighted, which doesn't seem to happen with normal icons). It would be nice if Unicode symbols (or more generally arbitrary character/text) could be used as the content of the icon box.

Currently, it is possible to just write Unicode symbols to the entry text. This works ok, but as the "icon" is then part of the entry text, it is not possible to control the style and layout of that Unicode symbol independently of the text style and layout in the theme file. For instance, the theme file cannot put that Unicode icon on top of the entry text because the Unicode icon is part of the entry textbox. Nor can the theme file make the Unicode symbol larger without affecting the text size.

EDIT: Also `-show-icons` would control the visibility of the Unicode symbols if they were in the icon box instead of part of the text box.

Or do you see some solution with currently existing features? I studied theme man page and couldn't figure out a solution, but it is very much possible that I just missed or misunderstood something.

**When reporting a feature request include the following information:**

```
$ rofi -v
Version: 1.5.4-dev
```

**Comment by jluttine** [comment]
Just one probably stupid solution suggestion: If the icon option value is wrapped inside `<span>`, treat the content as text instead of icon file name.

So, this would be interpreted as a normal icon file:

```
echo -en "aap\0icon\x1ffolder\n"
```

Whereas this would treat the content as a regular textbox:

```
echo -en "aap\0icon\x1f<span>\uf011</span>\n"
```

Or, another idea, put two `\x1f` if you want it to be treated as text:

```
echo -en "aap\0icon\x1f\x1f\uf011\n"
```

These were just quick thoughts. If the idea in general is acceptable, then we can think of better ideas for the syntax/implementation.

**Comment by DaveDavenport** [comment]
if you do:
```bash
cho -en "testing\0icon\x1f<span color='red'>⏻</span>" | ./rofi -dmenu
```
This should now work..  It does not inherit color/font from the parent widget (in current design and abstraction it is hard to do, as the part that fetches icons knows nothing about the widget), but the pango format allows setting this.
