### ISSUE TITLE
[BUG] Rofi doesn't read configuration (rofi.conf, config.rasi) from XDG_CONFIG_DIRS

### ISSUE THREAD

**Issue by mrschyte** [davatorium/rofi#1133]
## Version

Output of `rofi -v`: Version: 1.5.4

## Configuration

Output of `rofi -help`: [Link to gist](https://gist.github.com/mrschyte/6e4759030223293739a757711f06671b)

## Launch Command

`The commandline used to launch **rofi**`: rofi -modi combi -combi-modi window,drun -show combi

## Steps to reproduce

- Step 1: Create configuration file in a folder in XDG_CONFIG_DIRS: e.g. /etc/xdg/rofi/config.rasi
- Step 2: Remove configuration in XDG_USER_CONFIG_DIR
- Step 3: Run rofi

## What behaviour you see

- The configuration is ignored, even though no configuration exists in XDG_USER_CONFIG_DIR.

## What behaviour you expect to see

- If configuration is not present in XDG_USER_CONFIG_DIR, rofi should try to load the configuration from the directories listed in XDG_CONFIG_DIRS.

**Comment by DaveDavenport** [comment]
This has been fixed in git (see #1096).

**Comment by mrschyte** [comment]
Awesome, thank you!
