### ISSUE TITLE
[REQUEST] Allow paths relative to config dir for custom modi

### ISSUE THREAD

**Issue by perrin4869** [davatorium/rofi#1135]
**Describe the feature**
Right now if you want to use a custom modi, the path to the modi is relative to the `pwd`:

```bash
$ pwd
/home/perrin4869
$ rofi -modi pass:.config/rofi/modi/rofi-pass-modi -show pass
$ rofi -modi pass:./.config/rofi/modi/rofi-pass-modi -show pass
```
The command above will show rofi with the modi defined in `/home/perrin4869/.config/rofi/modi/rofi-pass-modi`

It would be more flexible for configuring modi inside `config.rasi` if we also searched for modi relative to the directory in which `config.rasi` defined it. For example, given `/home/perrin4869/.config/rofi/config.rasi`:

```rasi
configuration {
  modi: "pass:modi/rofi-pass-modi";
}
```

Running `rofi -show pass` would ideally load `/home/perrin4869/.config/rofi/modi/rofi-pass-modi`.
The only way to achieve this functionality in `config.rasi` as of right now, is to embed an absolute path:

```rasi
configuration {
  modi: "pass:~/.config/rofi/modi/rofi-pass-modi";
}
```

**When reporting a feature request include the following information:**
- Rofi version:
  - `Version 1.5.4`

**Comment by DaveDavenport** [comment]
Not sure if putting an executable in your config directory is the way to go. 
I personally put them in `~/.local/bin/ ` and make sure that is in my $PATH.

**Comment by perrin4869** [comment]
nice, that also works! Thanks!
