### ISSUE TITLE
[BUG] Scripts Segfault

### ISSUE THREAD

**Issue by progfolio** [davatorium/rofi#1138]
## Version

Version: 1.5.4-126-gdb308d2e (makepkg)

## Configuration

https://gist.github.com/progfolio/6791432af761a06a4d6341cd07d00242

## Launch Command

`rofi  -config "" -modi 'Select Workspace':rofiWorkspaceSelector -show 'Select Workspace'`

## Steps to reproduce

1. Launch rofi with the above command and the following script available on one's PATH:

rofiWorkspaceSelector:

```bash
#!/bin/bash
if [ -z "$@" ]; then
  gen_workspaces() {
      i3-msg -t get_workspaces \
        | jq '.[].name'
  }

  gen_workspaces
else
    workspace=$@

    [ -n "${workspace}" ] \
      && i3-msg workspace "${workspace}" >/dev/null
fi
```

2. Enter the name of an i3 workspace that does not currently exist
 

## What behaviour you see

- rofi segfaults:
`Segmentation fault (core dumped)`

## What behaviour you expect to see

- A new workspace with the input value is created/selected

**Additional details:**
- rofi Version 1.5.4 works fine with this script.
- The script works as expected when called without rofi from the command line:
  assuming a workspace named "new" does not exist yet:
`rofiWorkspaceSelector new`
  creates and selects the workspace.
- `uname -a`: Linux arch 5.6.15-arch1-1 #1 SMP PREEMPT Wed, 27 May 2020 23:42:26 +0000 x86_64 GNU/Linux

- Possibly related? The latest update also breaks other scripts of mine as of this commit:
  https://github.com/davatorium/rofi/commit/3604b12fde54ffe0b049dd2f47ece4eba5689989

**Comment by progfolio** [comment]
I've just tried adding 
https://github.com/davatorium/rofi-scripts/blob/master/i3_switch_workspace.sh
to my path and launching rofi with:
`rofi -config "" -modi "switch workspace":i3_switch_workspace.sh -show "switch workspace"`
and I get a new workspace named `Do not launch rofi from inside rofi`.

**Comment by DaveDavenport** [comment]
crash should be fixed.   

About the comment: Nesting is not supported in rofi.

**Comment by progfolio** [comment]
Confirmed that this does indeed fix the crash for me. 
Thank you.
