### ISSUE TITLE
[REQUEST] Script mode: pass -selected-row

### ISSUE THREAD

**Issue by vredesbyyrd** [davatorium/rofi#1145]
- Rofi version: 1.5.4-82-gc1ac4804 (makepkg)

**Describe the feature**

In script mode, some properties can be passed like: 

`echo -en "\0markup-rows\x1ftrue"`,  for _markup_, `echo -en "\0prompt\x1fChange prompt\n"`, _prompt_. Perhaps it would make sense to be able to pass `-selected-row` internally as well? 

**Use case**

My mpd script has a main menu containing options like: _artists_, _albums_, _genre_, _recent_, _queue_ ... Within _queue_ i'd like to have the currently playing track selected, but all other menu options `-selected-row` would remain unset or `1`.

**Comment by etosan** [comment]
Wouldn't this be better solved by passing selected row number in environment variable like the other state is, eg `ROFI_RETV`, `ROFI_INFO`, etc ?

**Comment by vredesbyyrd** [comment]
Active/urgent rows are passed as mode options rather than env variables. IMO it would be more consistent to pass`-selected-row`  the same way.

For my particular use case, a music queue, I realized signifying the currently playing track via active row rather than `-selected-row` makes more sense. 

Since `-selected-row` can already be passed from the cmd for mode scripts, and active/urgent rows as mode options, maybe this feature is not that important? 

@etosan Ill close this issue, can reopen need be.

**Comment by etosan** [comment]
I too made a mistake, I realized dataflow you had in mind is in reverse order as what I understood. You were talking about flow spawner-process -> rofi. I understood this as: rofi -> mode-script-process. Sorry my bad.
