### ISSUE TITLE
[REQUEST] Highlight the text in a results that is the same as you've written

### ISSUE THREAD

**Issue by AethanFoot** [davatorium/rofi#1146]
**Describe the feature**
The is purely aesthetic, currently this text is made bold and underlined (would be nice to change these settings as well, I don't like underlining :) ). I'm sorry if this is already possible, but I couldn't find how to do it so it might be worth making it more clear in documentation. I've added a photo of ulauncher as an example.
![image](https://user-images.githubusercontent.com/63980259/84491363-563dfc80-ac9c-11ea-8864-e430fe5ff2bb.png)

- Rofi version: Version: 1.5.4

**Comment by DaveDavenport** [comment]
See the `rofi-theme` manpage, for 'highlight'.

**Comment by DaveDavenport** [comment]
For demo see the sidebar theme. 
![rofi-2020-06-12-1232-00000](https://user-images.githubusercontent.com/406245/84493879-cf435100-aca8-11ea-96cc-e89efb57fff0.png)
