### ISSUE TITLE
[BUG] Rofi showing different icons for window mode vs drun mode

### ISSUE THREAD

**Issue by barjoco** [davatorium/rofi#1149]
## Version

Version: 1.5.4

## Configuration

https://gist.github.com/barjoco/5ec4aea56121d7a0054a13360a5443e4

## Launch Command

```
rofi -show drun
rofi -show window
```

## Steps to reproduce

- Enable show-icons property. I used a configuration block in the config.rasi rather than command-line argument.
```
configuration {
    show-icons: true;
}
```
- Change the `Icon` property in a .desktop application file to the absolute path of an SVG image on the filesystem. For example the file `/usr/share/applications/spotify.desktop` resembles:
```
[Desktop Entry]
Type=Application
Name=Spotify
GenericName=Music Player
Icon=/home/adam/.icons/spotify.svg
...
```
- Observe the icon in drun mode and in window mode.

## What behaviour you see

- The drun mode correctly displays the icon that the .desktop file points to. The window mode shows some other icon for the same application.

## What behaviour you expect to see

- window mode to show the same icons as drun mode.

**Additional details:**

- drun currectly showing absolute icons for Spotify and VS Code:

![image](https://user-images.githubusercontent.com/47948089/85798106-d18bbd80-b734-11ea-88e0-85fabfcdfa7d.png)

- window mode incorrectly showing a different icon for Spotify and no icon for VS Code (icon not showing is not a rofi problem, but it should show the same icon that drun mode shows):

![image](https://user-images.githubusercontent.com/47948089/85798206-fbdd7b00-b734-11ea-8e4e-e082c370cf34.png)

**Comment by DaveDavenport** [comment]
The window mode request the icon from Xorg, it requests the NET_WM_ICON property. 
Drun gets the icon from the desktop file.

Both modi follow the correct specification.   This is not a bug, this is intended behavior.

Beside this, there is no link between drun/window modi. There is no way to link a desktop file to a window or visa versa.
