### ISSUE TITLE
[ERROR] No puedo escribir en rofi (Kali-Linux); 

### ISSUE THREAD

**Issue by ZCristhian** [davatorium/rofi#1150]
:exclamation:
First read the [guidelines](https://github.com/DaveDavenport/rofi/blob/next/.github/CONTRIBUTING.md)!
This is not optional for any report/question. People must be able to understand the full context of the report when reading it, at any time.
If you feel like you “just have a simple question”, please consider you’re wrong and still fill the full report.
Any report missing these informations will be labeled as “Incomplete Report - Please follow the guidelines” and may not be answered in a timely fashion.
:exclamation:

## Version

Version: 1.5.4

## Configuration

Output of `rofi -help` (in a [gist](https://gist.github.com/))

## Launch Command

rofi -show run

## Steps to reproduce

No puedo escribir nada en el menu rofi. Solo funciona con el mouse mi distribucion es Kali-Linux. Mi notebook es Acer Nitro 5 515-52
- Step 2

## What behaviour you see

- ...

## What behaviour you expect to see

- ...

**Additional details:**
- Include a link to your private config
- Include screenshots/casts of your issue

**Please do not submit reports related to wayland, see
[here](https://github.com/DaveDavenport/rofi/wiki/Wayland) for more
information.**

**Comment by DaveDavenport** [comment]
I cannot understand this issue, nor does it contain the requested information.  closing.. 
Please file again in English and with the requested information.
