### ISSUE TITLE
[REQUEST] A way to add missing KDE search results to rofi #1151

### ISSUE THREAD

**Issue by CreamyCookie** [davatorium/rofi#1152]
It would be great if there was a way to add missing entries that the Plasma Search finds when running rofi with `drun`.

For example, the following appears in the Application Launcher search, but not in rofi:

![Untitled](https://user-images.githubusercontent.com/3063858/86275259-49456680-bbd3-11ea-8714-14e24257527e.png)

It would allow me (and other KDE users) to completely ditch the KDE search in favor of rofi.

- Rofi version: Version: 1.5.0

**Comment by DaveDavenport** [comment]
I don't use KDE so I cannot test, but rofi follows the XDG standard for discovering and displaying desktop files.

Can you:
1.) pastebin a desktop file of the missing entries, 
2.) The past of the desktop file.
3.) the value of the $XDG_DATA_DIRS environment variable.


(p.s.  you can edit your issue, instead of creating new ones, your rofi is 2 1/2 years old and not supported anymore).

**Comment by CreamyCookie** [comment]
@DaveDavenport You're right. I should have edited the previous issue. 



1.  With translations removed:
  ```desktop
[Desktop Entry]
Exec=kcmshell5 autostart
Icon=system-run
Type=Service
X-KDE-ServiceTypes=KCModule
X-DocPath=kcontrol/autostart/index.html

X-KDE-Library=kcm_autostart
X-KDE-ParentApp=kcontrol

X-KDE-System-Settings-Parent-Category=session
X-KDE-Weight=30

Name=Autostart
Comment=Automatically Started Applications
X-KDE-Keywords=Autostart Manager,autostart,startup,system startup,plasma start,cron
```

2. `/usr/share/kservices5/autostart.desktop`
3. `/home/anon/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share/:/usr/share/plasma:/home/anon/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share:/var/lib/snapd/desktop`

**Comment by DaveDavenport** [comment]
Rofi at the moment indeed does not show 'Services'. I guess we can add this as an option.

**Comment by CreamyCookie** [comment]
@DaveDavenport That would be awesome. Thank you! =)

**Comment by DaveDavenport** [comment]
Added to git, needs testing.

**Comment by CreamyCookie** [comment]
@DaveDavenport Thank you a lot! 

I couldn't figure out to compile this, and don't have much time atm. so hopefully someone else tests it.

**Comment by DaveDavenport** [comment]
thanks for replying. It should not break anything so it will be part of next release. So hopefully it works.
