### ISSUE TITLE
[BUG] mod -modi  slow typing with special character or after some command run

### ISSUE THREAD

**Issue by windwp** [davatorium/rofi#1156]
## Version
Version: 1.5.4

## Configuration
https://gist.github.com/windwp/3dd8340cc96fad7506046919d1d64dbb

## Launch Command
` entr rofi -modi "Global Search":"./rofi-ag.sh" -show "Global Search" `
my script here
https://gist.github.com/windwp/abea19a819c3cd8123b837543569c78c

## Steps to reproduce
I run my script rofi ag and after some search command it is very difficult to typing on rofi especially with special character ":,&"

https://www.youtube.com/watch?v=xTLUuV_AwWE

## What behaviour you see
slow typing
## What behaviour you expect to see
faster typing without delay. I don't know why it so slow my list only have few option but it is super slow on typing???
- ...

**Comment by DaveDavenport** [comment]
Can you get a timing trace? https://github.com/davatorium/rofi/wiki/Debugging-Rofi

**Comment by DaveDavenport** [comment]
please re-open when more info is available (f.e. timing trace).
