### ISSUE TITLE
[REQUEST] Option for eliding text in the center or at the start

### ISSUE THREAD

**Issue by CreamyCookie** [davatorium/rofi#1157]
Instead of having text elided at the end (`This is a very long entry ...`), it's sometimes useful to have it elided in the middle (`/home/anon/ ... very-interesting.mkv`), especially for file paths where you definitely want to see the file name and extension

This would be configurable via the theme string or file, presumably.

Rofi version: Version: 1.5.0

**Comment by DaveDavenport** [comment]
This has been implemented a few releases ago.

**Comment by CreamyCookie** [comment]
@DaveDavenport Oh, I'm sorry. I didn't find it when searching (both in general and on the theme page). What is it called?

**Comment by DaveDavenport** [comment]
https://github.com/davatorium/rofi/releases/tag/1.5.3   its called Ellipsizing.

**Comment by CreamyCookie** [comment]
@DaveDavenport Awesome, thanks!

**Comment by CreamyCookie** [comment]
@DaveDavenport Awesome, thanks!

Is there a way to set this via command line flag (or rofi theme file)?

**Comment by DaveDavenport** [comment]
No. not in current release.

In the next release (1.6.0) the dmenu mode does support then '-keep-right'  option, that sets ellipsize to end..

**Comment by CreamyCookie** [comment]
Nice. Will there also be one for ellipsizing the center?
