### ISSUE TITLE
Game runs at low fps when launched with rofi

### ISSUE THREAD

**Issue by ZilchGl1tch** [davatorium/rofi#1160]
I play a browser based fps game called krunker. Its an AppImage for Linux. So I made an entry for it in `/usr/share/applications/krunker.desktop`

Here is the entry:

>[Desktop Entry]
>Type=Application
>Version=1.0
>Name=Krunker
>Comment=FPS Game
>Exec=/home/zilch/krunker/krunker.AppImage
>Path=/home/zilch/
>Icon=/home/zilch/.config/krunker.png
>Terminal=false
>Categories=Game;Application;

When launching the game with shell by `exec /home/zilch/krunker/krunker.AppImage`,  it runs fine with fps in the hundreds. But when I launch it via rofi, it runs at 10 fps.

OS: Arch Linux 
Rofi is the latest version installed via pacman (v1.5.4)

Edit: added markdown

**Comment by DaveDavenport** [comment]
how do you launch rofi? maybe something in the environment is different?

Not sure how rofi can affect this, given it just launches the application and quits.

**Comment by ZilchGl1tch** [comment]
The issue might not be with rofi. I did some troubleshooting and my results varied a lot. I just wanted to make sure rofi had nothing to do with this. What is the default path that rofi uses?

**Comment by DaveDavenport** [comment]
What do you mean?  rofi uses the environment it is launched in.
