### ISSUE TITLE
"Setup Late Display" Lag

### ISSUE THREAD

**Issue by angrypanda1** [davatorium/rofi#1162]
I had no problems a few weeks ago, but rofi is taking ~10 seconds to load now. 
**Version**: 1.5.4
**Configuration**:
```
Monitor layout:
              ID: 0 (primary)
            name: eDP-1
        position: 0,0
            size: 1366,768
            size: 344mm,193mm  dpi: 101,101


Detected modi:
        * +window
        * windowcd
        * +run
        * +ssh
        * drun
        * combi
        * keys

Compile time options:
	* window  enabled
	* drun    enabled
	* gcov    disabled
	* asan    disabled

For more information see: man rofi
                 Version: 1.5.4
              Bugreports: https://github.com/davatorium/rofi/
                 Support: https://reddit.com/r/qtools/
                          #rofi @ freenode.net
      Configuration file: /home/svadrut/.config/rofi/config
[I]  ~ -help
```
**Steps to Reproduce**: Simply do 
`rofi -show drun` and there is a large space between
```
(process:126995): Timings-DEBUG: 14:04:41.155: 0.013429 (0.000060): source/view.c:rofi_view_workers_initialize:1877 Setup Threadpool, done

(process:126995): Timings-DEBUG: 14:04:45.475: 4.333428 (4.319999): source/rofi.c:main:1000 Setup late Display
```
**Expected Behavior**: Should be instant

**Comment by DaveDavenport** [comment]
If rofi did not change? any idea of what changed in your setup?

I suspect it might have to do with fonts (as they are loaded between thread pool and display setup ( see wiki to get more detailed output).
People noticed that other pango (like gtk) based application also started to start slow. Problem is this is not (as far as previous attempts) something I can fix within rofi  .

**Comment by DaveDavenport** [comment]
See also: #673

**Comment by angrypanda1** [comment]
No, GTK applications open normally, and I've used another font. It still takes ~4 seconds for rofi to open.

**Comment by DaveDavenport** [comment]
can you run this and pastebin/gist output:
```
G_MESSAGES_DEBUG=all rofi -show run
```

Do you know what changed on your system since it was fast en slow (as rofi did not update).

**Comment by angrypanda1** [comment]
https://gist.github.com/angrypanda1/f04ece54db5ebd1b9b680cf062fd2757
No clue :(

**Comment by DaveDavenport** [comment]
If I add more debug info, can you do a run from git for me?
Lets see if we can figure it out.

**Comment by angrypanda1** [comment]
What do I do lol I have no experience in messing with diff files. I installed from AUR.

**Comment by DaveDavenport** [comment]
aur? I assume the archlinux thingy?  if that has a package that installs the latest git version, that should work.

**Comment by angrypanda1** [comment]
reinstalled rofi-git, still the same result :(

**Comment by DaveDavenport** [comment]
Can you paste the timing log, I did add some stamps to it, to pin it down.

**Comment by angrypanda1** [comment]
https://gist.github.com/angrypanda1/de8f8f1f95780426e74a5079354541a4

Tried it with the `no-show-icons` parameter but it still didn't work. Something to do with `Icon fetcher initialize` that is taking ~3 seconds.

**Comment by DaveDavenport** [comment]
That is interesting, first time I see it being slow. Do you specify a specific icon theme?

**Comment by angrypanda1** [comment]
no, I don't specify an icon theme

**Comment by DaveDavenport** [comment]
@sardemff7  any ideas on this one?

**Comment by angrypanda1** [comment]
Lol my potato computer crashed and I `fsck`'d my entire drive. Suddenly rofi works great. Thanks!

**Comment by DaveDavenport** [comment]
Great to hear!
