### ISSUE TITLE
New Release?

### ISSUE THREAD

**Issue by Kratacoa** [davatorium/rofi#1164]
When is the new release coming? I've seen that there've been quite a few commits in between, and that the [release notes](https://github.com/davatorium/rofi/blob/0b1cef778a085097ee10ba456650a64be216472b/releasenotes/1.6.0/release-1.6.0.markdown) are ready too.

**Comment by DaveDavenport** [comment]
I have no to very little time to work on it, and it is currently blocked by meson: #1159
