### ISSUE TITLE
[REQUEST] Follow Type=Link standard desktop entries with drun

### ISSUE THREAD

**Issue by jsamr** [davatorium/rofi#1166]
**Describe the feature**
As per version 1.5 of the [Desktop Entry Specification](https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html), an entry can be of `Type=Link` to point to a resource, but rofi (1.5.4-2, archlinux) doesn't display such entries when running `rofi -show drun`.

Example of such entry:

```info
[Desktop Entry]
Name=Plex Server Console
Icon=plex-icon
Type=Link
URL=http://localhost:32400/web
```

**When reporting a feature request include the following information:**
- Rofi version:
  - `1.5.4`

**Comment by flavorjones** [comment]
@DaveDavenport would you be open to a PR introducing this behavior?

**Comment by DaveDavenport** [comment]
Yes.  I guess best is to launch URL  with `xdg-open` util.

**Comment by flavorjones** [comment]
I've opened #1168 with a proposed implementation for this.
