### ISSUE TITLE
[BUG] Rofi doesn't get the window coordinates correctly under bspwm.

### ISSUE THREAD

**Issue by useredsa** [davatorium/rofi#1169]
## Version

1.5.4

## Configuration

https://gist.github.com/useredsa/db2d3f3fd894eebddd2cb81aceb24d72

## Launch Command

`rofi -show run` via `sxhkd` using `super + p`.

## Steps to reproduce

- Work with `bspwm` version 0.9.10
- Hit the shortcut.

## What behaviour you see

- Rofi appears at coordinates `(0, 0)`, top left corner of the screen/monitor.
- The width is correctly set to the window's width.

## What behaviour you expect to see

- Rofi should appear at  the top left corner of the current window, instead of monitor.

**Additional details:**

The issue was previously discussed in the wrong place (another issue thread):
https://github.com/davatorium/rofi/issues/1163.

The reason for the bug is clearly stated there.

**Comment by DaveDavenport** [comment]
Possibly related to changes made here: #683
