### ISSUE TITLE
[BUG] Highlight doesn't seem to work

### ISSUE THREAD

**Issue by BigfootN** [davatorium/rofi#1170]
## Version

Output of `rofi -v`

Version: 1.5.4-152-g4f1169e3 (makepkg)

## Configuration

Output of `rofi -help` (in a [gist](https://gist.github.com/BigfootN/c464e3c28643a536646a5cd86672f071))

## Explanation

I am trying to modify the way the highlighted text is formatted. Unfortunately, after trying to add highlight (with my own style) in my every parts of the configuration, it still doesn't change the way the text is highlighted.

## Launch Command

`rofi -show run`

## Steps to reproduce

Launch:

`rofi  -show run -no-config -theme-str 'element { highlight: none; }'`

Try to type some known/installed program.

## What behaviour you see

- The matched text is highlighted

## What behaviour you expect to see

- The matched text shouldn't be highlighted

**Additional details:**

OS: Archlinux
Package: rofi-git

Thank you very much in advance for any help

**Comment by DaveDavenport** [comment]
In git the element got split into separate widgets.. try setting highlight on: `element-text`.

**Comment by BigfootN** [comment]
Sorry, didn't read thoroughly enough.
Works like a charm, thank you.
