### ISSUE TITLE
[REQUEST] Deleting item from dmenu

### ISSUE THREAD

**Issue by sencer** [davatorium/rofi#1171]
I think it would be very useful it rofi there was a way of updating the list rofi showing without restarting. Apologies if it exists, I couldn't find except for removal of history items https://github.com/davatorium/rofi/issues/22.

One obvious use case is deleting a notification in rofication. I built a [notification manager](https://github.com/sencer/i3-notifier), inspired by rofication, which also clusters notifications from the same apps together for example. When you choose a cluster it expands the cluster showing all the child nodes. Both deleting a notification/a cluster and expanding a notification works by restarting rofi, which works finely, but that would be a great addition.

**When reporting a feature request include the following information:**
- Rofi version:
  - `rofi -v` Version: 1.5.4-152-git-4f1169e3 (next)

**Comment by DaveDavenport** [comment]
Any idea on how the interaction between rofi and the script should work?

Maybe [this](https://github.com/OmarCastro/rofi-blocks) can work out of the box?

**Comment by sencer** [comment]
Thanks, indeed it seems like rofi-blocks is what I am looking for.
