### ISSUE TITLE
[REQUEST] Allow for styling of matched search results in Rofi

### ISSUE THREAD

**Issue by tamis-laan** [davatorium/rofi#1179]
**Feature description**
Allow for styling of matched search results in Rofi. When opening Rofi and searching for a search term every matched character will get a bold font. It would be nice if you could style these matched characters for example give them a different color, make them italic or change the font, font size etc... 

**Rofi version**
Version: 1.5.4

**Comment by DaveDavenport** [comment]
Italic/bold/underline and color is already supported.

**Comment by tamis-laan** [comment]
That's great! But I can't find it anywhere in the docs! Therefore the feature request. Could you point me in the right direction?

**Comment by DaveDavenport** [comment]
from manpage:

* **highlight**:         text style {color}.
    color is optional, multiple highlight styles can be added like: bold underline italic #000000;

## Text style

* Format: `(bold|italic|underline|strikethrough|none)`

Text style indicates how the highlighted text is emphasized. `None` indicates that no emphasis
should be applied.

 * `bold`: make the text thicker then the surrounding text.
 * `italic`: put the highlighted text in script type (slanted).
 * `underline`: put a line under the highlighted text.
 * `strikethrough`: put a line through the highlighted text.
 * `small caps`: emphasise the text using capitalization.

> For some reason `small caps` does not work on some systems.

**Comment by DaveDavenport** [comment]
`rofi -theme-str 'element { highlight: None; }' -show drun

**Comment by tamis-laan** [comment]
Great that works! However still can't find it in the man page! I'm on arch linux using the community package of rofi: [https://www.archlinux.org/packages/community/x86_64/rofi/](https://www.archlinux.org/packages/community/x86_64/rofi/)

**Comment by mdkcore0** [comment]
hey, just theming my rofi and using the `highlight` option, working as expected :)
but tried to set color from an already defined color using var, but it doesn't seems to work

any limitation on only use color as html code on highlight?

many thanks!
