### ISSUE TITLE
Type to filter

### ISSUE THREAD

**Issue by Shamaoke** [davatorium/rofi#1181]
After update to 1.6.0 I observe the message “Type to filter” at the input field. Also, at the right side of the field, some numbers is displayed. I suppose they should somehow indicate the number of entries at the list and something else. I'd prefer to keep the input field clean. Is there any way to remove these messages?

![type_to_filter](https://user-images.githubusercontent.com/625266/92413213-b89d8080-f157-11ea-962c-20ebf5cd4a61.png)

Thanks.

**Comment by DaveDavenport** [comment]
yes.

**Comment by Shamaoke** [comment]
@DaveDavenport How can this be accomplished?

**Comment by DaveDavenport** [comment]
Not a bug.

**Comment by DaveDavenport** [comment]
You can update the theme and remove the widgets/placeholder.

**Comment by garret** [comment]
Is there a way to put a string in the config file to don't show this "Type to filter" and the entries instead of doing it on the command line.

**Comment by Shamaoke** [comment]
@garret For that matter you will have to create your own theme and enable it in `config.rasi`.

~~~~
// ~/.config/rofi/config.rasi
configuration {
  theme: "sample";
}
~~~~

In the theme file besides styles for other rofi elements you should  include a style declaration for the `entry` element with either the `placeholder` property containing an empty line or without this property declaration at all.

~~~~
// ~/.config/rofi/sample.rasi
entry {
  placeholder: "";
}
// or just
entry { }
~~~~

I still don't know though how to enable/disable and style the thing which displays the number of filtered/overall lines (`4030/4030` in the image I gave in the title message).

**Comment by DaveDavenport** [comment]
@Shamaoke, @garret   This is incorrect, there is **no** need to make a new theme.
You can add modification to themes at the end of your `config.rasi` file.
```css
entry {
  placeholder: "";
}
```


If you want ot seperate it out, you can put it in a separate file and add `@import "mychange"`  at the end of your config file.

**Comment by DaveDavenport** [comment]
> I still don't know though how to enable/disable and style the thing which displays the number of filtered/overall lines (4030/4030 in the image I gave in the title message).

See my message 10 days ago, that will remove those entries for default theme.''

Locking topic, incomplete report and not an issue.
