### ISSUE TITLE
[BUG] Rofi ignores window command

### ISSUE THREAD

**Issue by thraizz** [davatorium/rofi#1183]
## Version

```
$ rofi -v
Version: 1.6.0
```

## Configuration

[configuration](https://gist.github.com/thraizz/1b1accd362ca650f588984daa4f20b4e)

## Launch Command

`rofi -no-config -window-command "echo {window}" -show window`

## Steps to reproduce

- Launch rofi window mode with a custom window command
- Watch how command is ignored

## What behaviour you see
Rofi ignores the `-window-command "command"` option and just uses its default value.

## What behaviour you expect to see
Rofi handles the `-window-command` and, in my case, echoes the selected window's id.

**Comment by DaveDavenport** [comment]
It works for me. 
The help says:
```
	-window-command [string]                Command executed on accept-entry-custom for window modus
		wmctrl -i -R {window} (Default)
```

Did you hit the 'accept-entry-custom' key binding?

**Comment by thraizz** [comment]
Yes, the same binding I use when not trying to invoke a custom command.
I'm on 5.8.7-arch1-1, window manager is Openbox.

**Comment by DaveDavenport** [comment]
`-window-command`  only works for the 'custom command' binding, not for the default one.  This is intended behavior.

**Comment by DaveDavenport** [comment]
Hmm that help is wrong.  it is `-kb-accept-alt`  by default 'Shift-Return'..  I will fix the help.

**Comment by DaveDavenport** [comment]
Made it more explicit in manpage and help output.

**Comment by thraizz** [comment]
Ah, I see, thanks. I tried to switch `kb-accept` and `kb-accept-alt` with `-kb-accept "Shift-Return" -kb-accept-alt "Return"` but I still get the `There's already a binding for Return` error, any idea what a solution might be?

**Comment by DaveDavenport** [comment]
I think it is `-kb-accept-entry` not `-kb-accept`. (see `rofi -show keys` to get a list )

**Comment by thraizz** [comment]
Yes it is indeed. Thank you for your kind help!
