### ISSUE TITLE
[REQUEST] Option to configure icons size

### ISSUE THREAD

**Issue by zodd18** [davatorium/rofi#1186]
**Issue**
With the release of [version 1.6.0](https://github.com/davatorium/rofi/releases/tag/1.6.0) there have been some visual changes to existing themes. Among them is: "[Icon] Set default size to 1.2 CH". This means that the icons now are so tiny that they're almost impossible to recognize. Attached screenshots: [before](https://imgur.com/a/Et9BT0D) and [now](https://imgur.com/a/PsMAr3f). I've researched through the manpages but I can't seem to find an option to edit icons size.

**Possible solution**
I propose that the icon change be reversed so that existing themes are not ruined by this change. And it could also be interesting to add some kind of option to configure the size of the icons.

**Approach**
e.g. when passing `-show-icons`, it'd be a really nice feature to pass the desired size for the icons like this: `-show-icons '20'`.

**Current version**
rofi-1.6.0-1-x86_64

**Comment by sardemff7** [comment]
Already possible, it’s a theme thingy. See `rofi-theme` man page and #1185.

**Comment by zodd18** [comment]
My bad, didn't see #1185, that indeed solved the problem. Thanks!

**Comment by Brottweiler** [comment]
So I have to make a theme to solve this? I am using default theme and icons are too small.. Do I have to create a new theme just to configure the icon size? 

I have looked through the linked issues in https://github.com/davatorium/rofi/issues/1195#issuecomment-692489417 and I still don't understand how to change icon size when using **default** theme.
