### ISSUE TITLE
[BUG] @media values don't support the 'px' suffix

### ISSUE THREAD

**Issue by vahnrr** [davatorium/rofi#1188]
## Version

Tested on:
- `Version: 1.6.0`
- `Version: 1.6.0-6-g3b86326b (makepkg)`

## Configuration

https://gist.github.com/vahnrr/84295b5d9967aa5dfeffab5870c9bf50

## Launch Command

`rofi -show window`

## Steps to reproduce

- Have the following *config.rasi*:

``` css
@media (max-width: 1920px) {
  * {
    background-color: #ff0000;
  }
}
```

- Run the command `rofi -show window`
- Get a dialog "**Error while parsing theme**" (see next section for the full dialog)

## What behaviour you see

Content of the error dialog:

>The following errors were detected when starting rofi:
>**Error while parsing theme:** */home/vahnrr/.config/rofi/config,rasi*
>    Parser error: *syntax error, unexpected UTF-8 encoded string, expecting Integer number or Floating-point number*
>    Location: line 1 column 19 to line 1 column 26.
>    File '/home/vahnrr/.config/rofi/config.rasi'

## What behaviour you expect to see

- The `rofi -show window` with a a red background
- [The 1.6.0 release](https://github.com/davatorium/rofi/releases/tag/1.6.0) says `rofi` supports the `1920px` notation while it doesn't

**Additional details:**
- Using `1920` instead of `1920px` seems to work

**Comment by DaveDavenport** [comment]
yep,  you are correct this is wrong

**Comment by DaveDavenport** [comment]
fixed the release notes...  Lets turn this into a feature request..

**Comment by DaveDavenport** [comment]
Adding a space between `1920` and `px`  should work.

**Comment by DaveDavenport** [comment]
Ok fixed it in git, no space between 1920 and px should now work.
