### ISSUE TITLE
[BUG] Listview lines not correctly showing the number of elements expected

### ISSUE THREAD

**Issue by steckhelena** [davatorium/rofi#1190]
## Version
`Version: 1.6.0`

## Configuration

https://gist.github.com/steckhelena/ba5c5f18216f7bf94453ff3080986e8e

## Launch Command

`echo "Headphone;Speakers" | rofi -sep ";" -dmenu -p "Select audio device:" -i -theme AudioSelMenu`

## Steps to reproduce

- Set, in the theme file, the following: (minimal config to reproduce it)
```css
* {
    font: "Cantarell 18";
}

window {
    children:   [ vertibox ];
}

vertibox {
    orientation: vertical;
    children:   [ prompt, listview ];
}

listview {
    lines: 2;
}

``` 
- Set **any** font in the global properties section(as shown above)
- If the **font** is set you will see a menu with one of the elements hidden, and only being able to be select with arrow keys up/down
- If the **font** property OR the **prompt** child is set the bug can be reproduced

## What behaviour you see

- Rofi does not show two lines as expected, and instead just show one line which, with the `cycle` option set to true, I can select the other option by pressing up or down keys.

## What behaviour you expect to see

- I expect to see both input lines without having to scroll between them because one is hidden.

**Additional details:**
- My current rofi configuration files:
  - https://github.com/steckhelena/dotfiles/tree/master/.config/rofi
- The script which I use to launch this dmenu:
  - https://github.com/steckhelena/dotfiles/blob/master/.config/i3/scripts/sel_audio_dev.sh
- Screenshot of bug:
![rsz_1screenshot_2020-09-12_15-43-17](https://user-images.githubusercontent.com/19346539/93002740-6cfc2580-f50f-11ea-908f-3166c0d41acd.png)
- Screenshot of expected behavior(removing the **font** property):
![Screenshot_2020-09-09_15-13-42(1)](https://user-images.githubusercontent.com/19346539/93002762-8b622100-f50f-11ea-9f0d-00767e0a7507.png)
- Screenshot of expected behavior(removing the **prompt** child, my current theme now):
![Screenshot_2020-09-12_15-43-17(1)](https://user-images.githubusercontent.com/19346539/93003105-396eca80-f512-11ea-8412-b4a30dc57cab.png)

I started experiencing this yesterday after updating rofi to the latest version, it worked as expected before that(at least I think it was the expected behavior, if I am wrong about it, please feel free to correct me)

Thanks for the amazing software! Any other information needed, or if I have some wrong config I will be following the issue.

**Comment by DaveDavenport** [comment]
Does it also happen without the icons?

**Comment by steckhelena** [comment]
Yes

**Comment by DaveDavenport** [comment]
Interresting it works for me.

What I had happened before is that pango indicated height (using ascent en descent query on font) is smaller then the actual font height when rendered.   This screws up rofi as the sizing goes off.

**Comment by DaveDavenport** [comment]
![rofi-2020-09-12-2126-00000](https://user-images.githubusercontent.com/406245/93003400-aac47280-f53e-11ea-8593-96f9502545d5.png)

**Comment by DaveDavenport** [comment]
what if you set 'fixed-height" to false (on listview) and lines to > 2?

**Comment by steckhelena** [comment]
If I set fixed-height to false, whatever number I put on lines it still has the same problem. With dynamic and >2 lines it shows all the entries. With dynamic and 2 lines it still has the same problem.

**Comment by steckhelena** [comment]
I found that with lines >2 it and no other properties, it shows both lines as expected, but an unwanted space at the bottom

**Comment by DaveDavenport** [comment]
Thanks. 

It seems for some reason the font height calculation on your system is different then on mine.
What distro are you running?

**Comment by steckhelena** [comment]
Btw, for me, the above example will be as follows:
![rofi-2020-09-12-1645-00000](https://user-images.githubusercontent.com/19346539/93003714-6f627d80-f517-11ea-8adc-e9f672646c93.png)

**Comment by steckhelena** [comment]
I am running Arch with i3

**Comment by DaveDavenport** [comment]
For some reason a simple thing as figuring out what the max height of a font line is difficult :(. This is a problem that keeps popping up. 

Thanks, I will make a vm with archlinux and try it out,  (weird issues like this seems to happen on arch more often with it 'bleeding edge' )

**Comment by DaveDavenport** [comment]
Found out its a rounding issue in box widget. Now to find a fix.

**Comment by DaveDavenport** [comment]
workaround might be to set : `expand: false;`  on listview.

**Comment by steckhelena** [comment]
That was fast, the workaround works on the minimal config I posted above:
![rofi-2020-09-12-1739-00000](https://user-images.githubusercontent.com/19346539/93004609-e2232700-f51e-11ea-9496-6a5e596a31f9.png)

But sadly it won't work if I set spacing on listview or padding on element, or margin on window xD

**Comment by DaveDavenport** [comment]
Yeah,  the problem is that with pango I get (sometimes) a 1 pixel difference in estimated height and actual height.. annoying ..
I wonder if this is a result of the new rendering backend.

**Comment by DaveDavenport** [comment]
Can you try the following patch?

```patch
diff --git a/include/widgets/textbox.h b/include/widgets/textbox.h
index 229e34d9..c5152a20 100644
--- a/include/widgets/textbox.h
+++ b/include/widgets/textbox.h
@@ -43,6 +43,17 @@
  *
  * @{
  */
+
+/** Cache to hold font descriptions. This it to avoid having to lookup each time. */
+typedef struct TBFontConfig
+{
+    /** Font description */
+    PangoFontDescription *pfd;
+    /** Font metrics */
+    PangoFontMetrics     *metrics;
+    /** height */
+    double               height;
+}TBFontConfig;
 /**
  * Internal structure of a textbox widget.
  * TODO make this internal to textbox
@@ -67,6 +78,8 @@ typedef struct
     double             xalign;
 
     PangoFontMetrics   *metrics;
+    TBFontConfig       *tbfc;
+
     PangoEllipsizeMode emode;
     //
     const char         *theme_name;
diff --git a/source/widgets/textbox.c b/source/widgets/textbox.c
index 3f5d0633..0667c1c4 100644
--- a/source/widgets/textbox.c
+++ b/source/widgets/textbox.c
@@ -55,16 +55,8 @@ static PangoContext     *p_context = NULL;
 /** The pango font metrics */
 static PangoFontMetrics *p_metrics = NULL;
 
-/** Cache to hold font descriptions. This it to avoid having to lookup each time. */
-typedef struct TBFontConfig
-{
-    /** Font description */
-    PangoFontDescription *pfd;
-    /** Font metrics */
-    PangoFontMetrics     *metrics;
-    /** height */
-    double               height;
-}TBFontConfig;
+
+TBFontConfig *tbfc_default = NULL;
 
 /** HashMap of previously parsed font descriptions. */
 static GHashTable *tbfc_cache = NULL;
@@ -133,6 +125,7 @@ static WidgetTriggerActionResult textbox_editable_trigger_action ( widget *wid,
 
 static void textbox_initialize_font ( textbox *tb )
 {
+    tb->tbfc = tbfc_default;
     tb->metrics = p_metrics;
     const char * font = rofi_theme_get_string ( WIDGET ( tb ), "font", NULL );
     if ( font ) {
@@ -142,7 +135,13 @@ static void textbox_initialize_font ( textbox *tb )
             tbfc->pfd = pango_font_description_from_string ( font );
             if ( helper_validate_font ( tbfc->pfd, font ) ) {
                 tbfc->metrics = pango_context_get_metrics ( p_context, tbfc->pfd, NULL );
-                tbfc->height  = pango_font_metrics_get_ascent ( tbfc->metrics ) + pango_font_metrics_get_descent ( tbfc->metrics );
+
+                PangoLayout *layout = pango_layout_new(p_context );
+                pango_layout_set_text(layout,"aAjb", -1);
+                PangoRectangle rect;
+                pango_layout_get_pixel_extents(layout, NULL, &rect );
+                tbfc->height  = rect.y + rect.height;
+                g_object_unref ( layout);
 
                 // Cast away consts. (*yuck*) because table_insert does not know it is const.
                 g_hash_table_insert ( tbfc_cache, (char *) font, tbfc );
@@ -157,6 +156,7 @@ static void textbox_initialize_font ( textbox *tb )
             // Update for used font.
             pango_layout_set_font_description ( tb->layout, tbfc->pfd );
             tb->metrics = tbfc->metrics;
+            tb->tbfc = tbfc;
         }
     }
 }
@@ -828,7 +828,15 @@ void textbox_set_pango_context ( const char *font, PangoContext *p )
     p_metrics = pango_context_get_metrics ( p_context, NULL, NULL );
     TBFontConfig *tbfc = g_malloc0 ( sizeof ( TBFontConfig ) );
     tbfc->metrics = p_metrics;
-    tbfc->height  = pango_font_metrics_get_ascent ( tbfc->metrics ) + pango_font_metrics_get_descent ( tbfc->metrics );
+
+    PangoLayout *layout = pango_layout_new( p_context );
+    pango_layout_set_text(layout,"aAjb", -1);
+    PangoRectangle rect;
+    pango_layout_get_pixel_extents(layout, NULL, &rect );
+    tbfc->height  = rect.y + rect.height;
+    g_object_unref ( layout);
+    tbfc_default = tbfc;
+
     g_hash_table_insert ( tbfc_cache, (gpointer *) ( font ? font : default_font_name ), tbfc );
 }
 
@@ -866,15 +874,15 @@ int textbox_get_height ( const textbox *tb )
 
 int textbox_get_font_height ( const textbox *tb )
 {
-    int height;
-    pango_layout_get_pixel_size ( tb->layout, NULL, &height );
-    return height;
+    PangoRectangle rect;
+    pango_layout_get_pixel_extents ( tb->layout, NULL, &rect );
+    return rect.height+ rect.y;
 }
 
 int textbox_get_font_width ( const textbox *tb )
 {
     PangoRectangle rect;
-    pango_layout_get_pixel_extents ( tb->layout, NULL, &rect );
+    pango_layout_get_pixel_extents ( tb->layout, NULL, &rect);
     return rect.width + rect.x;
 }
 
@@ -883,8 +891,7 @@ static double char_height = -1;
 double textbox_get_estimated_char_height ( void )
 {
     if ( char_height < 0 ) {
-        int height = pango_font_metrics_get_ascent ( p_metrics ) + pango_font_metrics_get_descent ( p_metrics );
-        char_height = ( height ) / (double) PANGO_SCALE;
+        char_height = tbfc_default->height;
     }
     return char_height;
 }
@@ -913,8 +920,8 @@ double textbox_get_estimated_ch ( void )
 
 int textbox_get_estimated_height ( const textbox *tb, int eh )
 {
-    int height = pango_font_metrics_get_ascent ( tb->metrics ) + pango_font_metrics_get_descent ( tb->metrics );
-    return ceil ( ( eh * height ) / (double) PANGO_SCALE ) + widget_padding_get_padding_height ( WIDGET ( tb ) );
+    int height = tb->tbfc->height;
+    return ceil ( ( eh * height ) ) + widget_padding_get_padding_height ( WIDGET ( tb ) );
 }
 int textbox_get_desired_width ( widget *wid )
 {
```

**Comment by steckhelena** [comment]
With the above patch, it works! Here's the result with my config(with **prompt** child back in it):

![rofi-2020-09-12-2019-00000](https://user-images.githubusercontent.com/19346539/93006658-6e404900-f535-11ea-98f4-5996d7f7a593.png)
