### ISSUE TITLE
[REQUEST] Update Ubuntu documentation

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [davatorium/rofi#1192]
Your [installation guide](https://github.com/davatorium/rofi/blob/next/INSTALL.md) has this:

> Ubuntu 16.04 Xenial
> 
> Please note that the latest version of rofi in Ubuntu 16.04 is extremely outdated (v0.15.11)

Yet, on Mint 20 - based on Ubuntu 20 - the Rofi package is version 1.5.4.

Also - if this is still relevant, and not reported already - I encounter the following problem (using Rofi 1.5.4 on Mint 20). In a terminal, I enter `rofi -show run`. Then I choose Firefox. Firefox runs. Yet, if an instance of Firefox is running already, an entirely new instance - or perhaps just a new window - opens. Surely what should happen is that the existing instance of Firefox should be brought to the foreground.

EDIT: I note also that, in the aforementioned setup, Rofi does not heed my system themes (I have a dark theme, but Rofi is using a light theme). Nor is it made at all obvious how I should troubleshoot that.

**Comment by DaveDavenport** [comment]
1. The info in documentation seems to be correct..  Yes 16.04 warning is outdated and could probably be removed (but is still valid and not sure what to update).

2. This is not a rofi issue,  rofi calls the firefox executable, what firefox does with this is not up to rofi.  I would suspect this is possible a environment issue.

3. Rofi does not integrate into system themes, not claims to be.  The manpage describes how you can set theme and links to the theme selector tool.

Please next time follow the guidelines for filing a request/issue.  For questions, please use IRC or reddits r/qtools

**Comment by DaveDavenport** [comment]
Removed the xenial warning from the documentation.

**Comment by LinuxOnTheDesktop** [comment]
Thank you the response.

On 3: I find no documentation about a theme selector tool - neither on your website nor in rofi's inbuilt help nor in `man rofi`. Perhaps I make some mistake.

Anyhow, the problem with applications - applications, plural, because I find it affects not only Firefox but also Nemo (other applications, I have not tested) - is a dealbreaker for me, Or it is such at least because I suspect that trying to debug it would be involved.

**Comment by DaveDavenport** [comment]
3:  theme selector is under 'see also': https://github.com/davatorium/rofi/blob/1.5.4/doc/rofi.1.markdown#see-also.
There is a manpage for it: https://github.com/davatorium/rofi/blob/1.5.4/doc/rofi-theme-selector.1.markdown
There is also a manpage for themes (rofi-theme) (lower level info), a wiki page https://github.com/davatorium/rofi/wiki/themes.

For the applications,  this is  very likely not a direct problem of rofi, it has to do with your setup. I don't know (the details) of your setup, I suspect in the Mint support channel they can provide better help.

**Comment by DaveDavenport** [comment]
Please ask questions in the correct place.    If (and only if) the application issue is a rofi problem and  still exists in the last issue please replay, I will reopen the issue.
