### ISSUE TITLE
How to change drun icon size?

### ISSUE THREAD

**Issue by meiuwa** [davatorium/rofi#1195]
**Rofi Version: 1.6.0**

The title is pretty much self explanatory... I can't find the documentation for this and my search result suggests that it is tied with the `font` config when it's not. How can one change the icon size in `drun` menu?

![Screenshot from 2020-09-15 20-20-43](https://user-images.githubusercontent.com/44991669/93165236-12044180-f74e-11ea-8d8d-9d6b92723c57.png)

**Comment by DaveDavenport** [comment]
Please don't just delete the template and ignore  the guidelines when filing an issue!

There is a large warning in[ release notes](https://github.com/davatorium/rofi/releases/tag/1.6.0), its in the rofi-themes manpage, and there are several other bugs on the topic: #1194, #1185, #1186.
