### ISSUE TITLE
[REQUEST] DEB Package

### ISSUE THREAD

**Issue by zero77** [davatorium/rofi#1200]
Could you please provide a deb package on github for each new release.
Because, most distro repositories now seem to be out of date:

[![Packaging status](https://repology.org/badge/vertical-allrepos/rofi.svg)](https://repology.org/project/rofi/versions)

**Comment by DaveDavenport** [comment]
I don't have the time nor interest in creating and maintaining distribution specific packages.

If somebody is willing to do this, that would be appreciated and I will link to them.
