### ISSUE TITLE
[BUG] Rofi doesn't detect some apps.

### ISSUE THREAD

**Issue by Valleriite** [davatorium/rofi#1203]
## Version
1.6.0-9-g6ba878e4 (makepkg)
## Configuration

https://gist.github.com/Valleriite/ddf710ae88f0d84ceda10273324b96fa

## Launch Command

I am not sure what to put here,I am using awesome wm with the material theme

## Steps to reproduce

- Install LXQt Configuration Center(lxqt-config) -Possibly other apps can cause the issue too-
- Open rofi
- Search for the term "lxqt-config" or "lxqt configuration center"

## What behavior you see

- LXQt Configuration Center doesn't show up.

## What behavior you expect to see

- LXQt Configuration Center shows up.

**Additional details:**
- The config is here:https://github.com/ChrisTitusTech/material-awesome/blob/master/configuration/rofi.rasi
I don't think a screenshot is needed
Also, sorry for reviving that old issue

**Comment by DaveDavenport** [comment]
What desktop environment are you running? the LXQt desktop specify they should only be shown when running LXQt.

**Comment by Valleriite** [comment]
As I said I am using awesome wm

**Comment by Valleriite** [comment]
with manjaro linux and this config:https://github.com/ChrisTitusTech/material-awesome

**Comment by Valleriite** [comment]
oh,you mean they wont show up on anything apart from lxqt

**Comment by Valleriite** [comment]
Shall I close the issue?

**Comment by DaveDavenport** [comment]
See here: https://github.com/lxqt/lxqt-config/blob/master/lxqt-config-monitor/resources/lxqt-config-monitor.desktop.in

The desktop file  says only show in LXQt. DRun mode tries to obey the standard.
If you want you can copy the desktop files in ~/.local/applications/ and remove this line.
