### ISSUE TITLE
[BUG] Text ended before matching quote was found for ".

### ISSUE THREAD

**Issue by scrouthtv** [davatorium/rofi#1205]
Hello,
I've encountered a problem with rofi and don't know where to start.
I have created to script files (`/home/lenni/git/rofi-scripts/actions.sh` and `/home/lenni/git/rofi-scripts/texdoc4rofi.sh`).

I first had this config:
```
configuration {
modi: [combi,"texdoc:~/git/rofi-scripts/texdoc4rofi.sh",window,run];
	combi-modi: [drun,window];
	matching: "normal";
	sidebar-mode: true; 
	font: "Fira Code 10";
	width: 960;
	lines: 16;
	yoffset: -180;
	bw: 0;
	window-format: "{n} {t}";
	fixed-num-lines: false;
	show-icons: true;
	terminal: "termite";
	drun-show-actions: true;
	scroll-method: 0;
	max-history-size: 100;
	theme: "/home/lenni/.config/rofi/theme.rasi";
}
```
Which worked perfectly fine.

Now I changed the `modi:` line to 
```
-       modi: [combi,"texdoc:~/git/rofi-scripts/texdoc4rofi.sh",window,run];
+       modi: [combi,"actions:~/git/rofi-scripts/actions.sh","texdoc:~/git/rofi-scripts/texdoc4rofi.sh",window,run];

```
Which seems fine for me too.
However, when I run rofi, I get this error:
![image](https://user-images.githubusercontent.com/23227405/94942809-131bc980-04d7-11eb-9c59-62d6d523b7d8.png)

Can I only use one script mode at a time? Or what am I missing?

Thank you in advance.

**Comment by scrouthtv** [comment]
Thank you. Should I close?

**Comment by DaveDavenport** [comment]
No, it is still a bug

**Comment by DaveDavenport** [comment]
Fixed in git, (I hope).
