### ISSUE TITLE
[BUG] window mode alignment issue with i3 scratchpad windows

### ISSUE THREAD

**Issue by infokiller** [davatorium/rofi#1209]
## Version

Output of `rofi -v`: `Version: 1.6.0`

## Configuration

Output of `rofi -help` (in a [gist](https://gist.github.com/), please paste the *full* output): https://gist.github.com/infokiller/c27758987dc51c929aff2cd49c1d4d49

## Launch Command

`The commandline used to launch **rofi**`: `rofi -no-config -show window`

## Steps to reproduce

- Install i3
- Create a window and send it to the scratchpad
- Invoke `rofi -no-config -show window`

## What behaviour you see

The columns of lines of scratchpad windows are not aligned:

![image](https://user-images.githubusercontent.com/10516814/95095206-70ac5200-0733-11eb-8904-5f95878baffa.png)

## What behaviour you expect to see

- Workspace names are aligned

## Workaround

Using this setting in my xresources file fixes the issue, though it also adds a lot of space after the desktop name in the entries:
```
rofi.window-format:               {w}\011{c} {t}
```

Note that `\011` is interpreted as a tab character by xrdb [1].

[1] https://jlk.fjfi.cvut.cz/arch/manpages/man/XrmGetDatabase.3#FILE_SYNTAX

**Comment by infokiller** [comment]
Using `rofi -window-format '{w:20} {c:-40} {t}' -show window` still results in the alignment issue above.
Am I missing something?

**Comment by DaveDavenport** [comment]
hmm under i3 I get no alignment issue for the workspace ..

**Comment by DaveDavenport** [comment]
![image](https://user-images.githubusercontent.com/406245/95098727-57090b80-072f-11eb-8c78-714e61739deb.png)

**Comment by DaveDavenport** [comment]
Yeah, that could be the issue. It uses 'g_utf8_strlen' to count chars, and that will most likely count them and screw up alignment.
