### ISSUE TITLE
[REQUEST] Ability To have different configurations per mode

### ISSUE THREAD

**Issue by YousefH** [davatorium/rofi#1210]
**Describe the feature**
Ability To have different configurations per mode. For example:

```
configuration {
	columns: 3;
	show-icons: false;
}
configuration.window {
	columns: 1;
	show-icons: true;
}
configuration.drun {
	show-icons: true;
}
```

- Rofi version: 1.6.0

Not that disparate for the feature tho.

**Comment by SquirrelSenpai** [comment]
@YousefH  This is already possible with -theme <config> 

eg. 
rofi -show run -theme run (run.rasi in config)
rofi -show window -theme win (win.rasi i config)

This feature already exist, please closed your ticket.
