### ISSUE TITLE
drun within user service

### ISSUE THREAD

**Issue by OJFord** [davatorium/rofi#1213]
In order to have the correct environment, (from `$XDG_CONFIG_HOME/environment.d/`) I'd like desktop files I launch with drun to run within the `user@pid.service` instead of `session-n.scope`.

I can achieve that with a `rofi-drun.service`:
```ini
[Unit]
Description=rofi drun

[Service]
Type=forking
ExecStart=rofi -show drun
```

but then I can only run (`systemctl --user start rofi-drun`) one application at a time (since rofi-drun is considered active already if I try to launch a second).

Is there any way to achieve this with rofi directly, or might it be considered as a feature if not?

**Comment by OJFord** [comment]
What... it gave me no template.. :thinking:

**Comment by dannycolin** [comment]
It does. Here's a screenshot of the editor when you open a new bug report:
![image](https://user-images.githubusercontent.com/7339076/95924378-78987180-0d85-11eb-900d-e061334d36c4.png)

**Comment by OJFord** [comment]
Yes, that happened when I tried again. I didn't delete it or anything though - I wasn't even presented with the bug/request choices when I opened this one.
