### ISSUE TITLE
[REQUEST] pango markup text rendering in prompt

### ISSUE THREAD

**Issue by wis** [davatorium/rofi#1220]
## Before creating a feature request
- [x] I checked the *next* branch to see if the feature has already been
  implemented
- [x] I searched existing reports to see if it is already requested.

## What is the user problem or growth opportunity you want to see solved?
pango markup works in results but does not work in prompt text

...

## How do you know that this problem exists today? Why is this important?
I tried `rofi -markup -markup-rows -p '<span color="red">enter action</span>' -dmenu`
it's useful because sometimes prompt can be long and you can use pango markup to make what is required from the user to input stand out. for example
`'I'm feeling lucky Google search <span color="red">query</span>'`
...

## Who will benefit from it?
users of rofi making and using complex workflows, for example:
./rofi-complex-workflow.sh
``` .bash
method="$(cat ~/.local/bin/methods | rofi -markup -i -markup-rows -p "action" -dmenu)"
echo "$method"
if [ ! -z "$method" ]; then
  query="$(rofi -markup -markup-rows -p "$method <span color=\"red\">query</span>" -dmenu)"
  echo "$query"
  action="$(cat "$HOME/.local/bin/actions/$method" | rofi -markup -markup-rows -i -p "$method actions for \"$query\"" -dmenu)"
  echo "$action"
  # ......
fi
```
./methods:
```
gs Google search
gls Google lucky search
```
./actions/gs Google search:
```
<span color="orange">Search</span>
<span color="orange">Show/update</span> suggestions
```
...

## Version

Output of `rofi -v`: `Version: 1.6.0`

## Configuration

Output of `rofi -help` (in a [gist](https://gist.github.com/), please paste the *full* output)
https://gist.github.com/wis/ba3fb19d39e5e141f5209426881d2a1f

**Additional details:**
- Include a link to your private config
```
 # Dark theme.
rofi.theme: ~/.cache/wal/colors-rofi-dark.rasi

# Light theme.
rofi.theme: ~/.cache/wal/colors-rofi-light.rasi
```
- Include screenshots/casts of your issue
screenshot with pango markup outputted literally in prompt text:
![rofi-prompt-bugg](https://user-images.githubusercontent.com/9993663/98789426-f2fef480-240a-11eb-8917-1488745b32f5.png)

**Comment by DaveDavenport** [comment]
You can already get the result replicated using the theme engine:

```
echo "oops" | rofi -dmenu -theme-str 'prompt { text-color: red; }' -p "Action"
```
