### ISSUE TITLE
[BUG] message text is invisible when surrounded with pango markup

### ISSUE THREAD

**Issue by wis** [davatorium/rofi#1221]
## Version
Output of `rofi -v`: `Version: 1.6.0`

## Configuration
Output of `rofi -help` (in a [gist](https://gist.github.com/), please paste the *full* output)
https://gist.github.com/wis/ba3fb19d39e5e141f5209426881d2a1f

## Launch Command
`rofi -mesg "<span color="red">actions:</span>" -i -markup -markup-rows -p "action" -dmenu`

## Steps to reproduce
- Step 1
run `rofi -mesg "<span color="red">actions:</span>" -i -markup -markup-rows -p "action" -dmenu`

## What behaviour you see
the message text is not visible
![rofi-bug2](https://user-images.githubusercontent.com/9993663/98790405-576e8380-240c-11eb-904a-ef02fad02859.png)

## What behaviour you expect to see
the message text should be visible and red
like this, but the text "actions:" should be red:
![rofi-bug1](https://user-images.githubusercontent.com/9993663/98790438-605f5500-240c-11eb-8fd8-67832f225205.png)
(the command I ran in this screenshot is the same but with the markup removed:
`rofi -mesg "actions:" -i -markup -markup-rows -p "action" -dmenu`)

**Additional details:**
- Include a link to your private config
```
 # Dark theme.
rofi.theme: ~/.cache/wal/colors-rofi-dark.rasi

# Light theme.
rofi.theme: ~/.cache/wal/colors-rofi-light.rasi
```
- Include screenshots/casts of your issue
see above

**Comment by DaveDavenport** [comment]
You commandline quoting is invalid and results in invalid pango markup (this is also dumped by pango on the terminal).

```rofi -mesg '<span color="red">actions:</span>' -i -markup -markup-rows -p "action" -dmenu```

**Comment by wis** [comment]
this is not a bug, I forget to escape quotes, so rofi get the message text input as `<span color=` and rendered it to invisible text.
`rofi -mesg "<span color=\"red\">actions:</span>" -i -markup -markup-rows -p "action:" -dmenu` or 
`rofi -mesg '<span color="red">actions:</span>' -i -markup -markup-rows -p "action:" -dmenu` works as expected.
