### ISSUE TITLE
Rofi slow startup

### ISSUE THREAD

**Issue by kushraj** [davatorium/rofi#1222]
## Version

Version: 1.6.0

## Configuration

[gist](https://gist.github.com/kushraj/6421c712943722d7c9bb8be9f7b4e59a)

## Launch Command

`The commandline used to launch **rofi**`

rofi -show drun

## Steps to reproduce

1. clear the cache using ```echo 1 > /proc/sys/vm/drop_caches```
2. run the launch command

## What behaviour you see
rofi window opening after min 3 seconds

## What behaviour you expect to see
rofi window should show up instantly < 1sec 

**Additional details:**
-Logs and config are in the gist

**Comment by DaveDavenport** [comment]
Given you need 'drop_vm_caches' to reproduce this, it sounds like a slow I/O system. This is a known "issue".

You can try passing: `rofi -drun-use-desktop-cache`  that should create a cache, this might speed it up after its been created (still needs to load the data, but less walking of filesystem is required).

**Comment by kushraj** [comment]
I did as you said, and lessening the number of user fonts indeed reduced the launch time by a second, 
but after using ``` rofi -drun-use-desktop-cache -show drun``` rofi is crashing after launching an application with error
    Dialogs.DRun:ERROR:source/dialogs/drun.c:1034:drun_mode_result: code should not be reached
Bail out! Dialogs.DRun:ERROR:source/dialogs/drun.c:1034:drun_mode_result: code should not be reached
[1]    5087 abort (core dumped)

**Comment by DaveDavenport** [comment]
That is right, I should make a new release to fix that bug.
