### ISSUE TITLE
No category for desktop entry[BUG] 

### ISSUE THREAD

**Issue by mrneilypops** [davatorium/rofi#1223]
I have installed Firefox on Debian 11 in addition to Firefox-ESR.
I have a desktop entry as per;

`[Desktop Entry]
Name=Firefox Stable
Comment=Web Browser
Exec=/usr/bin/firefox %u
Terminal=false
Type=Application
Icon=/opt/firefox/browser/chrome/icons/default/default128.png
Categories=Network;WebBrowser;
MimeType=text/html;text/xml;application/xhtml+xml;application/xml;application/vnd.mozilla.xul+xml;application/rss+xml;application/rdf+xml;image/gif;image/jpeg;image/png;x-scheme-handler/http;x-scheme-handler/https;
StartupNotify=true
Name[en_GB]=Firefox 82`

The menu does not show the category as per screenshot.
How can I fix this?
![Nov14::201946](https://user-images.githubusercontent.com/1450448/99155297-d4bd2100-26b6-11eb-9d0b-3602682df504.png)

**Comment by DaveDavenport** [comment]
Is that desktop file all on a single line? can you attach the actual file?

**Comment by mrneilypops** [comment]
Thanks Dave...no it is not...not sure why it does not format...please find attached text file.
[firefox-desktopentry.txt](https://github.com/davatorium/rofi/files/5541385/firefox-desktopentry.txt)

**Comment by DaveDavenport** [comment]
That desktop file works fine for me. 
```
 rofi -show drun -drun-categories 'WebBrowser'
```
makes it show up..

I think you are mixing up GenericName (that get printed between () after the name, with category.

**Comment by mrneilypops** [comment]
Yes. Firefox shows and runs fine but there is no category as per screenshot.
![rofi](https://user-images.githubusercontent.com/1450448/99156105-b529f680-26be-11eb-9903-48f8b95998f4.png)

**Comment by DaveDavenport** [comment]
You did not post your config, so I cannot check.

But if you use default, the text between brackets is **generic name** not **category**.

```
{name} [<span weight='light' size='small'><i>({generic})</i></span>]
```

**Comment by DaveDavenport** [comment]
Closing, does not look like a bug.. desktop file works fine.

**Comment by mrneilypops** [comment]
I am an idiot.
GenericName=Web Browser added to firefox.desktop.
Thanks for the hint.
