### ISSUE TITLE
[BUG] rofi lists windows of wrong X11 screen

### ISSUE THREAD

**Issue by mjk-gh** [davatorium/rofi#1225]
## Version

Output of `rofi -v`:

Version: 1.5.4, also tried git commit 94bd12e4.

## Configuration

Output of `rofi -help` (in a [gist](https://gist.github.com/), please paste the *full* output)

https://gist.github.com/mjk-gh/fac297d30bea93c8bcf88805acc9f54d
(That compose key entry error message is probably harmless, the first affected line reads:
<Multi_key> <exclam> <exclam>           : "\241"        exclamdown
)

## Launch Command

`The commandline used to launch **rofi**`

rofi -show-icons -show window

## Steps to reproduce

- Step 1: Configure X11 to manage your two monitors as two separate screens, :0 and :0.1, no Xinerama, like so:
```
--------------[ /etc/X11/xorg.conf ]---------------
Section "ServerLayout"
    Identifier            "LayoutDeskBoth"
    Screen             0  "ScreenDesk"  0  0

    # We choose 1921 instead of 1920, because that 1-pixel gap
    # disables switching screens by mouse (which would interfere with
    # our mouse-switching between different virtual pages on each
    # screen), instead we use the keyboard to switch screens, using
    # <https://de.mcbf.net/david/dualscreenmouseutils/>.
    Screen             1  "ScreenDeskRight"  1921 0
    Option                "Xinerama"  "0"
EndSection
---------------------------------------------------
```
  (Certainly, you don't need that 1-pixel gap, it's just the way my system is configured)
  Use fvwm 1:2.6.8-1+b1 in Debian testing (amd64) as your window manager.

- Step 2: Switch to the second screen (:0.1)
- Step 2: Call rofi

## What behaviour you see

- rofi appears on the second screen (:0.1), but lists only windows from the first screen (:0.0).

## What behaviour you expect to see

- rofi should show at least the windows of the current screen.

  Even better would be (as an option) listing all windows on all
  screens, grouped by screens (and with an appropriate title, so
  at least ":0.1" etc., or even an option to show configurable
  aliases of the screen names, like "Development" for ":0.1"),
  with a well visible separation between each group (empty
  (half-)line or a horizontal "ruler" (as in HTML-&lt;hr&gt;)).

**Additional details:**
- No private config, nothing configured, no /etc/rofi.conf and no ~/.config/rofi/config.

__*P.S.:*__ *I followed the bug reporting guidelines to a T, and the issue got immediately closed. After editing the closed issue and just adding the "Follow the guidelines" text block, the issue got re-openend. Then, for testing purposes, I removed that "Follow the guidelines" text block again (because other bug reports don't have this block, either), and now the issue stays open. What gives?*

**Comment by DaveDavenport** [comment]
No idea, AI works in mysterious ways.

**Comment by nPHYN1T3** [comment]
I can confirm this, I have 3 XScreens running 9 screens and rofi rofi -show window only lists windows from XScreen 0.0 on GPU 0 and ignores all the other XScreens on the other GPU's.

**Comment by DaveDavenport** [comment]
I don't have a setup like this to try it out. a patch to fix this would be appreciated.

**Comment by nPHYN1T3** [comment]
I'd wager you don't need the set up, just make rofi poll/query all XScreens rather than assume the default. I have noticed a lot of things are broken for more than one XScreen which recently made me give up on the XFCE4-panel since it won't list all windows correctly either. It's list is jailed to the XScreen it's running on so you need a separate panel instance for every XScreen (waste of space much). So I made a little cheese call script with zenity as a quick and dirty tide over that just uses a loop and wmctrl -l. What I can't answer is what in the system would be more efficient to poll for the number of XScreens, though I suppose you could sniff the xorg.conf but I'd think there is a better way than that.

**Comment by DaveDavenport** [comment]
trying to parse xorg.conf sounds like an epic bad solution.

**Comment by DaveDavenport** [comment]
```c
    xcb_connect (const char *display,
                 int *screen );

Connects to the X server specified by display. If display is null, uses the value of the DISPLAY environment variable. If a particular screen on that server is preferred, the int pointed to by screen (if non-null) will be set to that screen; otherwise the screen will be set to 0.
```
this method is used to get connection and the screen id.
The screen is then passed to the `xcb_ewmh_get_client_list` to get the list.

As I said, I don't have the right setup to properly debug the issue. Dry programming a solution when I am not sure what is going on is not going to work.

Patch is welcom.

**Comment by DaveDavenport** [comment]
^^ No idea if that will fix anything.

**Comment by DaveDavenport** [comment]
Given no reply, I will assume that the issue is fixed.

**Comment by nPHYN1T3** [comment]
Not fixed, I just moved on.
