### ISSUE TITLE
[BUG] How do I use <Alt+number> to switch between active modi

### ISSUE THREAD

**Issue by YHYJ** [davatorium/rofi#1226]
:exclamation:
First read the [guidelines](https://github.com/DaveDavenport/rofi/blob/next/.github/CONTRIBUTING.md)!
This is not optional for any report/question. People must be able to understand the full context of the report when reading it, at any time.
If you feel like you “just have a simple question”, please consider you’re wrong and still fill the full report.
Any report missing these informations will be labeled as “Incomplete Report - Please follow the guidelines” and may not be answered in a timely fashion.
:exclamation:

## Version

Output of `rofi -v`

`Version: 1.6.1`

## Configuration

Output of `rofi -help` (in a [gist](https://gist.github.com/), please paste the *full* output)

[rofi_help.txt](https://gist.github.com/YHYJ/339f3f4dbf75e73b5191b7a6cd05a765)

## Launch Command

`The commandline used to launch **rofi**`

```bash
bindsym $mod+d exec --no-startup-id rofi -show combi
```

## Steps to reproduce

- Step 1

  Use $mod+d shortcut to start rofi

- Step 2

  Use <Alt+number> (eg <Alt+2>) to switch to the second modi

## What behaviour you see

- rofi automatically quit

## What behaviour you expect to see

- rofi switches to the second modi

**Additional details:**
- Include a link to your private config
- Include screenshots/casts of your issue

It is normal to switch modi by <Alt+number> in rofi 1.6.0

**Comment by DaveDavenport** [comment]
Yet this indeed broke.

**Comment by YHYJ** [comment]
Is there a plan to fix it?

**Comment by DaveDavenport** [comment]
Given I did not close the bug with a `Won't Fix`. I suspect it will be fixed.

**Comment by YHYJ** [comment]
Ok, thanks!

**Comment by DaveDavenport** [comment]
This been partially fixed, only 'custom scripts'  break this for now.
