### ISSUE TITLE
[BUG] Window Manager loses focus after closing rofi

### ISSUE THREAD

**Issue by ortango** [davatorium/rofi#1228]
## Version

latest next build as of 1c9d975dd2aff1794c6484465482c796c41a1358

reverting this commit returns the old behavior.

## Steps to reproduce

- launch rofi (override-redirect)
- exit using escape

## What behaviour you see

- focus in not returned after rofi exits

## What behavior you expect to see

- the previous behavior kept focus intact after rofi exits

**Additional details:**
- this is with bspwm. i have not tried other WMs to see if they behave differently.

**Comment by dtrsan** [comment]
I can reproduce it on my laptop with themes that use configuration `fullscreen: true;`.
The minimal configuration that reproduce the bug is
```
configuration {
 fullscreen: true;
}
```
I'm using i3 wm.

E.g.
```shell
$ rofi -v
Version: 1.6.1-3-git-1c9d975d-dirty (next)
$ cat bug.rasi 
configuration {
 fullscreen: true;
}
$ rofi -show drun -modi drun -theme ./bug.rasi
# press escape to close rofi
```

Not sure when the bug is introduced.
