### ISSUE TITLE
[BUG] bw and theme options don't play nicely together

### ISSUE THREAD

**Issue by grenmester** [davatorium/rofi#1229]
## Version

Output of `rofi -v`

```
Version: 1.6.1
```

## Configuration

Output of `rofi -help` (in a [gist](https://gist.github.com/), please paste the *full* output)

https://gist.github.com/grenmester/519a5989d94f5f00e82cc9fc936880dc

## Launch Command

```
rofi -show drun
rofi -show drun -theme '~/.config/rofi/config.rasi'
```

## Steps to reproduce

```
# ~/.config/rofi/config.rasi

configuration {
  theme: "solarized";
  bw: 55;
}
```

## What behaviour you see

I'm trying to set a wider border around the `rofi` window using the `bw` option in `config.rasi` and running `rofi -show drun`. This usually works, however, when I include `theme: "solarized";` or any other theme for that matter, the `bw` option seems to get ignored. However, if I try to change other settings such as `font` or `show-icons` in `config.rasi` then it seems to register those options.

If on the other hand I try using `rofi -show drun -theme '~/.config/rofi/config.rasi'`, then the `theme` option in `config.rasi` gets ignored but the border option gets registered properly and the border width is changed accordingly.

I have also tried doing something like

```
#window {
  border: 55;
}
```

but this doesn't work either although if you were to set the border of something else like the `inputbar` then it works. After looking through the theme source config (https://github.com/davatorium/rofi-themes/blob/master/Official%20Themes/solarized.rasi), it seems like this is because the `window` border is set but the `inputbar` border is not.

Is the best or preferred option to just take the contents of the solarized `rasi` config, paste it into my config, modify what I need, and remove the `theme: "solarized";` line in my `config.rasi`?

## What behaviour you expect to see

I would expect to be able to use the solarized default theme and be able to not just set the border but in a way that doesn't override the solarized theme.

**Comment by DaveDavenport** [comment]
Not sure I completely follow the issue. but:

* The `-bw` option is deprecated. ( I see it is not correctly marked as this, will fix)
* ~/.config/rofi/config.rasi gets loaded by default (its it config file) loading this again as theme is weird.

The 'normal way' to do this is in your config.rasi file:

```css

configuration{

}

@theme "soralized"

window {
    border: 50px;
}
```

This will load solarized, and then override the `window::border` property.

**Comment by grenmester** [comment]
This answers my question. I had not seen this way of using `@theme "solarized"` and instead had been using `theme: "solarized"` in the configuration block since I was looking at the [example in the Arch Wiki](https://wiki.archlinux.org/index.php/Rofi). I was only trying to use `rofi -show drun -theme '~/.config/rofi/config.rasi'` because it seemed to do something different other than just doing `rofi -show drun` so it seemed to be worth a try.

**Comment by DaveDavenport** [comment]
The arch wiki had wrong/outdated instructions many times.. I gave up trying to correct it.
