### ISSUE TITLE
Allow multiple Rofi windows

### ISSUE THREAD

**Issue by JustinLovinger** [davatorium/rofi#1232]
## Before creating a feature request
- [x] I checked the *next* branch to see if the feature has already been
  implemented
- [x] I searched existing reports to see if it is already requested.

## What is the user problem or growth opportunity you want to see solved?

I would like to be able to open multiple simultaneous Rofi windows. I use Rofimoji to insert Unicode and Emoji through a Rofi menu. I setup a Rofi menu to create named Sway workspaces, with the intention of adding Emoji names, only to discover that the Rofimoji menu will not show up while another Rofi menu is open. I would like to be able to use Rofimoji to insert Unicode into another Rofi window.

## How do you know that this problem exists today? Why is this important?

See above.

## Who will benefit from it?

Anyone who uses Rofi to interact with windows and wants to interact with Rofi windows.

## Version

1.5.4-dev

## Configuration

https://gist.github.com/JustinLovinger/adb5218e4cc60a72b60b974249bb8c76

**Comment by DaveDavenport** [comment]
2 points:

1.)  This will break rofi, as you will have 2 window trying to grab keyboard/mouse and be on top of other windows.

2.)  If you combine it with 'normal-window' mode it might work, and you can already do this by giving them a different pid file.

**Comment by JustinLovinger** [comment]
@DaveDavenport Is the pid file only used for preventing multiple Rofi windows? If so, it might be helpful to ignore the pid file when `-normal-window` is used, or provide a separate option to ignore pid file. That would be easier on the user than creating separate pid file paths for separate calls.

**Comment by DaveDavenport** [comment]
`normal-window` should not be used except for testing (it is marked as experimental for a reason).

People who use `normal-window` should be more advanced users and for them I don't think setting another pid file should be a problem.
