### ISSUE TITLE
[BUG] window focus stolen by rofi restored after rofi quit, but active state not restored in -no-normall-window mode

### ISSUE THREAD

**Issue by unisgn** [davatorium/rofi#1238]
## Version
**rofi** latest git build next [11b677b](https://github.com/davatorium/rofi/commit/11b677b521140cd7d7451c54f48cd6c2d9c9bf4a)

## Launch Command

launch rofi in a terminal emulator, i.e. urxvt: rofi -show drun

## Configuration
-no-normal-window

## Steps to reproduce

- Step 1: open urxvt
- Step 2: launch rofi in urxvt: rofi -show drun
- Step 3: quit rofi by Escape or Ctrl + g

## What behaviour you see
I have a picom compositor with settings like inactive-opacity:0.8, active-opacity: 1.0

- after launch rofi in urxvt, the urxvt window's focus lost, cursor shape becomes the outline beam and opacity changed to 0.8
- after quit rofi by Escape or Ctrl + g, the urxvt window gains focus again, I can type some letter, but the cursor remains the outline beam shape, and the opacity remains the inactive-opacity, which is 0.8. It seems that focus was restored, but the active state was not.
- I have to click the urxvt window with the mouse, then the cursor becomes the solid beam shape, and window opacity was changed to active-opacity:1.0 

## What behaviour you expect to see

- after quit rofi, the urxvt window's active state should be restored too as the focus does .

**Additional details:**
- It seems this issue related to #1228 & #1233.
- I have to open a new window, then everything comes back normal.
- with version 1.6.1 build, everything is good.
- only happens in -no-normal-window mode, in the -normal-window mode, everything is good.

**Comment by DaveDavenport** [comment]
is this really a rofi issue? it seems picom fails to restore opacity after focus is restored.

**Comment by unisgn** [comment]
@DaveDavenport First, everything looks good before launch rofi. Second, with 1.6.1 build, everything is ok too. So I think the issue should be the commits after 1.6.1.

**Comment by DaveDavenport** [comment]
Playing a bit the 'advocate of the devil'  here:  maybe rofi new code exposed a flaw in picom?
If focus gets returned to the window correctly, shouldn't picom (who is responsible for setting opacity) update this?

**Comment by unisgn** [comment]
As I mentioned, this issue, and the previous issues #1228 & #1233, might be related.

**Comment by DaveDavenport** [comment]
I am not denying the change might have cause it, just wanting to keep the possibility open that this might be fixed somewhere else.

**Comment by unisgn** [comment]
Got it.
By the way, what is O-R mode in rofi? And what does 'focus stealing' do?
Due to my poor knowledge about x11 and C, and even newbie in rofi, it's hard to dive into the code. But I do like rofi, and pulled the prefix matching method request.

**Comment by sardemff7** [comment]
Does 2e1813366720cc5e59a9454a544f3af71b70dcae fixes this issue as suggested in your comment on 11b677b521140cd7d7451c54f48cd6c2d9c9bf4a?

**Comment by unisgn** [comment]
Sure, it does.
