### ISSUE TITLE
[REQUEST] -selected-row alternative to select a row by his displayed position

### ISSUE THREAD

**Issue by takuyozora** [davatorium/rofi#1245]
## Before creating a feature request
- [x] I checked the *next* branch to see if the feature has already been
  implemented
- [x] I searched existing reports to see if it is already requested.

## What is the user problem or growth opportunity you want to see solved?

I would like to be able to preselect a row by his displayed position, even if I use a filter with the `-filter` CLI option. 
Right now, mixing `-selected-row` and `-filter` result in a not obvious behavior.

## How do you know that this problem exists today? Why is this important?

I've made tests with the `next` branch :

```bash
$ echo "azerty,qwerty,bepo,pour,contre" | rofi -dmenu -sep "," -selected-row 1
# SELECTED LINE = 1, TEXT="qwerty"
$ echo "azerty,qwerty,bepo,pour,contre" | rofi -dmenu -sep "," -selected-row 1 -filter po
# SELECTED LINE = 0, TEXT="bepo"
```
The excepted result IMHO should be : 

```bash
$ echo "azerty,qwerty,bepo,pour,contre" | rofi -dmenu -sep "," -selected-row 1 -filter po
# SELECTED LINE = 1, TEXT="pour"
```

## Who will benefit from it?

I can understand that users can prefer to keep this behavior, nevertheless I think that some others should be interested by an option selecting a row by his displayed position. That's why I propose a new option : `-filtered-selected-row` (the name is not terrible but I haven't found any better).

I've made a commit in order to obtain this behavior, it's surely not perfect, but it does work : https://github.com/takuyozora/rofi/commit/b4b2c97f2cb78779079986ba87c4ed16b1516e45

With this commit you can do this : 

```bash
$ echo "azerty,qwerty,bepo,pour,contre" | rofi -dmenu -sep "," -filtered-selected-row 1 -filter "po"
# SELECTED_LINE = 1, TEXT="pour"
```

For instance, I use it for my Alt+tab switcher in order to pre-filter applications by their name (as the Alt+² in gnome-shell) but keeping my pre-select window behavior.

## Version

```bash
$ rofi -v
Version: 1.6.1-7-g36a78bae (makepkg)
```

I hope hat my request is rightly filled and a big thanks for this amazing piece of software, I use it a thousand times every day !

**Comment by DaveDavenport** [comment]
For me the current behavior is correct and obvious:

```bash
echo "azerty,qwerty,bepo,pour,contre" | rofi -dmenu -sep "," -selected-row 3 -filter po
```
selects the 4th row and highlights it.

The 'filtering' of the list is an additional operation. (maybe -selected-entry would have been a better name?)

For  `-filtered-selected-row` I wonder about a practical use case, as the filtering (and possible results) depends on user settings (like sorting/matching method), so it becomes very hard to 'select' the right entry.  I am afraid this will result in possible weird behavior for the user.

For this purpose we have `-select`  function.

```bash
 echo "azerty,qwerty,bepo,pour,contre" | rofi -dmenu -sep "," -select pour  -filter po
```
