### ISSUE TITLE
[REQUEST] Pass -selected-row as mode option

### ISSUE THREAD

**Issue by vredesbyyrd** [davatorium/rofi#1248]
## Before creating a feature request
- [x] I checked the *next* branch to see if the feature has already been
  implemented
- [x] I searched existing reports to see if it is already requested.

## What is the user problem or growth opportunity you want to see solved?

In script mode, a handful of options can be passed internally, eg .. `echo -en '\0active\x1f2\x0f` to set the active row. Having an option to pass `-selected-row` in the same fashion would be nice to have. 

## How do you know that this problem exists today? Why is this important?

Say you have a Main Menu with 5 rows. Each row will present a different submenu when selected. On selection of the 'MPD Queue'  row the currently playing track will be set as `selected-row`. 

Another use case below.    

## Who will benefit from it?

Anyone who uses the script mode

## Version

Version: 1.6.1

**Additional details:**

I am currently working a little rofi-media-browser. One option is to open a selections corresponding imdb page. When doing so it would be nice to have the view remain visually static to the user upon selection. With a `-selected-row` option this could be accomplished by passing the lines index to `-selected-row` for the next call. I can't say how difficult this would be to implement, but definitely a nice-to-have feature.  

![rofi-2020-12-31-2158-00000](https://user-images.githubusercontent.com/22080838/103433230-7808bd80-4bb3-11eb-85e9-a1f521951b79.png)

**Comment by DaveDavenport** [comment]
In next release (1.7.4) there is a 'keep selection'  option.
