### ISSUE TITLE
[BUG] Config files conflict

### ISSUE THREAD

**Issue by yPhil-gh** [davatorium/rofi#1249]
## Version

Version: 1.5.4

## Configuration

See below

## Launch Command

`rofi -show window -show-icons -normalize-match -window-thumbnail`

## Steps to reproduce

- Copy `~/.config/rofi/config.rasi` to `~/.config/rofi/config`
- So now you have two config files

## What behaviour you see

Although `rofi -h` still says "Configuration file: /home/x/.config/rofi/config" in fact, it seems that it reads from `/home/x/.config/rofi/config.rasi` instead.

## What behaviour you expect to see
Rofi should list the config file it actually uses, or state a conflict.

**Additional details:**
- https://framagit.org/yphil/dotfiles

**Comment by DaveDavenport** [comment]
I cannot reproduce this with latest release version of rofi.

**Comment by DaveDavenport** [comment]
please let me know if still exists in 1.6.1
