### ISSUE TITLE
[BUG] Unable to disable pango markup in message.

### ISSUE THREAD

**Issue by etosan** [davatorium/rofi#1255]
## Version
```
rofi -v
Version: 1.6.1
```

## Configuration

N/A but can be filled-in later if needed (basically default setup)

## Launch Command

With following setup:
```
$ echo "${some_cli_text}"
scp .ssh/authorized_keys $server.somedomain.maybelocal:.ssh/
```
One executes any of these:
`$echo lol | rofi  -dmenu -p "PROMPT"  -theme-str "textbox { markup: false; }"  -mesg "${some_cli_text}"`
`$echo lol | rofi  -dmenu -p "PROMPT"  -no-markup  -mesg "${some_cli_text}"`

## Steps to reproduce

Run any command above.

## What behaviour you see

message box textbox is empty and stderr blows up with:
```
(process:xxxxx): Pango-WARNING **: 20:16:43.581: pango_layout_set_markup_with_accel: Error on line 1: Entity did not end with a semicolon; most likely you used an ampersand character without intending to start an entity — escape ampersand as &amp;
```

wrapping cli text in `<pre/>` tags do not work either as pango is dumb as brick (even if that worked there is entities and all the other jazz problem):
```
(process:xxxxx): Pango-WARNING **: 20:17:04.018: pango_layout_set_markup_with_accel: Unknown tag 'pre' on line 1 char 14
```

## What behaviour you expect to see

- I would like to have command line snippet appear in messagebox proper.

**Additional details:**

Although this issue seems esoteric (who would want to use unstyled text in their message box right?), I believe having normal unstyled (eg. as-is and potentially complex, CLI like) text in message box is rather valid use case (but I may be wrong). I am also okay with being proven wrong.

The problem is `rofi` always using pango here. It seems that pango can not handle any normal text that is not SGMLized "properly". Unfortunately pango itself, as engine, turns out rather impotent for anything serious besides adding bold style, rainbow colors and picking cute fonts. It lacks any way to escape form it's SGMLy into raw uninterpeted text. I guess at least something like support for `<pre/>` and/or `<pre-span/>` tags would be enough for most basic use cases (but still does not solve all issues like encoding `<` and `>`) .  Anyway this would mean fixing, extending and upstreaming pango itself which I guess is extremely out of scope of rofi.

Second solution, which I would like to propose, would be giving user ability to enforce support for using raw text equivalent for messagebox textbox instead of pango styled one. I don't know how GTK is designed and if this can actually be done realistically (might not be possible), but this seems most doable option to me.

Final approach is to have some pangolized escaper (I consider this option the least preferable) which would consume normal raw text and would turn it into pango-friendly character soup. Unfortunately pango does not seem to conform to any known SGML/XML scheme, nor there is easily findable "official" list of all the entities, tags and other magic sequences it supports. This means such handwritten escaper would probably not be future proof (but maybe I missed something and such escaper is part of pango itself already).

More over, then there is the problem of where should this pangolizer reside: should it be part of rofi to allow rofi users to escape raw (cli) texts in all pango elements wherever applicable, or should it be separate tool that one would need to pipe their texts trough (like when using rofi from shell) to then push their escaped forms into rofi.

I don't know which is the proper answer, that is why I am posting this here.

**Comment by DaveDavenport** [comment]
I tweaked a recent modification to allow force markup, you can now also disable it:

```
rofi -dmenu -theme-str 'textbox { markup: false;}' 
```
should disable markup on the textbox in the 'message' box.

**Comment by etosan** [comment]
I can confirm it works beautifully! 
I tried all the problematic raw texts I had and I have detected no issues so far. 
Thank you very much!

**Comment by DaveDavenport** [comment]
Great, 99% support was already there, so easy addition.
