### ISSUE TITLE
[REQUEST] Verify theme or dry-run mode

### ISSUE THREAD

**Issue by aacebedo** [davatorium/rofi#1260]
## Before creating a feature request

- [x] I checked the *next* branch to see if the feature has already been
  implemented

- [x] I searched existing reports to see if it is already requested.

## What is the user problem or growth opportunity you want to see solved?
I would like to be able to know if a theme is valid before really displaying rofi.

## How do you know that this problem exists today? Why is this important?
I can't validate a rofi template without displaying a rofi window.
I have a app that uses rofi as a simple menu system. I give control of the theming to the user but to have a consistent experience I need to validate the theme before executing rofi. I did not find any dry-run or quiet mode to do so.

## Who will benefit from it?
Any users of rofi wanting to check the validity of a template.

## Version
1.6.1

## Configuration
N/A

**Comment by aacebedo** [comment]
Can I reopen it ? As I missed the template and cannot open a new one without being a duplicate ?

**Comment by DaveDavenport** [comment]
I think if you do 
```bash
$ rofi -no-config -theme mytheme.rasi -dump-theme
```

it outputs a valid theme if the theme is parsable, nothing if not.

To test if valid, you need to display rofi.

**Comment by aacebedo** [comment]
Hi!
Thank you for the answer

I tried to give it an invalid theme to the command but it didn't work.
It dumps the default theme even if the mytheme.rasi is invalid.

What I need is rofi telling me if the theme is valid or not without displaying the error message, just for the output.
As it is a custom format I cannot use an external parser/validator to do this.

**Comment by DaveDavenport** [comment]
aah I see it depends on how unparsable it is.

**Comment by aacebedo** [comment]
If you think it is not a desirable feature to be directly included in rofi, I can create another app and extract the template validation code from rofi.

I can also try to implement the feature as a PR if you do not have the time to do it :)

**Comment by DaveDavenport** [comment]
No, I think it is a good option to add.

**Comment by aacebedo** [comment]
BTW big fan of your app ! Super useful and working great.
thank you for your work !

**Comment by DaveDavenport** [comment]
option been added (see above commit), let me know if more  is needed.
