### ISSUE TITLE
[BUG] window switcher loses the QT window focus between workspaces

### ISSUE THREAD

**Issue by Skabit** [davatorium/rofi#1263]
## Version

Version: 1.5.1

## Configuration

Default rofi configuration (I only installed `rofi` and don't change anything)

## Launch Command

`rofi -show window`

## Steps to reproduce

- In workspace 1 open two apps: a QT window and a GTK window
- Move to workspace 2 and launch rofi command (rofi -show window) and select the QT app in workspace 1.

## What behaviour you see

- When I select the QT app in the workspace 1 the DE (Desktop Environment) lost the focus and selects the GTK window.

## What behaviour you expect to see

- After launch rofi command (rofi -show window) and select the QT app in workspace 1, I expect to maintain the focus on that app.

**Additional details:**
- OS: Debian 10
- DE: Xfce 4.12
- I've tried to select apps between workspaces with the default option for that operation (Alt + Tab) and the focus doesn't lose. In other words, I lost the application focus when only use the rofi command (rofi -show window).

**Comment by DaveDavenport** [comment]
Your version of rofi is almost 3 years old and is no longer supported.

This does sound like a bug in xfwm, for changing workspace/focus rofi sends ewmh request to the window manager.
(It first request a change of workspace, then change of focus). It seems xfwm does not handle these correctly.
