### ISSUE TITLE
[REQUEST] 

### ISSUE THREAD

**Issue by hejops** [davatorium/rofi#1267]
- [x] I checked the *next* branch to see if the feature has already been
  implemented

- [x] I searched existing reports to see if it is already requested.

## What is the user problem or growth opportunity you want to see solved?

I call rofi via `[get-playlist] | rofi -dmenu -i -l 21 -a 10`. I intend to display 21 rows and highlight only the middle row. However, the first row is always highlighted.

## How do you know that this problem exists today? Why is this important?

I've tried most of the options listed [here](https://github.com/davatorium/rofi/blob/01935064d8e9467795e21ec57e3fee9f5f19876b/doc/rofi.1.markdown), but haven't been able to find an option that achieves what I want.

## Who will benefit from it?

The current use case is to display a subset of an mpc playlist so that the user doesn't need to open and close the music client repeatedly. Not highlighting the first row would be a welcome cosmetic enhancement.

## Version

`1.6.1`

## Configuration

https://gist.github.com/hejops/fa448eaa9cc2b13d767157527bf12484
http://ix.io/2Nw3

**Additional details:**
https://i.imgur.com/0dZkGZH.png

**Comment by DaveDavenport** [comment]
I am confused:
```
 464 `-selected-row` *selected row*                                                                  
 465 
 466 Select a certain row.
 467 
 468 Default: *0*
````
is in the manpage you linked.
