### ISSUE TITLE
[BUG] -window-command doesn't work

### ISSUE THREAD

**Issue by juacq97** [davatorium/rofi#1274]
## Version
Output of `rofi -v`
Version: 1.6.1

## Configuration
[rofi -help](https://gist.github.com/juacq97/7c78315b2e18faad37757088a73ef8cf)

## Launch Command
~ $ rofi -window-command "firefox" -show window

## Steps to reproduce

- Run the command from terminal
- Press `Shift-Return`

## What behaviour you see

- Nothing happens (maybe the default `wmctrl` command it's executed, I don't know because `wmctrl -R` doesn't work on herbstluftwm)

## What behaviour you expect to see

- Firefox is launched. I selected firefox as command to be very clear if it worked. I tried with the command I really want to run, `herbstclient bring {window}` and doesn't work.

**Comment by DaveDavenport** [comment]
```rofi -window-command "echo {window}" -show window```

This works fine for me, I see the window id printed out on the terminal.

**Comment by juacq97** [comment]
I started to record the command to show you my issue and then worked... rofi of Schrödinger? Oh well, the ID used on rofi doesn't work with herbstluftwm since herbst expect an hexadecimal code, so I can't use it as I wanted. I'll write a little script instead. Thanks!
