### ISSUE TITLE
[BUG] Focus is "restored" incorrectly in some cases

### ISSUE THREAD

**Issue by ortango** [davatorium/rofi#1275]
:exclamation:
First read the [guidelines](https://github.com/DaveDavenport/rofi/blob/next/.github/CONTRIBUTING.md)!
This is not optional for any report/question. People must be able to understand the full context of the report when reading it, at any time.
If you feel like you “just have a simple question”, please consider you’re wrong and still fill the full report.
Any report missing these informations will be labeled as “Incomplete Report - Please follow the guidelines” and may not be answered in a timely fashion.
:exclamation:

## Version

Output of Version: `rofi -v`
Version: 1.6.1-30-g91a71fd0-dirty (makepkg)

## Configuration

Output of `rofi -help` (in a [gist](https://gist.github.com/), please paste the *full* output)
`rofi -no-config`
i think this is not relevant for this issue report

## Launch Command

`The commandline used to launch **rofi**`
    rofi -modi window -show window

## Steps to reproduce

- switch to an *empty* desktop or workspace
- launch rofi as override redirect using a modi that will focus a window (builtin _or otherwise_). the window can be pulled to the empty desktop, or focused on it's original desktop.

## What behaviour you see

- the newly focused window will not have input focus.
- 2e1813366720cc5e59a9454a544f3af71b70dcae

## What behaviour you expect to see

- the selected window should get input focus.

**Additional details:**
- this was observed while using `bspwm` as window manager (newest git master).
- i apologize for adding another complication to this issue.
- that commit does fix the issue it was intended to, it just causes this new one.
- (side issue/feature request) could the debug info be moved to stderr? as it stands info to stdout causes problems with dmenu style scripts (not relevant to this issue).

**Please do not submit reports related to wayland, see
[here](https://github.com/DaveDavenport/rofi/wiki/Wayland) for more
information.**

**Comment by DaveDavenport** [comment]
I can confirm this one on i3. But I hit it on rare occasion so did not have clear reproduction of it yet. This seems to be it. Thanks.

**Comment by DaveDavenport** [comment]
I noticed it tried to restore input focus to  the window manager XWindow, trying to avoid this, fixes it for me.

I have no idea if this is the right solution. (I also wonder if we should 'revert input focus' to the window we switch too, instead of the one we switch from; iow  update 'focus_revert' when we do a switch?)


```patch
diff --git a/source/xcb.c b/source/xcb.c
index a2ebefb4..84573969 100644
--- a/source/xcb.c
+++ b/source/xcb.c
@@ -1207,6 +1207,17 @@ void rofi_xcb_revert_input_focus (void)
     if ( xcb->focus_revert == 0 )
         return;
 
+
+    xcb_get_property_cookie_t cookie = xcb_ewmh_get_supporting_wm_check_unchecked ( &(xcb->ewmh),
+        xcb_stuff_get_root_window ());
+    xcb_window_t win;
+    if ( xcb_ewmh_get_supporting_wm_check_reply ( &xcb->ewmh, cookie, &win, NULL ) ) {
+      if ( win == xcb->focus_revert ) {
+        return;
+      }
+    }
+
+
     xcb_set_input_focus ( xcb->connection, XCB_INPUT_FOCUS_POINTER_ROOT, xcb->focus_revert, XCB_CURRENT_TIME );
     xcb_flush ( xcb->connection );
 }
```

**Comment by DaveDavenport** [comment]
This might be a better patch:

```patch
diff --git a/source/dialogs/window.c b/source/dialogs/window.c
index 56cc7f5b..73adf045 100644
--- a/source/dialogs/window.c
+++ b/source/dialogs/window.c
@@ -655,6 +655,8 @@ static ModeMode window_mode_result ( Mode *sw, int mretv, G_GNUC_UNUSED char **i
             act_on_window ( rmpd->ids->array[selected_line] );
         }
         else {
+            // Disable reverting input focus to previous window.
+            xcb->focus_revert = 0;
             rofi_view_hide ();
             if ( ( current_window_manager & WM_DO_NOT_CHANGE_CURRENT_DESKTOP ) == 0 ) {
                 // Get the desktop of the client to switch to
```

It disables the reverting of input focus when you switch window.

**Comment by ortango** [comment]
thanks for looking at this so quickly. the window.c specific patch works, but in the case of script.c something else would need to be done (when that custom modi's operation is to focus windows).

the first fix @`rofi_xcb_revert_input_focus()` doesn't seem to fix the issue on my setup (neither with window modi or custom). probably related to your comment about updating focus_revert (i can debug or link a backtrace if you want).

this issue is way over my head though, i wish i could be of more help.

**Comment by tdehaeze** [comment]
@DaveDavenport I as understand, to test the patch I should clone the repo, manually change lines you mentioned and then build rofi. Am I correct?

**Comment by DaveDavenport** [comment]
basically.. (you can use 'patch' to apply the patch, but given the minor changes, might be as quick doing it by hand.)

Thx.

**Comment by ortango** [comment]
the 750dbad72963b855ba927047a38b21de30d7bf64 solution works fine for my purposes. Thanks Dave. should i close this report?

**Comment by DaveDavenport** [comment]
not really, it is still broken. I just got so frustrated with it. :smile:

**Comment by DaveDavenport** [comment]
stealing focus is now an extra option..  -steal-focus.  is disabled by default.
