### ISSUE TITLE
Key binding in Spectrwm, Rofi does not see whats in ~/bin 

### ISSUE THREAD

**Issue by danrobi11** [davatorium/rofi#1280]
Hello. 
New Edit: I explain better.
I cant figure why rofi can execute the apps in my ~/bin when I run ```rofi -show window -sync``` from the terminal but not when I hit my Spectrwm keybind. Its the exact same command but rofi cant launch the apps in ~/bin with the keybind. Why ? How can I fix this ? Thanks! 

Rofi Version: 1.6.1
OS: MX 19.3 (patito feo) x86_64 based Debian GNU/Linux 10 (buster)
SysV init version: 2.93
Kernel: 4.19.0-9-amd64
Xorg v1:7.7+19
WM: Spectrwm

**Comment by DaveDavenport** [comment]
This is an environment issue, not a rofi issue. 
Make sure the PATH is set correctly (including ~/bin) that rofi sees when launched.

**Comment by danrobi11** [comment]
@DaveDavenport 

PATH is set. And it works when launching rofi from the terminal but not with keybind. Its the exact same command. Thats why I wonder whats going on.

```
 ->echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/home/danrobi/bin
```

**Comment by DaveDavenport** [comment]
This is something commonly going wrong, the $PATH rofi sees when launched from keybind is most likely not correct.
Rofi inherits the environment from where it launched from, if it works from terminal and not from keybind.
then the environment for the last is different.
