### ISSUE TITLE
[BUG] missing issue in windows switcher (x11 i3 ubuntu )

### ISSUE THREAD

**Issue by fvigotti** [davatorium/rofi#1282]
## Version
Version: 1.5.0

ubuntu 18.04, x11 , i3wm 

rofi windows switcher miss some windows,

I didn't have found a pattern in the missing windows yet... nor a reproducible path .. right now it show only 3 of 15 intellij instances,
I've tried with `rofi -show window` and even  `rofi -show windowcd` on specific desktop ( wich seems even more bogus )
showed windows

the problem seems more related to entire desktops windows missing ( while filing this bug report intellij instances on one of my desktops started again to be listed again but others still missing ) , executing the `windowcd` on one specific desktop show 0 windows available to switch.. even if it has more than 20 windows (let me add that I have available ram and disk  )

I've already tried to restart i3wm multiple times, nothing changes

I'm here to ask you for some command that I can execute to debug further, so I can be more exhaustive in this report , ie :

- there is a way to print a debug-list of all windows/desktop from rofi  ( which those are then used and filtered in the showed  application ( to check if it's a parsing issue or a sourcing issue ) )?
- which backend command rofi executes to gather data for winows switching ? ( this will help to exclude the backend (i3?) as the source of the issue )

if you have more command to execute to help me to find the exact issue I'll be here..

Thank you ,
Francesco

**Comment by DaveDavenport** [comment]
please update to latest rofi. 1.5.0 is no longer supported.

**Comment by DaveDavenport** [comment]
possible #1047

**Comment by fvigotti** [comment]
I've updated the issue because meanwhile I've found that the issue is more specific to specific desktops than specific windows, I'll try to update rofi and see if that problem goes away, having a troubleshooting command btw would help a lot in the application

**Comment by DaveDavenport** [comment]
` having a troubleshooting command btw would help a lot in the application`

Can you explain?  what does a 'troubleshooting command'  do?

**Comment by fvigotti** [comment]
I mean something that allow to check boundaries of the issue , I don't have inspected the internal of the application  but in this case as en example, I suspect that rofi have  (1) multiple way to gather information about available applications / desktops ? than I think it will do some (2) internal processing to find icons, when you write an input (3) it also execute a search on that data and then (4) display output,

I think that would be useful in troubleshooting ( anyway depending on how rofi is implemented ) to output ( i mean using a cli output or a log/stderr enabled with some params/envs) each input/output of those steps (and also maybe to provide -3- from cli )

**Comment by DaveDavenport** [comment]
Still not sure how you expect that to work, it sounds very elaborate to add a complete inspect interface to every internal bit.
There is (see wiki) an option to get a lot of insight into what it does by enabling debug output on certain domains.

**Comment by fvigotti** [comment]
for (3) ( and other inputs ) a cli param should be needed, to enable inspection/debug I see that the wiki talk about timings debug ( which require to recompile the application  ) and I have it installed using apt not the source.. ( I usually keep lts version for desktop applications, everything else run on snap/docker)  , but also why not using log levels (to debug other steps I've mentioned  )  ?

**Comment by DaveDavenport** [comment]
There is no need to recompile to get the debug output. But you are running a 3 year old version, it is not possible to support that. 
The guidelines also indicate this!

**Comment by fvigotti** [comment]
Yeah you are right sorry my bad I've ridden first line with CFLAGS and thought this was a pre-requisite to everything else further in the page ..,

 @DaveDavenport  don't worry I don't expect support for my current version ( I know it's old but in my ubuntu 18.04 lts  which is still "supported" and probably the more popular version out there now it's the latest available ) I'll probably end up with recompiling and installing a recent version because **I love rofi** thanks for your nice work :)

**Comment by DaveDavenport** [comment]
downside of opensource,  there is not a large support network.  Its time consuming enough maintaining rofi on my own, let alone support older version.

**Comment by fvigotti** [comment]
@DaveDavenport , here my solution, 3 minute , some copy paste , hugely compatible, and problem fixed (for me ) 
I hope  this can help others.. I've created a discussion but i'll add here to this dead issue  in case someone is looking for the same solution in future ,
https://github.com/davatorium/rofi/discussions/1293
