### ISSUE TITLE
[REQUEST] Dynamic Multi-line output 

### ISSUE THREAD

**Issue by syamsaran12345** [davatorium/rofi#1283]
Please consider to add dynamic multi-line output capability
using newline or text attribute

Use case:

for example 
Here are commands in file separated by some FIELD like ^A or @ etc
which may have newlines also, and it can be supplied to "rofi -dmenu -sep @"
and then will be launched from there directly (may be in terminal or directly.)
  
Here user have to freedom to have any set of commands than some fixed set.
  

As described in

In https://github.com/davatorium/rofi/issues/243#issuecomment-145593281

As noted I had tried

  echo -e 'aaa|bbb\nccc\nddd (3 lines)|xxxx\nyyyy\nzzzz (3 lines) ' | rofi -dmenu -sep \| 

or 

  echo -e 'aaa|bbb\nccc\nddd (2 lines)|xxxx\nyyyy\nzzzz (3 lines) ' | rofi -dmenu -sep \| -eh 2

Here only last entry is shown as multi-line not all, when that last entry selected 
it were changed to single in output.

**Comment by DaveDavenport** [comment]
#1076
