### ISSUE TITLE
[BUG][REQUEST] Add action to be able to switch directly into of the of configured modes

### ISSUE THREAD

**Issue by jose1711** [davatorium/rofi#1286]
## Before creating a feature request

- [x] I checked the *next* branch to see if the feature has already been
  implemented

- [x] I searched existing reports to see if it is already requested.

## What is the user problem or growth opportunity you want to see solved?

Currently I have 4 modes enabled - don't like combi because of performance penalty. The idea is to activate a given mode directly using a shortcut. There is a related discussion on reddit: https://www.reddit.com/r/qtools/comments/m2dfvn/can_rofi_jump_to_a_desired_switch_using_a_keybard/

## How do you know that this problem exists today? Why is this important?

This is not currently implemented, only workarounds exists.

## Who will benefit from it?

Users with >3 modes looking for a way how to switch to a specified mode without a need to cycle through them.

## Version

Output of `rofi -v`

```
Version: 1.6.1
```

## Configuration

Irrelevant

**Comment by DaveDavenport** [comment]
This used to be possible and still should be.
I will check why it broke.

**Comment by DaveDavenport** [comment]
similar to #1226

**Comment by DaveDavenport** [comment]
Can you give some information on this one:
```
Currently I have 4 modes enabled - don't like combi because of performance penalty. 
```
Given how it is implemented I find this very surprising, it is a pass-through mode and does not do much except store some (numeric) offsets. I would find it very interesting  if this has a noticeable impact.

**Comment by jose1711** [comment]
I think what I meant was worse performance with `combi` because it needs to scan all my `.desktop` files so startup is slower.

**Comment by DaveDavenport** [comment]
You can decide not to include drun in combi mode.  if you have drun in your modi, it will scan it anyway.
Thanks for the clarification.
