### ISSUE TITLE
[BUG] rofi crashes when moving past end of -filter string when listview is hidden

### ISSUE THREAD

**Issue by etosan** [davatorium/rofi#1297]
## Version

Output of `rofi -v`:
`Version: 1.6.1`

## Configuration

Default configuration, dump is not needed, invocation and steps posted below is enough to reproduce.

## Launch Command

`rofi -dmenu -theme-str "listview { enabled: false; }" -filter move-past-end-of-this-text`

## Steps to reproduce

- Use launch command from section above
- Ensure cursor is at last character, then press key to move it further right
- Cursor should stay in place, but instead rofi crashes.

## What behaviour you see

- rofi crashes momentarily when editing cursor reaches end of the `-filter` string with (disregard shell prefix): `zsh: floating point exception`

## What behaviour you expect to see

- rofi should not crash

**Additional details:**
- N/A

**Comment by DaveDavenport** [comment]
Can confirm the bug (I am pretty sure I know what is wrong).
What is the usecase for not showing the listview?

**Comment by etosan** [comment]
You probably won't like it, but my next iteration of rofi as "inputbox" hack :(. 

This is an invocation, where the asked input is prefilled with "current value" by means of `-filter`. One then uses rofi as line editor. Accept then sends the value back to asking script.

I understand you don't approve such hackarounds, but it otherwise works really really well, and I am pretty sure that rofi should still not crash even in this invocation.

I hope the code side of things is not overly complex to fix, or is it?

**Comment by etosan** [comment]
What I should I add to the issue, I would like to get rid of incomplete report label?
