### ISSUE TITLE
[BUG] Failed to get Keymap for current keyboard device

### ISSUE THREAD

**Issue by tau-rho** [davatorium/rofi#1299]
After update of `libxkbcommon` and `libxkbcommon-X11` (1.1.0-2 -> 1.2.0-1) rofi does not seem to work.

## Version

v1.6.1 (Arch community repo)

## Configuration

Output of `rofi -help`:

```
(process:9416): X11Helper-WARNING **: 08:59:15.737: Failed to get Keymap for current keyboard device.

(process:9416): Rofi-WARNING **: 08:59:15.738: Connection has error
```

## Launch Command

All rofi calls.

`rofi` or `rofi -show calc -modi calc -no-show-match -no-sort -width 10 -terse -no-history -lines 0`

## Steps to reproduce

- permanent

## What behaviour you see

`rofi` fails with the error output from above

## What behaviour you expect to see

Spawning any `rofi` window

**Comment by jsmnbom** [comment]
For the record, I am unable to reproduce this issue also using arch.
``` bash
$ rofi -version
Version: 1.6.1
$ pacman -Q libxkbcommon libxkbcommon-x11
libxkbcommon 1.2.0-1
libxkbcommon-x11 1.2.0-1
```
So there might be something different going on, that just the update 1.1.0-2 -> 1.2.0-1

**Comment by tau-rho** [comment]
On login lightdm performs the following command: `setxkbmap -option numpad:mac` (the option call is sourced from a file `~/.Xkbmap`).

When I remove this file and reboot, rofi works fine. When I then manually set this xkb option, rofi fails again.

If this might be of help, the output of `setxkbmap -query`:
```
rules:      evdev
model:      pc105
layout:     de
variant:    nodeadkeys
options:    numpad:mac,terminate:ctrl_alt_bksp
```

**Comment by jsmnbom** [comment]
Looks like a known bug that has now been fixed: https://bugs.archlinux.org/task/70293

**Comment by DaveDavenport** [comment]
love bugs that resolve themself.

**Comment by tau-rho** [comment]
Confirmed.
Update of `libxkbcommon` and `libxkbcommon-X11` (1.2.0-1 -> 1.2.0-2) fixed the problem.
