### ISSUE TITLE
[REQUEST] Allow scripts to signal that they need keyboard

### ISSUE THREAD

**Issue by nyarly** [davatorium/rofi#1305]
## Before creating a feature request

- [x] I checked the *next* branch to see if the feature has already been
  implemented

- [x] I searched existing reports to see if it is already requested.

## What is the user problem or growth opportunity you want to see solved?

For scripting, I'd like to be able to interleave Rofi with calls to outside applications. As a for instance, being able to edit files and then return to the Rofi mode.

## How do you know that this problem exists today? Why is this important?

There's a domain of rofi-script modi that are impossible without this feature. The closest one can come is to exit rofi, and leave a second application running, so that the user needs to re-launch at every cycle.

## Who will benefit from it?

Script writers and the hypothetical consumers of those scripts.

## Version

Output of `rofi -v`
1.6.0

## Configuration

Output of `rofi -help` (in a [gist](https://gist.github.com/), please paste the *full* output)

https://gist.github.com/3ee20fda93822888846532ff0badef07

**Requesting a feature is no guarantee it will be added.**
:+1:

**Comment by DaveDavenport** [comment]
I thought about this one,  I won't add this as it won't work well in the design, chaning the design to make this work well is not something I intend to do or have time for.

If you want interleaving, make  script that calls rofi via dmenu, then its easy to call rofi -> process result-> call other app -> call rofi.
