### ISSUE TITLE
[BUG] Rofi can't lauch Joplin 

### ISSUE THREAD

**Issue by enrico223** [davatorium/rofi#1306]
## Version

Output of `rofi -v`
`Version: 1.5.4`

## Configuration

Output of `rofi -help`
https://gist.github.com/enrico223/dac68e13be1f07352c9a32c842d91668/91d8e69640598f97a1071f34f3da5cd3742a4e74

## Launch Command

`The commandline used to launch **rofi**`
`rofi -show run`

## Steps to reproduce
download joplin from snap 
try to run joplin from rofi 

## What behaviour you see

- it doesn't open joplin 

## What behaviour you expect to see

- joplin opened

**Additional details:*
output of `neofetch`
`OS: Ubuntu 20.04.2 LTS 
Host: HP Spectre x360 Convertible 13-
Kernel: 5.8.0-50-generic 
Packages: 2182 (dpkg), 12 (snap) 
Shell: bash 5.0.17 
Resolution: 1920x1080 
DE: Plasma 
WM: i3 `

## Edit 
When I use `rofi -show drun` and I select Joplin, it starts the program as it should.

**Comment by DaveDavenport** [comment]
1.) Please update to a more recent version of rofi. Your version is 22 months old and 2 new versions have been released.
2.) Post the relevant desktop file.
3.) Post any output rofi prints on the commandline when failing to launch joplin.

**Comment by enrico223** [comment]
I'm sorry, how should I update rofi? I tried `rofi -upgrade-config` but it doesn't work. Could you link the correct section of the guidelines?

**Comment by DaveDavenport** [comment]
.. upgrade config does not upgrade rofi.  It upgrades from old configuration format to new one. (as the manpage explains).

The guideline does not tell you how to update, it does ask you to try with latest version:
https://github.com/davatorium/rofi/blob/next/.github/CONTRIBUTING.md#creating-a-bug-report

**Comment by DaveDavenport** [comment]
Without providing the requested information, I cannot help.
