### ISSUE TITLE
[BUG] dependency to locale

### ISSUE THREAD

**Issue by mmahmoudian** [davatorium/rofi#1307]
## Explanation

As far as I can think of, there is no reason that Rofi should be dependent on the locale. In my case, all my locale is `"en_US.UTF-8"` except for those that are awful choices for me:
- `LC_TIME` (US format is not ISO)
- `LC_MONETARY` (I live in Euro Zone)
- `LC_MEASUREMENT` (Metric system rocks)

## Version

Output of `rofi -v`
> ```
> (process:970020): Rofi-WARNING **: 13:28:48.118: Failed to set locale.
> ```

But from my package manager: Rofi version 1.6.1-1

## Configuration

Output of `rofi -help` (in a [gist](https://gist.github.com/), please paste the *full* output)
Default config and only the following lines are uncommented:
```sh
cat .config/rofi/config.rasi | grep -o -P "^[^/\*]*"
```
> ```
> configuration {
> 	modi: "window,drun,ssh,combi";
> 	font: "hack 10";
> 	show-icons: true;
> 	icon-theme: "Papirus";
> 	combi-modi: "window,drun,ssh";
> 	theme: "gruvbox-dark-soft.rasi";
> }
> ```

## Launch Command

`rofi`, `rofi --help`, `rofi --version`, ...

## Steps to reproduce

1. set `locale` to match the following:
> ```
> locale: Cannot set LC_ALL to default locale: No such file or directory
> LANG=en_US.UTF-8
> LC_CTYPE="en_US.UTF-8"
> LC_NUMERIC=en_US.UTF-8
> LC_TIME=en_FI.UTF-8
> LC_COLLATE="en_US.UTF-8"
> LC_MONETARY=en_FI.UTF-8
> LC_MESSAGES="en_US.UTF-8"
> LC_PAPER=en_US.UTF-8
> LC_NAME=en_US.UTF-8
> LC_ADDRESS=en_US.UTF-8
> LC_TELEPHONE=en_US.UTF-8
> LC_MEASUREMENT=en_FI.UTF-8
> LC_IDENTIFICATION=en_US.UTF-8
> LC_ALL=
> ```

2. run `rofi --help` and you will get

## What behaviour you see

> ```
> (process:970020): Rofi-WARNING **: 13:28:48.118: Failed to set locale.
> ```

## What behaviour you expect to see

Rofi works normal regardless of what locale is set by the user.

**Additional details:**
This is similar to #1109 but because **there was absolutely no way** to comment in that post I had no choice but to open this. the #1109 was closed because:

> This is not an issue with rofi, but with your locale setup. 

But I think that rofi should not care about all locale. similar to dmenu and other applications that behave nicely. At the end of the day, locale is meant to be configured and changed based on the users' needs.

**Comment by DaveDavenport** [comment]
A quick google suggest that `en_FI` is not a valid locale to begin with.

I don't understand this bugreport, the underlying system is mis-configured, yet you want the tool to still work 'correctly'.  How would you expect that to work?

**Comment by mmahmoudian** [comment]
> underlying system is mis-configured

I would be thankful if you tell me which part is mis-configured?


> should rofi just ignore localization

No, it should only care about those part of the locale that do matter to rofi. For instance, none of the parts that I have changed have anything to do with what rofi is supposed to do.

> The fact dmenu works sais 0 about rofi needing it or not?

I didn't say it does, all I meant was that others do work on the same setup and I would also like use rofi on the same setup as well.

I used KDE settings to set the locale and I didn't come up with the `en_FI.UTF-8` myself:
![image](https://user-images.githubusercontent.com/390889/116994504-783fd380-ace1-11eb-9fdf-7ec62c15b6dd.png)

**Comment by mmahmoudian** [comment]
I also found this (first result of [my google search](https://www.google.com/search?q=en_fi)):
https://www.localeplanet.com/icu/en-FI/index.html

to me it looks like it do exist 🤔

**Comment by DaveDavenport** [comment]
On my system, and searching on google for this, I find that en_FI is not a valid locale. I wonder why KDE sets it, or why your system has it (and then why it fails).
* https://www.reddit.com/r/Fedora/comments/6w7qky/failed_to_set_locale_defaulting_to_c_every_time_i/
* https://github.com/lutris/lutris/issues/2341

Also looking in locales-all package on my ubuntu machine it does not exist.
If it did and was setup, there should not be an error.


Rofi does a general 'setlocal(LC_ALLm,"")'  this is recommended for applications that use glib.


There are/where plugins for rofi that implemented a calculator and supported currencies.
To avoid problems in the future I did do the recommendation.

**Comment by DaveDavenport** [comment]
https://developer.gnome.org/glib/stable/glib-running.html

**Comment by DaveDavenport** [comment]
glibc: https://sourceware.org/git/?p=glibc.git;a=tree;f=localedata;h=8d0f0ecb60af11205034ee1566211906bec60d66;hb=HEAD

**Comment by DaveDavenport** [comment]
That it exists in a perl library or an online javascript library is not relevant here. Please file a bug against glibc to get it added there.

**Comment by mmahmoudian** [comment]
> perl library or an online javascript resource is not relevant here.

I know that rofi is written in C and Perl is not relevant, I was just making a point that it does exist.

I'm not a C developer but do you think that rofi can handle the issue altogether by considering the parent locale (en)? Kind of as a fall-back approach.


Thanks for the links. [A comment](https://github.com/lutris/lutris/issues/2341#issuecomment-541521295) in https://github.com/lutris/lutris/issues/2341 got me thinking that i should at least report this on Manjaro forum and link it to here and that that lutris issue comment. 

I close this as I assume your answer to the above question is "no".
Thanks for your patience.

**Comment by DaveDavenport** [comment]
No problem, I could do a fallback to C, but I prefer not to hide problems and 'limp' on, that has it downsides too.

**Comment by mmahmoudian** [comment]
I agree that it should not be pushed under the rug. How about a warning, then fallback?

**Comment by DaveDavenport** [comment]
People ignore those and still complain that other thing don't work. Debugging this then often is more difficult.  By failing I force them to fix that first.

**Comment by mmahmoudian** [comment]
Just for the reference, i created a support post on Manjaro's forum in case anyone else wants to add to the discussion or follow it:
https://forum.manjaro.org/t/invalid-locale-settings-using-kde-settings-format/65161?u=mmahmoudian
