### ISSUE TITLE
[BUG] Running a command with parameters ignores the parameter

### ISSUE THREAD

**Issue by dragonchaser** [davatorium/rofi#1311]
## Version

1.6.1

## Configuration

https://gist.github.com/dragonchaser/6f82c29885a588b99a8a6fb239812e95

## Launch Command

```terminal
$> rofi -theme arthur -show run 
```
## Steps to reproduce

- run `rofi -theme arthur -show run`
- type in `thunderbird --ProfileMangager`
- hit enter

## What behaviour you see

- if there is a thunderbird session running it will do nothing
- if there is no thunderbird session running it will start one, but will not start the Profile Manager

## What behaviour you expect to see

- independent if a thunderbird session is running or not I want to see the Profile Manager

**Comment by DaveDavenport** [comment]
This is intended behavior. 
Please read the manpage:

              • Ctrl-Enter: Use entered text as a command (in ssh/run modi)

This will launch the entered text, it will be added to the history (if enabled), so next time it is in list.
