### ISSUE TITLE
[BUG]  Suddenly Cannot use any xfce keyboard shortcuts with rofi. 

### ISSUE THREAD

**Issue by cocoonkid** [davatorium/rofi#1318]
## Version

Output of `rofi -v`
Version: 1.6.1

## Configuration
Monitor layout:
              ID: 0
            name: HDMI-A-0
        position: 3840,0
            size: 1440,2560
            size: 621mm,341mm  dpi: 59,191

              ID: 1
            name: DisplayPort-2
        position: 0,0
            size: 3840,1600
            size: 874mm,366mm  dpi: 112,111

Detected modi:
        * +window
        * windowcd
        * +run
        * +ssh
        * +drun
        * +combi
        * +keys
        * +file-browser
        * blocks

Compile time options:
	* window  enabled
	* drun    enabled
	* gcov    disabled
	* asan    disabled

For more information see: man rofi
                 Version: 1.6.1
              Bugreports: https://github.com/davatorium/rofi/
                 Support: https://reddit.com/r/qtools/
                          #rofi @ freenode.net
      Configuration file: /home/cocoonkid/.config/rofi/config.rasi
Output of `rofi -help` (in a [gist](https://gist.github.com/), please paste the *full* output)

## Launch Command

`The commandline used to launch **rofi**`

rofi -show window

## Steps to reproduce

Hard to reproduce

## What behaviour you see

- ...my super + w shortcut does not work,

## What behaviour you expect to see

- .rofi it works like it did for the last year

**Additional details:**
When changing the shortcut to other programs they all work.

rofi  works when launched from the terminal

But no xfce shortcuts work for rofi.

**Comment by DaveDavenport** [comment]
I don't think this is a rofi bug? rofi is not responsible for launching on a keybinding, this is handled by xfce.

**Comment by cocoonkid** [comment]
That's what I thought the last 3 days. But I confirmed it. The problem only exists with rofi...any other application is working with these keybindings. 

will read the guidelines to see what I have missesd. My apology.

**Comment by DaveDavenport** [comment]
No problem, but I don't think I can help, as I don't know xfce at all and rofi works when launched from a terminal (so rofi config is not broken).   Beside that there is *no* information to go on to help. 

9 out of 10 times something like this happens it is when something is wrong in the environment where rofi is launched from. But again, that is guess work.

**Comment by DaveDavenport** [comment]
Let me know if you have log file,

**Comment by cocoonkid** [comment]
Thanks for your help, No log file unfortunately.

I will report when I ever fix this.
