### ISSUE TITLE
[BUG] Unmatched single quote error in file-browser

### ISSUE THREAD

**Issue by dimitris-triantafyllidis** [davatorium/rofi#1319]
I encountered this issue while trying to open a pdf file whose name contains a single ' quote.

## Version

`Version: 1.6.1`

## Configuration

https://gist.github.com/dimitris-triantafyllidis/dedc21d0db354c6a4b7c5408554fd4c5

## Launch Command

`rofi -show file-browser`

## Steps to reproduce

- Step 1
`touch f\'ile`
- Step 2
`rofi -show file-browser`
- Step 3
Select `f'ile` to open it

## What behaviour you see

Rofi displays a pop-up with the message:
`Failed to parse: '{cmd}'`
`Error: 'Text ended before matching quote was found for '. (The text was "xdg-open '/home/dtr/f'ile'")'`

## What behaviour you expect to see

Well, file opens :P.

**Additional details:**
My rofi configuration is in .Xresources and the only relevant lines besides the colors are these:
```
rofi.modi:           drun,windowcd,window,file-browser
rofi.font:           Cantarell 12
rofi.width:          800
rofi.bw:             2
rofi.hide-scrollbar: true
```
Additionally, `xdg-open "f'ile"` and `xdg-open f\'ile` both work as expected.

**Comment by DaveDavenport** [comment]
This has been fixed:
https://github.com/davatorium/rofi/commit/04c006a4a23dd71a3c4af8df63329ab436411740
