### ISSUE TITLE
[REQUEST] Launcher: Add ability to type Math Equations In-Inline (and previews w/answers as-you-type)

### ISSUE THREAD

**Issue by eduncan911** [davatorium/rofi#1326]
- [x] I checked the *next* branch to see if the feature has already been
  implemented
- [X] I searched existing reports to see if it is already requested.

## What is the user problem or growth opportunity you want to see solved?

Quickly solve math problems from the Launcher, just like macOS' Spotlight.

![image](https://user-images.githubusercontent.com/104980/120907102-dfc4a800-c62c-11eb-8c8c-ddedcff35729.png)

The macOS Spotlight is their version of the Launcher/d-menu quick launch.  Normally, you'd type an application name there.  But, you can also type Math problems and have the dropdown show the answer in realtime.  macOS has had this feature for over a decade and it's pretty much muscle memory.

So for the launcher (on RegolithOS, it's CMD-SPACE), instead of typing an Application name, you type a Math formula or math problem to solve.  As you type, the answer is calculated and shown to you in real time (like where the application icons/names would normally be).  There is no "press enter/tab", the answer is always shown right there in the preview - easy to copy to clipboard.

It is all keyed off of just number-input, instead of letters.   That's how the Spotlight in macOS knows to switch to calculating the answer.

I looked for a long time and can't believe there's never been a Request for this!  lol

## How do you know that this problem exists today? Why is this important?

Because when I introduced Linux (Regolith) to my kids, coming from macOS, this is the number 1 thing they complain to me about.

Same goes with 2 friends that I suggested to try linux, who also came from macOS.  They were heavy Tile-Window users, so I had them try Regolith (which is an i3wm+gnome+rofi build).  They both complained that they can't do math with the launcher.

This is not to mention, all the dozens of times I've been trying to do it for years since switching to Rofi.  

## Who will benefit from it?

Anyone coming from macOS that has this memory muscle.

## Version

```
$ rofi -v
Version: 1.5.4
```

## Configuration

Not needed for this report.  :)

**Comment by eduncan911** [comment]
Because there's no configuration files uploaded, for a "feature request"?

**Comment by DaveDavenport** [comment]
There are multiple plugins for rofi providing this, f.e. https://github.com/svenstaro/rofi-calc
