### ISSUE TITLE
[REQUEST] Please publish Rofi on FlatHub

### ISSUE THREAD

**Issue by raj47i** [davatorium/rofi#1329]
- [x] I checked the *next* branch to see if the feature has already been
  implemented

- [x] I searched existing reports to see if it is already requested.

## What is the user problem or growth opportunity you want to see solved?

Many Linux Distributions contain rofi in their Repos. However, the version included is older.

## How do you know that this problem exists today? Why is this important?
For eg, Ubuntu-based distributions contain v1.5x. 
My primary machine, I am using Arch (+rofi), And I was trying to clone the configs for the same to ZorinOS(Ubuntu based) and it had v1,5x available in the repos.

Submitting rofi to Flathub will enable users to directly and easily install Rofi from flathub

## Version

Once the manifest is submitted, Flathub could use continuous integration to automatically pull/deploy the latest release from GitHub repository

## Configuration

NA

**Comment by DaveDavenport** [comment]
I have no time nor intention to support/maintain any packages (directly or indirectly).
(beside my personal opinion about snap/flatpack/etc.)
