### ISSUE TITLE
[BUG] rofi doesn't works with sxhkd

### ISSUE THREAD

**Issue by RafaelKudryashov** [davatorium/rofi#1330]
## Version

Version 1.6.1

## Configuration

Output of `rofi -help` (in a [gist](https://gist.github.com/), please paste the *full* output)
https://gist.github.com/RafaelKudryashov/f66d3c4c6f2a52cf76b9d1af39e331b4

## Launch Command

into sxhkd

`shift + @scape
rofi -show drun` or

`shift + r
	sh ~/.config/rofi/bin/launcher
`

## Steps to reproduce

- Install  rofi with sudo pacman -S rofi
- Define on sxhkd any bind for run rofi
- Tries execute the bind and nothing happens

## What behaviour you see

Nothing happens.
The bind doesn't works. Running the bind command into terminal, will works.

I tested these commands into terminal and works

`sh ~/.config/rofi/bin/launcher` and
`rofi -show drun`

## What behaviour you expect to see

The rofi window.

**Additional details:**
https://github.com/RafaelKudryashov/dotfiles

**Please do not submit reports related to wayland, see
[here](https://github.com/DaveDavenport/rofi/wiki/Wayland) for more
information.**

**Comment by DaveDavenport** [comment]
Can you provide more information?   Does rofi report an error to stdout/stderr when launched via sxhkd.

(I don't use it myself, but people use rofi with sxhkd).

**Comment by DaveDavenport** [comment]
I installed the sxhkd and it works fine for me (the shift + r worked).
