### ISSUE TITLE
[REQUEST] Skip or remove the current window

### ISSUE THREAD

**Issue by matheusfillipe** [davatorium/rofi#1336]
## Before creating a feature request

- [x] I checked the *next* branch to see if the feature has already been
  implemented

- [x] I searched existing reports to see if it is already requested.

Maybe I didn't because of the way I am phrasing it though or the way I am approaching the problem. In that case my excuses.

## What is the user problem or growth opportunity you want to see solved?

 It bothers me that the current window (window with focus before rofi is launched) is displayed on the window switcher. Maybe it could be optionally excluded from the list with some config option. Rofi will avoid choosing and highlighting it but it could as well just not be displayed.

## How do you know that this problem exists today? Why is this important?

I want to reduce the number of keystrokes and the screen pollution on the window and windowcd mode.

## Who will benefit from it?

Probably any window switcher user. Who wants to switch to the same window? One item less in the list makes everything better. This is not so useful if you have a custom script to run on the current window though so it should be an option or have blacklists not to exclude from the window.

## Version

```
$ rofi -v
Version: 1.6.1
```
## Configuration
https://gist.github.com/matheusfillipe/629296c5bff32839dff3d470fb007e92

**Additional details:**
- config: https://gist.github.com/matheusfillipe/7000e61a473dd6fcfbb270de670a80d3

**Comment by DaveDavenport** [comment]
Depending on your window manager the first is indeed the current window, you can 'skip' this by launching:
```rofi -show windowcd -selected-row 1```
(this is also in some other issue)

I've never had the 'hide' request before and it feels like a very niche option.

**Comment by matheusfillipe** [comment]
On qtile it is random. I've seen the current windows on all positions of the list. Well you can claim it is the the WM's duty on doing whatever it is doing wrong to display that on the incorrect position and i think you would have a good point.

Anyway I don't get what is the utility of having an extra item on the list that mostly does nothing besides being an "invalid" option that will only, at worst, require you more keystrokes to get you where you want but no utility at all besides if you want to have a complete view of what windows you have.

This should be at least configurable and maybe even a default, I don't think it is niche at all.
