### ISSUE TITLE
Rofi not showing programs when i start it with i3

### ISSUE THREAD

**Issue by Nils75owo** [davatorium/rofi#1337]
## version
Version: 1.5.4

## Configuration
standart

## Launch Command
rofi -show run

`The commandline used to launch **rofi**`
the terminal:        konsole
the i3 command: bindsym $mod+d exec rofi -show run

## What behaviour you see
(i3) when i type in the name of the programs it doesnt show it and if i press enter anyways i get the file not found error
(konsole) when i type in the name of the programs it shows them and if i press enter its starts them normally

## What behaviour you expect to see
 i want the version launched with i3 work like i would have started it with konsole

**Comment by DaveDavenport** [comment]
Your environment ($PATH) is not correct when launching from i3.
