### ISSUE TITLE
[BUG] Rofi not showing programs when launched with i3

### ISSUE THREAD

**Issue by Nils75owo** [davatorium/rofi#1338]
## Version
Version: 1.5.4

## Configuration
[output](https://gist.github.com/Nils75owo/370cce7cf8a465d4d8ae36b2cb8ebd58)

## Launch Command
rofi -show run

The commandline used to launch rofi
the terminal: konsole
the i3 command: bindsym $mod+d exec rofi -show run

## Steps to reproduce
i dont know i just installed (and reinstalled) rofi and i had this problem

## What behaviour you see
(i3) when i type in the name of the programs it doesnt show it and if i press enter anyways i get the file not found error
(konsole) when i type in the name of the programs it shows them and if i press enter its starts them normally

## What behaviour you expect to see
i want the version launched with i3 work like i would have started it with konsole

Launched with konsole (rofi -show run)
![image](https://user-images.githubusercontent.com/81255505/122264405-cac30100-ced7-11eb-95b2-14956119c84a.png)

Launched with i3 (bindsym $mod+d exec rofi -show run)
![image](https://user-images.githubusercontent.com/81255505/122264565-f7771880-ced7-11eb-8615-f9cc42f0a089.png)

**Comment by DaveDavenport** [comment]
This is not a rofi issue, but a setup issue. Rofi *cannot* fix this for you.
The environment when launched from i3 does not contain the correct $PATH.

You can either:
1. Make sure that i3 is launched with the correct environment.
2. More hackish: Fix the (with a small wrapper)  environment when launching rofi.

**Comment by DaveDavenport** [comment]
Duplicate of: #1337
