### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Mangeshrex** [davatorium/rofi#1341]
This is my rofi config and whenever i try to run rofi i get a segfault error. And this same config works very very good on my other arch linux which is not dual boot. This error is on void linux. what can i do to fix this?

```
* {
  black:      #000000;
  red:        #eb6e67;
  green:      #95ee8f;
  yellow:     #f8c456;
  blue:       #6eaafb;
  mangenta:   #d886f3;
  cyan:       #6cdcf7;
  emphasis:   #50536b;
  text:       #dfdfdf;
  text-alt:   #b2b2b2;
  fg:         #abb2bf;
  bg:         #282c34;

  spacing: 0;
  background-color: transparent;

  font: "JetBrains Mono Nerd Font 12";
  text-color: @text;
}

window {
  transparency: "real";
  fullscreen: true;
  background-color: #282c34dd;
}

mainbox {
  padding: 30% 30%;
}

inputbar {
  margin: 0px 0px 20px 0px;
  children: [prompt, textbox-prompt-colon, entry, case-indicator];
}

prompt {
    text-color: @blue;
}

textbox-prompt-colon {
  expand: false;
  str: ":";
  text-color: @text-alt;
}

entry {
  margin: 0px 10px;
}

listview {
  spacing: 5px;
  dynamic: true;
  scrollbar: true;
}

element {
  padding: 5px;
  text-color: @text-alt;
  highlight: bold #95ee8f; /* green */
  border-radius: 20px;
}

element selected {
  background-color: @emphasis;
  text-color: @text;
}

element urgent, element selected urgent {
  text-color: @red;
}

element active, element selected active {
  text-color: @purple;
}

message {
  padding: 5px;
  border-radius: 3px;
  background-color: @emphasis;
  border: 1px;
  border-color: @cyan;
}

button selected {
  padding: 5px;
  border-radius: 3px;
  background-color: @emphasis;
}```

**Comment by DaveDavenport** [comment]
Not sure why bot reopened, this is very incomplete.

**Comment by Mangeshrex** [comment]
i have provided all the info what should i send more?

**Comment by Mangeshrex** [comment]
![Uploading sf.jpg…]()
see

**Comment by DaveDavenport** [comment]
This is the issue template: 
https://github.com/davatorium/rofi/blob/next/.github/ISSUE_TEMPLATE/bug_report.md
This normally shows when filling in a bug!

Currently I can't help, as I miss basic yet important information (like the version you are running).

**Comment by DaveDavenport** [comment]
> Uploading sf.jpg…
> see

Why are you posting a link to this issue?

**Comment by Mangeshrex** [comment]
i am having 1.6.1

**Comment by Mangeshrex** [comment]
> see

arghh this didnt get posted a min

**Comment by Mangeshrex** [comment]
am not able to upload the pic but it just says segmentation fault nothing else

**Comment by Mangeshrex** [comment]
ig i tagged it wrong

**Comment by Mangeshrex** [comment]
i dont have any bug but its just some issue

**Comment by DaveDavenport** [comment]
We ask for certain information not to annoy the user, but to be best able to help the user.
This being removed, ignored (repeatedly) is just counter productive. Even now large parts are missing (see above link).

I tried your theme and it runs fine in 1.6.1 for me.
Can you get a backtrace?  I have no how this works on void linux, (normally `coredumpctl  dump` works if you have debug symbols).
