### ISSUE TITLE
[REQUEST] Release 1.6.2

### ISSUE THREAD

**Issue by YHYJ** [davatorium/rofi#1342]
:exclamation:
First read the [guidelines](https://github.com/DaveDavenport/rofi/blob/next/.github/CONTRIBUTING.md)!
This is not optional for any report/question. People must be able to understand the full context of the report when reading it, at any time.
If you feel like you “just have a simple question”, please consider you’re wrong and still fill the full report.
Any report missing these informations will be labeled as “Incomplete Report - Please follow the guidelines” and may not be answered in a timely fashion.
:exclamation:

## Before creating a feature request

- [x] I checked the *next* branch to see if the feature has already been
  implemented

- [x] I searched existing reports to see if it is already requested.

## What is the user problem or growth opportunity you want to see solved?

#1226 has been fixed, but not released

## How do you know that this problem exists today? Why is this important?

The latest release is still 1.6.1, so rofi in Arch Linux will not be updated, i can only continue to use 1.6.0 and ignore the rofi upgrade

## Who will benefit from it?

all user?

## Version

unimportant

## Configuration

unimportant

**Additional details:**
- Include a link to your private config
- Include screenshots/casts of your issue

**Please do not submit reports related to wayland, see
[here](https://github.com/DaveDavenport/rofi/wiki/Wayland) for more
information.**

**Requesting a feature is no guarantee it will be added.**

**Comment by DaveDavenport** [comment]
It will arrive when it does.  No time nor planning yet, it all depends on the amount of available time I have to prepare a release.

Contributions to get help with a release are welcome.
