### ISSUE TITLE
[BUG] Programs with `--option` are executed only without options.

### ISSUE THREAD

**Issue by silvio** [davatorium/rofi#1345]
In the `run:` mode it is not possible to specify options of the respective program. But it works if you write the line to be executed into the cache first. As an example `pulseaudio --kill` which only executes the installed `pulseaudio`. The counter in cachefile for this entry is incremented.

If I add the above-mentioned example into the cache, I can select this entry and execute it.

## Version
Version: 1.6.1

## Configuration
https://gist.github.com/silvio/c884ff2b6faa7223f660b7f1ce359fd1

## Launch Command

`The commandline used to launch **rofi**`

## Steps to reproduce
- `/usr/bin/rofi -show run`
- type in: `pulseaudio --kill`

## What behaviour you see
- Only the selected program is executed, but without the program specific options.

## What behaviour you expect to see
- The program WITH the options is executed.

**Comment by DaveDavenport** [comment]
The entry box is a filter, not a run prompt. The described behavior is correct.

Try the `accept-custom` keybinding (see rofi -show keys) to launch the content of the entry box.

Editing the cache file by hand is not supported.

**Comment by DaveDavenport** [comment]
Related  #870, #852, #874
