### ISSUE TITLE
[REQUEST] Match markup when filtering

### ISSUE THREAD

**Issue by andys8** [davatorium/rofi#1346]
## Before creating a feature request

- [x] I checked the *next* branch to see if the feature has already been
  implemented

- [x] I searched existing reports to see if it is already requested.

## What is the user problem or growth opportunity you want to see solved?

With `1.6.0` a bugfix was fixed, that solved "don't match markup when filtering" . (#579,#1128). There were scripts that used that feature and relied on the option to hide filterable content. Most prominent example are some rofi emoji picker scripts. The scripts were able to hide searchable information, but only show the emoji related to them.

* https://github.com/andys8/dotfiles/blob/7d5ce6cc599db5559d7c9fa283d6451ffacb6274/bin/emoji
* https://github.com/wstam88/rofi-fontawesome

Alternatives could show the search terms instead.

## How do you know that this problem exists today? Why is this important?

Emoji script is not working anymore. It might be possible that there are alternative - maybe better ways - to achieve the same functionality. I didn't find options that could enable this, or an example in the repository, or a comment in the closed issues. But there might still be a solution already at hand, that I'm not aware of.

If not, an option to allow searching markup could be a nice addition.

I can also see if this is maybe not intended behavior. Then I'll need to find a replacement instead.

## Who will benefit from it?

People using a script that hides searchable information.

## Version

```
Version: 1.6.1
```

## Configuration

Output of `rofi -help` (in a [gist](https://gist.github.com/), please paste the *full* output)

https://gist.github.com/andys8/2993e62f49bc31a7c0228a40b3e3351b

**Additional details:**
- Include a link to your private config
- Include screenshots/casts of your issue

**Please do not submit reports related to wayland, see
[here](https://github.com/DaveDavenport/rofi/wiki/Wayland) for more
information.**

**Requesting a feature is no guarantee it will be added.**

**Comment by DaveDavenport** [comment]
Yes, see `rofi-script` manpage for 'invisible search term'.
