### ISSUE TITLE
[REQUEST] -display-mode for mode with script

### ISSUE THREAD

**Issue by elig0n** [davatorium/rofi#1350]
## Before creating a feature request

- [X] I checked the *next* branch to see if the feature has already been
  implemented

- [X] I searched existing reports to see if it is already requested.

## What is the user problem or growth opportunity you want to see solved?

Running a mode like "calc:qalc" I could not come up with a way to name that specific modi:script via `-display-calc:qalc`

## Version

Version: 1.6.1

**Comment by DaveDavenport** [comment]
duplicate of https://github.com/davatorium/rofi/issues/905
