### ISSUE TITLE
[BUG] autogen.sh and configure scripts missing in a freshly cloned repo

### ISSUE THREAD

**Issue by ptsl** [davatorium/rofi#1353]
I've just cloned the repository to my computer. As stated in `INSTALL.md`, the fist step should be to `./configure` the build. However, the `configure` script is missing, and an `autogen.sh` script is missing, too.

It is, of course, possible that I just overlooked something, but if other steps are necessary before running the `./configure`, I think the `INSTALL.md` file should be updated accordingly.

Best regards,
Peter

**Comment by DaveDavenport** [comment]
I don't understand, it is all explained in INSTALL.md: https://github.com/davatorium/rofi/blob/next/INSTALL.md#install-a-checkout-from-git

**Comment by ptsl** [comment]
My bad, I just started reading the document from the top and didn't realize that installation from Git has its own section.
Apologies for my absentmindedness. And a big thanks for the great tool!
Peter
