### ISSUE TITLE
[BUG] Cursor theme property not working

### ISSUE THREAD

**Issue by jc65536** [davatorium/rofi#1360]
## Version

Version: 1.6.1

## Configuration

[rofi -help](https://gist.github.com/jc65536/157afb171957482d2a4d98e72b3bf9f1)

[theme-default.rasi](https://gist.github.com/jc65536/6014720daaf1696909783d97f58ee09b)

## Launch Command

rofi -show run

## Steps to reproduce

- Step 1
    Add the line `cursor: pointer;` in the theme file under the group `element`.
    (I also tried putting pointer in quotes, like so: `cursor: "pointer";`)
- Step 2
    Run rofi

## What behaviour you see
No quotes:
```
Error while parsing theme: theme-default
Parser error: syntax error, unexpected invalid property value
Location: line 6 column 12 to line 6 column 58.
File: '/home/jason/.config/rofi/theme-default.rasi'
```
With quotes: the cursor does not change. It seems like the property was ignored.

## What behaviour you expect to see
The wiki states that the cursor format is 
> Format: (default|pointer|text)

so either this is outdated or there is a bug. The cursor should have changed to a hand when I hover over any of the list elements.

**Additional details:**
Window manager: bspwm

**Comment by DaveDavenport** [comment]
<= 1.6.1 does not support cursor.
