### ISSUE TITLE
[BUG] Rofi is extremelly slow when not cached

### ISSUE THREAD

**Issue by matheusfillipe** [davatorium/rofi#1362]
## Version
`Version: 1.6.1-149-git-69c60046 (next)`
I also tested with the last release and the community arch package and they are all slow to me.

## Configuration

https://gist.github.com/eddf9a536ae050f54be8a4f5479488e2
```
configuration {
	theme: "~/.config/rofi/themes/dt-center.rasi";
	// 
  //modi: "window,run,drun,ssh,filebrowser,windowcd,combi,calc";
	//modi: "window,run,ssh,file-browser,windowcd,combi,calc";
	modi: "window,run,windowcd,calc";
	terminal: "/usr/bin/alacritty";
	ssh-client: "/usr/bin/mosh";
	ssh-command: "{terminal} -t {host} --class ssh_client -e {ssh-client} mattf -- mosh {host} -- tmux a";
	sorting-method: "fzf";
	matching: "fuzzy";
	sort: true;
	drun-use-desktop-cache: true;
	kb-row-up:                      "Up,ISO_Left_Tab,Control+k,Shift+Tab,Shift+ISO_Left_Tab";
	kb-row-down:                    "Down,Control+j";
	kb-accept-entry:                "Control+m,Return,KP_Enter";
	kb-remove-to-eol:               "Control+Shift+e";
  kb-mode-next:                   "Shift+Right,Control+Tab,Control+l";
	kb-mode-previous:               "Shift+Left,Control+Shift+Tab,Control+h";
	kb-remove-char-back:            "BackSpace";
	kb-remove-word-back:            "Alt+BackSpace,Control+BackSpace";
	kb-mode-complete:               "Alt+l";
}
```
## Launch Command
```
sudo echo 1 >> /proc/sys/vm/drop_caches 
rofi -show window
```

## What behaviour you see

`G_MESSAGES_DEBUG=Timings ./rofi -show window > timming.txt`
[timming.txt](https://github.com/davatorium/rofi/files/6947896/timming.txt)

## What behaviour you expect to see

With drun disabled rofi should load faster than 8 seconds I think. What can be wrong?

**Comment by DaveDavenport** [comment]
See several of the many issues about this.
without caching it *needs* to spider through many directories on your system and parse many (depending on your system) .desktop files.

If you are on a system where the I/O for this type of behavior there is little rofi can do about it to improve it, its I/O bound. 

This is why you can optionally enable a drun-cache in rofi, so it only has to read 1 file (see manpage), but it won't auto-discover new/changed files anymore.

**Comment by matheusfillipe** [comment]
@DaveDavenport 
Well I have not enabled drun. I tried using it with the drun-cache option, which i still have enabled but I don't think that makes any difference with it disabled.

Yeah `run` seems to be taking the longest. I did a smart check but the drive is not that old and there are no errors. It is a laptop. My `/` is on a nvme ssd and my home is on a 5400 rpm hd. 

Anyway Isn't there a (possibly dirty) workaround to at least keep rofi cached? I wouldn't mind having something like a cron firing it every minute as long as it doesn't display, which i don't know how to do. If you could tell me a way to do that I would be happy already.

**Comment by DaveDavenport** [comment]
hmm with / on an nvme it should not be slow, that would suggest it is slow on the part in your home directory.
What is your $PATH?

**Comment by DaveDavenport** [comment]
Can you try running:
```bash
PATH=/bin:/usr/bin:/usr/local/bin  G_MESSAGES_DEBUG=Timings ./rofi -show window > timings.txt
```
and post timings.txt?

**Comment by matheusfillipe** [comment]
Yep you are right. My $PATH is a mess and there are many things on the home drive (spinning disk). 
[timings.txt](https://github.com/davatorium/rofi/files/6948375/timings.txt)


It is much better now, for sure the biggest bottleneck are those in my home. Is there any way to check which of the directories on my path is taking longer?

Anyway there are still these two:

```
(process:1020972): Timings-DEBUG: 21:16:54.329: 0.880090 (0.000051): ../source/view.c:rofi_view_repaint:292 flush
(process:1020972): Timings-DEBUG: 21:16:55.486: 2.037380 (1.157290): ../source/view.c:rofi_view_update:1099 
```

```
(process:1020972): Timings-DEBUG: 21:16:56.691: 3.242046 (0.000029): ../source/view.c:rofi_view_repaint:292 flush
(process:1020972): Timings-DEBUG: 21:16:57.891: 4.441607 (1.199561): ../source/view.c:rofi_view_update:1099 
```

**Comment by DaveDavenport** [comment]
Those are at the interval of the  blinking of the cursor and should not be slowdowns.

```
(process:1020972): Timings-DEBUG: 21:16:54.113: 0.664098 (0.013065): ../source/dialogs/run.c:get_apps:244 start
(process:1020972): Timings-DEBUG: 21:16:54.170: 0.721313 (0.057215): ../source/dialogs/run.c:get_apps:377 stop
```

This looks more like a normal machine.   Is the 5400rpm disk aggressively spinning down? the behavior (of scanning relatively little files) feels off.

**Comment by matheusfillipe** [comment]
In my normal path I have 9646 executable files. From these 7830 are on my ssd. So the /home ones are just a few (1816). 

Anyway after I simplified my PATH and changed the shortcut that I use to call rofi prepending it with a PATH that has only what i really need it is twice as fast at least. It is already much more usable.

Thanks for the help @dannycolin!

**Comment by DaveDavenport** [comment]
In source/dialogs/run.c can you change that to:
```c
if ( is_homedir ) {
```
to 
```c
if ( 0 ) {
```
(e.g. disabling that extra check), see if this helps?
(still 4 seconds for 2000 files :-/)

**Comment by matheusfillipe** [comment]
[timings.txt](https://github.com/davatorium/rofi/files/6949818/timings.txt)
Seems it didn't do quite much of a difference

**Comment by DaveDavenport** [comment]
Thanks for testing.  Don't think I can do much to speed run up, beside making a cache file. But there are a lot of files that are opened in $home (like possibly fonts and fontconfig, rofi config, etc.) and it feels like treating symptoms.
