### ISSUE TITLE
[BUG] No input when there's no background windows.

### ISSUE THREAD

**Issue by DavidRojoM** [davatorium/rofi#1369]
## Version

Version: 1.6.1

## Configuration

https://gist.github.com/DavidRojoM/b03060001b0da324baedebbaadd1d577

## Launch Command

`bash -c "ls /home/david/proyectos/ | rofi -show -dmenu -i | xargs -I_ webstorm /home/david/proyectos/_"`

## Steps to reproduce

- Create a Gnome shortcut including `bash -c "ls /home/david/proyectos/ | rofi -show -dmenu -i | xargs -I_ webstorm /home/david/proyectos/_"`
- execute the shortcut without any window in the background

## What behaviour you see

- Rofi does't register any keyboard input

## What behaviour you expect to see

- Keyboard input, just as when theres any window in background

**Additional details:**
- Running on Manjaro
- Kernel: 5.10.56-1-MANJARO
- DE : GNOME 40.3

**Please do not submit reports related to wayland, see
[here](https://github.com/DaveDavenport/rofi/wiki/Wayland) for more
information.**

**Comment by DaveDavenport** [comment]
Are you on wayland or Xorg version?

**Comment by DavidRojoM** [comment]
> Are you on wayland or Xorg version?

Wayland

**Comment by DaveDavenport** [comment]
See the bottom of your own issue, there is a link there.
