### ISSUE TITLE
[REQUEST] It'd be cool if rofi issue tracking didn't lock resolved issues

### ISSUE THREAD

**Issue by DavidAntliff** [davatorium/rofi#1372]
I think it's a mistake to lock resolved issues, preventing new comments from non-original participants. Sometimes new people to the issue need to seek clarification and there's no way to do this without creating a new issue, that isn't really a bug or feature request (like this one). This can create more issues and more noise, but it's also off-putting to potential new contributors.

Very few open-source projects take this step, and for good reason - sometimes issues aren't actually fixed, or the resolution isn't clear to people outside the original discussion.

Apologies for the misuse of the Issues system to bring this up but I'm not sure how to otherwise bring this to anyone's attention.

**Comment by DaveDavenport** [comment]
To keep the issue tracker workable for us and usable for the users I want people to follow the guidelines and steer them to the right place. We put in effort to help the user with this.

For this reason when you click new issue, we present a menu with options:

![image](https://user-images.githubusercontent.com/406245/129991187-526f4a52-b382-4b49-8c6e-e41c993666c6.png)

Then when you click 'new issue',  It provides a template to fill in and it tells you to read the guidelines.

![image](https://user-images.githubusercontent.com/406245/129992887-9a60ef49-7923-4a5d-af10-9f94c2b15684.png)


In the guidelines it even tells you that we don't want old issues to be resurrected from the grave  and used to ask unrelated questions or get unrelated items added to it.

![image](https://user-images.githubusercontent.com/406245/129991866-ebd4e017-ead7-432a-8662-bbf189f52aaf.png)

we have a template that has the guideline in there we ask people to fill in. So it should be linked on the top of each issue.

This was not enough, people ignored these instructions. This to me made the issue tracker unworkable.

I do not know if you did this on purpose:

>  but  you clearly proofed my point by ignoring the instructions and making this discussion in the issue tracker, ignoring the menu and the guidelines where it offered  3 discussion places. (reddit, the discussion forum on github and irc) and deleting the template. 

From the guidelines:

![image](https://user-images.githubusercontent.com/406245/129991820-5b4dc304-ab23-4790-8351-445abc4f04be.png)

Therefore we now lock issues after a period of inactivity. This was not done out of spite or to frustrate new users, but it is regrettable the only way to keep the issue tracker clean and workable.



I will move this to the github discussion forum as that to me is the right place for this.
