### ISSUE TITLE
[BUG] depricated options lines, columns, width

### ISSUE THREAD

**Issue by pepper-jelly** [davatorium/rofi#1391]
## Version

Version: 1.7.0

## Configuration

default + theme

## Launch Command

I use custom dmenu script with lock, logout etc,
as example `rofi -show run -lines 5 -width 15`

## Steps to reproduce

- Step 1 hit shortcut

## What behaviour you see

In 1a9dac8 `-lines` and others flags were removed.
In case someone face same issue it's still possible with e.g. `-theme-str 'listview {lines: 5;}'` but confusing because `-lines` are still mentioned in docs.

## What behaviour you expect to see

behavior before 1a9dac80a9a39d5f71f204710c1b07057d805ead

**Comment by DaveDavenport** [comment]
This is not a bug, it is intended behavior. 

Please read the release notes, it explains the reason why I deprecated options.

I removed the examples with `-lines` from the manpage. Thanks.

**Comment by DaveDavenport** [comment]
duplicate #1390

**Comment by DaveDavenport** [comment]
I am open for a discussion on this in the [discussion](https://github.com/davatorium/rofi/discussions) forum. But Please don't keep opening new issues.

**Comment by alisianoi** [comment]
Hi, thank you for your work on rofi!

Came here to say that `-width` no longer works. Will be reading the deprecations/links now.

Edit: the new width setting seems to be discussed here: https://github.com/davatorium/rofi/discussions/1407

Edit 2: for me, the solution was:

1. Ignore the "theme" inside the "configuration" block
2. Have an outside `@theme` annotation and a `window` block like this:

```
@theme "gruvbox-dark-hard"
window {
    width: 80%;
}
```

**Comment by DaveDavenport** [comment]
```
    Ignore the "theme" inside the "configuration" block
```

yes, this is a left over from the -theme option (cmd line options and old configuration {} block options are automatically linked).  ```configuration { theme: "theme";}``` should not be used.
Before this release this was not reported and I did not think of it, otherwise I would have build in some special handler for this.
