### ISSUE TITLE
[BUG] Dmenu-theme example not working as intended

### ISSUE THREAD

**Issue by eloraju** [davatorium/rofi#1396]
## Version

Output of `rofi -v`
Version: 1.7.0

## Configuration

[rofi -help output](https://gist.github.com/eloraju/ad9e5ad5ee0999e9b598b818bf720cbc)

## Launch Command

`rofi -show run`

## Steps to reproduce

Copy the [dmenu example theme](https://github.com/davatorium/rofi/blob/next/doc/rofi-theme.5.markdown#children) from the theme readme and set it as your theme and run rofi

## What behaviour you see

The selected `element` only has blue background on where it has padding exceeding the dimensoins of `element-text`
![Erronous behaviour](https://user-images.githubusercontent.com/5363750/131389055-a65910ba-1e1c-48a7-8a0e-d3d6e6d4b6ed.png)

## What behaviour you expect to see

The selected `element` to have a blue background
![Expected behaviour](https://user-images.githubusercontent.com/5363750/131389129-b675cdad-679d-41a7-bd2b-b2e96d80d232.png)

**Additional details:**

Setting the `element-text selected` `background-color` to `inherit` fixes this, but it's not very intuitive. I know it's not a bug per se but it is confusing when the example doesn't work as expected.

**Comment by DaveDavenport** [comment]
Yes, the example needs to be fixed yes.
