### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by jiampong212** [davatorium/rofi#1402]
## Version
Version: 1.7.0

## Configuration

Output of `rofi -help` (in a [gist](https://gist.github.com/), please paste the *full* output)

## Launch Command

`The commandline used to launch **rofi**`

## Steps to reproduce

- Step 1
- Step 2

## What behaviour you see

- ...

## What behaviour you expect to see

- ...

**Additional details:**
- Include a link to your private config
- Include screenshots/casts of your issue

**Please do not submit reports related to wayland, see
[here](https://github.com/DaveDavenport/rofi/wiki/Wayland) for more
information.**

**Comment by DaveDavenport** [comment]
empty issue.
