### ISSUE TITLE
[BUG] Text color no longer set in 1.7.0

### ISSUE THREAD

**Issue by sam-lunt** [davatorium/rofi#1417]
I recently upgraded from version 1.6.1 to version 1.7.0, and my theme no longer sets the text color correctly. I downgraded to 1.6.1 and confirmed that the same config works correctly in that version.

I am using [this theme](https://github.com/jordiorlando/base16-rofi/blob/master/themes/base16-zenburn.rasi), but any theme with a dark background from that repo can be used to demonstrate the issue. If the issue is that the theme needs to be updated to handle a config change, I'm happy to do that if someone can point me in the right direction for what needs to change.

Here is a screenshot using 1.6.1:
![image](https://user-images.githubusercontent.com/26120519/131691341-c0b4bcee-3834-470a-b0df-b4dfbd0d88fa.png)

And here is a screenshot using the same config with 1.7.0:
![image](https://user-images.githubusercontent.com/26120519/131691253-1c599acc-27d9-487d-8c67-b98d00fa568c.png)

## Configuration
[Output of `rofi -help`](https://gist.github.com/sam-lunt/e19eba5fa5fdf25133a86b25e7383ba3)

## Launch Command
`rofi -show combi`

**Comment by DaveDavenport** [comment]
Please:

1.) read release notes.
2.) Read the sticky at the top of the issue list.
3.) Check out other issues. (see guidelines )

**Comment by DaveDavenport** [comment]
release notes: https://github.com/davatorium/rofi/releases
Sticky:             https://github.com/davatorium/rofi/issues/1397
issue this is duplicate of: https://github.com/davatorium/rofi/issues/1395

**Comment by sam-lunt** [comment]
Sorry about that, I missed the sticky. That solves my problem, thanks!
