### ISSUE TITLE
[REQUEST] drun support for categories and hidden items

### ISSUE THREAD

**Issue by jackghg** [davatorium/rofi#1418]
In drun there are a lot of items! So I'd like if it could show the menu categories and after click to show relative apps.
Also it could optionally hide the apps that are hidden in the system menu.
This would help browse the apps.

**Comment by DaveDavenport** [comment]
Provide the information as listed in the template https://github.com/davatorium/rofi/blob/next/.github/ISSUE_TEMPLATE/feature_request.md that should have been there when doing the feature request.

**Comment by jackghg** [comment]
> Provide...

no
