### ISSUE TITLE
icon and text is not in center

### ISSUE THREAD

**Issue by plus9a** [davatorium/rofi#1419]
### Rofi version (rofi -v)

1.7

### Configuration

cat ~/.config/rofi/colorful/style_1.rasi | paste  https://paste.rs/TtN

### Launch command

rofi -no-lazy-grab -show drun -modi drun -theme ~/.config/rofi/style_1.rasi

### Step to reproduce

.

### Expected behavior

https://github.com/davatorium/rofi/issues/1397 , I allrady readed this one .
at the previous vertion is was working perfectly fine.
the problem icon and text is not in center

### Actual behavior

the problem icon and text is not in center

### Additional information

https://github.com/davatorium/rofi/issues/1397

**Comment by DaveDavenport** [comment]
Can you please include the full config? (add colors.rasi) so I can fully test, I am getting a different result then reported.
(text is centered for me,   I need to add `textbox-icon { horizontal-align: 0.5; }` to center the icon.)

**Comment by plus9a** [comment]
ah...sorry
nothing special there...
cat ~/.config/rofi/colorful/colors.rasi | paste  
https://paste.rs/I7J

**Comment by DaveDavenport** [comment]
Thanks, I need to look into this, the icon default align values are centered. Not sure where it gets the different alignment from.

Text for me is centered.

**Comment by plus9a** [comment]
Old 1.6 stable config ( not useful information i believe)
https://github.com/kazi-sifat-plus9a/arch-star-calamares/tree/master/airootfs/usr/local/share/rofi

**Comment by DaveDavenport** [comment]
btw. to work-around this (for me) is to add horizontal-align: 0.5; to element-icon {}.

**Comment by plus9a** [comment]
https://github.com/davatorium/rofi/issues/1397
i am going  to make a comment there thanks a lot .boss

**Comment by DaveDavenport** [comment]
it might be a bug, lets figure this out first :D

**Comment by plus9a** [comment]
it worked

**Comment by DaveDavenport** [comment]
yes, but it should not be needed, it should default center.

**Comment by plus9a** [comment]
Hmmm. Right 👍 , looks like that page is only for Collaborator or admin . You should add one. 😇 Thanks a lot for your support
https://github.com/davatorium/rofi/issues/1397

**Comment by DaveDavenport** [comment]
Yes, that is not the correct page for that. That is the  'theme'  category on the discussion page. As mentioned there. Issue tracker should be for bugs (like this one), the discussion is a good place for questions, tips and tricks and more.

**Comment by DaveDavenport** [comment]
Found the bug.   Double properties fall back to integer when not found. This causes 0.5 to be seen as 0.. 

oops.

**Comment by DaveDavenport** [comment]
should be fixed in git.
