### ISSUE TITLE
[BUG] Background color of selected element is displayed incorrectly

### ISSUE THREAD

**Issue by ParaSait** [davatorium/rofi#1424]
### Rofi version (rofi -v)

1.7.0

### Configuration

https://gist.github.com/ParaSait/5e410c36566ffffa31aa198644cc2334

### Launch command

rofi -show drun

### Step to reproduce

* use rofi 1.7.0
* use the provided config and theme
* launch rofi

### Expected behavior

Selected items are shown in the SteelBlue color (attached screenshot is from rofi 1.6.1).

![rofi_161](https://user-images.githubusercontent.com/5515059/132098439-eab3d62a-2e5a-4a34-a6fa-bfd3b0e8ed02.png)

### Actual behavior

Only certain parts of the SteelBlue color are visible; most of it is still Black (attached screenshot is from rofi 1.7.0).

![rofi_170](https://user-images.githubusercontent.com/5515059/132098503-062ad9a1-fdf7-4e1d-8fc8-a989166fcc1f.png)

### Additional information

**OS:** Arch Linux
**Display server:** xorg 1.20.13-2
**Compositor:** picom 8.2-1
**WM:** qtile 0.17.0-1

**Comment by DaveDavenport** [comment]
Please see the pinned issue!
I has the solution mentioned there, and points you to the discussion forum for theme question.

**Comment by DaveDavenport** [comment]
See https://github.com/davatorium/rofi/issues/1397
