### ISSUE TITLE
[BUG] -mesg parsing fails if message starts with a dash

### ISSUE THREAD

**Issue by t-wissmann** [davatorium/rofi#1425]
### Rofi version (rofi -v)

1.7.0

### Configuration

https://github.com/t-wissmann/dotfiles/blob/master/config/rofi/config.rasi

### Launch command

rofi -dmenu -mesg "-- the mesg --" -no-custom < /dev/null

### Step to reproduce

* run the self-contained command.

### Expected behavior

I expected that the message `-- the mesg --` is used in the rofi window

### Actual behavior

Instead, a wrong error message is shown in the rofi window:
![image](https://user-images.githubusercontent.com/9048813/132119918-0a4fe325-73f5-4825-9d82-c024687f4791.png)

1. it is not about parsing the theme at all
2. `-no-custom` is not part of the message
3. no `bracket open ('{')` is contained in the command line at all

### Additional information

* This issue did not exist in rofi 1.6.1
* The configuration should not matter at all (it is the default config)

**Comment by DaveDavenport** [comment]
Nice one, yeah this needs fixing.

I've added some testing code that converts commandline options into the new config options and that fails.

**Comment by DaveDavenport** [comment]
quick workaround is to put an invisible character in front. 
unicode feff.

**Comment by t-wissmann** [comment]
Thanks for taking care of it! I've worked around this issue by prepending `<i></i>` to the message.
