### ISSUE TITLE
[BUG] Latest rofi breaks theme

### ISSUE THREAD

**Issue by Morantoine** [davatorium/rofi#1426]
### Rofi version (rofi -v)

1.7.0

### Configuration

https://gist.github.com/Morantxu/7ea956be81ee0741736c557849d91425

### Launch command

rofi -font 'Hack bold 14' -theme slate -combi-modi window#drun -show combi -modi combi

### Step to reproduce

* Launch rofi
* Look at the theme

### Expected behavior

The background of the text of the highlighted element is expected to be grey but it doesnt work on latest rofi version. Used to work fine before, I checked by downgrading the package.

### Actual behavior

![image](https://user-images.githubusercontent.com/71721545/132124935-944aa5d0-fd27-4e4c-9133-245d98a53b94.png)

**Comment by Bad3r** [comment]
There is a pinned issue with more information about themes breaking on rofi 1.7.0 (https://github.com/davatorium/rofi/issues/1397)

edit: check https://github.com/davatorium/rofi/issues/1427#issuecomment-913179583

**Comment by DaveDavenport** [comment]
I think the  the release notes and the hint in the pinned issue contains the fix.
