### ISSUE TITLE
[BUG] The Config file is not used (Default theme on start)

### ISSUE THREAD

**Issue by dvragulin** [davatorium/rofi#1427]
### Rofi version (rofi -v)

Version: 1.7.0

### Configuration

https://gist.github.com/dvragulin/41fa89ce884c15cbcb452057889a92e5

### Launch command

rofi -show

### Step to reproduce

1. Install the configuration file in [~/. config/rofi/config](https://gist.github.com/dvragulin/41fa89ce884c15cbcb452057889a92e5)
2. Run the `rofi-show`command

### Expected behavior

rofi starts with my mega cool theme

### Actual behavior

rofi starts with the default theme

### Additional information

After the update (possibly), the standard config located at the path [~/. config/rofi/config](https://gist.github.com/dvragulin/41fa89ce884c15cbcb452057889a92e5) stopped being read. The *default* theme is launched. The reason for this behavior is not clear to me, do you have any thoughts?

**Comment by Bad3r** [comment]
I encountered the same issue after the update. After reading the [release notes](https://github.com/davatorium/rofi/releases/tag/1.7.0), I realized that the update contains breaking changes.
To fix it, I regenerated my config file
```py
rofi -dump-config > ~/.config/rofi/config.rasi
```
and edited to specify the theme
```yaml
configuration {
    theme: "themes/nord"; 
  timeout {
      action: "kb-cancel";
      delay:  0;
  }
  filebrowser {
      directories-first: true;
      sorting-method:    "name";
  }
}

```
where `"themes/nord"` is `$XDG_CONFIG_HOME/rofi/themes/nord.rasi`

if you are curious, the theme I am using is [Nord rofi theme by @undiabler](https://github.com/undiabler/nord-rofi-theme/) 

Edit: You should also check https://github.com/davatorium/rofi/issues/1397

**Comment by DaveDavenport** [comment]
This is intended behaviour. After 4 years of being deprecated the old format has been removed. 
The previous version of rofi complained about this on the commandline with warning.
(I will make sure future releases will have annoying nag screens, so people don't miss it).

For more information see discussion form (see link Bad3r linked).

**Comment by dvragulin** [comment]
> I encountered the same issue after the update. After reading the [release notes](https://github.com/davatorium/rofi/releases/tag/1.7.0), I realized that the update contains breaking changes.
> To fix it, I regenerated my config file
> 
> ```python
> rofi -dump-config > ~/.config/rofi/config.rasi
> ```
> 
> and edited to specify the theme
> 
> ```yaml
> configuration {
>     theme: "themes/nord"; 
>   timeout {
>       action: "kb-cancel";
>       delay:  0;
>   }
>   filebrowser {
>       directories-first: true;
>       sorting-method:    "name";
>   }
> }
> ```
> 
> where `"themes/nord"` is `$XDG_CONFIG_HOME/rofi/themes/nord.rasi`
> 
> if you are curious, the theme I am using is [Nord rofi theme by @undiabler](https://github.com/undiabler/nord-rofi-theme/)
> 
> Edit: You should also check #1397

Thank you for your help and I'm sorry for being too lazy to read the release notes..
