### ISSUE TITLE
[REQUEST] Style With GTK Named Colors

### ISSUE THREAD

**Issue by bagnaram** [davatorium/rofi#1449]
### Before opening a feature request

- [X] I checked the *next* branch to see if the feature has already been implemented
- [X] I searched existing reports to see if it is already requested.

### What is the user problem or growth opportunity you want to see solved?

In order to support a seamless experience across applications, it would be great if rofi honored global GTK colors defined in https://gitlab.gnome.org/GNOME/gtk/-/blob/gtk-3-22/gtk/theme/Adwaita/_colors-public.scss

### How do you know that this problem exists today? Why is this important?

Currently specifying colors via the `foreground: @theme_fg_color;` results in parse errors upon rofi launch.

### Who will benefit from it?

GTK users themes will be able to inherit the user's environment

### Rofi version (rofi -v)

N/A

### Configuration

N/A

**Comment by DaveDavenport** [comment]
good maintained patches are welcome, I have no intention to implement this myself.
