### ISSUE TITLE
[BUG] -drun-match-fields doesn't seem to work

### ISSUE THREAD

**Issue by pitbuster** [davatorium/rofi#1456]
### Rofi version (rofi -v)

Version: 1.7.0

### Configuration

https://gist.github.com/pitbuster/8ec56395561fa346c549225aa224a302

### Launch command

ofi -show-icons -matching fuzzy -sort -drun-match-fields name -modi drun -show

### Step to reproduce

Launch with command above.

### Expected behavior

Filter only application name.

### Actual behavior

Filters also matches generic, as shown in screenshot below

![image](https://user-images.githubusercontent.com/650365/132957080-595ab2d5-38cf-429f-889e-d856f0552fdd.png)

**Comment by DaveDavenport** [comment]
Firstly, the highlighting does not exactly match the underlying matching.   This is an known issue (highlighting does a regex on the shown string).

I hope to fix this in one of the next releases, but have not come up with a good way that does not cause a negative performance impact.

I also thought that  all visible fields are searched by default, I need to double check as this was user contributed patch from a long time ago.

You can try:

```bash
rofi -drun-match-fields name  -drun-display-format "{name}" -show drun
```

**Comment by DaveDavenport** [comment]
https://github.com/davatorium/rofi/pull/911

**Comment by pitbuster** [comment]
Yes, I know about the highlighting issue, but as we can see in the screenshot, the first match (Darktable) only happens because it is matching the generic field. I tried your suggestion and it is good enough for me as a workaround.

**Comment by DaveDavenport** [comment]
@pitbuster  please see #911, all visible items are searched. (this was requested a few times before the patch was made).

**Comment by pitbuster** [comment]
Ah, my bad. I didn't catch that part. Closing then.

**Comment by DaveDavenport** [comment]
Hope the solution is sufficient for you.
( I thought the patch made sense, having visible fields searched seemed logical).

**Comment by pitbuster** [comment]
Yes, I am good with the provided solution, I was just confused on the model (I though that match forced display, not the other way).
