### ISSUE TITLE
[BUG] Double free crash when enabling `normalize-match`

### ISSUE THREAD

**Issue by lenormf** [davatorium/rofi#1459]
### Rofi version (rofi -v)

1.7.0

### Configuration

normalize-match: true;

### Launch command

rofi -show run

### Step to reproduce

* Run the command
* Type any letter

### Expected behavior

The input is fuzzy-matched.

### Actual behavior

Crash.

### Additional information

```
#0  0x00007ffff75bcd22 in raise () at /usr/lib/libc.so.6
#1  0x00007ffff75a6862 in abort () at /usr/lib/libc.so.6
#2  0x00007ffff75fed28 in __libc_message () at /usr/lib/libc.so.6
#3  0x00007ffff760692a in  () at /usr/lib/libc.so.6
#4  0x00007ffff7607d7c in _int_free () at /usr/lib/libc.so.6
#5  0x00007ffff760b9e8 in free () at /usr/lib/libc.so.6
#6  0x0000555555586e8c in helper_token_match (tokens=0x5555557ae5f0, input=0x5555556c2e00 <error: Cannot access memory at address 0x5555556c2e00>) at ../source/helper.c:509
#7  0x00005555555a3b2b in run_token_match (sw=0x5555555d5ae0 <run_mode>, tokens=0x5555557ae5f0, index=647) at ../source/dialogs/run.c:512
#8  0x0000555555585249 in mode_token_match (mode=0x5555555d5ae0 <run_mode>, tokens=0x5555557ae5f0, selected_line=647) at ../source/mode.c:114
```

Note the `input=0x5555556c2e00 <error: Cannot access memory at address 0x5555556c2e00>`.

**Comment by DaveDavenport** [comment]
can you attach full config (does not crash for me).

thanks.

**Comment by lenormf** [comment]
```
configuration {
    normalize-match: true;
}
```

I'm using ArchLinux.

**Comment by DaveDavenport** [comment]
That is all the configuration you use (you mentioned using fuzzy matcher)?  
I ask for output of `rofi -dump-config` not because I like being difficult, but to be able to help.

**Comment by lenormf** [comment]
I understand, I would have used gist.github.com as requested in the issue template if I had more configuration, but these are really the only lines I have in `config.rasi`.

I've also tried re-installing the package, to no avail. There doesn't seem to be much to the [upstream package](https://github.com/archlinux/svntogit-community/blob/packages/rofi/trunk/PKGBUILD) either.

**Comment by DaveDavenport** [comment]
perfect, just double checking because you mentioned fuzzy matching.

On arch vm could reproduce and found the issue in the normalize patch.

**Comment by lenormf** [comment]
My original configuration does use fuzzy matching, I suppose I shouldn't have mentioned it in the issue because all I need in the configuration to trigger the bug is normalisation. Sorry for the confusion.

**Comment by DaveDavenport** [comment]
Can you test that commit?

**Comment by lenormf** [comment]
It fixes the issue, I also made sure everything works with my regular configuration.

Could a new release (maybe a minor) be produced that includes this fix?

Thanks!

**Comment by DaveDavenport** [comment]
1.7.1 released once it is done. Sorry cannot give a time schedule.
