### ISSUE TITLE
[BUG] Can't change text-color of elements since 1.7.0

### ISSUE THREAD

**Issue by Hugo-loio** [davatorium/rofi#1460]
### Rofi version (rofi -v)

1.7.0

### Configuration

https://gist.github.com/Hugo-loio/42d58b35fe5e4235f7f30bf70f41259b

### Launch command

rofi -show run

### Step to reproduce

rofi -show run

### Expected behavior

Elements should show the text-color configured in theme.rasi.

### Actual behavior

Since 1.7.0 the text-color of all elements is black and I can't seem to change it. I can still change the background-color, just not the text-color. I can also change the text-color of other stuff such as the prompt, the entry... I just can't change the text-color of the elements.
When I downgrade to an earlier version, everything works perfectly again.

**Comment by TonCherAmi** [comment]
See the pinned issue #1397

**Comment by Hugo-loio** [comment]
Yup that worked. My bad, sry for the troubles
