### ISSUE TITLE
[BUG] Crash in file-browser when displaying filenames with special characters.

### ISSUE THREAD

**Issue by Adamskye** [davatorium/rofi#1471]
### Rofi version (rofi -v)

1.7.0

### Configuration

https://gist.github.com/Adamskye/99150e9f7a82a5f7f7dee6a52d5dc014#file-roficonfigs-txt

### Launch command

rofi -show filebrowser

### Step to reproduce

1. Download this [brokenfolder.zip](https://github.com/davatorium/rofi/files/7210726/brokenfolder.zip). Inside should be an empty folder with special characters in its filename.
2. Extract the zip file and place the folder somewhere.
3. Run `rofi -show filebrowser`and navigate to the directory that contains the broken folder.
4. Rofi won't be able to see the filename and will crash instead.

If you try and run `rofi -show filebrowser`again, rofi will crash immediately since it's still inside the directory containing the broken folder. Editing/deleting the cache or deleting the folder will allow you to run the rofi file-browser again.

### Expected behavior

This is what I expect the filebrowser to look like when viewing the folder's name:
![expected](https://user-images.githubusercontent.com/69760588/134347526-a7d57504-c85d-4c8b-b593-7a9033c5dd0c.png)

### Actual behavior

It crashes upon attempting to render the folder's name. In the terminal, I get:
`zsh: segmentation fault (core dumped) rofi -show filebrowser`.

### Additional information

Rofi does not crash when using file-browser-extended, a different file-browser plugin, rather than rofi's built-in file-browser. I used file-browser-extended to get the screenshot in the expected behaviour section.

**Comment by DaveDavenport** [comment]
Can you paste the broken filename (so I can copy) or a backtrace?

nm, got it.

**Comment by DaveDavenport** [comment]
possible fix in git, can you test?

**Comment by Adamskye** [comment]
The commit you referenced just replaces the filename with 'Invalid UTF-8 filename.'

Whilst that's okay, and it does stop the program from crashing, I think that it would be better if it at least attempted to render the filename by replacing invalid characters with placeholders, like seen in my screenshot, so that you can at least differentiate between different files which all have an invalid filename.

No worries though, I've just made a solution a few minutes ago which does exactly that :D. #1472

**Comment by DaveDavenport** [comment]
as mentioned before in other bug reports,  I don't want to add many work-arounds for broken input. 
If it valid Ill render it, if not, Ill go the most safe solution.

glib gave me an error, so I replace it.
I see your patch, and apperantly I did add a work around in the past. :smile: . man I need some memory juice. 

Looking at it closer, that rofi_force_utf8 is not the solution in this case as it does not do the initial conversion. It is only useful if the filesytem encoding is utf-8 and then there is an error.

**Comment by DaveDavenport** [comment]
(I still thing the problem should be fixed at the source, e.g.  make sure the filename fits the locale or visa versa.)

**Comment by Adamskye** [comment]
This commits fixes it, thanks!

**Comment by DaveDavenport** [comment]
great!.. thanks for the report.

**Comment by DaveDavenport** [comment]
still wondering if I should append (Invalid filename) or so, to make it clear.
