### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by jeffrey-xiao** [davatorium/rofi#1475]
### Rofi version (rofi -v)

Version: 1.7.0

### Configuration

https://gist.github.com/jeffrey-xiao/32a41eb08f5a1d43db9853444435de4e

### Launch command

rofi -show drun

### Step to reproduce

* Run `COLOR_0=#000 rofi -show drun`

### Expected behavior

I expect rofi to work fine with `${COLOR_0}`. It appears that using underscores in environment variables is not supported. Although this is consistent with the [spec](https://github.com/davatorium/rofi/blob/next/doc/rofi-theme.5.markdown), I think it should support underscores since it is a valid character for environment variables.

### Actual behavior

`rofi -show drun` outputs `syntax error: unexpected "property close (';')"`

**Comment by gryf** [comment]
This issue also manifests on 1.6.1. It gives message `syntax error, unexpected invalid property value` on the message window, and exits with exit status 65.

**Comment by DaveDavenport** [comment]
Can you test?

**Comment by gryf** [comment]
Works for me, thanks!
