### ISSUE TITLE
[BUG] Clicking custom button widget causes segfault in dmenu mode

### ISSUE THREAD

**Issue by Supreeeme** [davatorium/rofi#1504]
### Rofi version (rofi -v)

1.7.0

### Configuration

https://gist.github.com/Supreeeme/ee6d509b3afb32abf9e2f49b71869409

### Launch command

rofi -dmenu -config button_test.rasi

### Step to reproduce

1. Run the launch command
2. Click or press enter when the red button pops up
3. Segfault!

### Expected behavior

I would assume in dmenu mode, clicking the button would print the text from the button to stdout.

### Actual behavior

Segfaults!

**Comment by DaveDavenport** [comment]
Ok, I might not have considered people removing the key functionality of rofi.
What entry should it accept? there are no entries?

I think I should add a check and an error message if no listview is added to the view.

**Comment by DaveDavenport** [comment]
A second issue is I think, you binding a mouse binding..

"kb-accept-entry", "kb-cancel" behaves slightly better.

**Comment by DaveDavenport** [comment]
That should make things not crash and work.

**Comment by DaveDavenport** [comment]
@Supreeeme  Can you stress test this?

**Comment by Supreeeme** [comment]
It in fact does not crash now! I was trying this out because I just wanted to see what would happen lol. In my mind, I was assuming that it would print out the content of the button (being "Button!") but printing out nothing since dmenu mode is supposed to print one of the provided entries makes sense. I think some sort of warning that you're using dmenu mode but provided no input could be useful.

**Comment by DaveDavenport** [comment]
you can make an ok/cancel button now if you want. (can see result based on return code).
