### ISSUE TITLE
[REQUEST] "change to parent directory" keybind in filebrowser modi

### ISSUE THREAD

**Issue by Felecarpp** [davatorium/rofi#1508]
### Before opening a feature request

- [X] I checked the *next* branch to see if the feature has already been implemented
- [X] I searched existing reports to see if it is already requested.

### What is the user problem or growth opportunity you want to see solved?

They are not "change to parent directory" keybind in filebrowser modi. 

### How do you know that this problem exists today? Why is this important?

This keybind should allow use file browser more quicker. 

### Who will benefit from it?

rofi filebrowser users

### Rofi version (rofi -v)

1.7.0

### Configuration

https://gist.github.com/Felecarpp/aa9ba23fc080a242a50d86aa65f2af66

**Comment by ana-rchy** [comment]
working on it (to the best of my ability, its my first PR and id appreciate some help from other contributors)

**Comment by DaveDavenport** [comment]
kb-accept-custom-alt (ctrl+shift+return) is bound to this.
