### ISSUE TITLE
[BUG] Combi doesn't show .desktop file, but Drun does

### ISSUE THREAD

**Issue by 5HT2** [davatorium/rofi#1509]
### Rofi version (rofi -v)

1.7.0

### Configuration

https://cdn.l1v.in/paste-1635457906.txt

### Launch command

`rofi -show combi`

### Step to reproduce

* `rofi -show combi`
* Search for chemsketch (or any desktop file put inside `~/.local/share/applications`

### Expected behavior

It lists the desktop files found inside `~/.local/share/applications`, just like `rofi -show drun` does.

### Actual behavior

It does not.

### Additional information

The .desktop in question, which works fine via `rofi -show drun`: https://cdn.l1v.in/paste-1635457989.txt

**Comment by DaveDavenport** [comment]
It uses exactly the same code  (combi just calls the drun modi).

Can you get a debug log for both situations?

```bash
G_MESSAGES_DEBUG=all rofi -show drun
```
and
```bash
G_MESSAGES_DEBUG=all rofi -show combi
```

**Comment by 5HT2** [comment]
Drun: https://cdn.l1v.in/paste-1635458311.txt

Combi: https://cdn.l1v.in/paste-1635458341.txt

**Comment by 5HT2** [comment]
> It uses exactly the same code (combi just calls the drun modi).

That's indeed true, I was just cloning the repo to check that myself before you replied lol

```diff
source/dialogs/drun.c
1015:      dir = g_build_filename(g_get_user_data_dir(), "applications", NULL);
1036:          char *dir = g_build_filename(*iter, "applications", NULL);
```

**Comment by DaveDavenport** [comment]
aah, missed it on first read.. you don't use drun in combi mode. you currently combine window and run.

**Comment by DaveDavenport** [comment]
Try 

```bash
rofi -show combi -combi-modi "window,drun"
```

**Comment by 5HT2** [comment]
Oh, well that works. Unsure why `rofi -show combi` wouldn't work on it's own, then.

Is there a way to get rid of the `drun` text that's before each application?

**Comment by DaveDavenport** [comment]
it does not work on it own, because you have not configured it correctly in your config file.

The default for config is 'window,run'.

**Comment by 5HT2** [comment]
That makes sense, thank you!

**Comment by DaveDavenport** [comment]
from rofi -h:

```
	-[no-]combi-hide-mode-prefix            Hide the prefix mode prefix on the combi view.

```
(also see your config paste, where this option is commented out).

**Comment by 5HT2** [comment]
Much appreciated :)
