### ISSUE TITLE
[BUG] Setting `combi-mode` to include combi causes a Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by 5HT2** [davatorium/rofi#1510]
### Rofi version (rofi -v)

1.7.0

### Configuration

https://cdn.l1v.in/paste-1635459536.txt

### Launch command

`rofi -show combi`

### Step to reproduce

* Set `combi-modi: "combi,drun"`
* Run `combi -show combi`

### Expected behavior

Segfault (in terminal)

### Actual behavior

Maybe warn the user that they made a typo / they shouldn't do this? It was a bit weird to figure out what I configured wrong, since I just edited `modi: "combi,drun"` to `combi-modi: "combi,drun"`, so a segfault isn't the best description.

### Additional information

Not sure if this is worth fixing, I'm just documenting this in case someone else makes the same silly mistake.

**Comment by DaveDavenport** [comment]
he, never thought to test that.. yeah that needs to be fixed.
