### ISSUE TITLE
[BUG] Terminal & Nautilus take keyboard over rofi

### ISSUE THREAD

**Issue by Kilometres** [davatorium/rofi#1523]
### Rofi version (rofi -v)

Version: 1.5.4

### Configuration

default, fresh install from apt

### Launch command

rofi -show run

### Step to reproduce

* Open a terminal
* Open rofi by keybind
* Type
* Profit

### Expected behavior

keyboard uses rofi

### Actual behavior

keyboard uses terminal

### Additional information

Ubuntu

**Comment by DaveDavenport** [comment]
Running wayland or Xorg?
What ubuntu version?

Also you are using a very outdated (> 2years) version of rofi.

**Comment by DaveDavenport** [comment]
rofi does not support wayland, see the guidelines:

> Please do not submit reports related to wayland, see [here](https://github.com/DaveDavenport/rofi/wiki/Wayland) for more information.

**Comment by DaveDavenport** [comment]
I suggest trying https://github.com/lbonn/rofi it is a wayland support port of rofi.
