### ISSUE TITLE
[BUG] Rofi not using input

### ISSUE THREAD

**Issue by Kilometres** [davatorium/rofi#1526]
### Rofi version (rofi -v)

Version 1.7.0

### Configuration

https://gist.github.com/Kilometres/9fe3682d865b4c6f6afe639354993b8f

### Launch command

rofi -show run      (happens with every mode)

### Step to reproduce

* Install Rofi (I have tested V1.5.0 and V1.7.0)
* Open and focus a terminal
* Open rofi through keybind or terminal
* Type

### Expected behavior

Input is used in rofi menu. (Like when most programs are focused)

### Actual behavior

Input is used for terminal (or other specific programs e.g. nautilus)

### Additional information

Ubuntu 21.10
Wayland
Rofi 1.7.0

**Comment by DaveDavenport** [comment]
duplicate: #1523
