### ISSUE TITLE
[BUG] Thumbnails are loaded slow in wayland

### ISSUE THREAD

**Issue by Zeioth** [davatorium/rofi#1527]
### Rofi version (rofi -v)

1.7

### Configuration

https://gist.github.com/Zeioth/3e22fa39ee073d244d0068a3fa84faf4

### Launch command

rofi -show-icons -window-thumbnail -show drun

### Step to reproduce

Run rofi. It opens instantly. But you can see a 0.5s - 1.0s delay before the icons are displayed.

This doesn't happen when using wofi instead.

### Expected behavior

Instant load time for the icons.

### Actual behavior

0.5s - 1.0s delay before icons are displayed.

### Additional information

Testing in manjaro-sway. There will be a future wayland native version?

**Comment by DaveDavenport** [comment]
Please see the last line in the guidelines.
This also points to a port with native support.

**Comment by Zeioth** [comment]
It refers to this fork, for future reference:
https://github.com/lbonn/rofi
