### ISSUE TITLE
[BUG] build fails with --disable-windowmode

### ISSUE THREAD

**Issue by pastalian** [davatorium/rofi#1533]
### Rofi version (rofi -v)

1.7.1

### Configuration

N/A

### Launch command

N/A

### Step to reproduce

1. ./configure  --disable-check --disable-windowmode
2. make

### Expected behavior

Rofi build succeeds.

### Actual behavior

Rofi build fails.

log
```
/usr/lib/gcc/x86_64-pc-linux-gnu/11.2.1/../../../../x86_64-pc-linux-gnu/bin/ld: source/rofi-xcb.o: in function `main_loop_x11_event_handler_view':
/tmp/rofi-1.7.1/source/xcb.c:1101: undefined reference to `window_client_handle_signal'
/usr/lib/gcc/x86_64-pc-linux-gnu/11.2.1/../../../../x86_64-pc-linux-gnu/bin/ld: /tmp/rofi-1.7.1/source/xcb.c:1092: undefined reference to `window_client_handle_signal'
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:2415: rofi] Error 1
make[1]: Leaving directory '/tmp/rofi-1.7.1'
make: *** [Makefile:1980: all] Error 2
```

### Additional information

According to git blame, https://github.com/davatorium/rofi/pull/1421 seems to be the cause.

**Comment by DaveDavenport** [comment]
good one, should probably add this to the CI.
