### ISSUE TITLE
[BUG] Dumped default config seems to be deprecated

### ISSUE THREAD

**Issue by remolueoend** [davatorium/rofi#1534]
### Rofi version (rofi -v)

1.7.1

### Configuration

https://gist.github.com/remolueoend/5e86d571bf36682414d8bd391d41f671

### Launch command

rofi -show drun

### Step to reproduce

1. Dump default config (no `~/.config/rofi/config.rasi` exists) to `~/.config/rofi/config.rasi`
2. Un-comment `theme` to `theme: "/usr/share/rofi/themes/android_notification";
`
3. Start rofi using `rofi -show drun`

### Expected behavior

Rofi gets started with theme loaded from `/usr/share/rofi/themes/android_notification`.

### Actual behavior

Rofi not usable due to deprecation message:
```
** (process:9987): WARNING **: 16:45:17.353: /home/remo/.config/rofi/config.rasi:44:26: The option:
<b>
configuration
{
        theme: "/usr/share/rofi/themes/android_notification";
}</b>
is deprecated. Please replace with: <b>@theme "/usr/share/rofi/themes/android_notification"</b> after the configuration block.
```

### Additional information

* Even if the message just says *deprecated*, rofi is unusable. The UI gets replaced with the message above (I could not get screenshots and rofi run at the same time, sorry for that)
* I tried to adjust the config file as described in the deprecation message, but all of my attempts lead to parser-errors. It is not clear to me how the new config should look like.
* The config at `/usr/share/rofi/themes/android_notification` does not get loaded. I added the output of `rofi -dump-theme` and the content of `android_notification` to the linked Gist.

**Comment by DaveDavenport** [comment]
I am confused, the default config does not include 
```
theme: "/usr/share/rofi/themes/android_notification";
```

anyway comment that line and add

```css
@theme "/usr/share/rofi/themes/android_notification"
```
at the end after the closing '}' of the configuration block.
If this does not work, please paste the error message. I have no idea what you done and what is going wrong now?
(you can take a screenshot of rofi, with the build in key for this (alt-shift-s i think the default is))

**Comment by remolueoend** [comment]
wow, that was fast, thanks a lot! I tried this and it worked, I forgot to remove the semicolon at the end, sorry for that. I never contributed to rofi until now, but I may be able to adjust the default config in a new PR if that is desired from your side.

Thanks again for your help!

**Comment by DaveDavenport** [comment]
The default config should not point to `android_notification`, the one shipped with rofi does not.
It will output this if you pass that theme on the commandline:
```
rofi -theme "/usr/local/rofi/themes/android_notification" -dump-config
```

Maybe your distro is doing something weird? What one are you using?

**Comment by remolueoend** [comment]
My issue description might be confusing sorry. I replaced `/* theme: ;*/
` with `theme: "/usr/share/rofi/themes/android_notification"`. But it seems that this field is deprecated and instead themes have to be provides via `@theme ...`. I though about changing this.

**Comment by DaveDavenport** [comment]
Relevant bug  to fix:

```rofi -theme "/usr/local/rofi/themes/android_notification" -dump-config```

outputs an invalid config file.

@remolueoend  aah ok, thx.  I will fix this for the next release, it should not have outputted the theme field there.

**Comment by remolueoend** [comment]
> `rofi -theme "/usr/local/rofi/themes/android_notification" -dump-config`

Ah, that's the perfect command for reproducing it!

Thanks again!
