### ISSUE TITLE
[BUG]  windowcd broken in 1.7.1-1 

### ISSUE THREAD

**Issue by jn-novasol** [davatorium/rofi#1539]
### Rofi version (rofi -v)

1.7.1-1

### Configuration

https://gist.github.com/jn-novasol/0a84c814a2d955e6ab1c9a93d94a02fc

### Launch command

rofi \     -theme purple \     -show windowcd -show-icons \     -kb-cancel "Super+Escape,Escape" \     -kb-accept-entry "!Super-Tab,!Super_L,!Super+Super_L,Return"\     -kb-row-down "Super+Tab,Super+Down" \     -kb-row-up "Super+ISO_Left_Tab,Super+Shift+Tab,Super+Up"&

### Step to reproduce

Works as per usual on 1.7.0-1.
Then broke in 1.7.1-1.
Steps to reproduce: Upgrade to 1.7.1-1 and downgrade to 1.7.0-1 to work again.

### Expected behavior

Switch between programs in current window (or tag.. I use Awesome WM),

### Actual behavior

It suddenly started to show ALL open programs in ALL windows

### Additional information

OS: Arch Linux x86_64
Hostname: arch
Kernel Release: 5.15.5-arch1-1
Uptime: 0:30
WM: Awesome

**Comment by DaveDavenport** [comment]
windowcd still works fine for me in 1.7.2 and 1.7.1. I don't think I changed anything to that part of the code (git blame shows last 6 year no change (beside indenting and refactoring ) to that code (its as single line diff between cd/normal)).

not sure what 1.7.0-1 or 1.7.1-1 is? arch versioning?  please use `rofi -version` so i have actual version.

**Comment by DaveDavenport** [comment]
This is the line: https://github.com/davatorium/rofi/blob/next/source/dialogs/window.c#L662
For windowcd 'cd' is true.

**Comment by DaveDavenport** [comment]
any more hints on this? I asked other people and they also did not manage to reproduce this?

**Comment by jn-novasol** [comment]
I just looked at the pkgbuild and I think the -1 arch versioning is just package release..
https://archlinux.org/packages/community/x86_64/rofi/
https://github.com/archlinux/svntogit-community/blob/packages/rofi/trunk/PKGBUILD

When I do rofi -version I get it correct
~ ❯ rofi -version
Version: 1.7.0

**Comment by jn-novasol** [comment]
I will try and upgrade again and do some more testing later today to see If I can get some more info then =)

**Comment by DaveDavenport** [comment]
can you just try:  `rofi -show windowcd -no-config`  from a terminal, see if that works.
Then we can hopefully pinpoint where it goes wrong .

**Comment by jn-novasol** [comment]
When I run the above command in the same awesome wm tag, with the same applications running, I do get 9 results in rofi window with 1.7.1 and only 1 (the terminal i run it from) with 1.7.0

**Comment by jn-novasol** [comment]
I tried reboot after upgrade /downgrade and with/without external screen, same result

**Comment by DaveDavenport** [comment]
This is confusing, it works for multiple persons, this code has not been changed (beside a refactor) for 5 years.
I wonder what other bug is causing this side-effect.

**Comment by jn-novasol** [comment]
Okay finally had some time and I manage to get it working.
So before I had this in my awesome lua.rc:
`
    awful.key({ modkey }, "#49",
        function ()
            awful.client.focus.history.previous()
            if client.focus then
                awful.util.spawn( **rofi command here** )
            end
        end,
        {description = "Switch All windows", group = "client"}
    ),
`

Changed it to this and now it works as intended

`
    awful.key({ modkey }, "Tab", function ()
        os.execute([=[
            rofi -theme purple -show windowcd -show-icons \
                -kb-cancel "Super+Escape,Escape" \
                -kb-accept-entry "!Super-Tab,!Super_L,!Super+Super_L,Return" \
                -kb-row-down "Super+Tab,Super+Down" \
                -kb-row-up "Super+ISO_Left_Tab,Super+Shift+Tab,Super+Up"
        ]=]) end,
        {description = "Alt tabbing", group = "tag"}),
`

**Comment by DaveDavenport** [comment]
A proper fix been found and in git. Thanks to ForeverNoob
