### ISSUE TITLE
[BUG] Pressing Escape quits rofi but also passes to window behind it

### ISSUE THREAD

**Issue by LanHikari22** [davatorium/rofi#1541]
### Rofi version (rofi -v)

1.7.0

### Configuration

https://gist.github.com/LanHikari22/eaa06b67ac0427b33f17e848ee300e11

### Launch command

rofi -show window

### Step to reproduce

I am running this on KDE. I assigned a global shortcut Alt+Enter to launch "rofi -show window". When I press Escape to cancel my input, it also presses Escape in the application last used before launching rofi. 

### Expected behavior

I expect the keyboard input not to pass to any other application. This seems valid for other keys but not Escape.

### Actual behavior

Pressing "Escape"  closes rofi, but also passes the keyboard input to another window.

### Additional information

Note: I have also noticed in the configuration that I could do "Control+g" or "Control+left bracket" but if these mean Ctrl+g and Ctrl+[ they are not closing rofi.

**Comment by DaveDavenport** [comment]
Don't think this a rofi bug, but it does what you configured it to do. Rofi closes on the press of escape and quits instantly, by the time you release the key the underlying application  receives the release of the escape the key (and seems to be sensitive to this)
Try setting rofi to respond to the release off escape ( -kb-cancel '!Escape')

additional information: Works fine for me, both control-g  and control + [ closes rofi.

**Comment by LanHikari22** [comment]
Thank you! -kb-cancel '!Escape' resolved the issue for me! I must have not caught that while reading the docs.

I'm not sure what would be preventing Ctrl+g and Ctrl+[ from working for me for now, but that's minor.

Thanks for all the good work you put into this cool tool!
