### ISSUE TITLE
[BUG] Cannot set lines or width in 1.7.2

### ISSUE THREAD

**Issue by franburstall** [davatorium/rofi#1542]
### Rofi version (rofi -v)

Version: 1.7.2

### Configuration

https://gist.github.com/franburstall/a8caa1f2e6fede6aabc6567ebb908b11

### Launch command

rofi  -modi drun -show drun

### Step to reproduce

* Launch rofi

### Expected behavior

I expect to see six lines displayed because my config has `lines: 6`.

### Actual behavior

15 lines are displayed and I get the following in the invoking terminal:
```
(process:2921956): XrmOptions-WARNING **: 15:16:23.511: Option: width is not found.

(process:2921956): XrmOptions-WARNING **: 15:16:23.511: Option: lines is not found.
```

### Additional information

This behaviour is new in 1.7.0.  Have I missed something?

**Comment by DaveDavenport** [comment]
See pinned issue: https://github.com/davatorium/rofi/issues/1397

```css
listview {
lines: 6;
}
window {
width: 40%;
}
```
