### ISSUE TITLE
[BUG] 1.7.2-1 scroll bars and "type to filter prompt"

### ISSUE THREAD

**Issue by engageintellect** [davatorium/rofi#1543]
### Rofi version (rofi -v)

1.7.2-1

### Configuration

https://gist.github.com/jc9361/ad6c8fc0b16e2cd2dcf8a1c49823b696

### Launch command

#!/usr/bin/env bash  rofi -show run \     -font "Hack Nerd Font 10" \     -location 0 \     -theme-str '#window { width: 25%; height:25%; }'

### Step to reproduce

$ rofi -show run

### Expected behavior

I expect rofi to launch the way it was launching in the previous version.

### Actual behavior

- new version breaks pywal colorsscheme, again.
- had to remove "-theme" line from all rofi scripts to fix colors
- scroll bar now appears in all of my rofi scripts (want to disable this)
- "Type to filter prompt" appears in all of my scripts (want to disable this)

### Additional information

How can I get rid of scroll bars, and "type to filter prompt"

Also, where is rofi getting default theme from as now I no longer have to include "-theme" flag in rofi scripts, which I had to add in v1.7.1

Thanks

**Comment by DaveDavenport** [comment]
this is a support question? a rant? 
it also does not follow the guidelines.

I have no clue what is actually wrong, as there is no explanation. It just hints at things not working, but not how they don't work. 

1: What breaks? related to [https://github.com/davatorium/rofi/issues/1531]
2:  -theme option from the commandline has not changed in this release.  Only theme in configuration {} block (in 1.7.1).  Passing -theme from commandline works the same as in 1.7.1, 1.7.0. If it does not please tell me how it fails.
See my direct feedback to you in #1531 on how to it correctly so  you do not have to modify each 'script'.
3: See man rofi-theme and it is specified in the dumped theme.
4: See man rofi-theme

closing this 'issue', use the discussion forum for questions. 
The first version of the configuration {} contains an invalid entry as referenced in #1531.

your paste of configuration contains 1.9x a configuration that is not identical????

especially taking your replies on #1531 into account this report is very confusing. From the pasted config(s) you undid the fixes you did and now complain the new version does not work on items that have not been changed?

**Comment by DaveDavenport** [comment]
The theme you pasted works fine when passed with `-theme 1543-t.rasi`.
