### ISSUE TITLE
[BUG] Rofi can occasionally crash Xorg and cause it to restart

### ISSUE THREAD

**Issue by mkrasnitski** [davatorium/rofi#1544]
### Rofi version (rofi -v)

1.7.2

### Configuration

https://gist.github.com/mkrasnitski/cc0b99493c21ddb37dc46ee658bca012

### Launch command

rofi -show combi

### Step to reproduce

Launch Rofi

### Expected behavior

Menu pops up

### Actual behavior

Xorg crashes and coredumps. This does not happen every time, but does not seem to depend on how long Xorg has been running, or it rofi has been opened before or not.

### Additional information

Coredump: https://gist.github.com/mkrasnitski/7ba986320bdfebb8fdc3bccef878b316

**Comment by DaveDavenport** [comment]
never heard of this before.

Not sure how rofi could cause this (also not sure if it is rofi bug, it should not be capable of crashing xorg).

Can you give more details about your setup?

**Comment by mkrasnitski** [comment]
Sure. I'm running arch + sddm + i3. I've had sporadic xorg crashes the past few weeks and the last few times I've noticed it happens when I call rofi via keybind. As a note, each time this has happened I have audio/video playing in my browser, so maybe it's a pipewire issue, I don't know.

**Comment by DaveDavenport** [comment]
imho neither rofi or pipewire should be able to crash Xorg.

What Xorg version, AMD driver, etc?   (your trace showed amd dri ).
If we log enough information maybe we can find a common factor if more people report it.

I have no amd video card to test it on, on intel/nvidia I have not experienced an Xorg crash in years.

**Comment by mkrasnitski** [comment]
Xorg 21.1.1, xf86-video-amdgpu 21.0.0, mesa 21.3.1, vulkan-radeon 21.3.1. Running a 5700XT, and a Ryzen 3600.

**Comment by DaveDavenport** [comment]
See: https://bugs.archlinux.org/task/72799?string=xorg&project=1&type%5B0%5D=&sev%5B0%5D=&pri%5B0%5D=&due%5B0%5D=&reported%5B0%5D=&cat%5B0%5D=&status%5B0%5D=open&percent%5B0%5D=&opened=&dev=&closed=&duedatefrom=&duedateto=&changedfrom=&changedto=&openedfrom=&openedto=&closedfrom=&closedto=

I think it is the one you are hitting.
