### ISSUE TITLE
[REQUEST] rofi return value in script mode

### ISSUE THREAD

**Issue by numberokta** [davatorium/rofi#1546]
### Before opening a feature request

- [X] I checked the *next* branch to see if the feature has already been implemented
- [X] I searched existing reports to see if it is already requested.

### What is the user problem or growth opportunity you want to see solved?

rofi return selected or custom value, when using modi and script mode.
currently it return nothing.

### How do you know that this problem exists today? Why is this important?

`ret=$(rofi -modi "test:$HOME/test" -show test)`
`$ret` is **null**
it can be something like this:
`echo -en '\0return\x1fvalue\n'`
or when script return nothing, rofi return last script arguments `$@` to **parent script**

### Who will benefit from it?

users that want to return selected or custom value from **rofi script mode** to **parent script** that start rofi, like somthing that **-dmenu** do:
`sel=$(echo -en 'YES\nNO' | rofi -dmenu)`
when select **YES**, `$sel` value will be **YES**
maybe you say, use **-dmenu** instead of **-modi and script mode**, but **script mode** has more power then **-dmenu** and can be use to create application.

### Rofi version (rofi -v)

Version: 1.7.0

### Configuration

https://gist.github.com/numberokta/50bff49eb24b42590e662acdab0ca83e

**Comment by DaveDavenport** [comment]
This does not make a lot of sense to me in the rofi non dmenu context. 
The user can have multiple modi open you will not know what script returns the value.

**Comment by DaveDavenport** [comment]
>  but script mode has more power then -dmenu and can be use to create application.

What power?

**Comment by numberokta** [comment]
> This does not make a lot of sense to me in the rofi non dmenu context. The user can have multiple modi open you will not know what script returns the value.

it can be modify from script. each script return string with some kind of pattern that parent script know which script return value base on that pattern. actually rofi don't need do anything to specify which value are from which script, it just return value.

**Comment by numberokta** [comment]
> > but script mode has more power then -dmenu and can be use to create application.
> 
> What power?

**custom key binding** on **custom buttons** with **custom theme** make custom application that almost can do any thing. in script mode rofi will re execute script and find out what button pressed with `$ROFI_RETV` and then it will update content

**Comment by DaveDavenport** [comment]
>  it can be modify from script. each script return string with some kind of pattern that parent script know which script return value base on that pattern. actually rofi don't need do anything to specify which value are from which script, it just return value.

I don't follow this at all?  
A user can have,  run, drun, yourscript, userscript3 running.
how would you know (Based on return value) what script returned the return value?

Anything string the script 'prints' is captured by rofi for displaying.

**Comment by DaveDavenport** [comment]
> custom key binding on custom buttons with custom theme make custom application that almost can do any thing. in script mode rofi will re execute script and find out what button pressed with $ROFI_RETV 

dmenu mode sets return value on exit? you can detect the custom key that way.  I see no reason why you cannot do this with dmenu (otherwise that is a separate bug).

**Comment by numberokta** [comment]
> > it can be modify from script. each script return string with some kind of pattern that parent script know which script return value base on that pattern. actually rofi don't need do anything to specify which value are from which script, it just return value.
> 
> I don't follow this at all? A user can have, run, drun, yourscript, userscript3 running. how would you know (Based on return value) what script returned the return value?
> 
> Anything string the script 'prints' is captured by rofi for displaying.

let me explain that by example:
we have rofi (run, drun, yourscript, **userscript3**) running. in **userscript3** by **kb-custom-1** re execute **userscript3**.

**userscript3**
```
#!/usr/bin/env bash

if [ $ROFI_RETV -eq 10 ]; then
  echo -en '\0return\x1fuserscript3:hello'
  # \0return\x1f[script_name]:[value]
else
  echo -en 'YES\nNO'
fi
```
`[script_name]:[value]` is **pattern** that user make

**parent_script**
```
#!/usr/bin/env bash

ret=$(rofi -modi "run,drun,yourscript:$HOME/yourscript,userscript3:$HOME/userscript3" -show userscript3 -theme "$HOME/theme")
echo "$ret"
# userscript3:hello
```

**Comment by DaveDavenport** [comment]
a return value is  a number: https://en.wikipedia.org/wiki/Return_statement

rofi in non-dmenu mode is a standalone application. It is not designed to be used like that and that wil cause issue.

If you want to use rofi in a script, this is what dmenu mode is for.

I do not understand why people want to abuse rofi like this while there is a perfectly suitable solution (rofi -dmenu) for inclusion in scripts.

**Comment by numberokta** [comment]
> a return value is a number: https://en.wikipedia.org/wiki/Return_statement
> 
> rofi in non-dmenu mode is a standalone application. It is not designed to be used like that and that wil cause issue.
> 
> If you want to use rofi in a script, this is what dmenu mode is for.
> 
> I do not understand why people want to abuse rofi like this while there is a perfectly suitable solution (rofi -dmenu) for inclusion in scripts.

in dmenu mode if user want change content it must close rofi and open with new content each time but script mode just reload content.
about return value, i mean **return some value** in programming (like c) not just shell scripting

**Comment by DaveDavenport** [comment]
Then why not file a bug report against that? instead of this problematic 'work-around'.

Normal rofi is a standalone application where the user decide its configuration of what to show and how to show it.  It's calling should ideally not be more then `rofi -show run` or `rofi -show combi`.  It is up to the user, not the developer of a script.  On top of this, I am trying to uncouple themeing from configuration. 
Calling rofi from a script to do something specific of that script, having flags to override the user config is something I won't support in rofi (and I will actively make hard to do, because when it goes wrong (not if, but when) I will get users complaining).

Rofi called from scripts should use 'dmenu' mode.

Closing this issue.  

I am all for improving dmenu mode, so I don't mind a good discussion on how to improve this, maybe allow an option to launch a script from rofi dmenu mode?  `ret=$(rofi -dmenu myscript)`
Let do this in the discussion forum.

**Comment by DaveDavenport** [comment]
> about return value, i mean return some value in programming (like c) not just shell scripting

A return value (see the wiki page) is an integer number in the c programming language.
```c
int main (int argc, char **argv)
{
return 0;
}
```
this is the normal applications main function definition, the return value is declared as 'int'.

Sorry for the misunderstanding, but `return value` is a common way to the describe that. Its also how it is used in rofi.
You are talking about outputting to standard out/error out, this is done while the application is executing, not when it returns.
