### ISSUE TITLE
[REQUEST] Make --async-pre-read global option

### ISSUE THREAD

**Issue by nick87720z** [davatorium/rofi#1547]
### Before opening a feature request

- [X] I checked the *next* branch to see if the feature has already been implemented
- [X] I searched existing reports to see if it is already requested.

### What is the user problem or growth opportunity you want to see solved?

I discovered, that run mode, which collects executables from PATH, takes almost longest time to load, comparing to other modes, which was somewhat surprise for me (I assumed it's drun until this discovery).

I checked this using following dmenu script (I have dmenu symlink for rofi):
```sh
cat `which dmenu-run`
==============
#!/bin/sh

if [ -z "${DMENU}" ]; then
        DMENU=dmenu
fi

eval "$( printf '%s\n' "${PATH}" \
| sed -E '{s/:/" "/g; s/^.*/ls --color=never -1 "&"/}' \
| sh | sed '1d;/^$/{N;d;}' | sort | uniq -i | eval "${DMENU} -p Run $@" )"
```

Although first run is long, subsequent runs are almost instant. But if I add -sync option to dmenu, it because nearly as long as rofi run mode.
I tried to run like `time dmenu-run`, pressing esc after start to measure time to load.
For me it was ≈1s (0.9..1.1).

### How do you know that this problem exists today? Why is this important?

I made search for "--async-pre-pread" "async pre-read" and just "async" in this repo, looking commits and issues (not code).
And at last (may be too extra) - I ensured, that my current version matches this - live ebuild installs from there, without user patches to be applied. Version contains "dirty" - don't know, could it be cause by autoreconf.

### Who will benefit from it?

All rofi user

### Rofi version (rofi -v)

Version: 1.6.1-114-git-f72bae02-dirty (git-r3/HEAD)

### Configuration

https://gist.github.com/nick87720z/b4100082baf1f3ecaeb3718a79352e4b

### Additional information

Just for case - if array operations are frequent in rofi, I propose to try simultaneous change operations, when instead of one position change (add, remove) there is some sort of patch. Example:

```C
void array_change (
/* Add / remove cells in array. */

    T *data,
    /* Modified array */
    
    int *changes,
    /* Array of positions to be modified, as in original array.
     * Each position inserts new cell to position.
     * Negative position - remove cell with given abs position. */
    
    int ch_len
    /* Number of changes ('changes' array length) */
);
```

**Comment by DaveDavenport** [comment]
Can you paste a timing log? (see [wiki](https://github.com/davatorium/rofi/wiki/Debugging-Rofi#timing-traces)).

Normally scanning through binaries in PATH should not be slow from a clear state and most of the time should be cached and very fast.


Doing 'async' load on this will slow things down and will make the result of hitting the keybinding and typing the name of what you want less deterministic (as the match will change over time while it being loaded in background), that will mess with muscle memory.


Your issue report mentions many  things (something about git version?  and array changes) and is very confusing to read.
Please follow the guidelines and 1 thing per issue.

**Comment by DaveDavenport** [comment]
to comment on the title: --async-pre-read is a dmenu only option. I see no good reason to make this a global option as it only affects dmenu and its use depends on the script calling it.

**Comment by nick87720z** [comment]
Oh, right. I forgot, that rofi receives executable names not in sort order, used for view. Well, may be script modes could benefit from this if designed for async mode.

Timing with same config (not dmenu):
https://gist.github.com/nick87720z/030845559c469b4d9702f2c364226747/raw/ed4b159ce0884c4c9afbfecb3736ddeea3e8f0d6/rofi-timing

> to comment on the title: --async-pre-read is a dmenu only option. I see no good reason to make this a global option as it only affects dmenu and its use depends on the script calling it.

Well, I see, modes need to be adapted to async mode. May be script mode could also get this, as it looks like reverse dmenu mode, where rofi runs scripts (instead of scripts runing rofi).

**Comment by DaveDavenport** [comment]
From the trace, (first one)  drun  is the slowest (With 0.4 seconds) then run (0.2 sec).
It looks ok on the next runs (0.5 sec to be fully done, up and drawn to screen).

The DRun time can be reduced by enabling the drun cache.

**Comment by DaveDavenport** [comment]
> Doing 'async' load on this will slow things down and will make the result of hitting the keybinding and typing the name of what you want less deterministic (as the match will change over time while it being loaded in background), that will mess with muscle memory.


This is very critical point for me and that behavior stopped me from making it async in the past.

**Comment by nick87720z** [comment]
Wait... it's not drun, it's regular run mode, that cause slowdown. Will try lone run mode.
I indeed was sure originally, that it's drun, but actually it's not it.

**Comment by DaveDavenport** [comment]
sorry but that is not the log you posted.

**Comment by DaveDavenport** [comment]
(process:21940): Timings-DEBUG: 17:57:49.827: 0.137201 (0.003141): source/dialogs/drun.c:get_apps:948 Get Desktop apps (start)
(process:21940): Timings-DEBUG: 17:57:50.230: 0.539626 (0.**402425**): source/dialogs/drun.c:get_apps:960 Get Desktop apps (user dir)
(process:21940): Timings-DEBUG: 17:57:50.279: 0.588954 (0.049328): source/dialogs/drun.c:get_apps:983 Get Desktop apps (system dirs)
(process:21940): Timings-DEBUG: 17:57:50.279: 0.589004 (0.000050): source/dialogs/drun.c:get_apps_history:717 Start drun history
(process:21940): Timings-DEBUG: 17:57:50.280: 0.589330 (0.000326): source/dialogs/drun.c:get_apps_history:737 Stop drun history
(process:21940): Timings-DEBUG: 17:57:50.292: 0.601264 (0.011934): source/dialogs/drun.c:get_apps:989 Sorting done.
(process:21940): Timings-DEBUG: 17:57:50.292: 0.601347 (0.000083): source/dialogs/drun.c:write_cache:836 DRUN Write CACHE: start
(process:21940): Timings-DEBUG: 17:57:50.309: 0.618850 (0.017503): source/dialogs/drun.c:write_cache:868 DRUN Write CACHE: end
(process:21940): Timings-DEBUG: 17:57:50.422: 0.732114 (0.113264): source/dialogs/run.c:get_apps:244 start
(process:21940): Timings-DEBUG: 17:57:50.651: 0.960373 (0.**228259**): source/dialogs/run.c:get_apps:377 stop

**Comment by nick87720z** [comment]
There's run mode timing.
https://gist.github.com/nick87720z/030845559c469b4d9702f2c364226747/raw/45f198115bddac8384ab27d2f8d3b659ed3ee1a8/rofi-timing

Btw, `rofi -show drun -modi drun` much faster, ≈2 times faster show.
+ I don't press esc right after rofi start, but wait until it showes (adds some more lines after display moment).

**Comment by DaveDavenport** [comment]
looking at the logs you post I come to different conclusions. This is an interesting entry:
```
(process:18129): Timings-DEBUG: 18:28:05.909: 0.910453 (0.646021): source/widgets/listview.c:listview_set_num_elements:532 recompute elements
```
It takes a lot of time in each of the last trace and seems to be the main slowdown of rofi showing the interface.

**Comment by nick87720z** [comment]
Although it's guess - could it be that it does unnecessary processing on invisible elements?
Like, it could render visible as soon as possible, doing others later, just to update scrollbar (of course, if variable line number per item is allowed).

**Comment by DaveDavenport** [comment]
That is not how it currently works, the listview *only* renders the rows that are visible at that point in time. It provides a 'view' on the list, not the full list.

Rofi tries to do as much as possible 'lazy' in the ui, so only do it when it needed. 

What could (but this is just a guess) be causing a slow down there are fonts, I see you have multiple fonts. On the first load of a textbox in the listview it loads this font (it loads it once on first occurrence).
Can you try to make a timing trace with  the `-no-config` flag added?

(its confusing the traces you posted earlier don't show this).

**Comment by nick87720z** [comment]
Indeed, much faster with -no-config:
https://gist.github.com/nick87720z/030845559c469b4d9702f2c364226747/raw/689376d85f8eff0af7fad4a7e419e318692217fe/rofi-timing

**Comment by DaveDavenport** [comment]
That looks more in line with what I expect to see. 
I've have no good solution for the font issue,  the whole font config stuff seems to slow down when a lot of fonts are installed.
I have not hit this myself, but I know people hit it. It seems (from previous replies) not related to the specific font used, but more the total fonts (why? no idea this is deep in the trenches of pango).

Given I have not reproduced it, never been able to pin it down.

**Comment by DaveDavenport** [comment]
async-pre-read option has been removed.
