### ISSUE TITLE
[REQUEST] --async-pre-read auto

### ISSUE THREAD

**Issue by nick87720z** [davatorium/rofi#1548]
### Before opening a feature request

- [X] I checked the *next* branch to see if the feature has already been implemented
- [X] I searched existing reports to see if it is already requested.

### What is the user problem or growth opportunity you want to see solved?

It would be simpler to configure if rofi could calculate pre-fetched rows number, based on window height and rows density.
This would get list view completely filled in minimum possible time, leaving no gaps if final non-fixed rows number doesn't match --async-pre-read argument.

### How do you know that this problem exists today? Why is this important?

Simple: rofi allowes non-fixed number of visible strings, with no way to bind --async-pre-read to use their actual number on each run.

### Who will benefit from it?

All, who would like rofi's async loading mode.

### Rofi version (rofi -v)

Version: 1.6.1-114-git-f72bae02-dirty

### Configuration

https://gist.github.com/nick87720z/b4100082baf1f3ecaeb3718a79352e4b

### Additional information

Even without pre-calculation - should be enough to just fill the area for auto. N more additional rows could matter as they affect scrolling.
Yet there could be even more possible operators for --async-pre-read argument, also it could be like expression. For example: "auto*4+1".

**Comment by DaveDavenport** [comment]
In the current design this is not possible.  a mode (or dmenu) has no idea about the UI or how many rows there are.
This would break the current abstraction.

Also the number of rows (if it is not hard set in theme) is something that is dynamically calculated on window/widget size change.
When dmenu starts reading, this information is not available and it will (possibly) change over time.

**Comment by nick87720z** [comment]
May be rofi could be in two threads - with UI, processing --async-pre-read, and data loading part, which could do everything up to sorting, so that #1547 could be finally ok for other modes than dmenu and script.

**Comment by DaveDavenport** [comment]
async pre-read option has been removed.
