### ISSUE TITLE
[BUG] Steam games ordered higher than steam

### ISSUE THREAD

**Issue by 5HT2** [davatorium/rofi#1557]
### Rofi version (rofi -v)

1.7.2

### Configuration

https://cdn.l1v.in/paste-1640820284.txt https://cdn.l1v.in/paste-1640820291.txt

### Launch command

`rofi -show combi`

### Step to reproduce

* Run `rofi -show combi` 
* Type team

### Expected behavior

`Steam (Runtime)` is the first item

### Actual behavior

Steam games are the first items, with `Steam (Runtime)` being second to last (alphabetical order).

### Additional information

I'm using the same rofi version and config on my laptop, could this have something to do with *where* the .desktop files are?

I don't know where they are, I let steam automatically make them.

**Comment by DaveDavenport** [comment]
Rofi does not know what it is it showed, a logical order (steam above its game) is not something its aware off.
It currently lists them in order it was found scanning the folders, if steam is installed globally but makes desktop files per user, those will be first parsed, as local desktop files (per standard) have a higher priority then global one)

You can try enabling sorting, so if you start searching they sort based on match?
not sure where the "bug" is.

**Comment by 5HT2** [comment]
> You can try enabling sorting

Using `-sort`, this does not produce the desired behavior. See the screenshot below:

![](https://frogg.ie/WTU)

> not sure where the "bug" is.

I'm using the exact same config on both computers, I'd kind of expect Steam to be the first entry like it is on my laptop.

Either way, my end goal is getting steam to show up first (before my steam games) when it is not opened.

**Comment by DaveDavenport** [comment]
I see you have history enabled (is default), if you launch steam a few times, drun should have it as 'favorite' and (with match sorting disabled) should show first. That might be what is happening on other laptop.

With the match sort, the tricky thing with desktop files is that it 'PAYDAY 2' desktop file probably has steam in it a few times (in f.e. the exec field) and gets matched on that, resulting it to appear high. This can all be fine-tuned in the config (what fields to match, etc.)

**Comment by 5HT2** [comment]
Thank you for explaining!

**Comment by DaveDavenport** [comment]
I hope the 'history'/favorite feature sorts it out for you.  For me that (very quickly) on active use makes that what I use often is always the first match.
