### ISSUE TITLE
First item of custom menu selected after closing rofi menu w/out input

### ISSUE THREAD

**Issue by arilebedey** [davatorium/rofi#1561]
I know this issue probably has a very easy solution but even after searching, I could not find it..

Here is my bare-bones script: 
```
#!/bin/sh

link="Useful menu" 
ch="Chrome"

sel=$(echo "${ch}" | rofi -dmenu -p "${link}")

if [[ "${sel}" == "$ch" ]]; then
        chromium
fi
```
I am trying to find a way to cancel the menu without rofi issuing the `chromium` command.. 

I have tried passing the variable "MENU_CUSTOM_INPUT" mentioned in the commit (cited below) that closed a similar issue, but it did not work..

Also : I have added "kb-cancel: "Escape";" to the configuration portion of `config.rasi`..

Above mentioned similar issue:    
https://github.com/davatorium/rofi/issues/322#issuecomment-174425417_

**Comment by DaveDavenport** [comment]
This is a support question, not an issue, please use the discussion forum.
