### ISSUE TITLE
It's impossible to type in via virtual keyboards 

### ISSUE THREAD

**Issue by trappedinspacetime** [davatorium/rofi#1565]
### Before opening a feature request

- [X] I checked the *next* branch to see if the feature has already been implemented
- [X] I searched existing reports to see if it is already requested.

### What is the user problem or growth opportunity you want to see solved?

When I try to type in via virtual screen keyboards `rofi` disappears immediately. 

### How do you know that this problem exists today? Why is this important?

It's important for accessibility and broken keyboards.

### Who will benefit from it?

Persons who needs accessibility feature will benefit from it.

### Rofi version (rofi -v)

Version: addfc1d (next)

### Configuration

https://gist.github.com/trappedinspacetime/3eb5a619638b1ed3e1736477e58605e0

**Comment by DaveDavenport** [comment]
By default rofi closes when a mouse click happens outside the window, see your attached config:
```
/*	click-to-exit: true;*/
```
How rofi 'overlays' on the deskop, I don't expect this to work, you can try running it in 'normal-window' mode?

Can you include some information so we can try to reproduce? (what virtual keyboard/desktop/etc.)

**Comment by trappedinspacetime** [comment]
@DaveDavenport Thank you for responding. I am on Ubuntu 20.04 Mate Desktop environment. I am using `onboard` virtual keyboard. I tested your suggestion `click-to-exit: false;`, it kinda works but `rofi` overlays the VK, so it's not to possible to click some letters that `rofi` covers.
I just started to use `rofi` today, I am not aware of all the settings it has.

**Comment by DaveDavenport** [comment]
you can try to modify the theme to move rofi window up?
Try appending:
```css
window { achor: north; location: north; }
```
to your `~/.config/rofi/config.rasi`

**Comment by trappedinspacetime** [comment]
window { achor: north; location: north; }
won't obey `rofi`, it's still in the center.

**Comment by DaveDavenport** [comment]
can you pastebin your config, if you appended at the end it should work.

The command is valid and normally works fine, you can also try:
```bash
rofi -no-config -show drun -no-click-to-exit -theme-str 'window { achor: north; location: north; }'
```

**Comment by trappedinspacetime** [comment]
It's my bad, I had pasted it inside the main curly braces.
I pasted it outside of main settings and it works now. I'll move it to top left corner of the screen. 
Thank you for your help.
All the best.

**Comment by DaveDavenport** [comment]
Great it works.
