### ISSUE TITLE
[BUG] Rofi spawns on screen with mouse rather than focused screen

### ISSUE THREAD

**Issue by elParaguayo** [davatorium/rofi#1566]
### Rofi version (rofi -v)

1.7.2

### Configuration

default config and theme

### Launch command

rofi -show drun

### Step to reproduce

Focus one screen. Put mouse cursor on another screen and start rofi. 

### Expected behavior

Rofi should spawn on the focused screen.

### Actual behavior

Rofi starts on the screen with the mouse cursor.

### Additional information

This is a continuation of #1158.

I am one of the developers for qtile and I'm trying to fix this bug. I have a patch which implements `_NET_DESKTOP_VIEWPORT` but it's still not working.

With the patch in place, running `xprop -root` gives:
```
_NET_ACTIVE_WINDOW(WINDOW): window id # 0x1200002
XFree86_DDC_EDID1_RAWDATA(INTEGER) = 0, -1, -1, -1, -1, -1, -1, 0, 77, 16, 73, 20, 0, 0, 0, 0, 32, 25, 1, 4, -91, 29, 17, 120, 14, -34, 80, -93, 84, 76, -103, 38, 15, 80, 84, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 26, 54, -128, -96, 112, 56, 31, 64, 48, 32, 53, 0, 38, -91, 16, 0, 0, 24, 0, 0, 0, 16, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -2, 0, 68, 74, 67, 80, 54, -128, 76, 81, 49, 51, 51, 77, 49, 0, 0, 0, 0, 0, 2, 65, 3, 40, 0, 18, 0, 0, 11, 1, 10, 32, 32, 0, 102
_NET_CLIENT_LIST_STACKING(WINDOW): window id # 0x600002, 0x1200002
_NET_CLIENT_LIST(WINDOW): window id # 0x600002, 0x1200002
ESETROOT_PMAP_ID(PIXMAP): pixmap id # 0x800000
_XROOTPMAP_ID(PIXMAP): pixmap id # 0x800000
_NET_DESKTOP_VIEWPORT(CARDINAL) = 0, 0, 0, 0, 1920, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
_NET_CURRENT_DESKTOP(CARDINAL) = 1
_NET_DESKTOP_NAMES(UTF8_STRING) = "scratchpad", "1", "2", "3", "4", "5", "6", "7"
_NET_NUMBER_OF_DESKTOPS(CARDINAL) = 8
_NET_SUPPORTING_WM_CHECK(WINDOW): window id # 0x40011d
_NET_SUPPORTED(ATOM) = _NET_SUPPORTED, _NET_CLIENT_LIST, _NET_CLIENT_LIST_STACKING, _NET_CURRENT_DESKTOP, _NET_DESKTOP_VIEWPORT, _NET_ACTIVE_WINDOW, _NET_SUPPORTING_WM_CHECK, _NET_WM_NAME, _NET_WM_VISIBLE_NAME, _NET_WM_ICON_NAME, _NET_WM_DESKTOP, _NET_WM_WINDOW_TYPE, _NET_WM_STATE, _NET_WM_STRUT_PARTIAL, _NET_WM_PID, _NET_WM_WINDOW_TYPE_DESKTOP, _NET_WM_WINDOW_TYPE_DOCK, _NET_WM_WINDOW_TYPE_TOOLBAR, _NET_WM_WINDOW_TYPE_MENU, _NET_WM_WINDOW_TYPE_UTILITY, _NET_WM_WINDOW_TYPE_SPLASH, _NET_WM_WINDOW_TYPE_DIALOG, _NET_WM_WINDOW_TYPE_DROPDOWN_MENU, _NET_WM_WINDOW_TYPE_POPUP_MENU, _NET_WM_WINDOW_TYPE_TOOLTIP, _NET_WM_WINDOW_TYPE_NOTIFICATION, _NET_WM_WINDOW_TYPE_COMBO, _NET_WM_WINDOW_TYPE_DND, _NET_WM_WINDOW_TYPE_NORMAL, _NET_WM_STATE_MODAL, _NET_WM_STATE_STICKY, _NET_WM_STATE_MAXIMIZED_VERT, _NET_WM_STATE_MAXIMIZED_HORZ, _NET_WM_STATE_SHADED, _NET_WM_STATE_SKIP_TASKBAR, _NET_WM_STATE_SKIP_PAGER, _NET_WM_STATE_HIDDEN, _NET_WM_STATE_FULLSCREEN, _NET_WM_STATE_ABOVE, _NET_WM_STATE_BELOW, _NET_WM_STATE_DEMANDS_ATTENTION, _NET_WM_STATE_FOCUSED
RESOURCE_MANAGER(STRING) = "XTerm.vt100.faceName:\tDejaVu Sans Mono:style=Book:antialias=false\nXTerm.vt100.faceSize:\t12\nXTerm.vt100.reverseVideo:\ttrue\n"
_XKB_RULES_NAMES(STRING) = "evdev", "pc105", "gb", "", ""
XFree86_has_VT(INTEGER) = 1
XFree86_VT(INTEGER) = 2
```

Running `G_MESSAGES_DEBUG=X11Helper rofi -monitor -1 -show combi -no-config` gives:
```
(process:414264): X11Helper-DEBUG: 18:56:06.415: Query RANDR for monitor layout.
(process:414264): X11Helper-DEBUG: 18:56:06.415: Randr XCB api version: 1.6.
(process:414264): X11Helper-DEBUG: 18:56:06.416: Found randr version: 1.5
(process:414264): X11Helper-DEBUG: 18:56:06.418: Found window manager: |LG3D|
(process:414264): X11Helper-DEBUG: 18:56:10.399: Cleaning up XCB and XKB
```

Unlike #1158, there are no error messages about rofi being unable to find a viewport yet the issue persists.

Is there anything else that we need to change in qtile to ensure rofi spawns on the focused screen?

Many thanks.

**Comment by DaveDavenport** [comment]
Thanks for investing effort to get this working, its been a while. This is the current code for resolving it:


```c
else if (mon_id == -1) {
    // Get the current desktop.
    unsigned int current_desktop = 0;
    xcb_get_property_cookie_t gcdc;                                                                                                                                                           
    gcdc = xcb_ewmh_get_current_desktop(&xcb->ewmh, xcb->screen_nbr);                                                                                                                         
    if (xcb_ewmh_get_current_desktop_reply(&xcb->ewmh, gcdc, &current_desktop,                                                                                                                
                                           NULL)) {                                                                                                                                           
      xcb_get_property_cookie_t c =                                                                                                                                                           
          xcb_ewmh_get_desktop_viewport(&xcb->ewmh, xcb->screen_nbr);                                                                                                                         
      xcb_ewmh_get_desktop_viewport_reply_t vp;                                                                                                                                               
      if (xcb_ewmh_get_desktop_viewport_reply(&xcb->ewmh, c, &vp, NULL)) {                                                                                                                    
        if (current_desktop < vp.desktop_viewport_len) {                                                                                                                                      
          monitor_dimensions(vp.desktop_viewport[current_desktop].x,                                                                                                                          
                             vp.desktop_viewport[current_desktop].y, mon);                                                                                                                    
          xcb_ewmh_get_desktop_viewport_reply_wipe(&vp);                                                                                                                                      
          return TRUE;                                                                                                                                                                        
        }                                                                                                                                                                                     
        g_debug("Viewport does not exist for current desktop: %d, falling "                                                                                                                   
                "back to mouse location (-5)",                                                                                                                                                
                current_desktop);                                                                                                                                                             
        xcb_ewmh_get_desktop_viewport_reply_wipe(&vp);                                                                                                                                        
      } else {                                                                                                                                                                                
        g_debug("Failed to get viewport for current desktop: %d, falling back "                                                                                                               
                "to mouse location (-5).",                                                                                                                                                    
                current_desktop);                                                                                                                                                             
      }                                                                                                                                                                                       
    } else {
      g_debug("Failed to get current desktop, falling back to mouse location "
              "(-5).");
    }
```
so I expect it to show up at monitor located at (0,0) based on your X properties?.
What was expected to be the correct behaviour?

**Comment by elParaguayo** [comment]
In that example, the mouse is over desktop 2 which had a viewport of (1920, 0). I would have expected rofi to open on the monitor located at (0, 0) as you say but, instead, it opens on the monitor at (1920, 0).

**Comment by DaveDavenport** [comment]
If I add some extra debug information can compile git and test that?

**Comment by elParaguayo** [comment]
Yes. Very happy to.

**Comment by DaveDavenport** [comment]
added some debug to next

**Comment by DaveDavenport** [comment]
```
(process:1164434): X11Helper-DEBUG: 21:15:11.299: Monitor lookup  by name : -1
(process:1164434): X11Helper-DEBUG: 21:15:11.299: Monitor lookup  by name failed: -1
(process:1164434): X11Helper-DEBUG: 21:15:11.299: Monitor id: -1
(process:1164434): X11Helper-DEBUG: 21:15:11.299: rofi on current monitor
(process:1164434): X11Helper-DEBUG: 21:15:11.299: Found current desktop: 0
(process:1164434): X11Helper-DEBUG: 21:15:11.299: Found 11 number of desktops
(process:1164434): X11Helper-DEBUG: 21:15:11.299: Found viewport for desktop: 0 0
(process:1164434): X11Helper-DEBUG: 21:15:11.299: Found monitor @: 0 0 1920x1080
```
(will cleanup later, just for debuggin now)

**Comment by elParaguayo** [comment]
Ran it the focused screen and got this:
```
(process:425575): X11Helper-DEBUG: 20:53:48.202: Randr XCB api version: 1.6.
(process:425575): X11Helper-DEBUG: 20:53:48.203: Found randr version: 1.5
(process:425575): X11Helper-DEBUG: 20:53:48.205: Found window manager: |LG3D\xff\xff\xff\xff1|
(process:425575): X11Helper-DEBUG: 20:53:48.293: Monitor active
(process:425575): X11Helper-DEBUG: 20:53:48.293: Monitor lookup  by name : -5
(process:425575): X11Helper-DEBUG: 20:53:48.293: Monitor lookup  by name failed: -5
(process:425575): X11Helper-DEBUG: 20:53:48.293: Monitor id: -5
(process:425575): X11Helper-DEBUG: 20:53:48.298: Monitor active
(process:425575): X11Helper-DEBUG: 20:53:48.345: Monitor active
Mode drun is not enabled. I have enabled it for now.
Please consider adding drun to the list of enabled modi: modi: [window,run,ssh,drun].
(process:425575): X11Helper-DEBUG: 20:53:52.078: Cleaning up XCB and XKB
```
Move mouse onto the second screen (but focus still on the first), rofi opened on screen with mouse and got I this:
```
(process:425599): X11Helper-DEBUG: 20:53:53.033: Query RANDR for monitor layout.
(process:425599): X11Helper-DEBUG: 20:53:53.033: Randr XCB api version: 1.6.
(process:425599): X11Helper-DEBUG: 20:53:53.034: Found randr version: 1.5
(process:425599): X11Helper-DEBUG: 20:53:53.036: Found window manager: |LG3D|
(process:425599): X11Helper-DEBUG: 20:53:53.114: Monitor active
(process:425599): X11Helper-DEBUG: 20:53:53.114: Monitor lookup  by name : -5
(process:425599): X11Helper-DEBUG: 20:53:53.114: Monitor lookup  by name failed: -5
(process:425599): X11Helper-DEBUG: 20:53:53.114: Monitor id: -5
(process:425599): X11Helper-DEBUG: 20:53:53.116: Monitor active
(process:425599): X11Helper-DEBUG: 20:53:53.142: Monitor active
Mode drun is not enabled. I have enabled it for now.
Please consider adding drun to the list of enabled modi: modi: [window,run,ssh,drun].
(process:425599): X11Helper-DEBUG: 20:53:54.809: Cleaning up XCB and XKB
```

**Comment by elParaguayo** [comment]
It's not finding the viewports.

Can you paste the `xprop` output from your setup so I can compare to mine?

**Comment by DaveDavenport** [comment]
why are you doing -5?  the initial one was -1

**Comment by elParaguayo** [comment]
I didn't pass any number this time. Just ran `G_MESSAGES_DEBUG=X11Helper rofi -show drun -no-config`. I don't know where the 5 came from.

**Comment by DaveDavenport** [comment]
you are asking for different behaviour now.. please pass the -1, that has the above code + debug..

**Comment by elParaguayo** [comment]
Ah, so the default behaviour is actually to spawn rofi where the mouse is (`-5`). So, if we want to spawn on the focused screen then we need the `-1`.

Passing `-1` makes it behave as we want and it finds the viewport correctly.

I suspect I must have mucked up at the beginning and not bound the correct rofi command when moving the mouse.]

Sorry for wasting your time.

**Comment by DaveDavenport** [comment]
no problem, happy it works.

**Comment by elParaguayo** [comment]
Good news is that we can merge our viewport patch and I just need to tell the user posting the original issue that they need to use `-monitor -1` if they want rofi the currently focused screen.

**Comment by elParaguayo** [comment]
Thanks again.

EDIT: Don't lock this yet. I'll see if I can get other people to confirm it works for them.

**Comment by samtrek** [comment]
> Thanks for investing effort to get this working, its been a while. This is the current code for resolving it:
> 
> ```c
> else if (mon_id == -1) {
>     // Get the current desktop.
>     unsigned int current_desktop = 0;
>     xcb_get_property_cookie_t gcdc;                                                                                                                                                           
>     gcdc = xcb_ewmh_get_current_desktop(&xcb->ewmh, xcb->screen_nbr);                                                                                                                         
>     if (xcb_ewmh_get_current_desktop_reply(&xcb->ewmh, gcdc, &current_desktop,                                                                                                                
>                                            NULL)) {                                                                                                                                           
>       xcb_get_property_cookie_t c =                                                                                                                                                           
>           xcb_ewmh_get_desktop_viewport(&xcb->ewmh, xcb->screen_nbr);                                                                                                                         
>       xcb_ewmh_get_desktop_viewport_reply_t vp;                                                                                                                                               
>       if (xcb_ewmh_get_desktop_viewport_reply(&xcb->ewmh, c, &vp, NULL)) {                                                                                                                    
>         if (current_desktop < vp.desktop_viewport_len) {                                                                                                                                      
>           monitor_dimensions(vp.desktop_viewport[current_desktop].x,                                                                                                                          
>                              vp.desktop_viewport[current_desktop].y, mon);                                                                                                                    
>           xcb_ewmh_get_desktop_viewport_reply_wipe(&vp);                                                                                                                                      
>           return TRUE;                                                                                                                                                                        
>         }                                                                                                                                                                                     
>         g_debug("Viewport does not exist for current desktop: %d, falling "                                                                                                                   
>                 "back to mouse location (-5)",                                                                                                                                                
>                 current_desktop);                                                                                                                                                             
>         xcb_ewmh_get_desktop_viewport_reply_wipe(&vp);                                                                                                                                        
>       } else {                                                                                                                                                                                
>         g_debug("Failed to get viewport for current desktop: %d, falling back "                                                                                                               
>                 "to mouse location (-5).",                                                                                                                                                    
>                 current_desktop);                                                                                                                                                             
>       }                                                                                                                                                                                       
>     } else {
>       g_debug("Failed to get current desktop, falling back to mouse location "
>               "(-5).");
>     }
> ```
> 
> so I expect it to show up at monitor located at (0,0) based on your X properties?. What was expected to be the correct behaviour?

where will this code be place because I am facing similar issues with my dwm + rofi config

**Comment by DaveDavenport** [comment]
@samtrek Please read the guidelines and **do not highjack** a topic. This is something I strongly dislike as I cannot properly help (you have provided none of the required/asked information).  Please open a new issue *iff*  it is a rofi issue. For help setting rofi up, please use the discussion forum.

**Comment by DaveDavenport** [comment]
@elParaguayo  any feedback yet? I would like to close/lock this if it is resolved.

**Comment by elParaguayo** [comment]
@DaveDavenport - yup, all good for us. Confirmed that viewports are being respected. Another old issue of focus moving to the screen where the mouse was _after_ rofi closed is also solved.

We've pushed the viewport fix so nothing else needed from my perspective.

Thanks again.

**Comment by DaveDavenport** [comment]
Great to hear!
