### ISSUE TITLE
[REQUEST] Add round, floor and ceiling functions

### ISSUE THREAD

**Issue by 9las** [davatorium/rofi#1569]
### Before opening a feature request

- [X] I checked the *next* branch to see if the feature has already been implemented
- [X] I searched existing reports to see if it is already requested.

### What is the user problem or growth opportunity you want to see solved?

I would like to make a theme that works on monitors with different resolutions and DPI.
If I create an element with dimensions in e.g. mm or % and set its background to an image that repeats (using `background-image: url("path to image");`), then the repeated image will most likely get cropped off due to the dimensions
of the element not being an integer multiple of the dimensions of the repeated image.

I suggest that three functions get added: `round`, `floor` and `ceiling`, that works as follows:

`round(distance1, distance2)`: Round `distance1` to nearest multiple of `distance2`

`floor(distance1, distance2)`: Round `distance1` down to nearest multiple of `distance2`

`ceiling(distance1, distance2)`: Round `distance1` up to nearest multiple of `distance2`

Examples:

If `round_to_integer` is a function that rounds a float to the nearest integer, the above listed function round would work as follows:

`round(15mm, 4mm)= round_to_integer( 15mm / 4mm ) * 4mm = 4 * 4mm = 16mm`

likewise we have

`floor(15mm, 4mm) = floor_to_integer( 15mm / 4mm ) * 4mm = 3 * 4mm = 12mm`

`ceiling(15mm, 7mm) = ceiling_to_integer( 15mm / 7mm ) * 7mm = 3 * 7mm = 21mm`

The functions should also work when mixing dimensions e.g. `round(27mm, 8px)` would convert 27mm to px and then round to nearest multiple of 8px.

Likewise the functions should work with the different operations (addition, subtrarction and so on). That is something like the following should work:
`calc( round( 100% - 37px, 4px ) + 5px )`

[Here](https://github.com/w3c/csswg-drafts/issues/2513) is a relevant discussion I found, which might be usefull.

### How do you know that this problem exists today? Why is this important?

It is important if you want to make a theme that works on monitors with different resolutions and where it is necessary that the elements only take dimensions that are a multiple of a certain integer. An example could be when the element has a background image that gets repeated and you do not want the image to get cropped off.

### Who will benefit from it?

Users who want to make a theme that works with different resolutions and want to use repeating background images.

### Rofi version (rofi -v)

1.7.2

### Configuration

https://gist.github.com/9las/4a31a922ffe67c90dedfd5c1bb59cd3c

**Comment by DaveDavenport** [comment]
What is up with trying to embedded javascript.. that is very weird..

**Comment by DaveDavenport** [comment]
The feature I think is something that could be useful, I will probably add this.

**Comment by 9las** [comment]
> 

Haha that was a mistake. the link is now fixed

**Comment by 9las** [comment]
> What is up with trying to embedded javascript.. that is very weird..

Haha that was a mistake. the link is now fixed

**Comment by 9las** [comment]
> The feature I think is something that could be useful, I will probably add this.

Nice!

**Comment by DaveDavenport** [comment]
completely untested implementation in git. needs testing.
