### ISSUE TITLE
Typo in my name in 1.7.3 release notes

### ISSUE THREAD

**Issue by jirutka** [davatorium/rofi#1579]
### Rofi version (rofi -v)

1.7.3

### Configuration

https://github.com/davatorium/rofi/releases/tag/1.7.3

### Launch command

rofi

### Step to reproduce

There’s a typo in my name in the [release notes for 1.7.3](https://github.com/davatorium/rofi/releases/tag/1.7.3).

```diff
-Jiruta
+Jirutka
```

Thank you for fixing it!

### Expected behavior

.

### Actual behavior

.

**Comment by DaveDavenport** [comment]
apologies (this is why I put in a disclaimer.)
