### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by greenbourne277** [davatorium/rofi#1581]
### Rofi version (rofi -v)

Version: 1.7.3-7-ga34c13bd (makepkg)

### Configuration

https://gist.github.com/greenbourne277/5b8374e5b0c16e40076b0b49bdb6b477

### Launch command

rofi -theme PATH/TO/GISTFILE.rasi

### Step to reproduce

Run rofi command

### Expected behavior

There  was no error beforehand, so I assume it should still work.

### Actual behavior

Error message displayed:
```
The following errors were detected when starting rofi:

Failed to resolve : `inputbar { border-color: var(border); }
Failed to resolve: `element normal urgent { background-color: var(urgent);}`
There are 2 more errors
```

### Additional information

I build rofi from the AUR. Since today i get this error so I assume it's caused by the commit https://github.com/davatorium/rofi/commit/a34c13bdb2e4099b14da814e32c92a4a6a5f4261

**Comment by DaveDavenport** [comment]
Your theme is incomplete and has broken links (variables), in the past this was ignored, I now highlight the errors.

**Comment by DaveDavenport** [comment]
In the past people complained that I did not put errors/warning in the users face, so this time I did not just print it on commandline (that people ignored for years).

**Comment by greenbourne277** [comment]
I see, thanks for your explanation and fair enough :)

**Comment by DaveDavenport** [comment]
thanks!
