### ISSUE TITLE
[BUG] Modi `calc` broken

### ISSUE THREAD

**Issue by VersusF** [davatorium/rofi#1582]
### Rofi version (rofi -v)

1.7.3

### Configuration

https://github.com/svenstaro/rofi-calc/issues/82

### Launch command

rofi -show drun

### Step to reproduce

Install modi https://github.com/svenstaro/rofi-calc
Use this config:
```
configuration {
	show-icons: true;
	icon-theme: "Tela-dark";
	modi: [drun,filebrowser,run,calc];
	combi-modi: [file-browser,drun,calc];
	display-drun: "Run";
	display-calc: "Calc";
	display-run: "Exec";
	display-file-browser: "Explore";
}
@theme "theme.rasi"
```

run `rofi -show drun`

### Expected behavior

Use "calc" modi instead of having a syntax error

### Actual behavior

Prints a syntax error

### Additional information

Copied from https://github.com/svenstaro/rofi-calc/issues/82
> Hello
>     After updating to rofi 1.7.3 I get a syntax error as it expects a "(" after the calc keyword.
>     My hypotesis is that calc is a reserved word to perform calculations and it is not seen as a mode.
>     
>     Here is the configuration:
>     
>     configuration {
> 	    show-icons: true;
> 	    icon-theme: "Tela-dark";
> 	    modi: [drun,filebrowser,run,calc];
> 	    combi-modi: [file-browser,drun,calc];
> 	    display-drun: "Run";
> 	    display-calc: "Calc";
> 	    display-run: "Exec";
> 	    display-file-browser: "Explore";
>     }
>     @theme "theme.rasi"
>     
>     Let me know if you need additional info.
>     Thanks a lot!

The developer suggested me to open an issue here

**Comment by DaveDavenport** [comment]
aah good catch. calc is a keyword in rofi any other name should work.
I can see if we can fix that.

**Comment by DaveDavenport** [comment]
hmm not trivial to fix this one..

**Comment by DaveDavenport** [comment]
possible fix in git, but needs testing as the grammar parser might need to backtrack on this one and go into another branch.

**Comment by VersusF** [comment]
Hello.
Sorry for the late reply, I finally got time to test your fix and it seems to be good to me. However now a strange error appears to me:
`Failed to resolve "element alternate normal { background-color: var(alternate-normal-background); }`

From the configurations and the theme ([gist](https://gist.github.com/VersusF/eec4406390946b924b1b3c32ed49d4a7)) it seems that the dot between `alternate` and `normal` is not considered. The theme works on the stable 1.7.3 release.

Is it related to the fix?

Nevertheless, using the double quotes on the configuration file resolves the issue, so it may be enough to update the configuration docs to solve the issue. See [comment](https://github.com/svenstaro/rofi-calc/issues/82#issuecomment-1030814811).

**Comment by DaveDavenport** [comment]
no. your theme is broken, this was ignored before, causing issues with users. so now I highlight the fact the theme is broken.
It has nothing to do with '.'s in the theme.. but with the fact `alternate-normal-background` does not resolve.

**Comment by DaveDavenport** [comment]
![rofi-2022-02-06-1839-00000](https://user-images.githubusercontent.com/406245/152693588-d5d5600f-9ee9-460b-af92-720059e152ac.png)
this one is undefined, as the message sais: https://gist.github.com/VersusF/eec4406390946b924b1b3c32ed49d4a7#file-theme-rasi-L82

I've added extra clarification in the error message in git.

**Comment by VersusF** [comment]
You're right, setting the variable solves the issue. Thanks for your support. Shall i close the issue or do you prefer to have more tests?

**Comment by DaveDavenport** [comment]
if you can confirm `calc` without `"` works, I think we can close it.

**Comment by VersusF** [comment]
It works! Thanks again

**Comment by DaveDavenport** [comment]
great!, thx for the quick reaction.
