### ISSUE TITLE
[BUG] Rofi opens spotify in terminal although Terminal=false in desktop file

### ISSUE THREAD

**Issue by 3nt3** [davatorium/rofi#1591]
### Rofi version (rofi -v)

1.7.3-12-gfb1eefb2 and 1.7.3-1 from pacman

### Configuration

https://gist.github.com/3nt3/0ac4cfb3e7a987be05db7f01b9ae56c9

### Launch command

rofi -show drun

### Step to reproduce

* run `rofi -show drun`
* search for spotify
* a new terminal window (alacritty) opens in which the `spotify` command is executed

### Expected behavior

Spotify should open (like all the other applications I tested with) without opening a new terminal window

### Actual behavior

A new terminal window (alacritty) opens in which the `spotify` command is executed

### Additional information

[running rofi with strace](https://gist.github.com/3nt3/85203efc8e85b92f60d9446848af442b)

spotify.desktop:
```
[Desktop Entry]
Type=Application
Terminal=false
Name=Spotify
GenericName=Music Player
Icon=spotify-client
TryExec=spotify
Exec=spotify %U
MimeType=x-scheme-handler/spotify;
Categories=Audio;Music;Player;AudioVideo;
StartupWMClass=spotify
```

**Comment by 3nt3** [comment]
Ffs I quickly searched through the strace and found out there was an additional desktop file for spotify in my `~/.local/share/applications` that *did have* Terminal=true

**Comment by DaveDavenport** [comment]
aah good you found it :+1: .

The ~/.local/ entries have priority.
