### ISSUE TITLE
[BUG] inconsistent auto completion with arguments

### ISSUE THREAD

**Issue by dongho-jung** [davatorium/rofi#1598]
### Rofi version (rofi -v)

Version: 1.7.3

### Configuration

https://gist.github.com/0xF4D3C0D3/16da231700363d919cd34c7f47086d33

### Launch command

rofi -show run; it's been registered as shortcut Mod+d

### Step to reproduce

Mod+d; enter `foo x` to the input; rofi suggests `foo` `foo bar` `foo baz`

and then

Mod+d again; enter `foo y` to the input; rofi suggests nothing

### Expected behavior

I think it shouldn't suggest `foo`, `foo bar`, `foo baz` for the input `foo x`. 
What I was trying to do is run `google-chrome-stable --incognito`. However rofi always ignores that `--incognito` argument. So I use `execsnoop` to check how rofi interpret it. And yes it ignores --incognito and just run `google-chrome-stable`. 

BUT

if I enter `google--chrome-stable -r`, rofi runs `google-chrome-stable -r`..!

for arbitrary samples..

`google-chrome-stable -a`
`google-chrome-stable -b`
`google-chrome-stable -c`
`google-chrome-stable -e`
-> rofi runs them with the argument well

`google-chrome-stable -d`
`google-chrome-stable -f`
-> rofi suggests `google-chrome-stable` and runs them wihtout arguments D:

### Actual behavior

![image](https://user-images.githubusercontent.com/19762154/154832251-506d98be-85ff-4fab-a7ed-fdc7f1f9be4f.png)

with `--incognito` argument, it suggests `google-chrome-stable` and it runs `google-chrome-stable` not `google-chrome-stable --incognito`

but

![image](https://user-images.githubusercontent.com/19762154/154832287-db39e85d-08cf-4704-a473-b62217b5edca.png)
with `-r` argument or -g or -h but -x (I don't know the pattern at all) it suggests nothing and runs them without a problem

**Comment by DaveDavenport** [comment]
Related too #877 ?

**Comment by dongho-jung** [comment]
@DaveDavenport  oh.. yeah indeed that issue is just the same as my issue. I gotta use `ctrl+enter` or `\-\-` as a workaround.. thanks!

**Comment by DaveDavenport** [comment]
or disable the negate option (see manpage)

**Comment by dongho-jung** [comment]
I overlooked it. I re-registered it as `bindsym $mod+d exec --no-startup-id rofi -show run -matching-negate-char --`. so now I'm happy to rofi with chrome in incognito mode thanks
