### ISSUE TITLE
[REQUEST] 

### ISSUE THREAD

**Issue by Bug-Reaper** [davatorium/rofi#1604]
### Before opening a feature request

- [X] I checked the *next* branch to see if the feature has already been implemented
- [X] I searched existing reports to see if it is already requested.

### What is the user problem or growth opportunity you want to see solved?

 I want to have a rofi menu where the inputbar widget is disabled.

### How do you know that this problem exists today? Why is this important?

I have a rofi script that could benefit from disabled text filter of results. Completely ignoring alphanumeric inputs from the user.

### Who will benefit from it?

People that write menus with simple options where it's the same 2 or 3 every time and don't ever want these results filtered by text

### Rofi version (rofi -v)

Latest

### Configuration

https://gist.github.com/Bug-Reaper/a8fce52fc72f2ce6ac452c271f0b3f90

### Additional information

So you can "disable" the inputbar widget with a config change such as =>
```
inputbar { enabled: false; }
prompt { enabled: false; }
``` 
However the plug is really just hidden, not disabled as the configuration suggests. Results are still filtered by text. I believe there are valid use cases where results should never be filter-able by the user text entry.

Add a command line option called `-no-filter` and it could exist for those that want it (similar to `-no-sort`)

Or potentially upgrade => : 
```
	-matching [string]                      Set the matching algorithm. (normal, regex, glob, fuzzy, prefix)
	normal (Default)
```
Add an option called none. This effectively means the results would never be filtered away by any input user text.

**Comment by Bug-Reaper** [comment]
So I kinda was able to achieve the behavior I want with
`-matching regex` & `-filter "/*|"` & `-theme-str 'inputbar { enabled: false;}'`

Hacky AF solution tho, I think an officially supported option for this behavior is worthwhile to implement.

**Comment by DaveDavenport** [comment]
This is already supported by removing the entry widget from the theme.
