### ISSUE TITLE
[REQUEST] -keep-right for custom modes

### ISSUE THREAD

**Issue by danjenson** [davatorium/rofi#1606]
### Before opening a feature request

- [X] I checked the *next* branch to see if the feature has already been implemented
- [X] I searched existing reports to see if it is already requested.

### What is the user problem or growth opportunity you want to see solved?

I have custom scripts that search for pdfs and videos that I use in combi-mode. It would be nice to have -keep-right available in combi mode so that I can view the file names rather than the beginning of their paths (currently I extract the file name and then return a tuple of <file name, dir> so I can see the file names, but then I only see the top level of the directory).

### How do you know that this problem exists today? Why is this important?

Because I am constantly opening the wrong file when I have two files in my system with the same name.

### Who will benefit from it?

Those who use Rofi for file searching.

### Rofi version (rofi -v)

Version: 1.7.3

### Configuration

https://gist.github.com/danjenson/8f1ebeb3e0e15c42a28cf8d53d1e9ba0

**Comment by DaveDavenport** [comment]
>I have custom scripts that search for pdfs and videos that I use in combi-mode. It would be nice to have -keep-right available in combi mode so that I can view the file names rather than the beginning of their paths (currently I extract the file name and then return a tuple of <file name, dir> so I can see the file names, but then I only see the top level of the directory)

Not sure I completely follow this very long sentence.  The () part seems to suggest you want to see all the parts of the full path, but the request is to have an option that by default cut off the start? 

There is a keybinding to toggle ellipsizing on runtime.
Is this not sufficient?  

the ellipsizing is mode independent. So a  'generic' keep right would ellipsize everything to right. I think toggling at runtime is more logic.

> It would be nice to have -keep-right available in combi mode so that I can view the file names rather than the beginning of their paths 

Maybe display only the information to what you want to see?  if you want to filter on more then visible, you can add it as a hidden search field, see `man rofi-script`.
If you need the full path when accepted, you can also pass this along, see `man rofi-script`.

The request to me feels like a work-around.

**Comment by danjenson** [comment]
In sum, when I use combi-mode, I'd like everything that yields paths to be ellipsized on the left, so I only see the file name and maybe a parent directory. Alt+. is an awkward key combo, especially since I'm using a special kinesis advantage keyboard. I'll look into searching on hidden text. It seems like a good solution for paths is a common request though

**Comment by DaveDavenport** [comment]
you can re-bind any of the keybindings, see  `man rofi-keys`.

**Comment by DaveDavenport** [comment]
> It seems like a good solution for paths is a common request though

What do you mean with this?

**Comment by DaveDavenport** [comment]
To summarize, I think the solution I proposed still is the right solution.

**Only display the information that is relevant to the user.**

Instead of adding weird niche options to ´hide' part of the information, please put some smartness in the script.

If you need more information for the next execution of the script, you can pass this along.
See `man rofi-script` for the **meta** and the **info** option.

Closing.
