### ISSUE TITLE
[REQUEST] Escape UTF-16 characters in *.rasi config files

### ISSUE THREAD

**Issue by arielnmz** [davatorium/rofi#1612]
### Before opening a feature request

- [X] I checked the *next* branch to see if the feature has already been implemented
- [X] I searched existing reports to see if it is already requested.

### What is the user problem or growth opportunity you want to see solved?

I'm using the material design icons webfont in my system and I'd like to use a character instead of the default display name for the combi mode:

```
display-name: "󰍉";
```

I can copy-paste the character just fine but it'd be good if one could also just input the appropriate character code point:

```
display-name: "\00F0349";
```

### How do you know that this problem exists today? Why is this important?

I've tried to use a character code

### Who will benefit from it?

People using icon fonts

### Rofi version (rofi -v)

1.7.3

### Configuration

https://gist.github.com/arielnmz/ac0a7aa0dac827324e0837738a52819b

**Comment by DaveDavenport** [comment]
I can enter utf-8 code points in almost every entry box/editor.
ctrl-shift-u 1f40E   gives me 🐎.
For the effort it would  take, the changing/breaking of the config format . I don't directly see the benefit.

**Comment by arielnmz** [comment]
Well I actually just wanted to know if it was possible, this seems to be something you'd find in most languages/formats and I thought it used a slightly tweaked *CSS parser...

**Comment by DaveDavenport** [comment]
If you just wanted to know if it was possible,why make a feature request.
There is a discussion forum for asking questions.
