### ISSUE TITLE
[BUG] Swap ctrl-w and ctrl-backspace keybinds

### ISSUE THREAD

**Issue by UnkwUsr** [davatorium/rofi#1615]
### Rofi version (rofi -v)

Version: 1.7.3

### Configuration

https://gist.github.com/UnkwUsr/91b5aa185ed55573d084f71d2bb269d2

### Launch command

rofi -show drun

### Step to reproduce

1. Type a few words, for example: `asd zxcv fhrt lpqw`
2. Press `Ctrl-w`

### Expected behavior

Only last word should be deleted, like if we press `Ctrl-backspace` on second step. Resulting line should be `asd zxcv fhrt`.

(`lpqw` deleted)

### Actual behavior

Whole line deleted.

### Additional information

I have found that at this time default binds is:
https://github.com/davatorium/rofi/blob/2cc21909f5ebc6b7fab59c11aeb6c2ed848d3540/source/keyb.c#L55-L57
https://github.com/davatorium/rofi/blob/2cc21909f5ebc6b7fab59c11aeb6c2ed848d3540/source/keyb.c#L83-L85
And i think they should be swapped. Why? Because in many programs that have emacs-like shortcuts (for example bash or zsh), default behavior is `kb-remove-word-back` for `ctrl-w`.

I'm not actually emacs-user (I'm vimmer, ha-ha:D), so maybe I don't know some other things about this shortcuts? Anyway, it should be discussed.

**Comment by DaveDavenport** [comment]
>  Anyway, it should be discussed.

is the discussion section then not a better place?

**Comment by DaveDavenport** [comment]
http://www.rgrjr.com/emacs/emacs_cheat.html

I am not a emacs user either, I think I was told the current bindings where the right ones. 

I am hesitating to fix the current 'defaults' as it always causes shit load of complaints.  You can easily modify this yourself in the config file.

**Comment by UnkwUsr** [comment]
> I am hesitating to fix the current 'defaults' as it always causes shit load of complaints. You can easily modify this yourself in the config file.

I got you. Thanks for the answer!
