### ISSUE TITLE
[REQUEST] Load themes from XDG_DATA_DIRS

### ISSUE THREAD

**Issue by sagikazarmark** [davatorium/rofi#1617]
### Before opening a feature request

- [X] I checked the *next* branch to see if the feature has already been implemented
- [X] I searched existing reports to see if it is already requested.

### What is the user problem or growth opportunity you want to see solved?

When  installing themes as packages (using OS package manager), packages might not always end up  in /usr (eg. in case of NixOS). As a result, Rofi won't find themes installed as packages.

By adding XDG_DATA_DIRS to the list of search paths (install dir, XDG_DATA_DIRS, XDG_DATA_HOME, XDG_CONFIG_HOME), Rofi could find themes in other (standard) locations.

### How do you know that this problem exists today? Why is this important?

Tried to install themes using Nix and they are not discovered. Also checked the relevant code.

### Who will benefit from it?

NixOS users will certainly will benefit, but anyone else who installs software in non-standard locations would also benefit.

### Rofi version (rofi -v)

1.7.3

### Configuration

N/A

### Additional information

As far as I understood, it should be added above this line: https://github.com/davatorium/rofi/blob/eff3b86c944c192c036ecebcec504f9f30d24fdf/source/helper.c#L1095

**Comment by DaveDavenport** [comment]
This was not done as themes might not be backwards compatible. So if you have multiple versions of rofi installed (f.e. in /usr from dist and /usr/local by hand) it should find the matching themes of the install, not all.

**Comment by sagikazarmark** [comment]
I see. Well, that should really up to be the package manager, isn't it? I mean most package managers can handle conflicts.

But I understand that not all installations might happen via a package manager.

How about an optional setting then (eg. env var) that either enables searching in XDG_DATA_DIRS or accepts a list of additional paths to search in?

> This was not done as themes might not be backwards compatible.

On that note: is there a test command in rofi to make sure a given theme is compatible with it? It would help build scripts/CI determine if a set of themes can be packaged for a specific rofi version.

**Comment by DaveDavenport** [comment]
The themes seem to be stabilizing after we moved to the new engine a few years back and deprecating the old format.
Maybe we do not need to do this anymore.

(rofi -rasi-validate exists, but only check if it parses.)

**Comment by sagikazarmark** [comment]
Do you want me to draft a PR adding XDG_DATA_DIRS to the search paths?

> rofi -rasi-validate exists, but only check if it parses

Is there anything else necessary to ensure the theme is valid and will work?

**Comment by DaveDavenport** [comment]
Currently i don't think so, the major changes are done.  its now more adding features (like tab-stop) and the language constructs for it. so the -rasi-validate should be sufficient.

**Comment by DaveDavenport** [comment]
I think that should do it?

**Comment by sagikazarmark** [comment]
Looks good, thanks!

I'll give it a try later.

**Comment by DaveDavenport** [comment]
Did it work?

**Comment by sagikazarmark** [comment]
Yeah, it worked.

**Comment by DaveDavenport** [comment]
thanks.
