### ISSUE TITLE
[BUG] cannot get the ROFI_DATA

### ISSUE THREAD

**Issue by sunn4room** [davatorium/rofi#1625]
### Rofi version (rofi -v)

1.7.3

### Configuration

no configuration

### Launch command

rofi -modi "example:./Examples/test_script_env.sh" -show example

### Step to reproduce

no step

### Expected behavior

no

### Actual behavior

no

### Additional information

my enviroment:
- system: manjaro i3
- linux: 5.15.32
- shell: zsh

**Comment by DaveDavenport** [comment]
No information provided, just replied no everywhere.   The example script works fine for me in git (just tested), but if you cannot be bothered to actually try to explain, I cannot fix it.
