### ISSUE TITLE
[REQUEST] drun Additional applications actions

### ISSUE THREAD

**Issue by nobodyatandnothing** [davatorium/rofi#1629]
### Before opening a feature request

- [X] I checked the *next* branch to see if the feature has already been implemented
- [X] I searched existing reports to see if it is already requested.

### What is the user problem or growth opportunity you want to see solved?

conformance to XDG Desktop Entry Specification (Extra Actions in particular)
https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-1.1.html#extra-actions

### How do you know that this problem exists today? Why is this important?

this enables applications to specify additional ways to invoke it.
for example firefox specifies these additional actions
```
[Desktop Action new-window]
Name=New Window
Exec=/usr/lib/firefox/firefox --new-window %u
```
```
[Desktop Action new-private-window]
Name=New Private Window
Exec=/usr/lib/firefox/firefox --private-window %u
```

### Who will benefit from it?

those who benifit from drun

### Rofi version (rofi -v)

Version: 1.7.0-33-ga97ba40b (makepkg)

### Configuration

https://gist.github.com/nobodyatandnothing/37057275dc78227d7d68ea7cb8be82a8

### Additional information

[sway-luancher-desktop](https://github.com/Biont/sway-launcher-desktop) partialy implements this

although i once saw a launcher that implemented it as a dropdown menu of the containing applications menu entry

**Comment by DaveDavenport** [comment]
https://github.com/davatorium/rofi/issues/836

**Comment by DaveDavenport** [comment]
Why did you check the first two checkboxes?  you clearly did not.

**Comment by DaveDavenport** [comment]
The version you report:
```
Version: 1.7.0-33-ga97ba40b (makepkg)
```
does not exist, but 1.7.0 includes support for showing additional application actions. See the manpage!

**Comment by DaveDavenport** [comment]
Can you please answer my question, it might help me improve the issue reporting process.

**Comment by nobodyatandnothing** [comment]
im using a modified version built for my specific distro.
i searched for it in the issues but i did not find it.
i did not see it in the changelogs.

i did find it in the manpage though, when you mentioned it.

**Comment by DaveDavenport** [comment]
Thanks. 

The modified version is something your distro does, and could be potential problematic for bugs (as I don´t know what code/patches/etc are being used because the commit hash does not exist). But that is an distribution issue (what are you running?)

Weird that it did not show up in search, I tried several variants and it did always show up. regrettable there is little I can do about this, as it is githubs interface.

It is indeed missing in the changelog, that is an oversight. My apologies.
