### ISSUE TITLE
[REQUEST] fallback icons for each mode

### ISSUE THREAD

**Issue by acheronfail** [davatorium/rofi#1633]
### Before opening a feature request

- [X] I checked the *next* branch to see if the feature has already been implemented
- [X] I searched existing reports to see if it is already requested.

### What is the user problem or growth opportunity you want to see solved?

I'd love for there to be a way to add fallback icons for each mode, not just for the `drun` mode!

There's the configuration option:
```
configuration {
	application-fallback-icon: "/path/to/icon";
}
```

This is great! But, I would really love a way to be able to add fallback/default icons to other modes, such as `ssh` or custom modes such as [`emoji`](https://github.com/Mange/rofi-emoji).

### How do you know that this problem exists today? Why is this important?

If you run `rofi` with `show-icons: true` in any mode which doesn't have icons, there's a gap at the start of each element.

Only the `drun`, `run` and `window` modes have icon support (either natively with rofi, or via `application-fallback-icon`). If these modes are used together with any other mode (ie: `ssh` or custom modes) the interface appears to be missing icons, or at least has some unsightly gaps in the UI where there are no icons.

### Who will benefit from it?

Primarily me! :laughing: 

But also any users who want icons and are using `combi` modes with modes other than the `run`, `drun` and `window` modes (which support icons).

### Rofi version (rofi -v)

Version: 1.7.3

### Configuration

https://gist.github.com/acheronfail/fa105b2774b69289be1e7a3e1279f5d7

**Comment by DaveDavenport** [comment]
implemented.

**Comment by acheronfail** [comment]
It works perfectly, and looks beautiful! Thank you so much, and thanks for doing it so quickly. :)
