### ISSUE TITLE
[REQUEST] Runtime switches for css elements 

### ISSUE THREAD

**Issue by ruanformigoni** [davatorium/rofi#1641]
### Before opening a feature request

- [X] I checked the *next* branch to see if the feature has already been implemented
- [X] I searched existing reports to see if it is already requested.

### What is the user problem or growth opportunity you want to see solved?

Hability to update/change the background color/image dynamically.

This could be based on directives passed through elements of a list. Where one could pass itens to rofi as:
```
item 1 /* rofi: background-color: blue; */
item 2 /* rofi: background-color: yellow; */
item 3 /* rofi: background-color: green; */
```

Or it could be also implemented through simple string matching. Where one could pass itens to rofi as:

```
item 1
item 2
item 3
```
and the matches could be specified  in `config.rasi` as:
```
background-match: "item 1" blue;
background-match: "item 2" yellow;
background-match: "item 3" green;
```
This second method is more limited, since all the possible colors for each entry needs to be known before hand.

### How do you know that this problem exists today? Why is this important?

Sample use cases:

- A music player widget, where the user would scroll through the list and see the cover art of each track.
- A file search widget with a preview panel.

### Who will benefit from it?

Everyone who needs a simple dynamic interface without the need to code it from scratch in gtk, qt, etc.

### Rofi version (rofi -v)

1.7.3

### Configuration

https://gist.github.com/ruanformigoni/7acfae726d640d4bff93fb7f0259bf28

**Comment by DaveDavenport** [comment]
What about? https://git.sr.ht/~qball/rofi/commit/fb1840bd06b4abb3af5845749cb33f7df797006c#Examples/test_script_mode_color.sh

**Comment by ruanformigoni** [comment]
> What about? https://git.sr.ht/~qball/rofi/commit/fb1840bd06b4abb3af5845749cb33f7df797006c#Examples/test_script_mode_color.sh

Thanks a lot for the reply! The mentioned script does not seem to be working for me, the colors do not change. I tested with 1.7.3 and trunk.

**Comment by DaveDavenport** [comment]
I linked to the branch/commit you need to run.

**Comment by ruanformigoni** [comment]
> I linked to the branch/commit you need to run.

It worked! It was a mistake on my side :) Is there a way for this behavior to occur on change selection (without choosing an option, just hovering) ?

**Comment by DaveDavenport** [comment]
No, changes are limited to runs of the script.
If you need that flexibility, I don't think rofi is the tool for you, you need a toolkit. (like eww)

**Comment by DaveDavenport** [comment]
This is not merged yet, and I need to evaluate if this does not causes to much of a 'abuse' point that can break rofi.

**Comment by ruanformigoni** [comment]
> This is not merged yet, and I need to evaluate if this does not causes to much of a 'abuse' point that can break rofi.

Ok, thanks!

**Comment by DaveDavenport** [comment]
this been merged on main branch.
