### ISSUE TITLE
[BUG]  Can't type in rofi box.

### ISSUE THREAD

**Issue by vikomen** [davatorium/rofi#1648]
### Rofi version (rofi -v)

Version 1.7.1

### Configuration

Default

### Launch command

rofi -show window

### Step to reproduce

I should say this is on Ubuntu 22.

I have a blank version of rofi and here are the steps required:
https://www.youtube.com/watch?v=7Cl2LOCHhhk

### Expected behavior

I should be able to type in the rofi box directly. Moreover, I can't even select that window without alt tabing

### Actual behavior

I am typing in the terminal instead of in rofi.

**Comment by DaveDavenport** [comment]
wayland or Xorg?

**Comment by vikomen** [comment]
I believe it is Wayland.

**Comment by DaveDavenport** [comment]
thanks.

**Comment by DaveDavenport** [comment]
See this line that was bold and highlighted when reporting the issue:

Please do not submit reports related to wayland, see [here](https://github.com/DaveDavenport/rofi/wiki/Wayland) for more information.

**Comment by vikomen** [comment]
Hi, I now understand what the issue is. Thank you.

**Comment by DaveDavenport** [comment]
Please try the fork, it might work.

https://github.com/lbonn/rofi
