### ISSUE TITLE
[BUG] Custom keybindings don't work in combi modi

### ISSUE THREAD

**Issue by Dartegnian** [davatorium/rofi#1650]
### Rofi version (rofi -v)

Version: 1.7.3

### Configuration

https://gist.github.com/Dartegnian/634d9d5e0b0e2f40c211d696763eb376

### Launch command

rofi -show combi -combi-modi "drun" -combi-hide-mode-prefix -theme $XDG_CONFIG_HOME/rofi/rofi-metro/start-screen.rasi

### Step to reproduce

* Make start-screen.sh executable
* Click any tile
* Rofi returns no exit code

### Expected behavior

Rofi should return an exit code variable and the programs should launch. Additionally, the combi should show programs from `drun`.

kb-custom-1 should run Thunderbird
kb-custom-2 should run Firefox
kb-custom-3 should run Steam
kb-custom-4 should run Discord
kb-custom-5 should run mpv

### Actual behavior

✅ Rofi shows items from drun
❎ Clicking on the custom widgets/tiles launches the programs

Click on the tiles doesn't exit rofi and no exit code can be found other than 0.

### Additional information

The full theme can be found in: https://github.com/Dartegnian/rofi-metro.

**Comment by DaveDavenport** [comment]
This is very confusing and not how rofi is intended to work.

```bash
#!/usr/bin/env bash

theme_location=$XDG_CONFIG_HOME/rofi/rofi-metro/start-screen.rasi
echo "" | rofi -theme $theme_location -show combi -combi-modi "drun" -combi-hide-mode-prefix
exit_code="$?"
echo $exit_code

case "$exit_code" in
    10)
        coproc ( thunderbird > /dev/null  2>&1 )
        ;;
    11)
        coproc ( firefox http:// > /dev/null  2>&1 )
        ;;
    12)
        coproc ( steam > /dev/null  2>&1 )
        ;;
    13)
        coproc ( discord > /dev/null  2>&1 )
        ;;
    14)
        coproc ( mpv > /dev/null  2>&1 )
        ;;
    *)
        ;;
esac
```
This is just wrong.
1. Combi mode only has one combined mode, so why use combi mode.
2. Rofi normally does not read anything from stdin.  Only in dmenu mode.
3. The  return value rofi returns is its status. It returns 0 when successfull,  !0 when there is an error.  EXCEPT for dmenu mode.
4. -kb-custom-X bindings in normal mode are bound to switch between modes.
5. rofi is not a toolkit, use something like [eww](https://github.com/elkowar/eww) if you want to build a custom interface. 

I have no idea what you are trying to do, but this is not the way.

**Comment by DaveDavenport** [comment]
```css
    background-image: url ("(null)");
```
this is just wrong.  Rofi does not know "(null)" and will try to look that up as an image..

**Comment by Dartegnian** [comment]
> ```css
>     background-image: url ("(null)");
> ```
> 
> this is just wrong. Rofi does not know "(null)" and will try to look that up as an image..

The image used here is just `user-photo: url("/usr/share/sddm/faces/USERNAME.face.icon", both);`. It just shows the SDDM image for my user. It works and isn't really related to the issue.

**Comment by DaveDavenport** [comment]
That does not make it more or less invalid.   Excuse me for pointing out errors in the provided files I am expected to use for validating this issue. 
Locking now, this is not getting us anywhere.
