### ISSUE TITLE
[BUG] Firefox freezes when launched from rofi

### ISSUE THREAD

**Issue by Sahnvour** [davatorium/rofi#1652]
### Rofi version (rofi -v)

1.7.3

### Configuration

https://gist.github.com/Sahnvour/78aec8a031fc951178d97b49719e1cea

### Launch command

rofi -combi-modi drun,ssh -show combi

### Step to reproduce

* open rofi
* type `firefox` and select it
* use firefox/wait for it to freeze

### Expected behavior

I can launch firefox from rofi and use it without issues.

### Actual behavior

When I launch firefox from rofi, it will always end up in some sort of freeze.
Usually it's shortly after launch but sometimes it works fine for tens of minutes.

Eventually, firefox will "freeze", most of its rendering not working anymore. If an audio/video stream is playing, sound is still functional. Window can't be moved/closed via the usual i3 keybind, I need to kill the process another way.

I don't have any issue when launching firefox from a terminal or dmenu.

### Additional information

Using i3 on arch linux x64.
rofi is launched as: `bindsym $mod+d exec --no-startup-id "rofi -combi-modi drun,ssh -show combi"`

The issue is not new, but wasn't always there on my system, up to one point it worked flawlessly. However I didn't notice it right away and don't know if it was tied to a rofi update.

**Comment by DaveDavenport** [comment]
works perfectly fine for me.  Rofi just normally launches programs, I am not sure how rofi in particular causes this.
I would need a lot more information.

I would check the environment , there is a difference often launching from a terminal (that loads a new shell and sets up an evironment) and from rofi (that inherits i3).

You can also try change how rofi launches the application and launch it via bash.

(given this is the first time I ever heard of this, I suspect it is specific to your setup).

**Comment by DaveDavenport** [comment]
I asked several other users and nobody seen this issue.
Also no more information is provided, so closing.
