### ISSUE TITLE
[BUG] Nonsense symbols for all keyboard keys for czech keyboard layout, not possible to write to rofi.

### ISSUE THREAD

**Issue by raven2cz** [davatorium/rofi#1655]
### Rofi version (rofi -v)

Version: 1.7.3

### Configuration

https://gist.github.com/raven2cz/0f4189f4359ddf48009314ea14e468ac

### Launch command

rofi -show-icons -modi windowcd,window,drun -show drun

### Step to reproduce

* Change to czech keyboard layout, or cz (qwerty)
* Run Rofi standard -show run, any causes the problem
* Start typing to search field. All letters are nonsense, see attached screenshot.
* This started before around month back from this issue creation. It was ok before. Just rofi has this problem. All next apps and OS is ok.

![rofi-czech-keyboard](https://user-images.githubusercontent.com/20504243/178436431-b5645e38-4a81-4d94-951b-a02e351395b0.jpg)

### Expected behavior

Normal letters of keyboard will be used, not nonsense symbols.

### Actual behavior

Nonsense symbols are used instead of keyboard letters.

### Additional information

It works all time. It stopped working around 1 month back from creation time of this issue.

System: Arch Linux.

**Comment by DaveDavenport** [comment]
Duplicate of: https://github.com/davatorium/rofi/issues/1642?

**Comment by raven2cz** [comment]
Not exactly, I don't use AltGr in keybinding for change keyboard layout. Just standard left alt+shift. I can confirm that these symbols are identical as pressed AltGr with keyboard keys. But the AltGr is not present anywhere in the testcase. 

In analysis time of this issue, it is important to say that it is not dependent on AltGr directly. But some how the AltGr modifier is internally set active (somewhere).

**Comment by sproott** [comment]
I think it is a duplicate. In the mentioned issue, the problem is the same, but for the Finnish layout vs. the Czech one. I have the same problem with the Czech layout, but the [mentioned fix](https://github.com/davatorium/rofi/issues/1642#issuecomment-1149853370) works for me. So I think the issue is either completely on xkeyboard-config's side, or some API changes to xkeyboard-config broke the way rofi gets keyboard input.

**Comment by raven2cz** [comment]
Ok. Thanks for solution!

**Comment by DaveDavenport** [comment]
I regrettable don't have a system to produce it on, and no time to set one up so I haven't been able to debug this further.
