### ISSUE TITLE
[FEATURE] Change mode switcher buttons text

### ISSUE THREAD

**Issue by AlecsFerra** [davatorium/rofi#1656]
### Before opening a feature request

- [X] I checked the *next* branch to see if the feature has already been implemented
- [x] I searched existing reports to see if it is already requested.

### What is the user problem or growth opportunity you want to see solved?

A user should be ave to rename the displayed text in the mode switcher buttons

![image](https://user-images.githubusercontent.com/35380179/179039948-c3edf3a2-9e04-4e85-8f3c-2ca63799ee08.png)

### How do you know that this problem exists today? Why is this important?

I searched everywhere but I found nothing

### Who will benefit from it?

??

### Rofi version (rofi -v)

Version: 1.7.3

### Configuration

https://gist.github.com/AlecsFerra/5a63036449316a3d8e609b965088d87c

**Comment by DaveDavenport** [comment]
Not sure why you file this report, wait 1/2 an hour then ask on irc if this is possible. Seems to be the wrong order.

Yes, this is supported. See [man rofi]( https://github.com/davatorium/rofi/blob/1.7.3/doc/rofi.1.markdown#other) at the `-display-{mode}` option.
