### ISSUE TITLE
File finder: Can't open file pressing key Enter

### ISSUE THREAD

**Issue by Everest10** [davatorium/rofi#1658]
### Rofi version (rofi -v)

1.7.3

### Configuration

https://gist.github.com/Everest10/28bb90946d7a297fdeb8aa9f708947ab

### Launch command

rofi -show find -modi find:~/.local/share/rofi/finder.sh

### Step to reproduce

I run rofi -show find -modi find:~/.local/share/rofi/finder.sh and the rofi can find the file in your window search but when I press enter to open the file nothing happen. How to fix it ?

Distro: Fedora 36
WM: IceWM
Rofi: 1.7.3

I noticed this issue in the terminal ...

❯ rofi -show find -modi find:~/.local/share/rofi/finder.sh
xkbcommon: ERROR: /home/dom/.XCompose:4:14: unrecognized keysym "Ç" on left-hand side

.XCompose content ... (necessary to portuguese-br keyboard)
include "%L"

<dead_acute> : "ç" ccedilla
<dead_acute> <Ç> : "Ç" ccedilla

but without the .XCompose file the same error happen, can't open the file pressing key enter.

### Expected behavior

After find file open pressing Enter

### Actual behavior

After find file can't open pressing Enter. nothing happen.

**Comment by DaveDavenport** [comment]
This is not a rofi bug, but a meta question about two non-rofi things:
1.) ask how a unknown unprovided script works?
2.) a (not provided) broken .Xcompose file where xkbcommon (not rofi) tells you what is wrong in error mesg.
