### ISSUE TITLE
[REQUEST] Publish rofi in Homebrew

### ISSUE THREAD

**Issue by trey-pindrop** [davatorium/rofi#1672]
### Before opening a feature request

- [X] I checked the *next* branch to see if the feature has already been implemented
- [X] I searched existing reports to see if it is already requested.

### What is the user problem or growth opportunity you want to see solved?

The MacPorts mirrors are consistently broken, and I have been unable to install rofi on macOS because of it.

### How do you know that this problem exists today? Why is this important?

I have been completely unable to `port selfupdate` MacPorts, which I had not done until I tried to install rofi.  I can't get to the point where I have the latest ports list, because all the MacPorts mirrors appear to have invalid/broken signatures for every file downloaded.

### Who will benefit from it?

macOS users who have a working installation of [Homebrew](https://brew.sh).  MacPorts is horribly broken at the moment, [and this seems to be a common occurrence](https://trac.macports.org/ticket/49233) (first hit when searching the error in Google).

### Rofi version (rofi -v)

N/A I don't have rofi installed

### Configuration

N/A I don't have rofi installed

### Additional information

If publishing to Homebrew is not possible, consider posting the build instructions for macOS in the README.md.

**Comment by DaveDavenport** [comment]
I don't do packaging for distributions.

**Comment by DaveDavenport** [comment]
See https://github.com/davatorium/rofi/issues/1329
and https://github.com/davatorium/rofi/issues/1624

**Comment by trey-pindrop** [comment]
@DaveDavenport  Who provided the MacPorts build you mentioned?  Perhaps they can post the instructions for building rofi on macOS?

**Comment by DaveDavenport** [comment]
did I? I think I only mentioned in releasenotes that building on mac was fixed.

**Comment by DaveDavenport** [comment]
Wasn't me: https://github.com/davatorium/rofi/commit/eb494ddc7b7ee0160cd7067a26e0863c23c5ab48

I have no hardware to test, so I assumed this was fixed.

**Comment by DaveDavenport** [comment]
@sainnhe can you answer?

**Comment by sainnhe** [comment]
I don't use homebrew so I can't package for it.

But if anyone would like to create a package for rofi, you can refer to the Portfile and the patches here: https://github.com/macports/macports-ports/pull/15503/files

The patches can be remove in next release since https://github.com/davatorium/rofi/pull/1662 has been merged.

**Comment by trey-pindrop** [comment]
Thanks!  I was able to build the 'next' branch of rofi using the meson/ninja 
method.  Now I get to play with it to see if I can get it to behave properly.

Cheers!
