### ISSUE TITLE
[BUG] some icons are not displayed

### ISSUE THREAD

**Issue by 0rtz** [davatorium/rofi#1673]
### Rofi version (rofi -v)

Version: 1.7.3

### Configuration

https://gist.github.com/0xRZ/474bee86f881af5895f765397b9a3734

### Launch command

rofi -combi-modi drun -show drun -show-icons

### Step to reproduce

* run launch command

### Expected behavior

all icons are shown

### Actual behavior

some icons are not shown
![Screenshot from 2022-08-09 19-26-13](https://user-images.githubusercontent.com/46892933/183706295-caeed99e-f0a3-4192-8195-4ecb494c935c.png)

### Additional information

I use arch linux and I have `Adwaita` and `hicolor` icon themes (which is used by default as i understood) installed in `/usr/share/icons` and icons for the missing apps, e.g `Character map` or `picom` exist there. Still they are not shown in rofi

**Comment by DaveDavenport** [comment]
@sardemff7 is Adwaita used as default theme?

I cannot reproduce this, for me they both show up fine.

Can you run:

```bash
G_MESSAGES_DEBUG=Helpers.IconFetcher rofi -combi-modi drun -show drun -show-icons
```

and pastebin the debug output it spits out.

**Comment by DaveDavenport** [comment]
Second can you try telling rofi to use an icon theme (`-icon-theme`).

**Comment by 0rtz** [comment]
Log when run with `G_MESSAGES_DEBUG=Helpers.IconFetcher` :
https://gist.github.com/0xRZ/a5d87bfcad633733e6c628f400fcaef7
If I run with `-icon-theme "Adwaita"` log is the same.

I also have `Papirus` icon theme and when I specify it, every icon is shown succesfully:
https://gist.github.com/0xRZ/72862f31decad379c8d2c4555175c092

**Comment by DaveDavenport** [comment]
i see accessories-character-map is called `accessories-character-map-symbolic.symbolic.png` in Adwaita. I suspect that might not resolve. The icon is in the legacy map, but I have no idea what the standard says about that.
I see other themes do provide icons for `accessories-character-map`.

@sardemff7 Do you know how it works with this symbolic/legacy stuff?

**Comment by DaveDavenport** [comment]
@0xRZ   can you get the output of  `locate accessories-character-map | grep Adwaita`

**Comment by 0rtz** [comment]
@DaveDavenport 
```
❯ locate accessories-character-map | grep Adwaita
/usr/share/icons/Adwaita/16x16/legacy/accessories-character-map-symbolic.symbolic.png
/usr/share/icons/Adwaita/24x24/legacy/accessories-character-map-symbolic.symbolic.png
/usr/share/icons/Adwaita/32x32/legacy/accessories-character-map-symbolic.symbolic.png
/usr/share/icons/Adwaita/48x48/legacy/accessories-character-map-symbolic.symbolic.png
/usr/share/icons/Adwaita/64x64/legacy/accessories-character-map-symbolic.symbolic.png
/usr/share/icons/Adwaita/96x96/legacy/accessories-character-map-symbolic.symbolic.png
/usr/share/icons/Adwaita/scalable/legacy/accessories-character-map-symbolic.svg
```

**Comment by DaveDavenport** [comment]
ok, so there is no icon that matches in adwaita according to the spec: https://specifications.freedesktop.org/icon-theme-spec/icon-theme-spec-latest.html
My hicolor also does not ship an icon for it.

**Comment by 0rtz** [comment]
Icon names with `symbolic` suffix are not handled right? So it is just Adwaita specific problem?

**Comment by DaveDavenport** [comment]
I don't see anything in the spec about it.

**Comment by 0rtz** [comment]
Ok, i specified `gtk-icon-theme-name = Papirus` in `.config/gtk-3.0/settings.ini` and rofi seems to take Papirus icons for the ones that miss in Adwaita. Will close the issue then

**Comment by sardemff7** [comment]
IIRC, symbolics icons are to be used explicitly  
The spec (and my implementation) will fallback to the non-symbolic gracefully if missing, but it won’t search for a symbolic icon when the non-symbolic is asked for  

There is no default theme (except the spec-mandated `hicolor` fallback) but I do check GNOME settings under GNOME, KDE settings under KDE, and GTK (4 and 3) settings in search for a user-chosen theme

If a lookup function with multiple names is wanted I can see how to implement it (the sound file lookup has something like that due to the spec but I’m not sure I’d fit here, I need to recheck the algorithm)
