### ISSUE TITLE
[BUG] rofi-dmenu behaving incorrect when pre-selecting entry

### ISSUE THREAD

**Issue by bfkss** [davatorium/rofi#1679]
### Rofi version (rofi -v)

1.7.4

### Configuration

https://gist.github.com/bfkss/c8326532ecc65c886ec629ad886b041b

### Launch command

echo "a|b|c|d" | rofi -sep "|" -dmenu -select "b" -no-config

### Step to reproduce

* execute `echo "a|b|c|d" | rofi -sep "|" -dmenu -no-config` for desired behavior
* add `-select "b"` and execute again for faulty behavior

### Expected behavior

Menu with entries
* a
* b
* c
* d

When selecting any entry it should return just that char.

### Actual behavior

Menu with entries:
* a|
* b|
* c|
* d

When selecting an entry, the return value contains the separator.

**Comment by DaveDavenport** [comment]
Interesting. can reproduce.

**Comment by bfkss** [comment]
@DaveDavenport what information is missing to make the report incomplete? I'm happy to provide any information

**Comment by DaveDavenport** [comment]
A title to the issue, this makes it hard for people to find.

**Comment by bfkss** [comment]
@DaveDavenport oh wow. One sec^^

**Comment by DaveDavenport** [comment]
Why wow?

**Comment by bfkss** [comment]
that I missed the title... my bad

**Comment by DaveDavenport** [comment]
btw. the issue is not with pre-select, but with sync mode.

**Comment by bfkss** [comment]
that was fast. thank you :)

**Comment by DaveDavenport** [comment]
easy fix,  but without many beta testers  I need to run a release before we find them :(.

**Comment by bfkss** [comment]
I wouldn't mind running beta software for you
