### ISSUE TITLE
[BUG] Slow input ends up being read as if with `-sync`

### ISSUE THREAD

**Issue by 7c6f434c** [davatorium/rofi#1680]
### Rofi version (rofi -v)

1.7.4; 1.7.4.dev rev 78d596dc535d2a6ecba873071fa4a3edd4062b84

### Configuration

https://gist.github.com/7c6f434c/8f7082e8232a98c9cab2eaf310062756

### Launch command

rofi -dmenu

### Step to reproduce

```
for i in $(seq 500); do
  echo $i; sleep 0.01; 
done | 
G_MESSAGES_DEBUG=Timings \
  rofi -dmenu -config /dev/null -no-sync
```

(without `-no-sync` nothing changes, as expected)

### Expected behavior

Like 1.7.3: after less than 1 second a window with the first part of the data appears, the rest of data is loaded as it becomes available.

### Actual behavior

The window appears but it is empty until all data has been generated (i.e. multiple seconds). The effect scales to an even longer delay if there are more lines. 

Typing works, i.e. GUI processing is not blocked.

### Additional information

Timings output: https://gist.github.com/7c6f434c/710a9549744b9f9a164197860b26e833

Tried 1.7.4 + https://github.com/davatorium/rofi/commit/65b48aae4faf946fdd94b6f04bf61047c76339b4 as a patch, does not change the behaviour.

#1678 seems remotely similar but unrelated.

The effect seems to disappear when delay is at least 0.250 seconds. This matches the timeout of 250000 microseconds in the new dmenu input implementation from #1621 commit https://github.com/davatorium/rofi/pull/1621/commits/ede31d830f078e9c5b776de1ec4c637bee7f765f and might be related as a read with 0.25 second timeout always produces some new data. 

Setting a very low timeout in `dmenu.c` makes the behaviour disappear.

As expected, the behaviour is not a problem for really fast input (it will be read without timeout being relevant), or input with long pauses in generation (the timeout happens and the data gets drawn in the window).

**Comment by DaveDavenport** [comment]
What is the use case for having input being generated with such long intervals?
(the use case here seems to be especially tailored to make it look as bad as possible).

I am trying to find a trade-off between speed/cpu/exeprience/etc.. 
Lowering that limit will raise cpu usage and may slow down the ui a bit.. 


Yeah, if I lower the BLOCK_LINES_SIZE for big lists cpu goes to 100% and rofi does not get enough time to redraw.

**Comment by DaveDavenport** [comment]
What about this as an solution, forcing it to update atleast 10 times/sec:

```patch
diff --git a/source/modes/dmenu.c b/source/modes/dmenu.c
index c0066099..00d02828 100644
--- a/source/modes/dmenu.c
+++ b/source/modes/dmenu.c
@@ -256,6 +256,7 @@ static gpointer read_input_thread(gpointer userdata) {
   pd->async_queue = g_async_queue_new();
   Block *block = NULL;
 
+  GTimer *tim = g_timer_new();
   int fd = pd->fd;
   while (1) {
     // Wait for input from the input or from the main thread.
@@ -295,10 +296,14 @@ static gpointer read_input_thread(gpointer userdata) {
               memmove(&line[0], &line[i + 1], nread - (i + 1));
               nread -= (i + 1);
               i = 0;
-              if (block && block->length == BLOCK_LINES_SIZE) {
-                g_async_queue_push(pd->async_queue, block);
-                block = NULL;
-                write(pd->pipefd2[1], "r", 1);
+              if (block) {
+                double elapsed = g_timer_elapsed(tim, NULL);
+                if ( elapsed >= 0.1 || block->length == BLOCK_LINES_SIZE) {
+                  g_timer_start(tim);
+                  g_async_queue_push(pd->async_queue, block);
+                  block = NULL;
+                  write(pd->pipefd2[1], "r", 1);
+                }
               }
             } else {
               i++;
@@ -311,6 +316,7 @@ static gpointer read_input_thread(gpointer userdata) {
             read_add_block(pd, &block, line, nread);
           }
           if (block) {
+            g_timer_start(tim);
             g_async_queue_push(pd->async_queue, block);
             block = NULL;
             write(pd->pipefd2[1], "r", 1);
@@ -326,6 +332,7 @@ static gpointer read_input_thread(gpointer userdata) {
         nread = 0;
       }
       if (block) {
+        g_timer_start(tim);
         g_async_queue_push(pd->async_queue, block);
         block = NULL;
         write(pd->pipefd2[1], "r", 1);
```

**Comment by DaveDavenport** [comment]
Does slow down things for me on huge lists, but not by too much.

**Comment by 7c6f434c** [comment]
Thank you!

The real use case generates ~10k lines in ~4 seconds (this includes multiple scripts extracting data from various files, there are some requests to a DB, etc.). It's kind of a multi-use-launcher invocation, with the first few hundreds of entries having higher priority. I was trying to check which part got slower and ended up using an exaggerated test case for debugging.

(I think that 1 line per 0.01 seconds with 500 lines overall in my test case is not _completely_ unreasonable for stuff generated line-by-line by a shell script; 0.25 was just checking if I guessed correctly which part of the code is relevant)

> Yeah, if I lower the BLOCK_LINES_SIZE for big lists cpu goes to 100% and rofi does not get enough time to redraw.

If the current value of BLOCK_LINES_SIZE is necessary for large blocks, would it be acceptable to start with «effective» BLOCK_LINES_SIZE of 1, then double it until its desired maximum (the current one or maybe double it)? I could try implementing it if this seems a good idea.

> What about this as an solution, forcing it to update atleast 10 times/sec:

Overcomes even the exaggerated test, and handles perfectly my real use case, thanks! Not sure if it is worth adding a configuration parameter to avoid harming the huge-list cases.

**Comment by DaveDavenport** [comment]
>If the current value of BLOCK_LINES_SIZE is necessary for large blocks, would it be acceptable to start with «effective» BLOCK_LINES_SIZE of 1, then double it until its desired maximum (the current one or maybe double it)? I could try implementing it if this seems a good idea.

I tried this, it did not work out well and still was slow loading the last 'block' in your example.

**Comment by 7c6f434c** [comment]
> I tried this, it did not work out well and still was slow loading the last 'block' in your example.

I must admit that it wouldn't impact my use case (unlike the current behaviour). Not seeing the (quickly-generated) first hundred of lines of the list at all until at least 2000 lines are generated is noticeable (it's ~0.2s → ~2.5s), some lines taking 50% longer to appear due to batching feels natural.

So if block-doubling is better for huge lists / resource consumption, my use case does not provide a justification against it.

Or was not working out well also harming other use cases?

**Comment by DaveDavenport** [comment]
I think the above patch is a more natural feeling..  for huge lists there is an impact but hope it is acceptable (I tried up to 4 mil lines, there it is a 11% slowdown.  0.7 vs 0.78 s,   for 46 mil lines 7,1 vs 6.2).
