### ISSUE TITLE
[BUG] dmenu with -no-custom option writes a blank line after each selected line

### ISSUE THREAD

**Issue by GrumpyDave** [davatorium/rofi#1682]
### Rofi version (rofi -v)

Version: 1.7.4

### Configuration

https://gist.github.com/GrumpyDave/dc2075f62749960d10c98034af029ae2

### Launch command

rofi -dmenu -no-custom

### Step to reproduce

echo a | rofi -dmenu -no-custom
press ENTER on the "a" line

### Expected behavior

I expect to see one line with "a" on it.

### Actual behavior

I see one line with "a" on it and one blank line.

### Additional information

When -multi-select is also enabled each selected line is followed by a blank line.  Without the -no-custom option rofi works as expected.  The problem appeared in version 1.7.4.  I confirmed it was working as expected in 1.7.3.

**Comment by DaveDavenport** [comment]
Yes, and has been fixed already.
See https://github.com/davatorium/rofi/issues/1679 and https://github.com/davatorium/rofi/discussions/1594
