### ISSUE TITLE
[REQUEST] Please add back Pop-Dark.rasi theme

### ISSUE THREAD

**Issue by groowyCZ** [davatorium/rofi#1687]
### Before opening a feature request

- [X] I checked the *next* branch to see if the feature has already been implemented
- [X] I searched existing reports to see if it is already requested.

### What is the user problem or growth opportunity you want to see solved?

Removing this theme straight up broken rofi for me as there currently isn't anything like fallback theme so opening rofi after updating from the Arch Linux repositories resulted in an unrecoverable error state that could be only resolved by manually launching `rofi-theme-selector` from a terminal (as this application thankfully has a fallback theme) and selecting a theme so that rofi would be functional again.

### How do you know that this problem exists today? Why is this important?

See my previous point.

### Who will benefit from it?

If anyone else like me has been used to this theme for as long as I have it would be very desirable to keep using for the sake of keeping the familiarized aesthetic of rofi intact.

### Rofi version (rofi -v)

1.7.4 and above

### Configuration

https://gist.github.com/groowyCZ/e7f83e5845f615195ec6a410a6d3c7a0

### Additional information

I know this theme was remove because it contained undefined variables but this could have been very easily solved as I've done so in attached file [Pop-Dark.txt](https://github.com/davatorium/rofi/files/9428494/Pop-Dark.txt) (file extension was changed due to GitHub's limitations)

**Comment by DaveDavenport** [comment]
I don't have time to maintain themes.
