### ISSUE TITLE
[BUG] Dmenu ballot settings in config not respected

### ISSUE THREAD

**Issue by fabian-thomas** [davatorium/rofi#1695]
### Rofi version (rofi -v)

Version: 1.7.5

### Configuration

https://gist.github.com/fabian-thomas/558f764fd82d817366479d4fe8e30ab5

### Theme

https://gist.github.com/fabian-thomas/558f764fd82d817366479d4fe8e30ab5

### Launch command

rofi -dmenu -multi-select

### Step to reproduce

* Change ballot settings in `config.rasi` to:
  ```
  configuration {
    ballot {
        unselected-str: "";
        selected-str: " ";
    }
  }
  ```
* Launch rofi with `echo "1\n2" | rofi -dmenu -multi-select`

### Expected behavior

Rofi should use the ballot settings from `config.rasi`, so an empty string for non-selected entries and just a space for selected ones.

### Actual behavior

Rofi uses the default ballot settings (checkboxes) besides dump-config output containing the modified ballot settings.

**Comment by DaveDavenport** [comment]
Correct, this is a dmenu specific option and should be set as commandline argument, just like multi-select.

I am not sure where  you got the above configuration setting from.

**Comment by fabian-thomas** [comment]
@DaveDavenport Why is it listed in `dump-config` then? `-l` is not.

Then I would convert this to a feature request, since people may want to redefine the default ballot selectors globally.

**Comment by DaveDavenport** [comment]
If **you** put it into your configuration file (or pass it on cmd,  that is effectively the same. This is side effect from migrating to newer configuration system without breaking old.), `-dump-config` will dump it out.

try:
```bash
rofi -dump-config -no-config
```

Most dmenu only options are not in the theme/config file as people tend to override these per script.

**Comment by fabian-thomas** [comment]
Ok, I see.

Still not sure if there should be a way to specify a default (un-)selected string in the config files.
