### ISSUE TITLE
[BUG] config parser does not ignore commented lines

### ISSUE THREAD

**Issue by mmahmoudian** [davatorium/rofi#1708]
### Rofi version (rofi -v)

version: 1.7.5

### Configuration

https://bin.snopyta.org/?327e3a0a1a82ad4e#GqiARYpi2wQUjRDa8fFToqFR5e4yFsAVqFApU5EZhAS6

### Theme

https://bin.snopyta.org/?d840d86d5ea66c39#DcvmfNmhwYdEFCiifBwuhZd4mtKyg2uVz4CiyXYbn2QW

### Launch command

rofi -show drun

### Step to reproduce

0. have a fully functional Rofi config that works just fine with immediate previous version
1. update to latest version (1.7.5)
2. run `rofi -show drun`
3. observe the following error

![image](https://user-images.githubusercontent.com/390889/190861047-77aadae0-18ef-4cdb-ad52-d0371c5b858c.png)

### Expected behavior

Rofi works as before, listing installed software

### Actual behavior

![image](https://user-images.githubusercontent.com/390889/190860825-12d5e3a5-c1c1-499a-a7b1-c92a23633d1e.png)

### Additional information

Thanks for developing this software. It is pretty useful and configurable. Cheers.

**Comment by DaveDavenport** [comment]
This is not a config parser error. 1.7.5 adds  two extra keybindings: `element-next` and `element-prev`.  After discussion we decided to give them a default binding, this seems to clash with your config.  Unsetting them should fix it.

**Comment by mmahmoudian** [comment]
If this is an intended change, why not generating proper (detailed) error message instead of this default cryptic one? If I knew I wouldn't have wasted your time

Also, unsettling what? I don't understand. Do you mean that I cannot use the left_Tab for the function I want anymore?

**Comment by mmahmoudian** [comment]
Also, this new thing you mentioned is not communicated or listed in the release notes:

https://github.com/davatorium/rofi/releases/tag/1.7.5

Would it be possible to add it there?

**Comment by DaveDavenport** [comment]
It is in 1.7.4, apologies. 

```css
configuration {
  kb-element-next: "";
  kb-element-prev: "";
}
```
or change your config to remove it from the row-up/row-down binding. The element-next/prev is the same (but works more logical with the new flow option).

Yeah, I wrote down to improve the default error message.
To me the current version is pretty clear (it mention the binding already exists), but I will see if I can also add the other (colliding binding).

**Comment by mmahmoudian** [comment]
@DaveDavenport As far as I understand, my first assessment/hypothesis was right:

![image](https://user-images.githubusercontent.com/390889/190865067-f3575095-7ae7-4aeb-98e1-b09208d6600d.png)

What do you think is causing this? It seems even when the line is commented, it still reads it. Perhaps I am missing something. Would you please point me to the correct direction?

**Comment by DaveDavenport** [comment]
No, I don't think that is a correct interpretation. If comments are not ignored parsing would completely fail.

There is a default list, that always get loaded..  
https://github.com/davatorium/rofi/blob/next/source/keyb.c

If you do `rofi -h` it tells you where it found the setting.

**Comment by DaveDavenport** [comment]
```
        -kb-row-down [string]                   Select next entry
                Down,Control+n (Default)
```

You need to unbind the bound key to remove a default binding. You do this in your config already and I pointed it out above.

**Comment by mmahmoudian** [comment]
ok, I just understood what has happened. Thanks for the explanation. One comment though:

The error message is correct but not informative. Because one keybinding I set was colliding with a default keybinding. The error message imho should specify that what user has defined is colliding with a default setting of XXXX value. This way the user knows what to unset and what to set.

Thanks for your patience and helping me understand the issue. Cheers.

**Comment by DaveDavenport** [comment]
Yes, see my remark above about updating the error message to indicate what binding it collides with.
