### ISSUE TITLE
[REQUEST] Option to specify exluded applications that will be shown i window mode

### ISSUE THREAD

**Issue by Sveske-Juice** [davatorium/rofi#1714]
### Before opening a feature request

- [X] I checked the *next* branch to see if the feature has already been implemented
- [X] I searched existing reports to see if it is already requested.

### What is the user problem or growth opportunity you want to see solved?

When you open the window switcher where you can see all the open windows, it would be nice to exclude certain windows from showing. 

For example some applications like panels/docks, widgets etc. should not be shown in the menu.

### How do you know that this problem exists today? Why is this important?

Like i explained, sometimes some applications do not report their window properties correctly. That way a dock or panel shows up as a normal window, and therefore in the window tab.

### Who will benefit from it?

people that have the problem of applications not reporting their window type correctly or if you just want to ignore showing some specific windows.

### Rofi version (rofi -v)

Version: 1.7.5

### Configuration

not relevant :)

### Additional information

I face the problem where i have a certain application that i would like to ignore when i open the window list:

`rofi -show window`

**Comment by DaveDavenport** [comment]
Why not fix the applications that do not report the correct window type?

**Comment by Sveske-Juice** [comment]
I run i3 window manager and have two docks. One of them has the window type set to "dock". And the other dock has the window type "normal window" because if that was also set to "dock" it wouldn't be possible to place the docks on top of one another:

![image](https://user-images.githubusercontent.com/66884216/192161757-6b8fd50f-a459-4109-b619-1693e031b5a8.png)

as you can see if both were set to dock it would look like this:
![image](https://user-images.githubusercontent.com/66884216/192161780-453d69b8-57a7-4660-88c7-5700dae4ae63.png)

**Comment by DaveDavenport** [comment]
Maybe set SKIP_PAGER or SKIP_TASKBAR on the 2nd dock?

**Comment by DaveDavenport** [comment]
That needs a small fix in rofi :-D.. will add in a second.

**Comment by Sveske-Juice** [comment]
> Maybe set SKIP_PAGER or SKIP_TASKBAR on the 2nd dock?

How can i do this?

**Comment by DaveDavenport** [comment]
xprop can do it..  but you need to update your rofi to the latest git. I found a bug testing it.

**Comment by DaveDavenport** [comment]
```bash
xprop -f _NET_WM_STATE 32a -id 0x1600032 -set _NET_WM_STATE _NET_WM_SKIP_PAGER
```

**Comment by DaveDavenport** [comment]
Closing, the pushed fix should resolve this. If the application set the right property, it should now be hidden.
