### ISSUE TITLE
[BUG] rofi ssh does not recognized ssh-agent / keychain when opening ssh connections

### ISSUE THREAD

**Issue by Daniel451** [davatorium/rofi#1717]
### Rofi version (rofi -v)

1.7.5

### Configuration

https://gist.github.com/Daniel451/e476ef6c30a10b77611b4c674a807eec

### Theme

https://gist.github.com/Daniel451/c1a03c1ef3722866c811bb363fd73373

### Launch command

rofi -show ssh

### Step to reproduce

In i3wm, start rofi via hotkey (e.g. config `bindsym $mod+s exec rofi -show ssh`)

### Expected behavior

ssh keys in `keychain` should get recognized and unlocked keys in `ssh-agent` should result in password-free login to configured ssh hosts

### Actual behavior

ssh keys in `keychain` and unlocked in `ssh-agent` do not get recognized

### Additional information

I am using i3wm. When I am in a terminal and manually entering `rofi -show ssh` rofi correctly uses my `keychain` and running `ssh-agent` so that I can connect to my hosts without password but when I launch it via i3 (`bindsym $mod+s exec rofi -show ssh`) rofi ignores `keychain`, just tries to open `id_rsa` (which does not exist since I have multiple keys) and thus fails so that ssh ask me for password.

**Comment by DaveDavenport** [comment]
This is not a rofi issue.   ssh launched from rofi does not know about your SSH_AGENT, this is an environment issue.

**Comment by DaveDavenport** [comment]
See also here: https://www.reddit.com/r/qtools/comments/xpbs78/shell_environment_issue/

you want to have the SSH_AGENT environment set it up correctly in the environment that launches i3. 
Or make a small wrapper that sets the environment and calls ssh and set that as `ssh-command` in rofi.
