### ISSUE TITLE
[BUG] rofi script mode only accept one colon (problem with filename which includes colons)

### ISSUE THREAD

**Issue by matclab** [davatorium/rofi#1718]
### Rofi version (rofi -v)

1.7.5

### Configuration

https://gist.github.com/matclab/e3600d7b89e898a6efdd35b595b25346#file-rofi-dump-txt

### Theme

https://gist.github.com/matclab/e3600d7b89e898a6efdd35b595b25346#file-rofi-theme

### Timing report

NA

### Launch command

rofi -show mimeopen -modes 'mimeopen:echo -e b:1.pdf\\nc.pdf'

### Step to reproduce

- launch the given command

### Expected behavior

I would expect rofi to show a menu with 
- b:1.pdf
- c.pdf

### Actual behavior

But instead I get the error:
```
The script command 'mimeopen:echo -e b:1.pdf\\nc.pdf' has 3 options, but needs 2: <name>:<script>.
```

### Additional information

I didn't see a way to escape colon.

Shall I try to send a PR which makes rofi accept several colons for the modi script argument ?

**Comment by DaveDavenport** [comment]
You should pass a path to a script (or executable name if in $PATH) as second argument, not inline the script.
(I never even think about people doing this).

For me this is a no-fix, this: `mimeopen:echo -e b:1.pdf\\nc.pdf` is not valid.

I will add a check to see if an actual executable file is passed as 2nd argument.

**Comment by matclab** [comment]
You can always expect random user to find interesting or stupid but unexpected way to use your tool ;-).

The initial use case was motivated by my scripts https://gitlab.com/matclab/rofi-file-selector (`choosexe.sh`) where I use a helper script to get a list of executables registered as able to open the mimetype of the given file. 

I guess I can find a way to communicate the filename between the script calling rofi and the modi script (via temporary file for example), but at first look the command line was a nice way to do it.

Anyway, thank you for your very nice tool.
I close this issue.

**Comment by DaveDavenport** [comment]
Interesting, always good to see the usecase.

I think argument to the script is a valid use-case. 
What might be a good fix is to allow 'escaping' the ':'. 
Currently it does a simple split on ':#' as separator, this we might need to change.

**Comment by DaveDavenport** [comment]
Can you check if that fix works ^^.  I kept it simple, I only split once on ':'.

**Comment by matclab** [comment]
Wow, It was quick !
Yes. It seems to work flawlessly.
Simple is good.

Thank you very much !
