### ISSUE TITLE
[REQUEST] Set the height of each line/prompt and entry to e.g. 20px

### ISSUE THREAD

**Issue by fritzrehde** [davatorium/rofi#1726]
### Before opening a feature request

- [X] I checked the *next* branch to see if the feature has already been implemented
- [X] I searched existing reports to see if it is already requested.

### What is the user problem or growth opportunity you want to see solved?

Allow a setting so that the height of each line and/or the prompt and entry line can be set to a certain px integer (e.g. 20px).

### How do you know that this problem exists today? Why is this important?

I was looking for such a feature, because my status bar (`polybar`) is exactly 20px tall, and I would like to have an entry prompt that has the exact same height, so all of the bar is covered. This feature would allow more customization.

### Who will benefit from it?

Anyone who wants to set the height of the line. Probably people with a status bar like me.

### Rofi version (rofi -v)

1.7.5

### Configuration

https://gist.github.com/fritzrehde/12eaf3a814bbae5964c01d25d621eed7

**Comment by DaveDavenport** [comment]
Sizing is done based on content; e.g. fontsize, iconsize, padding and margins.
height/width can only be set on the window.

Being able to 'hardcode' fixed sizes (esp. when pixel sizes) is gonna result issues. It opens a lot of possibilities to create themes that work on one pc, but not the other. 
This will result in people complaining here. 


While I see the usecase here, I am a bit hesitant adding this. It might be possible to achieve this more 'sensibly' by using the 'calc' method (although this does have to limited extend some of the same issues).

```bash
rofi -show drun -no-config -theme-str 'window {  location: north; anchor: north;} inputbar { padding: calc( ( 20px - 1em )/2); margin:0; }'
```

**Comment by DaveDavenport** [comment]
Discussed this and closing as a won't-fix. I see to many possible issues with this.

**Comment by fritzrehde** [comment]
I found a working solution now anyways (so don't necessarily need this issue for my setup). Thanks for the explanation!
