### ISSUE TITLE
[BUG] Virtual pressing of enter button after Rofi

### ISSUE THREAD

**Issue by nerdkick** [davatorium/rofi#1730]
### Rofi version (rofi -v)

Version: 1.7.5

### Configuration

https://github.com/nk-d/dotfiles/blob/master/dot_config/rofi/config.rasi

### Theme

https://gist.github.com/nk-d/a87d8c03201ccf59a214cf6dee885909

### Timing report

https://gist.github.com/nk-d/fd6636aef9b499ded5641ee1d8c50f10

### Launch command

rofi -show run

### Step to reproduce

- exec "rofi -show run"
- open any text editor
- there will be a lot of new lines

### Expected behavior

The program will open and enter will not be pressed

### Actual behavior

When opening program, after profi, a continuous line break appears, as if I press enter button. I checked, it's not related to my usb devices.
As soon as I press the enter button, everything is fixed. Until I open rofi again
This also applies to Rofi. If I open Rofi for the second time, then the first application opens. And also in all applications, enter key is pressed.
I tried not to use rofi, everything is fine, but I can't without rofi)

### Additional information

Sway logs:
https://termbin.com/4ci7

**Comment by DaveDavenport** [comment]
It clearly states **in bold** to not report issues related to wayland.
