### ISSUE TITLE
[BUG] wrong icon folder in makefile

### ISSUE THREAD

**Issue by xlucn** [davatorium/rofi#1733]
### Rofi version (rofi -v)

Version: 1.7.5 from Arch Linux repo

### Configuration

default

### Theme

default

### Timing report

-

### Launch command

-

### Step to reproduce

1. Open a app launcher, e.g., rofi
2. Find "rofi" itelf :)
3. Probably see no icons

### Expected behavior

See icon of rofi in the launcher

### Actual behavior

No icon is shown

### Additional information

Arch's package build rofi with makefile, where the icon folder is set to `$(datadir)/icons/hicolor/apps/`:

https://github.com/davatorium/rofi/blob/next/Makefile.am#L629

while it should be `$(datadir)/icons/hicolor/scalable/apps/`, as in meson.build settings. Otherwise, `apps` subfolder is not in the icon theme's index.theme file, thus won't be searched by launchers.

**Comment by DaveDavenport** [comment]
owh yeah, that is wrong..   haven't used Makefiles in ages, so have not noticed.
