### ISSUE TITLE
[BUG] failed to compile with lto

### ISSUE THREAD

**Issue by PetrusZ** [davatorium/rofi#1743]
### Rofi version (rofi -v)

1.7.5

### Configuration

not related

### Theme

not related

### Timing report

not related

### Launch command

not related

### Step to reproduce

* compile from source with `CFLAGS=-flto -Werror=odr -Werror=lto-type-mismatch -Werror=strict-aliasing`

### Expected behavior

* compile successfully

### Actual behavior

 * failed to compile with lto
 * ./include/widgets/textbox.h:251:8: error: type of �-Werror=lto-type-mismatch][]]
 * full build log: https://881281.bugs.gentoo.org/attachment.cgi?id=832445
 * about -Werror=lto-type-mismatch:
User to find possible runtime issues in packages. It likely means the package is unsafe to build & use with LTO.
For projects using the same identifier but with different types across different files, they must be fixed to be consistent across the codebase.

### Additional information

This bug is orignal reported at [bugs.gentoo.org/881281](https://bugs.gentoo.org/881281).

**Comment by DaveDavenport** [comment]
Should be fixed, please test.

**Comment by PetrusZ** [comment]
Confirm it fix, thank you!
