### ISSUE TITLE
[BUG] ellipsize not working correctly

### ISSUE THREAD

**Issue by cognitiond** [davatorium/rofi#1746]
### Rofi version (rofi -v)

1.7.5-49-g96e81d1b (next)

### Configuration

run with -no-config

### Theme

run with -no-config

### Launch command

echo "1111111111111111111111222222222222222222222222222223333333333333333333333333333333344444444444444444555555555555555555555566666666666677777777777777777788888888888888888899999999" | rofi -no-config -dmenu -keep-right

### Step to reproduce

1. Run launch command
2. Look at the entry and its ellipsis

### Expected behavior

The text is ellipsized at the start, i.e the text is kept right of the ellipsis.

### Actual behavior

The text is ellipsized at the end.

### Additional information

The help text from `rofi -dmenu -help` says that the `-keep-right` option sets the ellipsis to the end, but after looking at the code at source/modes/dmenu.c:958, it actually sets (or attempts to set) the ellipsis to the start.

If you take a look at this screengrab: [rofi-ellipsize.webm](https://user-images.githubusercontent.com/118043135/202629436-417b2e4f-77e2-4042-ba38-2d664d024aaf.webm), you'll notice that toggling through the ellipsize modes goes end->middle->end->(regular flow), which lead me to believe that the ellipsize mode was set, but not for the text entry (keep in mind I'm not familiar with rofi's code).

After looking through the code, I noticed that listview_set_ellipsize_start(...) - called from rofi_view_ellipsize_start(), and in turn from dmenu_mode_dialog() when it handles -keep-right - should be setting the listview's emode, as well as ellipsizing all its textboxes.

But, through gdb, I discovered that at the point that dmenu_mode_dialog() calls rofi_view_ellipsize_start(), the state->list_view's cur_elements member (which listview_set_ellipsize_start() uses to iterate through its textboxes) is 0, effectively saying it has no elements/textboxes, which makes me think that the listview is being populated after the ellipsizing happens.

I'm not sure where to go from here, or whether my suspicions are correct, so yeah, have this information dump.

**Comment by DaveDavenport** [comment]
fixed, I hope.
