### ISSUE TITLE
[REQUEST] Launch programs in dedicated cgroups

### ISSUE THREAD

**Issue by mweinelt** [davatorium/rofi#1751]
### Before opening a feature request

- [X] I checked the *next* branch to see if the feature has already been implemented
- [X] I searched existing reports to see if it is already requested.

### What is the user problem or growth opportunity you want to see solved?

I want better out of memory management than what the Linux kernel provides. So I went and enabled `systemd-oomd.service` on my machine. But it cannot work properly because everything rofi starts is launched in the `session.scope`, not a dedicated cgroup.

> Be aware that if you intend to enable monitoring and actions on user.slice, user-$UID.slice, or their ancestor cgroups, it is highly recommended that your programs be managed by the systemd user manager to prevent running too many processes under the same session scope (and thus avoid a situation where memory intensive tasks trigger systemd-oomd to kill everything under the cgroup). If you're using a desktop environment like GNOME or KDE, it already spawns many session components with the systemd user manager. 

https://www.freedesktop.org/software/systemd/man/systemd-oomd.service.html#System%20requirements%20and%20configuration

### How do you know that this problem exists today? Why is this important?

Looking through `systemd-cgtop` reveals many cgroups in the system.slice (per systemd unit), a few in the user.slice (user units), and a large session-1.scope, where every app launched through rofi lands in.

### Who will benefit from it?

Users on distros that run with systemd by default can enable oomd to prevent stalls due to out of memory usage. Oomd will have the opportunity to kill the correct cgroup instead of the coarse `session-1.scope`.

### Rofi version (rofi -v)

1.7.5+wayland1

### Configuration

n/a

**Comment by DaveDavenport** [comment]
Can't this be achieved by changing the run*command options?

Also if rofi is launched in the user cgroup, should the programs it launch also wind up in the user cgroup?  If I launch firefox from rofi on my system, it winds up in user.slice.

**Comment by mweinelt** [comment]
Indeed, that would be possibly, let me look into that.

**Comment by DaveDavenport** [comment]
I am not cgroup expert (used it in the past, but never at 'desktop level') but shouldn't it inherit from its parent, so as long as rofi runs in the right slice, so will the applications it launches.
Given rofi is launched by the user in the user session, it should run in the user slice to begin with.

**Comment by mweinelt** [comment]
The GNOME people decoupled programs started from the launcher and through Alt+F2 from the launchers scope in this PR:  https://gitlab.gnome.org/GNOME/gnome-shell/-/merge_requests/863/commits

>  Given rofi is launched by the user in the user session, it should run in the user slice to begin with.

A slice is a hierarchical helper to group scopes. From what I understand of the matter a launched program could be started in a scope within in that slice.

**Comment by mweinelt** [comment]
> Indeed, that would be possibly, let me look into that.

I guess something like ` -run-command "systemd-run --user {cmd}"` would work for me personally.

**Comment by DaveDavenport** [comment]
Currently GLib is used to spawn applications, is there a universal way to launch applications in a cgroup? 
The current method will universally work across distros and linux/bsd/mac, want to avoid breaking stuff.

**Comment by mweinelt** [comment]
> Currently GLib is used to spawn applications, is there a universal way to launch applications in a cgroup?

I don't think GLib can do that, because setting up a cgroup is a bit more involved and systemd provides a runtime abstraction for that.

> The current method will universally work across distros and linux/bsd/mac, want to avoid breaking stuff.

That's a good point. I think documenting such a setup with `-run-command`  would be a good start.

**Comment by DaveDavenport** [comment]
A documentation PR would be very much appreciated. 

'script mode' scripts are not launched via this command, i guess that should be fine in this setup?

**Comment by mweinelt** [comment]
No idea about "script mode", never used it.

**Comment by DaveDavenport** [comment]
documentation updated.. closing.
