### ISSUE TITLE
[BUG] Listing View Doesn't Stay Left-Aligned In dmenu Mode

### ISSUE THREAD

**Issue by ghost** [davatorium/rofi#1754]
### Rofi version (rofi -v)

1.7.5

### Configuration

https://gist.github.com/isaacbrown92/65a49d6a3cdab7e7cc4d573f1147e93c

### Theme

https://gist.github.com/isaacbrown92/aeb7bd522529c50189e175fa95c6bd47

### Launch command

rofi -show run drun -m DisplayPort-1

### Step to reproduce

Run the launch command, then start tabbing through listings. Once you hit the end of the currently visible row, shift-tab to flip back to the prior row.

### Expected behavior

The listings view should always be left-aligned:

| drun | search | L1 L2 L3 L4 L5 L6 \\\\\\\\\\\\ |

### Actual behavior

The listings view is left-aligned initially, but right-aligned once you shift-tab back into a prior row.

| drun | search | \\\\\\\\\\\\ L1 L2 L3 L4 L5 L6 |

### Additional information

You can see the behaviour more clearly if you limit the amount of visible listning to 2 or so. In fact, if your items perfectly span the first two rows, or near-perfectly, you won't be able to see the behaviour.

**Comment by DaveDavenport** [comment]
This is how rofi works, not directly a bug.
See also https://github.com/davatorium/rofi/discussions/1661

I have no intention to fix this, I plan to deprecate this code and remove it in the future.
A fix would be to fix  the number of columns (see above discussion) and use the normal listview.

**Comment by ghost** [comment]
Ok, I see. Thank you. I've implemented what you suggeted in #1661. This is better, however now there is somewhat strange spacing between the results because the result lengths vary but the columns have a fixed size. Is there a way to shrink the columns to their content size to get rid of the uneven whitespace?
