### ISSUE TITLE
[BUG] "monitor: -1" doesn't show rofi on the active monitor under wayland (sway)

### ISSUE THREAD

**Issue by Zeioth** [davatorium/rofi#1758]
### Rofi version (rofi -v)

1.7.5

### Configuration

configuration {   monitor:  -1; }

### Theme

/**  * rofi -dump-theme output.  * Rofi version: 1.7.5  **/ * {     red:                         rgba ( 220, 50, 47, 100 % );     selected-active-foreground:  var(background);     lightfg:                     rgba ( 88, 104, 117, 100 % );     separatorcolor:              var(foreground);     urgent-foreground:           var(red);     alternate-urgent-background: var(lightbg);     lightbg:                     rgba ( 238, 232, 213, 100 % );     background-color:            transparent;     border-color:                var(foreground);     normal-background:           var(background);     selected-urgent-background:  var(red);     alternate-active-background: var(lightbg);     spacing:                     2;     blue:                        rgba ( 38, 139, 210, 100 % );     alternate-normal-foreground: var(foreground);     urgent-background:           var(background);     selected-normal-foreground:  var(lightbg);     active-foreground:           var(blue);     background:                  rgba ( 253, 246, 227, 100 % );     selected-active-background:  var(blue);     active-background:           var(background);     selected-normal-background:  var(lightfg);     alternate-normal-background: var(lightbg);     foreground:                  rgba ( 0, 43, 54, 100 % );     selected-urgent-foreground:  var(background);     normal-foreground:           var(foreground);     alternate-urgent-foreground: var(red);     alternate-active-foreground: var(blue); } element {     padding: 1px ;     cursor:  pointer;     spacing: 5px ;     border:  0; } element normal.normal {     background-color: var(normal-background);     text-color:       var(normal-foreground); } element normal.urgent {     background-color: var(urgent-background);     text-color:       var(urgent-foreground); } element normal.active {     background-color: var(active-background);     text-color:       var(active-foreground); } element selected.normal {     background-color: var(selected-normal-background);     text-color:       var(selected-normal-foreground); } element selected.urgent {     background-color: var(selected-urgent-background);     text-color:       var(selected-urgent-foreground); } element selected.active {     background-color: var(selected-active-background);     text-color:       var(selected-active-foreground); } element alternate.normal {     background-color: var(alternate-normal-background);     text-color:       var(alternate-normal-foreground); } element alternate.urgent {     background-color: var(alternate-urgent-background);     text-color:       var(alternate-urgent-foreground); } element alternate.active {     background-color: var(alternate-active-background);     text-color:       var(alternate-active-foreground); } element-text {     background-color: transparent;     cursor:           inherit;     highlight:        inherit;     text-color:       inherit; } element-icon {     background-color: transparent;     size:             100;     cursor:           inherit;     text-color:       inherit;     border:           0px ; } window {     padding:          5;     background-color: var(background);     orientation:      horizontal;     width:            40.0000% ;     margin-right:     60px ;     border:           1;     height:           60.0000% ; } mainbox {     padding: 0;     border:  0; } message {     padding:      1px ;     border-color: var(separatorcolor);     border:       2px dash 0px 0px ; } textbox {     text-color: var(foreground); } listview {     padding:      2px 0px 0px ;     scrollbar:    true;     border-color: var(separatorcolor);     spacing:      2px ;     fixed-height: 0;     border:       2px dash 0px 0px ; } scrollbar {     width:        4px ;     padding:      0;     handle-width: 8px ;     border:       0;     handle-color: var(normal-foreground); } sidebar {     border-color: var(separatorcolor);     border:       2px dash 0px 0px ; } button {     cursor:     pointer;     spacing:    0;     text-color: var(normal-foreground); } button selected {     background-color: var(selected-normal-background);     text-color:       var(selected-normal-foreground); } num-filtered-rows {     expand:     false;     text-color: Gray; } num-rows {     expand:     false;     text-color: Gray; } textbox-num-sep {     expand:     false;     str:        "/";     text-color: Gray; } inputbar {     padding:    1px ;     spacing:    0px ;     text-color: var(normal-foreground);     children:   [ "prompt","textbox-prompt-colon","entry","num-filtered-rows","textbox-num-sep","num-rows","case-indicator" ]; } case-indicator {     spacing:    0;     text-color: var(normal-foreground); } entry {     text-color:        var(normal-foreground);     cursor:            text;     spacing:           0;     placeholder-color: Gray;     placeholder:       "Type to filter"; } prompt {     spacing:    0;     text-color: var(normal-foreground); } textbox-prompt-colon {     margin:     0px 0.3000em 0.0000em 0.0000em ;     expand:     false;     str:        ":";     text-color: inherit; }

### Launch command

rofi -show drun -modi drun

### Step to reproduce

Open wofi with this configuration file. It won't display in the active display.

### Expected behavior

    configuration {   monitor: -1; }

Makes rofi appear in the focused monitor.

### Actual behavior

It always appear in the same monitor.

### Additional information

I have 6 monitors. I'm on sway.

I've tried from -1 to -5 and none of those seem to be behaving as it should. Only 1-6 work fine.

**Comment by DaveDavenport** [comment]
Please read the **bold** message in the issue template or the **bold** text at the bottom of the guidelines..

**Comment by DaveDavenport** [comment]
**Please do not submit reports related to wayland, see
        [here](https://github.com/DaveDavenport/rofi/wiki/Wayland) for more
        information.**
