### ISSUE TITLE
[BUG] Segfault if mainbox does not contain "listview" as a child in dmenu mode

### ISSUE THREAD

**Issue by the-argus** [davatorium/rofi#1759]
### Rofi version (rofi -v)

1.7.5

### Configuration

https://gist.github.com/the-argus/dd252a3d3471a90ef17d7dbf55c034d8

### Theme

https://gist.github.com/the-argus/9623cd9f104d51eb0155698615a9d42e

### Timing report

none (rofi doesn't launch)

### Launch command

rofi -theme theme.rasi -dmenu -p "Master Password" -password -lines 0

### Step to reproduce

If you have a working nix installation, you can run the following:
```bash
git clone https://github.com/the-argus/bitwarden-rofi
cd bitwarden-rofi
git checkout rofi-segfault
nix build
./result/bin/bwmenu
```
You will see that the program silently exits.

If you don't have a working nix installation, clone the respository, check out the rofi-segfault branch, and install ``jq``, ``bitwarden-cli``, ``xclip`` or ``wlclipboard``, ``gnupg``, and ``keyutils`` in order to get the ``keyctl`` command, if your distro doesn't ship it by default. Then, run ``./bwmenu``. Hopefully the versions of programs will be similar and you will see a similar exit.
NOTE: I don't think installing this stuff is actually necessary, but it reproduces the same issue as in nix the best. For a much easier way of reproducing what I believe to be the same problem, scroll down to the Additional Information section

Rofi is invoked and segfaults at line 106 in the ``bwmenu`` script in my repository.

### Expected behavior

The ability to remove any listview area because it is unused. Something like this: ![preview](https://user-images.githubusercontent.com/34305318/188023683-c4c764bc-aca6-45fc-b00c-c80c8209ffe5.png)

### Actual behavior

Rofi segfaults immediately

### Additional information

The script in my repository that I gave is suppressing some output. To distill it further, try running ``rofi -dmenu -theme default_themes/askpass_theme.rasi`` while in my repository on the rofi-segfault branch. Then, remove the mainbox's ``children`` definition (line 35) inside of ``default_themes/askpass_theme.rasi``. Run the command again and you will see that the segfault disappears.

**Comment by DaveDavenport** [comment]
Can you try git? I think this was fixed.

**Comment by DaveDavenport** [comment]
```css
listview { enabled: false; }
```
should work in 1.7.5

**Comment by DaveDavenport** [comment]
As a side-note, rofi was **not** designed to be a secure password prompt. No extra security features are implemented.

**Comment by the-argus** [comment]
> ```css
> listview { enabled: false; }
> ```
> 
> should work in 1.7.5

This works perfectly, thank you. I'm going to leave this issue open though, assuming you want to fix it despite the fact that there is an easy workaround. I used rofi from commit ``23de9e9d2c35af8cce72b060f6d2916cd6215a23`` and the issue persists.

And I've added a warning to my README saying that rofi isnt a secure password prompt.

**Comment by DaveDavenport** [comment]
I can reproduce the issue with 1.7.5 but not latest git..  
(I am using the provided theme, not nix (its gin ?))

Can you get a backtrace?

**Comment by the-argus** [comment]
I made some kind of mistake in my nix packaging- it seems that I was accidentally still using rofi 1.7.5. I built it from source manually from the commit I mentioned before and found the issue resolved. Thanks for your effort.

**Comment by DaveDavenport** [comment]
Thanks for double-checking.
