### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by cayhorstmann** [davatorium/rofi#1766]
### Rofi version (rofi -v)

1.7.1

### Configuration

https://gist.github.com/cayhorstmann/fc91db7e317ee4b5a9cf84c61ff36ace

### Theme

https://gist.github.com/cayhorstmann/0ffa9d81c60c0dce9a1fc05951e443d2

### Launch command

rofi -show window

### Step to reproduce

* Add these to `.Xresources`
    ```
    Xft.dpi: 192
   *dpi: 192
    ```
* Run `xrdb -merge ~/.Xresources`
* Run `xrdb -query | grep dpi` 
* Run `rofi -show window`

### Expected behavior

The font size should have changed (as if run with `rofi -dpi 192 -show window`)

### Actual behavior

The font size hasn't changed (it's tiny on my HiDPI screen)

### Additional information

I followed #423 but it doesn't seem to have done me any good. Am running Ubuntu 22.04 with OpenBox.

**Comment by DaveDavenport** [comment]
Rofi does not support Xresources.. 
See 1.7.0 releasenotes.
