### ISSUE TITLE
[BUG] Long list delays listview's appearance

### ISSUE THREAD

**Issue by yusufaktepe** [davatorium/rofi#1769]
### Rofi version (rofi -v)

Version: 1.7.5-65-g34810e72 (makepkg)

### Configuration

https://gist.github.com/yusufaktepe/1a966a08f2d74b54e08025dc585a3337

### Theme

https://gist.github.com/yusufaktepe/bd1d7c5706ae87dc5f4593eb88840724

### Timing report

https://gist.github.com/yusufaktepe/14371b160857dc1a9dde17d95b647eda

### Launch command

seq 10000 | rofi -dmenu

### Step to reproduce

* Set `dynamic: true;`  for listview.
* Pass long list to `rofi -dmenu`

### Expected behavior

Listview should appear at the same time as the inputbar? (This was the case in v1.7.3)

[1.7.3.webm](https://user-images.githubusercontent.com/32964025/209983099-82ecd1d5-6f44-499e-a06b-841857f74409.webm)

### Actual behavior

Listview appears a second later after the inputbar is shown.

[1.7.5.webm](https://user-images.githubusercontent.com/32964025/209982954-1a8efdfa-dbd5-439a-a5aa-6e4905704edf.webm)

**Comment by DaveDavenport** [comment]
Its triggered by `fixed-height`. 
minimal reproduce:

```bash
seq 10000 | rofi -dmenu -no-config -theme-str 'listview { fixed-height: false; }'
```

**Comment by DaveDavenport** [comment]
Possible fix in git, can you check?

**Comment by yusufaktepe** [comment]
Yes, it seems to be fixed. Thank you.
