### ISSUE TITLE
[BUG] -monitor -1 does't behave as it should

### ISSUE THREAD

**Issue by Zeioth** [davatorium/rofi#1773]
### Rofi version (rofi -v)

1.7.5

### Configuration

https://pastebin.com/GCeK1v8k

### Theme

https://pastebin.com/vQYnTn6D

### Launch command

rofi -show drun -monitor -1

### Step to reproduce

On sway, run 'rofi -show drun' having at least 2 monitors. → (I have 6)

### Expected behavior

Rofi opens in the active monitor.

### Actual behavior

Rofi will fail to detect the active monitor, and it will display on a different one.

**Comment by DaveDavenport** [comment]
Rofi is not supported on wayland, as stated **both**  in the issue template, as guideline.
Please read the linked page, where it links  the wayland rofi port  that most likely fixes your issues.
