### ISSUE TITLE
[REQUEST] Multiple prompts in the same rofi instance

### ISSUE THREAD

**Issue by SingularisArt** [davatorium/rofi#1774]
### Before opening a feature request

- [X] I checked the *next* branch to see if the feature has already been implemented
- [x] I searched existing reports to see if it is already requested.

### What is the user problem or growth opportunity you want to see solved?

My current problem that I keep running into is:

I need information from a user, like a username, password, and email and I would like to get this via rofi.
But, to do this, I'll have to create three instances of rofi, one after the other asking for that information.
Instance 1: What is your username: 
Instance 2: What is your password: 
Instance 3: What is your email: 

That's annoying, at least for me.
My idea is you have the ability to create multiple prompts on each instance. So, you can ask those three questions on the same instance and get the input required.

I understand if this is going a tad bit crazy. If so, you can just close this issue.

### How do you know that this problem exists today? Why is this important?

I'm currently working on a ton of projects that require manual inputs, and I would love to use rofi for getting that information without opening dozens of instances of rofi one after the other.

### Who will benefit from it?

I don't know who will benefit from it. If you think you would benefit from it, you can just leave a comment on this issue, and if you think you won't use this idea, then you can also leave a comment, and from that, maybe we can decide if we'd like to continue. I'd love to help build this idea, but I know very little about C. If you can give me some tips on what to learn for what parts, I'll be happy to lend a hand if we decide to continue with this feature.

### Rofi version (rofi -v)

Version: 1.7.5

### Configuration

https://gist.github.com/SingularisArt/27f159e16dcfd967510a3267d066390f

**Comment by DaveDavenport** [comment]
Clarification question, do you mean multiple entry boxes in one view? or not having to close/relaunch rofi between prompts?

**Comment by SingularisArt** [comment]
I mean multiple entry boxes in one view

**Comment by TonCherAmi** [comment]
Looks similar to #1269

**Comment by DaveDavenport** [comment]
Yes, the comments on that issue hold here.  I think if you want something more dynamic, you might want to use something build for this purpose, like [zenity](https://help.gnome.org/users/zenity/stable/forms.html.en).

**Comment by SingularisArt** [comment]
Oh. I've never heard of zenity. Thanks for the recommendation!

**Comment by DaveDavenport** [comment]
To be honest, if somebody want to extend rofi (in a clean-ish way) to add zenity support to it I would not reject this. 
A lot of the infrastructure is there (75%), but the last 25% is still a lot of work and currently I don't have the time (nor motivation/energy) to implement this.
