### ISSUE TITLE
[REQUEST] make appimage or binary file

### ISSUE THREAD

**Issue by newyorkthink** [davatorium/rofi#1782]
### Before opening a feature request

- [X] I checked the *next* branch to see if the feature has already been implemented
- [X] I searched existing reports to see if it is already requested.

### What is the user problem or growth opportunity you want to see solved?

1

### How do you know that this problem exists today? Why is this important?

1

### Who will benefit from it?

1

### Rofi version (rofi -v)

1

### Configuration

1

**Comment by DaveDavenport** [comment]
See  #1624, #1329 and point [two, three, four and five](https://github.com/davatorium/rofi/blob/next/.github/CONTRIBUTING.md#creating-a-feature-request).
