### ISSUE TITLE
[BUG] Rofi paste, removes the tabs (\t) from string in the rofi -show run menu

### ISSUE THREAD

**Issue by mizhozan** [davatorium/rofi#1784]
### Rofi version (rofi -v)

Version: 1.7.5

### Configuration

https://gist.github.com/mizhozan/a89e9a01daa6d160381a8325968e3b38

### Theme

https://gist.github.com/mizhozan/a6f9d4b78fcc067ce5020c1a9de4d6c3

### Launch command

rofi -show run

### Step to reproduce

* Copy a string with tabs instead of space:  Use [this gist](https://gist.github.com/mizhozan/96d630b36dd10b2adf5d36f3c2d74004) since GitHub replace the tabs
* `rofi -show run`
* paste the copied string using C-V
* The tabs are removed (not replaced by space)

### Expected behavior

I expected, if rofi does not pass tabs, instead replace them by space.

### Actual behavior

 The current behavior, it just removes the \t characters when I paste the string in its menu. 

### Additional information

I'm using linux with Xorg. I have a script which call it by rofi, so sometimes I pass it string with tab. I expect rofi either:
* replace \t with space
* pass \t

### Using wayland display server protocol

- [X] No, I don't use the wayland display server protocol

**Comment by DaveDavenport** [comment]
The entry box does not allow you to enter  control character as this can screw things up (using g_unichar_iscntrl), this also filters out tabs.

as  a paste 'simulates' typing in that causes it to be removed.

Need to see how to deal with this.

**Comment by DaveDavenport** [comment]
Above commit replaces any 'space' character ( space, tab, or line separator (newline, carriage return, etc.) with a space.

**Comment by mizhozan** [comment]
I just tested [a20f828](https://github.com/davatorium/rofi/commit/a20f8280a78f5fbfc9d0559e9607788ec2fca94b), and can confirm it solves the issue. I also didn't notice any other problem or corner case.

Thanks for the prompt fix.

**Comment by DaveDavenport** [comment]
thanks for testing!
