### ISSUE TITLE
Rofi Theme Selector won't run

### ISSUE THREAD

**Issue by Rpergy** [davatorium/rofi#1797]
### Rofi version (rofi -v)

Version: 1.7.5

### Configuration

https://gist.github.com/Rpergy/496daa6bfa287d47d1ce6cc210ae1129

### Theme

https://gist.github.com/Rpergy/e49d020909dea1598cf5910f167e2a49

### Launch command

rofi-theme-selector

### Step to reproduce

* Open terminal (in order to see the output)
* Run `rofi-theme-selector`

### Expected behavior

Opening the Rofi Theme Selector application

### Actual behavior

The program returns this error message whenever I run `rofi-theme-selector`:
`/usr/bin/rofi-theme-selector: line 6: which: command not found
/usr/bin/rofi-theme-selector: line 7: which: command not found
/usr/bin/rofi-theme-selector: line 8: which: command not found
Did not find 'sed', script cannot continue.`

### Using wayland display server protocol

- [X] No, I don't use the wayland display server protocol

**Comment by DaveDavenport** [comment]
Install sed? as the script  reports  it does not find.
