### ISSUE TITLE
[REQUEST] rofi plugin manager

### ISSUE THREAD

**Issue by jonbakerfish** [davatorium/rofi#1800]
### Before opening a feature request

- [X] I checked the *next* branch to see if the feature has already been implemented
- [X] I searched existing reports to see if it is already requested.

### What is the user problem or growth opportunity you want to see solved?

Do we have a plugin manager for rofi, like the [tpm](https://github.com/tmux-plugins/tpm) for tmux? It will simplify the installation of plugins.

### How do you know that this problem exists today? Why is this important?

After searching the doc and googling, didn't find anything related.

### Who will benefit from it?

rofi users

### Rofi version (rofi -v)

1.7.1

### Configuration

NA

**Comment by DaveDavenport** [comment]
Is this a question? or request?

> Do we have a plugin manager for rofi, like the [tpm](https://github.com/tmux-plugins/tpm) for tmux?

No

Given no details are given in this question what you exactly want to request. I assume rofi terminology and that you are talking about the (C) plugins that rofi supports to extends it functionality.
Like https://github.com/OmarCastro/rofi-blocks, https://github.com/marvinkreis/rofi-file-browser-extended or https://github.com/svenstaro/rofi-calc.

I don't see how this would be done easily?  It would require compilation, dependency installation,etc.     imho they should be part of the distributions packages.
It just sounds like a lot of effort for the few actual plugins that exits. I know only of a few that people might actually use, rofi-blocks, rofi-calc, rofi-extended-file-browser and rofi-ntfy?
