### ISSUE TITLE
[REQUEST] Pre-check some or all boxes on `-demu -multi-select`

### ISSUE THREAD

**Issue by KSXGitHub** [davatorium/rofi#1806]
### Before opening a feature request

- [X] I checked the *next* branch to see if the feature has already been implemented
- [X] I searched existing reports to see if it is already requested.

### What is the user problem or growth opportunity you want to see solved?

When I launch `rofi -dmenu -multi-select`, all boxes are unchecked by default, but my use case requires all boxes are checked by default, and user may manually uncheck undesired boxes.

### How do you know that this problem exists today? Why is this important?

Rofi dmenu use case is similar to a terminal based fuzzy finder program, both capable of multi-selection, except Rofi dmenu can't pre-check boxes.

### Who will benefit from it?

People who want to use rofi as a fuzzy finder

### Rofi version (rofi -v)

Version: 1.7.5

### Configuration

https://gist.github.com/KSXGitHub/40e74f10d3aec68d92c748333bb11bab

**Comment by DaveDavenport** [comment]
Please test PR.

**Comment by DaveDavenport** [comment]
no longer interrested in implementing this.  A good PR is welcome.
