### ISSUE TITLE
[REQUEST] print command to be executed in drun, run modes to stdout

### ISSUE THREAD

**Issue by lmccartneystar** [davatorium/rofi#1828]
### Before opening a feature request

- [X] I checked the *next* branch to see if the feature has already been implemented
- [X] I searched existing reports to see if it is already requested.

### What is the user problem or growth opportunity you want to see solved?

I would like rofi's drun and run modes to have an option to output the command of a selected item to run.
I want this so that I can implement it in some of my scripts.
Maybe a `-no-exec` option that prints the command instead of executing it would be okay.

### How do you know that this problem exists today? Why is this important?

I mainly use rofi as an app launcher, it's really useful and easy to customize, but these modes don't output anything to the command-line, so it makes them useless from within scripts (at least for me, unlike the dmenu mode).
Making a script to replicate these modes and then piping to dmenu mode just doesn't make sense, since they're already implemented.

### Who will benefit from it?

command-line users

### Rofi version (rofi -v)

Version: 1.7.5

### Configuration

N/A

**Comment by DaveDavenport** [comment]
rofi (except for dmenu mode) is not intended to be integrated into scripts. It obeys local and global configuration that can change it behaviour. So I see a few problems with this:

* Not all desktop files execute a binary. Some open a link.
* What is shown/not shown is set in (global) configuration.
* The user can switch to another mode (what modes can be set in config), so its not sure what it returned.
* What to do with working directory? This can be important to be able to correctly run the desktop file
* What to do with the field codes?

Also, as requested in the guidelines, can you give a use-case for this?

**Comment by lmccartneystar** [comment]
I use a tiling window manager (dwm) and multiple monitors, and I want the apps I open from "n" tag in "x" monitor display in that same "n" tag and "x" monitor, this is what happens most of the time, but certain GUI apps take a while to load, so if I switch to another tag or monitor before these apps fully load they'll appear there.
I assume this happens in any window manager or desktop environment.

So I want to programmatically move the windows of these apps to where they were originally launched from, I'm looking for a general approach not for a specific app. I couldn't get any hint of what app is being opened, nor a WID, PID, class name, or the command.

Another use-case will be to slightly modify the returned command with certain flags, for example, you select Firefox in drun mode and programmatically add flags to it to open it in a normal window, private window, specific profile, specific url, and pass these commands into rofi with dmenu mode to choose from.

**Comment by DaveDavenport** [comment]
> Another use-case will be to slightly modify the returned command with certain flags, for example, you select Firefox in drun mode and programmatically add flags to it to open it in a normal window, private window, specific profile, specific url, and pass these commands into rofi with dmenu mode to choose from.

Some of this is already there, look at `-drun-show-actions`.

> I use a tiling window manager (dwm) and multiple monitors, and I want the apps I open from "n" tag in "x" monitor display in that same "n" tag and "x" monitor, this is what happens most of the time, but certain GUI apps take a while to load, so if I switch to another tag or monitor before these apps fully load they'll appear there.
I assume this happens in any window manager or desktop environment.

Depends on the window manager, I thought rofi  setups startup-notification correctly so this does not happen in window managers that correctly support this. But I doubt dwm supports this.


Maybe `run-command` and `run-shell-command` can help you?

**Comment by DaveDavenport** [comment]
Not going to implement the request. 
1.) modes should not be used in scripts, use dmenu to get interactive interface.
2.) request, while 1 is still valid,  is already possible with a bit of a hack:  `-run-command "echo {cmd}" '
3.) use case described is already in rofi.
  * launch on right desktop -> startup notification normally takes care of this.
  * multiple different actions per application ->  see drun-show-actions
  * launch with argument -> for file use the  `ctrl-l` keybinding.   For urls, we either add desktop files to list the extra 'actions', or we need to add support for this (via the same way 'file' complete works)  in rofi somehow (new feature request?)
