### ISSUE TITLE
[BUG] Cannot parse multiple special row options

### ISSUE THREAD

**Issue by REALERvolker1** [davatorium/rofi#1829]
### Rofi version (rofi -v)

Version: 1.7.5-134-g0133697f (next)

### Configuration

https://gist.github.com/REALERvolker1/a7536a1b203602a8ecd1a63be422a242

### Theme

https://gist.github.com/REALERvolker1/e3dc22aa0f760a087281c72ba2e9e61a

### Timing report

https://gist.github.com/REALERvolker1/ddfafcd2909d4e843f24d72c814fcf79

### Launch command

/home/vlk/.local/src/rofi/build/rofi -show nerd -modes "nerd:$(which rofi-nerd.sh)"

### Step to reproduce

1. write a script:
```sh
#!/usr/bin/env bash

printf "Test Entry\0icon\x1forg.mozilla.Firefox
Test Entry 2\0icon\x1fpath-combine" | /home/vlk/.local/src/rofi/build/rofi -dmenu
```
![image](https://user-images.githubusercontent.com/73304952/229866283-3c0e60e5-76b8-4ba6-b15d-beb116cfd689.png)
2. Add special row options. Notice that your icons do not show up
```sh
printf "Test Entry\0meta\x1ffirefox\0icon\x1forg.mozilla.Firefox
Test Entry 2\0meta\x1fcombine\0icon\x1fpath-combine" | /home/vlk/.local/src/rofi/build/rofi -dmenu
```
![image](https://user-images.githubusercontent.com/73304952/229866567-3b03cb81-6798-47f1-beeb-6de35149007f.png)
3. Try it out as a custom `rofi-script` mode
`/home/vlk/.local/src/rofi/build/rofi -show nerd -modes "nerd:$(which rofi-nerd.sh)"`
```sh
#!/usr/bin/env bash

printf "Test Entry\0meta\x1ffirefox\0icon\x1forg.mozilla.Firefox
Test Entry 2\0meta\x1fcombine\0icon\x1fpath-combine"
```
![image](https://user-images.githubusercontent.com/73304952/229867327-2da252a5-d594-466a-8ac8-f4c43245a146.png)

### Expected behavior

`/home/vlk/.local/src/rofi/build/rofi -show nerd -modes "nerd:$(which rofi-nerd.sh)"`
```sh
#!/usr/bin/env bash

case "$@" in
    'Test'*)
        exit 0
    ;;
esac

printf "Test Entry\0meta\x1ffirefox\0icon\x1forg.mozilla.Firefox
Test Entry 2\0meta\x1ftrue\0icon\x1fpath-combine"
```
![image](https://user-images.githubusercontent.com/73304952/229867951-e9fe22f1-bd08-4cd9-94f8-70eb6215e37c.png)

### Actual behavior

![image](https://user-images.githubusercontent.com/73304952/229866567-3b03cb81-6798-47f1-beeb-6de35149007f.png)

### Additional information

The output of my [rofi -help](https://gist.github.com/REALERvolker1/f0cca1f6a1221c9ff48cfa3bf2850c7b)

This also occurs in rofi `Version: 1.7.5+wayland1`

### Using wayland display server protocol

- [X] No, I don't use the wayland display server protocol

### I've checked if the issue exists in the latest stable release

- [X] Yes, I have checked the problem exists in the latest stable version

**Comment by DaveDavenport** [comment]
Please check the following section from the manpage:

```markdown
       multiple entries can be passed using the \x1f separator.

                  echo -en "aap\0icon\x1ffolder\x1finfo\x1ftest\n"
```
(https://davatorium.github.io/rofi/current/rofi-script.5/#parsing-row-options)

**Comment by DaveDavenport** [comment]
Example usage: https://github.com/davatorium/rofi/blob/next/Examples/test_script_env.sh
