### ISSUE TITLE
[REQUEST] Custom directories for drun

### ISSUE THREAD

**Issue by LordMZTE** [davatorium/rofi#1831]
### Before opening a feature request

- [X] I checked the *next* branch to see if the feature has already been implemented
- [X] I searched existing reports to see if it is already requested.

### What is the user problem or growth opportunity you want to see solved?

Many applications install desktop files in other directories such as `~/Desktop` (for example, PrismLauncher will create shortcuts here).

Some people also like to put other shortcuts in `~/Desktop`, for example for important documents.

Because of this, I propose that we add a `-drun-dirs` flag, which can be used to pass additional directories to search for desktop files. As an alternative solution, we could also have Rofi search in `$XDG_DESKTOP_DIR`.

### How do you know that this problem exists today? Why is this important?

Since the `~/Desktop` directory is a place commonly used to create shortcuts (`.desktop` files) for important purposes such as to documents that are being worked on, it would be useful if those could be shown in Rofi, too.

### Who will benefit from it?

This would be great to implement in order to help people who like to keep desktop files outside of the 2 paths that Rofi searches currently.

### Rofi version (rofi -v)

Version: 1.7.5

### Configuration

https://gist.github.com/LordMZTE/62a1892dd8472d457ae40b6137743101

**Comment by DaveDavenport** [comment]
I thought normally they should be placed in the user data directory?
(steam and the like adds stuff there).
I have never seen an application do this on the desktop, I've checked several machines. Do you have an example?


```patch
diff --git a/source/modes/drun.c b/source/modes/drun.c
index 3e82561b..36e4bc67 100644
--- a/source/modes/drun.c
+++ b/source/modes/drun.c
@@ -1007,8 +1007,17 @@ static void get_apps(DRunModePrivateData *pd) {
   if (drun_read_cache(pd, cache_file)) {
     ThemeWidget *wid = rofi_config_find_widget(drun_mode.name, NULL, TRUE);

+    /** Load desktop entries */
+    Property *p = rofi_theme_find_property(wid, P_BOOLEAN, "scan-desktop", FALSE);
+    if (p == NULL || (p->type == P_BOOLEAN && p->value.b)) {
+      const gchar *dir;
+      // First read the user directory.
+      dir = g_get_user_special_dir(G_USER_DIRECTORY_DESKTOP );
+      walk_dir(pd, dir, dir);
+      TICK_N("Get Desktop dir apps");
+    }
     /** Load user entires */
-    Property *p = rofi_theme_find_property(wid, P_BOOLEAN, "parse-user", TRUE);
+    p = rofi_theme_find_property(wid, P_BOOLEAN, "parse-user", TRUE);
     if (p == NULL || (p->type == P_BOOLEAN && p->value.b)) {
       gchar *dir;
       // First read the user directory.
```

```bash
rofi -show drun -theme-str ' configuration { drun { scan-desktop: true; } }'
```

This is fully untested as I've been unable to find any application that places desktop files on your Desktop.

**Comment by LordMZTE** [comment]
Applications placing desktop files in ~/Desktop might be rare/not XDG-compliant, but the main use-case here is probably user-created shortcuts on the desktop. But as I said, one application I know that does this is Prismlauncher.

**Comment by DaveDavenport** [comment]
Are user created shortcuts actually desktop files? or just simlinks.
I don't really use mouse-based desktop and haven't made a shortcut in a DE for ages.

**Comment by LordMZTE** [comment]
I think most desktops create .desktop files for those shortcuts, although I've not been using one either.

It's to support more features like a description, custom icons and so on.

**Comment by DaveDavenport** [comment]
If it is a common thing (as stated in the main request) I am willing to add it.
But if it is the one-off odd behaving application (rare as mentioned in reply)  I am not sure if it worth adding 'yet another option'. 

I am have little time to develop/maintain rofi, I am trying to limit the new options to the absolute minimum, as everything needs to be maintained.

**Comment by LordMZTE** [comment]
I think this is mostly to support people's custom shortcuts rather than applications who put their desktop entries in ~/Desktop.

I also believe this should be reasonably simple to implement, given that we'd just have to add an option in the drun module and then call `walk_dir` on that.

**Comment by DaveDavenport** [comment]
Yes, I pasted a patch above that does exactly this....  ...

But, as mentioned before, that is 1/2 the story. There needs to be documentation, its needs to be maintained and support for provided.
And for this 50 other equal 'niche' requests.
