### ISSUE TITLE
[REQUEST] Initial text option

### ISSUE THREAD

**Issue by ikeji** [davatorium/rofi#1836]
### Before opening a feature request

- [X] I checked the *next* branch to see if the feature has already been implemented
- [X] I searched existing reports to see if it is already requested.

### What is the user problem or growth opportunity you want to see solved?

In the case, most of time run one command but sometime changed to different command.
I want to add a default program as command line argument.

Ex. -it is an argument for initial text.
echo "vim\nemacs\ncode" | rofi -dmenu -it "vim"

Ex. have multiple choice but preferred set
$ ls ~/bin
abc
def
preferred-abc
preferred-def
$ rofi -show run -it "preferred-"

### How do you know that this problem exists today? Why is this important?

dmenu already have this option.
https://tools.suckless.org/dmenu/patches/initialtext/

### Who will benefit from it?

When I use rofi in part of other script.

### Rofi version (rofi -v)

next

### Configuration

N/A

**Comment by DaveDavenport** [comment]
This option already exists (for >= 8 years).

`-filter 'test'` to pre-set the filter.

https://davatorium.github.io/rofi/current/rofi.1/

**Comment by ikeji** [comment]
Oh, sorry I missed that.
Thanks,
