### ISSUE TITLE
[BUG] Please enable xcb_imdkit by default to allow input method for Chinese (like fcitx)

### ISSUE THREAD

**Issue by lzh01** [davatorium/rofi#1841]
### Rofi version (rofi -v)

1.7.3

### Configuration

NA

### Theme

NA

### Launch command

NA

### Step to reproduce

not able to type Chinese in rofi (the key to switch input method not working)

### Expected behavior

able to type chinese to filter options

### Actual behavior

not able to.

### Additional information

after I build a local rofi version with xcb_imdkit enabled, I am able to type Chinese now. but the distribution I not include this library.

```
meson setup --reconfigure -Dimdkit=true --prefix=~/.local/ build
```

### Using wayland display server protocol

- [X] No, I don't use the wayland display server protocol

### I've checked if the issue exists in the latest stable release

- [X] Yes, I have checked the problem exists in the latest stable version

**Comment by DaveDavenport** [comment]
Please follow the guidelines...
https://github.com/davatorium/rofi/pull/1735
