### ISSUE TITLE
[BUG] No keyboard input

### ISSUE THREAD

**Issue by DeathOfBalance** [davatorium/rofi#1846]
### Rofi version (rofi -v)

Version 1.7.3

### Configuration

https://gist.github.com/DeathOfBalance/eeffd6abccef3fb5e8af3a76e9e197fc

### Theme

https://gist.github.com/DeathOfBalance/93593755a0d93e70d0acbac46adb0762

### Launch command

rofi -show run

### Step to reproduce

* Open terminal
* Type rofi -show run
* Anything I type goes to the terminal and not the rofi window; it's impossible to type in the filter box. Mouse input works fine.

### Expected behavior

To be able to type in rofi.

### Actual behavior

All keyboard input goes in the background applications.

### Using wayland display server protocol

- [x] No, I don't use the wayland display server protocol

### I've checked if the issue exists in the latest stable release

- [X] Yes, I have checked the problem exists in the latest stable version

**Comment by DaveDavenport** [comment]
Can you paste the output of `rofi -h`?
Are you sure you don't run wayland? This tends to happen under wayland.

**Comment by DeathOfBalance** [comment]
Sorry, turns out that I am using Wayland. I haven't used Ubuntu in a while and I didn't realize that this is now the default. Is only Xorg supported?

**Comment by DaveDavenport** [comment]
Yes. There are two solutions, switch to Xorg in your login manager, or for rofi under wayland see the lbonn fork. This is linked on the page [as linked](https://github.com/DaveDavenport/rofi/wiki/Wayland)  in guidelines/issue template.
