### ISSUE TITLE
[BUG] Gnome apps don't open via rofi, only via terminal

### ISSUE THREAD

**Issue by victorpigmeo** [davatorium/rofi#1854]
### Rofi version (rofi -v)

Version: 1.7.5

### Configuration

https://gist.github.com/victorpigmeo/ea7b25ee6005c2e8f0fe0f2ed17bbb19

### Theme

https://gist.github.com/victorpigmeo/65c86a8a90a097f514b77aaf6db74b8c

### Timing report

https://gist.github.com/victorpigmeo/8760a44f16fc64a7547e9810569a33a8

### Launch command

rofi -show drun -show-icons -theme $HOME/.config/rofi/launchers/type-7/style-7.rasi

### Step to reproduce

- Try to open a gnome app from bspwm (like nautilus or gnome-calculator)

### Expected behavior

The app opens

### Actual behavior

Nothing happens

### Additional information

On [this gist](https://gist.github.com/victorpigmeo/8760a44f16fc64a7547e9810569a33a8) the 4 last lines are me trying to open gnome-calculator from rofi, that icon that it complains exists and I have read permission on it. Opening from the terminal works normally (`gnome-calculator` command). The same behavior occurs with `nautilus` opening from terminal (`nautilus &` command) works normally but from rofi nothing happens. 

ps. I don't know if I'm using wayland protocol 😕 

### Using wayland display server protocol

- [X] No, I don't use the wayland display server protocol

### I've checked if the issue exists in the latest stable release

- [X] Yes, I have checked the problem exists in the latest stable version

**Comment by DaveDavenport** [comment]
It works fine for me.

How do you launch rofi? it seems the environment rofi is launched from breaks gnome-calculator?

**Comment by DaveDavenport** [comment]
can you paste output of `rofi -h` and list what gnome version and distro you are using?

**Comment by dannycolin** [comment]
Do you know if the Gnome apps not working with Rofi are Flatpak packages? Does it also happen if you launch Rofi from a terminal (same command you mentioned) instead of bspwm/sxhkd?

**Comment by DaveDavenport** [comment]
No reaction. closing.
