### ISSUE TITLE
[BUG]  rofi doesn't open mimetypes with a cli applications setted as the default one

### ISSUE THREAD

**Issue by thealio** [davatorium/rofi#1861]
### Rofi version (rofi -v)

1.7.5

### Configuration

https://gist.github.com/thealio/be5da24c362ccfc5906e75d06ad5a7f2

### Theme

https://gist.github.com/thealio/6feea66fe41172b21d4fc2b709fcbf15

### Launch command

find ~ | rofi -dmenu -i | xargs -r -0  xdg-open

### Step to reproduce

Hi
I have an issue with a script I wrote

```
#!/bin/sh
#
find ~ | rofi -dmenu -i | xargs -r -0  xdg-open
```
I have setted vifm (cli file manager) as default on my ` ~/.config/mimeapp.list`
```
inode/directory=vifm.desktop
inode/mount-point=vifm.desktop
```
if I launch  `find ~ | rofi -dmenu -i | xargs -r -0  xdg-open`   from a terminal, the folders are correctly opened using `vifm`

But, if I launch my sh script with a keybind shortcut , it doesn't work , even using Shift+Enter

### Expected behavior

I expected that, when I launch this simple script using a key combination (not from a terminal) and I press Enter on a folder, the folder were opened in vifm

### Actual behavior

vifm didn't be opened

### Additional information

OS: Arch Linux

Additional infos:

The folder was opened in firefox

if I uninstall firefox , nothing happens

Running the command via terminal, it works as expected

### Using wayland display server protocol

- [X] No, I don't use the wayland display server protocol

### I've checked if the issue exists in the latest stable release

- [X] Yes, I have checked the problem exists in the latest stable version

**Comment by DaveDavenport** [comment]
rofi does not open any application in the pasted script.  I do not see how this is a rofi issue?

**Comment by thealio** [comment]
The script opens files and folders setted in the mimeapps.list file using xdg-open 

It doesn't launch applications

**Comment by DaveDavenport** [comment]
1.) xdg-open does the launching of application/folder/file. rofi in this situation only selects an entry. It has 0 involvement in the issue.
2.) If there is a different between launching from terminal and keybinding. It is most likely an issue with the environment.  Check if the environment passed to the script when launched for the keybinding is correct for xdg-open to function.

**Comment by DaveDavenport** [comment]
> The script opens files and folders setted in the mimeapps.list file using xdg-open
> 
> It doesn't launch applications

it does (via xdg-open) launch~es~ an application to open the file or folder.

**Comment by thealio** [comment]
Hi
It seems an old xdg-open unresolved bug

https://q2a.vifm.info/1455/vifm-as-default-filemanager-using-xargs?show=1463#c1463

https://unix.stackexchange.com/questions/177976/set-default-xdg-open-application-to-terminal-program/590093#590093

This suggest me a feature request: specify a terminal command for applications declared by the user.
Example: let's suppose I want to start vifm using run mode in rofi.
The binary won't start, of course, because it's a terminal application.
So, i n this case, I need an option that permits me to declare a terminal where the application have to be launched, ex. alacritty -e.
So in the confg file I need to set
- the default terminal
- if I want to open in a terminal all the binariries in run mode, or only someone specifically declared by the user

**Comment by DaveDavenport** [comment]
this already exists.

**Comment by thealio** [comment]
Nice
How can I do that?
I read the manpage, but it's unclear to me

I meant, I'd like to open all the binaries in the terminal just pressing Enter

**Comment by DaveDavenport** [comment]
change `run-command` or the binding for running in terminal.

**Comment by thealio** [comment]
I

> change `run-command` or the binding for running in terminal.

How it can be done?
Sorry, I haven't findvhow to do that

**Comment by DaveDavenport** [comment]
Change `run-command` in your rofi configuration file or commandline.

```bash
rofi -run-command '{terminal} -e {cmd}' -show run -modi run
```

This is all in manpage

**Comment by thealio** [comment]
Thank you!
I'll try it this evening
