### ISSUE TITLE
[REQUEST] make rofi independ of workspace

### ISSUE THREAD

**Issue by forestchen1224** [davatorium/rofi#1874]
### Before opening a feature request

- [X] I checked the *next* branch to see if the feature has already been implemented
- [X] I searched existing reports to see if it is already requested.

### What is the user problem or growth opportunity you want to see solved?

The keyboard will be lost after switching to a different workspace in sway.
This may be a bug related to wayland.
If each workspace has its own instance of rofi, the problem may be alleviated. 

### How do you know that this problem exists today? Why is this important?

as above

### Who will benefit from it?

sway users or wayland users

### Rofi version (rofi -v)

Version: 1.7.5

### Configuration
config: https://gist.github.com/forestchen1224/e68397477bb607b2d1aa532c50a4934d
theme:https://gist.github.com/forestchen1224/e223c138d30147a87d1b5b173764f04e

**Comment by DaveDavenport** [comment]
As mentioned in BOLD in the template and the guidelines:

> **Please do not submit reports related to wayland, see [here](https://github.com/DaveDavenport/rofi/wiki/Wayland) for more information.**
