### ISSUE TITLE
[BUG]  Failed to set locale 

### ISSUE THREAD

**Issue by Adamkaram** [davatorium/rofi#1877]
### Rofi version (rofi -v)

Version: 1.7.5

### Configuration

https://gist.github.com/Adamkaram/52decc81643aa87c57e4d7aedb3efc7e

### Theme

https://gist.github.com/Adamkaram/8c585a4bea729b5e6afc49618fd3fb23

### Timing report

https://gist.github.com/Adamkaram/a30b932ec684ffc7e18191e1f6edb90b

### Launch command

rofi -show drun

### Step to reproduce

rofi -show drun
rofi spotify 

### Expected behavior

to open spotify 

### Actual behavior

(process:36673): Rofi-WARNING **: 06:36:44.391: Failed to set locale.

### Additional information

nothing is working except if i do 
LANG=C rofi -show drun
or 
 export LC_ALL="C" 
 
or 

 editing `/etc/default/locale` file
```
LC_ALL="C"
insted of LC_ALL=en_us_utf-8
```

u could see my disscusion about locales i've and decide if it's not a bug

### Using wayland display server protocol

- [X] No, I don't use the wayland display server protocol

### I've checked if the issue exists in the latest stable release

- [X] Yes, I have checked the problem exists in the latest stable version

**Comment by DaveDavenport** [comment]
This is not a rofi bug, it is normally misconfiguration of the host system.
As I mentioned before rofi directly passes this on to an underlying library that then throws the error. 


Closing as it is not a rofi bug.
