### ISSUE TITLE
[REQUEST] Support YAML config alongside rasi

### ISSUE THREAD

**Issue by EmilyGraceSeville7cf** [davatorium/rofi#1884]
### Before opening a feature request

- [X] I checked the *next* branch to see if the feature has already been implemented
- [X] I searched existing reports to see if it is already requested.

### What is the user problem or growth opportunity you want to see solved?

There is [no IntelliSence (link to extension)](https://marketplace.visualstudio.com/items?itemName=dlasagno.rasi) in VS Code for .rasi files, just syntax highlighting. So it's not very convenient to write .rasi files without any assistance.

### How do you know that this problem exists today? Why is this important?

There is no JSON schema available for rofi neither in SchemaStore nor here. Also, AFAIS there is no YAML config support for now.

### Who will benefit from it?

Users who use YAML Red Hat extension in VS Code or similar extensions in other editors which provide IntelliSence based on JSON schema.

### Rofi version (rofi -v)

1.7.1

### Configuration

default settings

### Additional information

I [can](https://github.com/SchemaStore/schemastore/pulls/EmilySeville7cfg) write JSON schemas, so this is one of the reasons I'm suggesting this feature to be implemented. I can design YAML schema and provide YAML config examples I would like to see.

As a sidenote, [there is](https://github.com/yamnikov-oleg/projektor#configuration) already application launcher (at least one) configured in YAML.

**Comment by EmilyGraceSeville7cf** [comment]
Another possible solution of issue not having config linting is to implement LSP for .rasi. But I can't do it right now, unfortunately.

**Comment by DaveDavenport** [comment]
I have no plans for changing the config file or supporting multiple parsers. 

> As a sidenote, [there is](https://github.com/yamnikov-oleg/projektor#configuration) already application launcher (at least one) configured in YAML.

Great, so there is a solution for you.

**Comment by DaveDavenport** [comment]
On a side note, yaml can be terrible to work with.  While I don't have time go into details, this 
https://ruudvanasseldonk.com/2023/01/11/the-yaml-document-from-hell explains some of the issues I've ran into.

**Comment by EmilyGraceSeville7cf** [comment]
Thanks for the article. ;)
