### ISSUE TITLE
[BUG] Microsoft Teams is at the top of sort when searching for pycharm

### ISSUE THREAD

**Issue by f0ff886f** [davatorium/rofi#1885]
### Rofi version (rofi -v)

Version: 1.7.5

### Configuration

https://gist.github.com/f0ff886f/bda841bbb955ab240795c8c69fa9f69a

### Theme

https://gist.github.com/f0ff886f/3488cd3c8fa6d61300fc458204747979

### Launch command

`rofi drun -show drun -matching fuzzy -sort -sort-method fzf -theme Arc-Dark`

### Step to reproduce

Open rofi with `rofi drun -show drun -matching fuzzy -sort -sort-method fzf -theme Arc-Dark`
Type `pycharm`

Observe `Microsoft Teams` is at the top of the list

### Expected behavior

Pycharm would be first on the list and likely the only thing on the list.

### Actual behavior

Microsoft Teams shows up and it is really adamant about being everywhere.

It is the first result for `pyc` and it shows up if I just type `subl` too.

### Additional information

Contents of `~/.local/share/applications/msedge-cifhbcnohmdccbgoicgdjpfamggdegmo-Default.desktop`:

In case this has anything to do with it...

```
#!/usr/bin/env xdg-open
[Desktop Entry]
Version=1.0
Terminal=false
Type=Application
Name=Microsoft Teams
Exec=/opt/microsoft/msedge/microsoft-edge --profile-directory=Default --app-id=cifhbcnohmdccbgoicgdjpfamggdegmo "--app-url=https://teams.microsoft.com/?clientType=pwa"
Icon=msedge-cifhbcnohmdccbgoicgdjpfamggdegmo-Default
StartupWMClass=crx__cifhbcnohmdccbgoicgdjpfamggdegmo
```

Contents of `/usr/local/applications/pycharm-professional.desktop`:

```
[Desktop Entry]
Type=Application
Name=PyCharm Professional Edition
Icon=pycharm
Comment=Python IDE for Professional Developers.
Exec=pycharm %f
Terminal=false
Categories=Development;IDE;Python;
StartupNotify=true
StartupWMClass=jetbrains-pycharm
```

### Using wayland display server protocol

- [X] No, I don't use the wayland display server protocol

### I've checked if the issue exists in the latest stable release

- [X] Yes, I have checked the problem exists in the latest stable version

**Comment by f0ff886f** [comment]
Sorry this is a literal photo, but my printscr button doesn't work when rofi is active:

![image](https://github.com/davatorium/rofi/assets/528239/cf8e7ae4-b5cb-4692-9b1c-47c7de75bba5)

**Comment by DaveDavenport** [comment]
Its a side effect of the fuzzy matcher that is 'fuzzy'. Especially with randomized strings in the searched fields.
@MaskRay  do you have any input on this?

Using the normal matcher this does not happen.

**Comment by DaveDavenport** [comment]
You can also tweak what it searches with `-drun-match-fields`.

**Comment by DaveDavenport** [comment]
> Sorry this is a literal photo, but my printscr button doesn't work when rofi is active:
> 
> ![image](https://user-images.githubusercontent.com/528239/258806561-cf8e7ae4-b5cb-4692-9b1c-47c7de75bba5.png)

There is a screenshot keybinding in rofi.  (Alt+Shift+s)

**Comment by f0ff886f** [comment]
Oh! Thank you for that hint:

```
rofi drun -show drun -matching fuzzy -sort -sort-method fzf -theme Arc-Dark -drun-match-fields name
```

worked perfectly. And thank you for the screenshot hint!
