### ISSUE TITLE
However, rofi uses black text instead in the newer releases.

### ISSUE THREAD

**Issue by ReneFroger** [davatorium/rofi#1886]
### Rofi version (rofi -v)

1.7.1 and 1.7.5

### Configuration

https://gist.github.com/ReneFroger/7081306666fe8f7136b9bb4a8c427c3b

### Theme

https://gist.github.com/ReneFroger/40f6ba1c4f422f0ec3479aa2da8be76b

### Launch command

rofi -show drun

### Step to reproduce

In rofi 1.5.4 with the `Mycustomtheme` (As indicated in the [confirguration file](https://gist.github.com/ReneFroger/7081306666fe8f7136b9bb4a8c427c3b) and [theme file](https://gist.github.com/ReneFroger/40f6ba1c4f422f0ec3479aa2da8be76b)) I have the following output with `rofi -show drun`:

![image](https://github.com/davatorium/rofi/assets/5211845/bfc60e18-d7bc-4d6c-8991-113ad12fc39b)

It works fine. 

When I upgraded my system to 22.04, the new rofi version is included. 

The version is 1.7.1. But the output of `rofi -show drun looks however like this:

![image](https://github.com/davatorium/rofi/assets/5211845/b850c01c-4041-46a2-a015-bfdbd4eeb057)

### Expected behavior

The foreground property should be recognized by Rofi. 

### Actual behavior

I tried to debug it with making everything white in my theme file. When launch `rofi -show drun` with the adjusted theme file, everything is white except the text of application files, they stay black whereas they should be supposed to be white too . So I suspect there might another foreground property in the newer releases of Rofi, because the changed value for foreground are not 'seen' by Rofi (as in that the text stays black).  Or it doesn't exist anymore for Rofi. I looked into the documentation what might be changed there, but it wasn't mentioned there, only that there were more dynamic variables added for themes.

So the conclusion is that rofi in the newer releases uses system-wide text color/black text instead of the color in theme configuration, and doesn't take foreground property into consideration for text.

### Using wayland display server protocol

- [X] No, I don't use the wayland display server protocol

### I've checked if the issue exists in the latest stable release

- [X] Yes, I have checked the problem exists in the latest stable version

**Comment by DaveDavenport** [comment]
Did you read? https://github.com/davatorium/rofi/issues/1397. It is pinned on the issue page.

**Comment by DaveDavenport** [comment]
> I looked into the documentation what might be changed there, but it wasn't mentioned there, only that there were more dynamic variables added for themes.

It is:
https://github.com/davatorium/rofi/releases/tag/1.7.0

**Comment by DaveDavenport** [comment]
Closing. Not  bug.

**Comment by ReneFroger** [comment]
I couldn't find it earlier when looking on "foreground", but thanks for letting me know. All your work for Rofi is really appreciated, Dave!
