### ISSUE TITLE
[BUG] Searching for a theme fails when a file exists in CWD with the same name

### ISSUE THREAD

**Issue by aarondill** [davatorium/rofi#1889]
### Rofi version (rofi -v)

Version: 1.7.1 AND Version: 1.7.5

### Configuration

N/A

### Theme

N/A

### Timing report

https://gist.github.com/aarondill/405e6a5811943cbcd84fa6c59c47a8b2

### Launch command

rofi -show

### Step to reproduce

1. `mkdir -p ~/.config/rofi`
2. make `~/.config/rofi/config.rasi` with the contents `@theme "theme_name"`
3. `touch ~/.config/rofi/theme_name.rasi`
4. Create a file in your CWD with the name `theme_name`
5. `rofi -show`
6. Observe the failure from `rofi` (<HOME>/<USER> was the absolute path):

```
The following errors were detected when starting rofi:

Failed to open theme: /<HOME>/<USER>/.config/rofi/theme_name
Error: No such file or directory
```

7. `touch ~/.config/rofi/theme_name` (notice no `.rasi`)
8. `rofi -show`
9. Success. :frowning_face: This is not supposed to happen.
10. `rm ~/.config/rofi/theme_name`
11. `rm ./theme_name`
12. `rofi -show`
13. Success :smile:

### Expected behavior

The presence of a file in your CWD with the name of the theme should _not_ rofi's ability to search `XDG_CONFIG_HOME` (or other files) for the theme

### Actual behavior

A file named the same as the theme in your CWD makes rofi search for the theme without a file extension.

### Additional information

This is _not_ an issue with `@theme "theme_name.rasi"`. Since the `.rasi` extension is never added anyways, `theme_name.rasi` _is_ correctly found.

### Using wayland display server protocol

- [X] No, I don't use the wayland display server protocol

### I've checked if the issue exists in the latest stable release

- [X] Yes, I have checked the problem exists in the latest stable version

**Comment by aarondill** [comment]
[Here](https://gist.github.com/aarondill/22826603f4aeb3e3171a10dc58b514d7) is a simple bash script that can be used to test this.
Simply run `./repro.sh` and press escape when `rofi` spawns:
```shell
./repro.sh
With file in CWD - @theme without .rasi
should pass: failed
should pass: failed
should fail: passed

Without file in CWD - @theme without .rasi
should pass: passed
should pass: passed
should fail: failed

With file in CWD - @theme full name
should pass: passed
should pass: passed
should fail: passed

Without file in CWD - @theme full name
should pass: passed
should pass: passed
should fail: failed
```

**Comment by DaveDavenport** [comment]
To avoid confusion, what do you mean with version  1.7.6?
The latest stable is 1.7.5, the latest git is 1.7.5-162-g52841926.

**Comment by aarondill** [comment]
@DaveDavenport That was a typo. I downloaded the latest stable (1.7.5) and tested against it.

**Comment by DaveDavenport** [comment]
Thanks, and thanks for updating the issue.

I see that on trying to open the file it does:

```c
fn = rofi_expand_path(file)l
if ( g_file_test(fn,EXISTS)){
}
```

Before it tries to look up the path.
This causes the issue, lets fix this.

**Comment by DaveDavenport** [comment]
This needs testing.

**Comment by DaveDavenport** [comment]
The specified file can either by *name*, *filename*,*full path*.

If a filename is provided, it will try to resolve it in the following order:

- If path is absolute and file exists, it will open the file. This includes expansion of '~' or '~user'
- On an `@import` or `@theme` it looks in the directory of the file that tried to include  it.
- `${XDG_CONFIG_HOME}/rofi/themes/`
- `${XDG_CONFIG_HOME}/rofi/`
- `${XDG_DATA_HOME}/rofi/themes/`
- `${INSTALL PREFIX}/share/rofi/themes/`

A name is resolved (if it has no valid extension) as a filename by appending the `.rasi` extension.

**Comment by DaveDavenport** [comment]
pushed some more small (backward comp.) fixes.
