### ISSUE TITLE
[BUG] Combi modes always display the same wrong view

### ISSUE THREAD

**Issue by timmytit** [davatorium/rofi#1908]
### Rofi version (rofi -v)

Version: 1.7.3

### Configuration

https://gist.github.com/timmytit/922a888042e665371f755fb7947cce6b

### Theme

https://gist.github.com/timmytit/43b09ce40187b097b6f1b4188d37764a

### Timing report

https://gist.github.com/timmytit/77ab4ffadc7019c4e1b05bb5821219ae

### Launch command

rofi -modi combi,drun,window -combi-mode "window,drun" -show

### Step to reproduce

1. Open terminal
2. Enter the "Launch command" or any of the following variations of it:

> rofi -modi combi,drun,window -combi-mode "window,drun" -show combi

> rofi -show combi -modi combi,drun,window -combi-mode "window,drun" 

4. See rofi pop up on the screen with a combination of `window` and `run`
5.  Cry

### Expected behavior

Expect rofi to show `window` and `drun`.

### Actual behavior

Rofi shows `window` and `run`.

![image](https://github.com/davatorium/rofi/assets/97111235/8e938ad8-57c5-4d0c-b33f-35d243c7a43e)

### Additional information

It does not matter what `-combi-mode`s I use, they all show the same thing. Even if I do only one mode in the `combi-mode`.

### Using wayland display server protocol

- [X] No, I don't use the wayland display server protocol

### I've checked if the issue exists in the latest stable release

- [ ] Yes, I have checked the problem exists in the latest stable version

**Comment by DaveDavenport** [comment]
If you want other modes combined in  the combi mode, you need to configure it to use other modes.

For 1.7.3 and up:

```bash
rofi -show combi -combi-modi 'window,drun'
```
and/or
for 1.7.4 and up:

```bash
rofi -show combi -combi-modes 'window,drun'
```


``` -combi-mode``` is not a valid argument.
