### ISSUE TITLE
[BUG] Segmentation fault

### ISSUE THREAD

**Issue by Sogomn** [davatorium/rofi#1911]
### Rofi version (rofi -v)

1.7.5

### Configuration

https://gist.github.com/Sogomn/cc3977d4af97da018ec06f74d4da331d

### Theme

https://gist.github.com/Sogomn/1f2673974e791876f5fdaae42ea9fae9

### Timing report

https://gist.github.com/Sogomn/cd282c17dbd39c0883954ac37e3f0854

### Launch command

rofi -dmenu -p  -config ~/.config/rofi/config_single_line.rasi

### Step to reproduce

* Launch Rofi with the given config and theme
* Kernel version 6.5.9_1

### Expected behavior

* No segfault

### Actual behavior

* Segfault

### Additional information

* Excluding the `-p` argument does not make a difference
* It works with a very similar theme: https://gist.github.com/Sogomn/11351f07812d4790e2034f512d333a19

### Using wayland display server protocol

- [X] No, I don't use the wayland display server protocol

### I've checked if the issue exists in the latest stable release

- [X] Yes, I have checked the problem exists in the latest stable version

**Comment by DaveDavenport** [comment]
can you generate a backtrace?

(it does not crash for me)

**Comment by DaveDavenport** [comment]
Can you explain your config:
```
rofi -dmenu -p  -config ~/.config/rofi/config_single_line.rasi
```

What is exactly in the config here? 


I suspect this one is fixed in git, can you confirm? (#1759)

**Comment by Sogomn** [comment]
I don't know my way around the C tools very well, how do I compile it to get the backtrace?

> What is exactly in the config here?

It's the one I linked: https://gist.github.com/Sogomn/cc3977d4af97da018ec06f74d4da331d
This is the entire file:
```
@import "~/.config/rofi/config"
@theme "~/.config/rofi/theme_single_line"
```

**Comment by DaveDavenport** [comment]
> I don't know my way around the C tools very well, how do I compile it to get the backtrace?
> 
> > What is exactly in the config here?
> 
> It's the one I linked: https://gist.github.com/Sogomn/cc3977d4af97da018ec06f74d4da331d This is the entire file:
> 
> ```
> @import "~/.config/rofi/config"
> @theme "~/.config/rofi/theme_single_line"
> ```

Thanks, I wanted to confirm how you loaded every part. 

I am pretty sure it is fixed in git.

**Comment by Sogomn** [comment]
Ah I searched for "segmentation" so I didn't find that one. Will try and update the issue.

**Comment by Sogomn** [comment]
Yep that fixed it. Closing this, thanks!

**Comment by DaveDavenport** [comment]
Thanks for testing.
