### ISSUE TITLE
[REQUEST] Allow output of `Type=Link` files' `URL` in `drun-display-format`

### ISSUE THREAD

**Issue by aarondill** [davatorium/rofi#1914]
### Before opening a feature request

- [X] I checked the *next* branch to see if the feature has already been implemented
- [X] I searched existing reports to see if it is already requested.

### What is the user problem or growth opportunity you want to see solved?

I would like to display the `URL` of my desktop files with `Type=Link` while using drun.

### How do you know that this problem exists today? Why is this important?

I've tried the intuitive way of displaying the '{exec}' field, but this is a null field when using URLs. I've also searched the source, hoping for an (undocumented) way to do this, but the code only checks for `dr->exec` (NULL), thusly this is currently impossible.

https://github.com/davatorium/rofi/blob/9cea843b4df98884a440acb50df1a1d1d667a4c5/source/modes/drun.c#L1338-L1341

Note: it seems there may be a bug in the current implementation. Shouldn't `dr->exec` be escaped too (like name, comment, and generic_name)?

### Who will benefit from it?

Anyone who wants to *know* what pressing a button would do (typically the same people that would display the `{exec}` field)

### Rofi version (rofi -v)

Version: 1.7.1 (and HEAD)

### Configuration

https://gist.github.com/aarondill/b809c4954f2d1147a2cfeebb83d20c20

### Additional information

One of two implementations could be chosen:
1. Create a new `{url}` field, null if using Type=Application, like `{exec}` is for Type=Link
2. Assign the `{exec}` field to the URL when using Type=Link (more intuitive IMO)

**Comment by DaveDavenport** [comment]
Please test above commit.

**Comment by aarondill** [comment]
It works amazingly for me! Glad to finally be able to search for the URLs of my Links! :smile:

**Comment by DaveDavenport** [comment]
>  It works amazingly for me! Glad to finally be able to search for the URLs of my Links! 😄

I don't think that was requested?

**Comment by DaveDavenport** [comment]
Should work now.

**Comment by aarondill** [comment]
> > It works amazingly for me! Glad to finally be able to search for the URLs of my Links! 😄
> 
> I don't think that was requested?

It wasn't explicitly requested, but by including it in drun-display-format, it became searchable

**Comment by DaveDavenport** [comment]
>  but by including it in drun-display-format, it became searchable

not until the last commit.

**Comment by aarondill** [comment]
Oh! You seem to be correct. My mistake. I've set the Comment field in my Links to the same as the URL as a hack for this previously, so I didn't realize it was still matching due to that.
