### ISSUE TITLE
[BUG] Rofi breaks if started with alternate keyboard layout, since Ubuntu 23.04

### ISSUE THREAD

**Issue by fleutot** [davatorium/rofi#1915]
### Rofi version (rofi -v)

1.7.3

### Configuration

https://gist.github.com/fleutot/3373c79ad74eb1f561add7207ca7f36c

### Theme

https://gist.github.com/fleutot/22847d1667fb20c56ef2c3125088d734

### Launch command

rofi -show

### Step to reproduce

- set xkbcomp layout with `setxkbmap us,se -option 'grp:alt_caps_toggle'`
- start `rofi -show`
- type a letter, then backspace. Expect it to work
- get [my keyboard config](https://raw.githubusercontent.com/fleutot/kinesis/fix-undefined/kinesis-wip.xkb) into a local file (it is pretty standard, only a key swap for one group. See the [process to create this file](https://github.com/fleutot/kinesis/blob/fix-undefined/todo.md)).
- activate the layout: `xkbcomp ~/kinesis/kinesis-wip.xkb $DISPLAY`
- start `rofi -show`
- type a letter, then backspace. Expect it to work
- exit rofi with Ctrl+g
- swap layout group with Alt+Caps Lock
- start `rofi -show`
- type a letter, then backspace. Backspace does not work. Ctrl+g does not work, arrows, Enter, nothing works. Additional letters do work.

### Expected behavior

All control keys continue to work after selecting Group2 in a custom xkbcomp setup.

### Actual behavior

Control keys, escape, enter, and so on, stop working if using Group2 of a custom xkbcomp setup.

### Additional information

I understand that the error might be some other place than rofi. Either way, I would appreciate help in investigating this further.

My method of creating my xkb config is [pretty standard](https://wiki.archlinux.org/title/X_keyboard_extension). It was working fine until I upgraded from Ubuntu 22.04 to 23.04. I am not sure if the breaking change was in X, or rofi, or some other place.

Some more background: in xmonad WM.

### Using wayland display server protocol

- [X] No, I don't use the wayland display server protocol

### I've checked if the issue exists in the latest stable release

- [ ] Yes, I have checked the problem exists in the latest stable version

**Comment by fleutot** [comment]
I just built rofi 1.7.5, it seems to work there.

**Comment by DaveDavenport** [comment]
I think it is related to this one: https://github.com/davatorium/rofi/issues/1642

**Comment by fleutot** [comment]
I don't know about the release cycle, but is there any way to notify Canonical that the current release distributed with apt in Ubuntu 23.04 is broken, and make them upgrade? I mean, if 1.7.3 breaks for every user with an AltGr key (or is it only for multiple layouts?), it's in rofi's interested to make Ubuntu upgrade with the fix?

**Comment by DaveDavenport** [comment]
I have no idea why ubuntu 23.04 ships a version from jan. 2022. 

I do not have the time to  chase distros to update their packages.

**Comment by fleutot** [comment]
Got it, I was not implying that you would or should. I guess some bigger projects have some kind of "distro chasing" strategy, so I was just throwing that bottle into the ocean. Your work is much appreciated.
