### ISSUE TITLE
[BUG] Cannot change `lines` property of `listview` during runtime in script mode

### ISSUE THREAD

**Issue by mageowl** [davatorium/rofi#1917]
### Rofi version (rofi -v)

1.7.5

### Configuration

https://gist.github.com/mageowl/a1a5e579d4c18d5ee30723da8b6d18fa

### Theme

https://gist.github.com/mageowl/a1a5e579d4c18d5ee30723da8b6d18fa

### Launch command

rofi -show {script}

### Step to reproduce

1. Create a script stored in ~/.config/rofi/scripts/
```bash
#!/bin/env bash
# bug_report.bash
echo "Change number of lines"
[[ $ROFI_RETV = 1 ]] && echo "\0theme\xf1listview { lines: 1; }"
```
2. Run rofi using `rofi -show bug_report`
3. Choose the hello there option.

### Expected behavior

After choosing the option, the number of displayed lines would be reduced to one.

### Actual behavior

Nothing happens.

### Using wayland display server protocol

- [X] No, I don't use the wayland display server protocol

### I've checked if the issue exists in the latest stable release

- [X] Yes, I have checked the problem exists in the latest stable version

**Comment by mageowl** [comment]
It also does not work to change the `children` property.

**Comment by DaveDavenport** [comment]
Yes, this is not supported. The interface is build up once on startup and cannot be modified afterwards (except for some colors).

added clarification in manpage.
