### ISSUE TITLE
Rofi as a open selector

### ISSUE THREAD

**Issue by pzant** [davatorium/rofi#1923]
### Before opening a feature request

- [X] I checked the *next* branch to see if the feature has already been implemented
- [X] I searched existing reports to see if it is already requested.

### What is the user problem or growth opportunity you want to see solved?

It would be great if I could use rofi to select the application that will open the file specified in one of the arguments.

### How do you know that this problem exists today? Why is this important?

I haven't figured out how to do this via dmenu, so I'm asking for advice.

### Who will benefit from it?

A function that could replace "Open With" in file managers and replace xdg-open for the terminal.

### Rofi version (rofi -v)

Version: 1.7.5

### Configuration

default

**Comment by DaveDavenport** [comment]
> I haven't figured out how to do this via dmenu, so I'm asking for advice.

Is the discussion forum then not the better place?

To pick an application in ""dmenu"" mode:

```bash
 rofi -show drun -modes drun -run-command 'echo {cmd}'
```
Then you can get the result and launch it ?

rofi has a file picker build in, so if you run `rofi -show drun` select your application, hit ctrl-l  (kb-mode-complete) it switches to file browser (if the application indicates it can open a file in its desktop file)  allow you to select the file and launch it using the selected application (also works in run mode).

**Comment by pzant** [comment]
@DaveDavenport Perhaps a discussion would be a better place. File picker is not quite suitable for this task. The above solutions is suitable. Thank you.
