### ISSUE TITLE
[BUG] In window mode, some apps don't have an icon

### ISSUE THREAD

**Issue by Luzzifus** [davatorium/rofi#1931]
### Rofi version (rofi -v)

1.7.5-189-g11d801ea-dirty (next)

### Configuration

https://gist.github.com/Luzzifus/468af44845b0729358dbd8a6bab5a3be

### Theme

https://gist.github.com/Luzzifus/53e44e97dd9171f4e8a730d1adfc0321

### Launch command

rofi -show window

### Step to reproduce

* get one of the problematic applications listed below
* execute launch command
* look at icons of application windows

### Expected behavior

All application windows in the list should have an icon.

### Actual behavior

This works for most applications, but not all. The applications in question do have an icon in drun mode, but not in window mode when they have been started already. There is no error message, just the space for the icon is blank.

Some examples for applications missing icons in window mode:
* Freetube (flatpak)
* Upnote - (snap)
* Pinta - (flatpak)
* Paleta - (flatpak)
* gnome-multi-writer

### Additional information

* I am running Pop! OS 22.04.
* This problem occurred for me in v1.7.1 (via apt) as well as the latest version (next branch, compiled from source). 
* Other launchers can display the icons fine (e.g. the Cosmic Launcher in Pop! OS).

### Using wayland display server protocol

- [X] No, I don't use the wayland display server protocol

### I've checked if the issue exists in the latest stable release

- [X] Yes, I have checked the problem exists in the latest stable version

**Comment by DaveDavenport** [comment]
There is no relation between "run" and "window" in source of icon.

Therefor if the application does not set an icon on its windows, and the class name does not resolve to an icon, rofi has nothing to display .

I am also confused,  "gnome-multi-writer" has no icon under "run" only under "drun" on pop! os 22.04..

**Comment by Luzzifus** [comment]
> I am also confused, "gnome-multi-writer" has no icon under "run" only under "drun" on pop! os 22.04..

Yes, I meant drun, sorry.

**Comment by Luzzifus** [comment]
> Therefor if the application does not set an icon on its windows, and the class name does not resolve to an icon, rofi has nothing to display.

So is there a way I can "help" rofi resolve the icons? E.g. by manually placing them in the right spot with a resolvable name?

**Comment by DaveDavenport** [comment]
This:
`cp "/usr/share/icons/hicolor/256x256/apps/org.gnome.MultiWriter.png" ~/.local/share/icons/gnome-multi-writer.png`

should do it.

**Comment by Luzzifus** [comment]
Thanks, that worked. I was able to fix the other apps that way too.

**Comment by Luzzifus** [comment]
I think the frequency of this issue occurring could be reduced by searching for the executable name in .desktop files. In all of my cases the executable name is either the filename of the respective .desktop file itself (case insensitive comparison) or is part of its command field. Then the icon could be resolved from the desktop file itself.

**Comment by DaveDavenport** [comment]
That won't work in rofi's design, there is no link between desktop file and window, or "executable" and window.

 I prefer it if applications just properly set an icon on their window.
