### ISSUE TITLE
[BUG] Commands launched in 'run' mode are duplicated in history, enclosed in quotes.

### ISSUE THREAD

**Issue by yusufaktepe** [davatorium/rofi#1951]
### Rofi version (rofi -v)

1.7.5-211-geae65b2c

### Configuration

'-no-config'

### Theme

'-no-config'

### Launch command

rofi -no-config -show run

### Step to reproduce

- Open rofi in run mode.
- type some 'command' and run it.
- Now if you open rofi again, you will see 'command' is duplicated in quoted form.

### Expected behavior

Duplication should not happen.

### Actual behavior

'command' is duplicated in quoted form, as seen in the video:
[rofi-command_duplication.webm](https://github.com/davatorium/rofi/assets/32964025/9d8f7a6e-8075-4b98-9c1f-82b4e811678c)

### Using wayland display server protocol

- [X] No, I don't use the wayland display server protocol

### I've checked if the issue exists in the latest stable release

- [ ] Yes, I have checked the problem exists in the latest stable version

**Comment by DaveDavenport** [comment]
thx for reporting.  This is a known issue introduced when fixing executing of executable with a space in its name. I have not yet had time to fix.

**Comment by DaveDavenport** [comment]
Hopefully this fixes it all cases

**Comment by yusufaktepe** [comment]
Yes, it seems fixed. Thank you.
