### ISSUE TITLE
[BUG] Stop quoting entries in history when running them

### ISSUE THREAD

**Issue by quyykk** [davatorium/rofi#1961]
### Rofi version (rofi -v)

afc65ac12565e5376c602156db76f6273423a538

### Configuration

n/a

### Theme

n/a

### Launch command

rofi -show run

### Step to reproduce

1. Run say `code /path/to/project` (it's in history so gets autocompleted)
2. The full entry is quoted, so it tries to run `"code /path/to/project"` which is a non-existent command

### Expected behavior

I expect the entry to be run unquoted, respecting the arguments passed.

### Actual behavior

Quotes the full history entry before running it, result in it trying to run a command that includes the arguments.

### Additional information

I saw that this was intentional, so maybe the solution here would be to make the command handling smarter by only quoting the entry if the quoted entry is an actual command in PATH, and if not retain the old behavior (idk if this is feasible, was just an idea).

Note: Another related bug is that, if the command with spaces is *not* in the history (so no `code /path/to/project` in history), then the command doesn't get quoted and runs. This seems like an inconsistency that should probably be fixed too.

### Using wayland display server protocol

- [X] No, I don't use the wayland display server protocol

### I've checked if the issue exists in the latest stable release

- [ ] Yes, I have checked the problem exists in the latest stable version

**Comment by DaveDavenport** [comment]
#1951

**Comment by quyykk** [comment]
I don't understand how this is a duplicate. That issue is about having duplicate entries in your history, and this issue is about how commands with arguments are quoted when run (making them fail, because the arguments are not part of the command name).

**Comment by DaveDavenport** [comment]
Where did it say it is duplicate, It should be fixed by the fix in that issue.

**Comment by quyykk** [comment]
Oh sorry. But I'm on afc65ac12565e5376c602156db76f6273423a538 which should include the commit that fixes the linked issue, so it seems like this is still a problem?
