### ISSUE TITLE
[REQUEST] filter mode option

### ISSUE THREAD

**Issue by su55y** [davatorium/rofi#1962]
### Before opening a feature request

- [X] I checked the *next* branch to see if the feature has already been implemented
- [X] I searched existing reports to see if it is already requested.

### What is the user problem or growth opportunity you want to see solved?

In the rofi script, after filtering and selecting/keybind pressing, the only way I see to keep the filter is to restart rofi with the `-filter` option. Which is not even a complete solution to the problem, since there is also nowhere to get the value for the filter.

### How do you know that this problem exists today? Why is this important?

This limits me and I do not have enough competences to implement it, that is why I am opening this report.

### Who will benefit from it?

Me and possibly other rofi scripts authors.

### Rofi version (rofi -v)

Version: 1.7.5

### Configuration

-

### Additional information

The intuitive way in my opinion is to have a mode option `filter`, by analogy with `prompt`, `message` etc., and then it would be convenient to take the value for the filter from the environment variable `ROFI_INPUT`.

A more straightforward way to do the above is the `keep-filter` mode option, by analogy with `keep-selection`, but I guess it less straightforward to implement.

**Comment by DaveDavenport** [comment]
In git you the filter box has history so its one binding to get old entry back.

But `keep-filter` might be a nice option.
