### ISSUE TITLE
[REQUEST] Sort combi modes option

### ISSUE THREAD

**Issue by katashisano** [davatorium/rofi#1963]
### Before opening a feature request

- [X] I checked the *next* branch to see if the feature has already been implemented
- [X] I searched existing reports to see if it is already requested.

### What is the user problem or growth opportunity you want to see solved?

Being able to sort elements by mode in combi mode, like for example: window elements appear first in the list, then drun, then run.

### How do you know that this problem exists today? Why is this important?

I like to have rofi display apps in the .desktop format which provides description and a proper name vs the executable name, e.g.: Firefox Web Browser *(Web Browser)* / firefox. But I still need run mode for apps which don't have a .desktop or scripts I like to execute from within rofi.

### Who will benefit from it?

Me and people who like convenient sorting in their launcher.

### Rofi version (rofi -v)

1.7.5

### Configuration

https://gist.github.com/katashisano/39f4ceb1c95004f85d6c170cef77c9fa

**Comment by DaveDavenport** [comment]
I am confused what the exact request is. Combi mode does not sort or is involved with sorting, so if you specify 'window,drun,run' it should show them in that order.

This is how I use it to make sure that if I open it, type 'firefox' it switches to open window or if none is open it launches it.

edit: the attached config does not use combi mode?

**Comment by DaveDavenport** [comment]
> I like to have rofi display apps in the .desktop format which provides description and a proper name vs the executable name, e.g.: Firefox Web Browser (Web Browser) / firefox. But I still need run mode for apps which don't have a .desktop or scripts I like to execute from within rofi.

This is what combi solves? `rofi -show combi -combi-modes "drun,run"`

**Comment by katashisano** [comment]
> This is what combi solves? `rofi -show combi -combi-modes "drun,run"`
> 

Oops, I just checked my hyprland config (that's why the gist config doesn't use combi mode) and I had "window,run,drun" instead of "window,drun,run" which I thought I had, sorry for not checking well before opening this issue.
