### ISSUE TITLE
[REQUEST] 

### ISSUE THREAD

**Issue by pavukach** [davatorium/rofi#1971]
### Before opening a feature request

- [X] I checked the *next* branch to see if the feature has already been implemented
- [X] I searched existing reports to see if it is already requested.

### What is the user problem or growth opportunity you want to see solved?

I cannot find rofi-wayland-devel package on fedora.

### How do you know that this problem exists today? Why is this important?

Since there is currently a difference between rofi and rofi-wayland: https://github.com/NixOS/nixpkgs/issues/298539 it is hard to use just rofi-devel. But fedora has only this package.

### Who will benefit from it?

Fedora users willing to install rofi-calc or extended rofi file browser.

### Rofi version (rofi -v)

Version: 1.7.5+wayland3

### Configuration

https://gist.github.com/BbIXOD/5059c6114535b7e6b954fa7b2273486c

### Additional information

Open to alternative suggestions like other way to find devels or to build. Open to alternative suggestions. Maybe should I use container to bake all there or smth like that?

**Comment by DaveDavenport** [comment]
1.) this is not rofi-wayland..  You ignored the big bold text in the template:
**Please do not submit reports related to wayland, see [here](https://github.com/DaveDavenport/rofi/wiki/Wayland) for more information.**
2.) We do not maintain distribution packages or have any influence over it. This seems like a fedora issue, not a rofi one.
