### ISSUE TITLE
[BUG] Icon fetcher fails to load icons/thumbnails for animated GIFs

### ISSUE THREAD

**Issue by martinsifrar** [davatorium/rofi#1974]
### Rofi version (rofi -v)

Version: 1.7.5,  also checked on (next 1.7.5-228-g6c38a49d)

### Configuration

https://gist.github.com/martinsifrar/e2b3724060c81bafe4682698d2252174

### Theme

https://gist.github.com/martinsifrar/5343660f12cd4fd8cec0125ba5296899

### Launch command

rofi -show-icons -show filebrowser

### Step to reproduce

* Start rofi filebrowser with -show-icons option
* Navigate to a folder containing an animated GIF ([example file to reproduce](https://github.com/davatorium/rofi/assets/53146732/5b9859ad-8ad2-48ef-92ce-e575e1256a60))

### Expected behavior

Rofi should show the first frame of the animated GIF.

### Actual behavior

The thumbnail is not shown. Rofi prints out a debug `Helpers.IconFetcher-WARNING` warning
```
(process:360901): Helpers.IconFetcher-WARNING **: 12:01:47.513: Failed to load image: |/home/martin/testgif/animated/rotating-95.gif| 23 23 Not all frames of the GIF image were loaded. (0x7ee188003970)
```

### Using wayland display server protocol

- [X] No, I don't use the wayland display server protocol

### I've checked if the issue exists in the latest stable release

- [X] Yes, I have checked the problem exists in the latest stable version

**Comment by DaveDavenport** [comment]
We use gdkpixbuf for image loading, I think this might be relevant: https://gitlab.gnome.org/GNOME/gdk-pixbuf/-/issues/45

**Comment by martinsifrar** [comment]
> We use gdkpixbuf for image loading, I think this might be relevant: https://gitlab.gnome.org/GNOME/gdk-pixbuf/-/issues/45

I already had the fix running on my computer. It just kinda took me a while to make the issue and the PR, as I'm not very used to Github.

**Comment by DaveDavenport** [comment]
Thanks for the PR! merged.
