### ISSUE TITLE
[BUG] run mode does not update with new files in $PATH when run from a keybind (e.g. from sxhkd)

### ISSUE THREAD

**Issue by promitheas17j** [davatorium/rofi#1978]
### Rofi version (rofi -v)

Version: 1.7.5

### Configuration

https://gist.github.com/promitheas17j/7274aa19c3c82a9f357144d7c6586b28

### Theme

https://gist.github.com/promitheas17j/597010c6920330d26eb982aae2cb673a

### Launch command

```rofi -fuzzy -m 1 -show run```

### Step to reproduce

1.  Create a new script in $HOME/.bin and make it executable. $HOME/.bin is in $PATH and I have verified this.
2. Hit the keybind to run the launch command above from sxhkd
```
# Relevant section of my sxhkdrc:
super + r
    rofi -fuzzy -m 1 -show run
``` 
3. When the rofi window pops up, search for the script created in step 1. It will not show up.
4. Note: Some scripts in $HOME/.bin can be found. Running any one of the scripts which can be found from rofi in the $HOME/.bin directory gives the following error:
```
Failed to execute: 'script-name' 
Error: 'Failed to execute child process "script-name" (No such file or directory)'
```
 After closing the error and closing the rofi window, the next time I run the command by using my keybind the script which could be searched for and found earlier is not present anymore. I need to run the rofi  command directly from the terminal, search for and run the script, and then the next time I use the keybind to run it the script shows up (will give the error above if I try to run it though).

If I run the command ```rofi -fuzzy -m 1 -show run``` in a terminal directly I get all scripts that i created and they run correctly.

If I try to run a script or command which is not in the $PATH directory I created (i.e. something like ```bash```) it will not give the error and not disappear from the list.

### Expected behavior

I expect to be able to find any newly created scripts if they have been created in a directory which is in the $PATH variable, and run scripts which can be found without getting an error that they do not exist.

### Actual behavior

- Running a script that I created give the error above and then disappears from the list until I run the command ```rofi -show run``` manually from a terminal.
- Scripts that can be searched for and found will not run but give an error and then disappear from the list the next time ```rofi -show run``` is ran from a keybinding. Running directly in the terminal doesn't present this issue. 

### Additional information

I've searched in the issues for anything related to this but couldn't find anything in either the open or closed issues.

### Using wayland display server protocol

- [X] No, I don't use the wayland display server protocol

### I've checked if the issue exists in the latest stable release

- [X] Yes, I have checked the problem exists in the latest stable version

**Comment by yusufaktepe** [comment]
If [this is where](https://github.com/promitheas17j/dotfiles/blob/f73fe8ef1584fd4519510e3379526b40ee0c44b4/dot_zshrc#L83) you're setting `PATH`, it won't be seen by programs outside the interactive shell. You should set it [globally/by user](https://wiki.archlinux.org/title/Environment_variables#Per_user).

**Comment by DaveDavenport** [comment]
rofi run rescans $PATH on every launch..  It is impossible to 'not update' as it does not store state for it to 'not update'. -> closing bug as there is no update process to be broken.

To debug your issue:  

99 % of these bugs are environment bugs. If it works on terminal and not from keybinding, you are most likely not setting the environment in the right place.
Rofi inherits the environment from the application that launched it. 

>  Create a new script in $HOME/.bin and make it executable. $HOME/.bin is in $PATH and I have verified this.

How did you verify this.

**Comment by DaveDavenport** [comment]
See also: https://github.com/davatorium/rofi/discussions/1281
