### ISSUE TITLE
[BUG] Segfault somewhere in PCRE on archlinux

### ISSUE THREAD

**Issue by Lattay** [davatorium/rofi#1979]
### Rofi version (rofi -v)

1.7.5-2 and 1.7.5-228-g6c38a49d

### Configuration

https://gist.github.com/Lattay/77d4556858074b130132b291cb5c7243

### Theme

https://gist.github.com/Lattay/9348d32a4a06de4b54efc476a4aad5e0

### Launch command

rofi -show combi

### Step to reproduce

Not able to very reliably reproduce yet, although it is very common.

### Expected behavior

Not crashing.

### Actual behavior

The program crash on the first keypress.

### Additional information

When running with GDB (I had not read rofi-debugging page yet, I need to do that tomorrow) the segfault is reported inside libpcre.

### Using wayland display server protocol

- [X] No, I don't use the wayland display server protocol

### I've checked if the issue exists in the latest stable release

- [X] Yes, I have checked the problem exists in the latest stable version

**Comment by lbonn** [comment]
This sounds similar to https://github.com/davatorium/rofi/issues/1966, but it should already be patched on ArchLinux? What is the pcre2 package version? (from `pacman -Qi pcre2`)

**Comment by Lattay** [comment]
On my work machine (up to date arch with the rofi 1.7.5 package from the repo) I cannot reproduce the crash using [this](https://github.com/davatorium/rofi/issues/1966#issuecomment-2014086866), which either mean my home laptop is having a different crash, or there is something to do with the fact that my home laptop is crap and old and slow. I'll have to look into that tonight or at some point in the week.

**Comment by DaveDavenport** [comment]
What version of PCRE do you run on your home laptop?

**Comment by Lattay** [comment]
Ok, don't mind me, I was on pcre2 10.43-1. I don't seem to be able to reproduce the bug with 10.43-3 so it was probably the same crash.
