### ISSUE TITLE
[BUG] rofi-theme-selector does not work as which is not found

### ISSUE THREAD

**Issue by CrazycatASG** [davatorium/rofi#1985]
### Rofi version (rofi -v)

1.7.5

### Configuration

https://gist.github.com/CrazycatASG/2f08f479df2f3142271fdebbcb9aab9b

### Theme

https://gist.github.com/CrazycatASG/0b35687663b1adc0771ce1967ff3313b

### Launch command

rofi-theme-selector

### Step to reproduce

Step 1: Attempt to open the rofi theme selector

### Expected behavior

Rofi theme selector opens and allows me to choose a theme

### Actual behavior

Rofi crashes being unable to find which

### Additional information

The program ran fine until a full reinstall of my OS, then the issues came along with it. 

### Using wayland display server protocol

- [X] No, I don't use the wayland display server protocol

### I've checked if the issue exists in the latest stable release

- [X] Yes, I have checked the problem exists in the latest stable version

**Comment by DaveDavenport** [comment]
Install which should fix this.  Might want to report this missing dependency to your distro packager.

Git does not longer uses which, but uses command -v . 
https://github.com/davatorium/rofi/pull/1704
