### ISSUE TITLE
[BUG] rofi takes 3s to starts, if icons are enabled

### ISSUE THREAD

**Issue by PerchunPak** [davatorium/rofi#2005]
### Rofi version (rofi -v)

1.7.5

### Configuration

-no-config

### Theme

-no-config

### Timing report

https://gist.github.com/PerchunPak/203502ba0b2e82bbe8ceeb4fcbf055cf

### Launch command

rofi -drun-use-desktop-cache -show drun -no-config -show-icons

### Step to reproduce

* run `rofi -drun-use-desktop-cache -show drun -no-config -show-icons` and start pressing keys, rofi doesn't react

### Expected behavior

rofi should react instantly 

### Actual behavior

rofi doesn't react for 3 seconds (turn on sound)

https://github.com/user-attachments/assets/16627258-0f81-44d1-9d8e-1ca9185906e8

### Additional information

The issue is the same if I remove `-drun-use-desktop-cache`

I use NixOS on unstable branch (https://github.com/NixOS/nixpkgs/commit/7e7c39ea35c5cdd002cd4588b03a3fb9ece6fad9) and hyprland v0.41.2 (which also means I use Wayland, I don't know why am I required to say that I don't even when wiki page says you support Wayland)

### Using wayland display server protocol

- [ ] No, I don't use the wayland display server protocol

### I've checked if the issue exists in the latest stable release

- [X] Yes, I have checked the problem exists in the latest stable version

**Comment by PerchunPak** [comment]
Also tried to build from source on 8eb8ff3 and it didn't help as well.

EDIT: Though build from `next` also takes a second to start even if I just use `rofi -show drun -no-config` (but if I enable icons, it starts even longer)

**Comment by lbonn** [comment]
@PerchunPak Which version of rofi was your original report for? (`rofi -version`)

Not sure it is related to the slowdown but there are two packages in nixpkgs, one with wayland support from the [fork](https://github.com/lbonn/rofi): https://github.com/NixOS/nixpkgs/tree/master/pkgs/applications/misc/rofi

If you were using mainline rofi for both of your tests, maybe try also with the wayland version with timing reports as well.

**Comment by PerchunPak** [comment]
oh yeah, `rofi-wayland` works. sorry for the confusion

**Comment by DaveDavenport** [comment]
>  (which also means I use Wayland, I don't know why am I required to say that I don't even when wiki page says you support Wayland)

 Where does it say this?  this should be fixed then.

**Comment by PerchunPak** [comment]
> Where does it say this? this should be fixed then.

https://github.com/davatorium/rofi/blob/8eb8ff3b6f5e0639e20006161f1ae308414f0f70/.github/ISSUE_TEMPLATE/bug_report.yml?plain=1#L103

**Comment by DaveDavenport** [comment]
Sorry for being unclear, where in the wiki does it say we support wayland?

The question in the bug report is there as it helps pin-point problems and redirect people to the right issue tracker.

**Comment by PerchunPak** [comment]
Yes, something like "current release doesn't support wayland, so you should use the fork" would guide me in the right direction

**Comment by DaveDavenport** [comment]
like the current text on the wiki?

> A [pull request](https://github.com/davatorium/rofi/pull/1139) was opened to allow Rofi to work under Wayland with Sway and some other window managers. If you are are interested, check out the [fork](https://github.com/lbonn/rofi) that was spun off from the PR and send your feedback there.

> Sorry for being unclear, where in the wiki does it say we support wayland?

can you please point out where?

**Comment by PerchunPak** [comment]
Exactly here, changing it to would guide me in the right direction, because for some reason I didn't check linked PR and assumed it was merged

> A [pull request](https://github.com/davatorium/rofi/pull/1139) was opened to allow Rofi to work under Wayland with Sway and some other window managers, **but it wasn't merged**. If you **need proper Wayland support**, check out the [fork](https://github.com/lbonn/rofi) that was spun off from the PR and send your feedback there.

(Changed parts are bold)

You can also ignore this as my skill issue, since I didn't know that PR was closed until now

**Comment by DaveDavenport** [comment]
Thanks, changed the text.
