### ISSUE TITLE
[Doc] Documentation for script mode indicates `-modes` but only `-modi` works

### ISSUE THREAD

**Issue by lud-wj** [davatorium/rofi#2033]
### Rofi version (rofi -v)

Version: 1.7.3

### URL

https://davatorium.github.io/rofi/1.7.3/rofi-script.5/

### Explain the issue with the documentation, please be verbose.

With this script in cwd:

```
echo "hello"
echo "world"
```

This works:

```
rofi -show tt -modi "tt:a.sh"
```

This does not:

```
rofi -show tt -modes "tt:a.sh"
```

(What is working / not working is displaying the list, obvioulsy my script would not handle selection of an item)

But the documentation tells to use `-modes`.

I'm a noob so it may be me.

### Optional fixed text

> Yes, I have checked the problem exists in the latest stable version

Well, if you consider that latest stable on ubuntu is 1.7.3 then yes.

### Using wayland display server protocol

- [X] No, my documentation issue is not about running rofi using the wayland display server protocol

### I've checked if the issue exists in the latest stable release

- [X] Yes, I have checked the problem exists in the latest stable version

**Comment by DaveDavenport** [comment]
Indeed a problem in 1.7.3 website. The manpage on your system should be correct.

I recommend upgrading as you are running a very old version.

**Comment by DaveDavenport** [comment]
website should be updated,

thanks.
