### ISSUE TITLE
[BUG] script mode didn't find scripts under $HOME/.config/rofi/scripts/

### ISSUE THREAD

**Issue by kuppo** [davatorium/rofi#2043]
### Rofi version (rofi -v)

Version: 1.7.5

### Configuration

default config with rofi -no-config

### Theme

no theme

### Launch command

rofi -show Mode -modes "Mode:script.sh"

### Step to reproduce

1. Suppose I have a script under `$HOME/.config/rofi/scripts/script.sh` with `+x` bit set.
2. when I run `rofi -show Mode -modes "Mode:script.sh"`, it gives an error 'no such file or directory'

### Expected behavior

rofi should find the script and runs it.

### Actual behavior

It give error about 'no such file and dirctory'

### Additional information

rofi-script manual page says, I quote,

> Scripts located in the following location are loaded on startup:
> - The script is in $XDG_CONFIG_PATH/rofi/scripts/, this is usually ~/.config/rofi/scripts/.

The XDG specification doesn't have a variable called `XDG_CONFIG_PATH`, only `XDG_CONFIG_HOME`. Don't know if this is just an manual typo or an implementation error. Anyhow, it doesn't work.

### Using wayland display server protocol

- [X] No, I don't use the wayland display server protocol

### I've checked if the issue exists in the latest stable release

- [X] Yes, I have checked the problem exists in the latest stable version

**Comment by DaveDavenport** [comment]
aah, that is not clearly documented..
If you have a file `script.sh`  in `~/.config/rofi/scripts/`
this is made available as mode automatically.
You do not need to 'load it again'.

You can use it by doing:  `rofi -show script`
this is showin in `rofi -h`

> Detected user scripts:
        • script (/home/qball/.config/rofi/scripts/script.sh)

**Comment by kuppo** [comment]
> aah, that is not clearly documented..
> If you have a file `script.sh`  in `~/.config/rofi/scripts/`
> this is made available as mode automatically.
> You do not need to 'load it again'.
> 
> You can use it by doing:  `rofi -show script`
> this is showin in `rofi -h`
> 
> > Detected user scripts:
>         • script (/home/qball/.config/rofi/scripts/script.sh)
> 
> 
> 
Yes, you are right. It automatically works as a mode. We can close it here. Thank you!
