### ISSUE TITLE
[Feature Request] Show Thumbnails for Windows Across All Workspaces in i3wm

### ISSUE THREAD

**Issue by eKeiran** [davatorium/rofi#2052]
### Before opening a feature request

- [X] I checked the *next* branch to see if the feature has already been implemented
- [X] I searched existing reports to see if it is already requested.

### What is the user problem or growth opportunity you want to see solved?

Problem: When using rofi in window-switching mode on i3wm, thumbnails are only shown for windows in the active workspace. Windows in other workspaces are listed by name but do not display thumbnails.
Solved:  Thumbnails should be shown for all windows, regardless of the workspace they are in, so users can easily identify and switch between windows across different workspaces.

### How do you know that this problem exists today? Why is this important?

Here's an image of the problem (current workspace is one and it's the only one with thumbnails): 
![image](https://github.com/user-attachments/assets/5f33fa25-50c8-42b1-95d5-0c62c15f25a9)

Users with multiple workspaces often rely on visual cues to identify windows quickly. Without thumbnails for windows in non-active workspaces, it becomes much harder to navigate between them.

### Who will benefit from it?

This feature would be very useful for users who manage multiple workspaces in i3wm and need to easily switch between windows across workspaces.

### Rofi version (rofi -v)

1.7.5

### Configuration

https://gist.github.com/eKeiran/72b1619baf95fdbd7bf19ef55fd2ffbb

**Comment by DaveDavenport** [comment]
This is not a rofi limitation.  Rofi cannot take a screenshot of a X11 surface that is not on a visible workspace.

**Comment by DaveDavenport** [comment]
If there is a solution, please let me know.
