### ISSUE TITLE
dmenu custom entry accept issues (Was confused: dmenu binding is not the same here!)

### ISSUE THREAD

**Issue by yuki-tsubaki** [davatorium/rofi#2056]
### Rofi version (rofi -v)

Version: 1.7.5

### Configuration

https://gist.github.com/yuki-tsubaki/a85a8c3d3143af1e737878c8fb757362

### Theme

https://gist.github.com/yuki-tsubaki/f090b5943d12e40f5b798a8308826bd1

### Launch command

echo -e 11\n111\n1111 | rofi -dmenu -no-config

### Step to reproduce

1. Run any command in dmenu mode with options given
2. Type part of the input but something that does not completely match any (e.g. 1 in my example of `echo -e 11\n111\n1111 | rofi -dmenu -no-config`)
3. With input of `1` press `Shift+Return` (or whatever the `kb-accept-alt` binding is)
4. The first/selected match is output to stdout rather than the partially matching input. (e.g. in my example it outputs `11` instead of `1`; when I all this with real dmenu with no config it works as expected and outputs `1`)

### Expected behavior

Output exactly the input even when it partially matches an option if the kb-accept-alt key is pressed.

In my example this should be `1`

### Actual behavior

Outputs a partially matched candidate.

In my example, it outputs `11`.

### Additional information

I installed the real dmenu and ran `echo -e 11\n111\n1111 | dmenu` and it worked as expected, outputting `1`.

### Using wayland display server protocol

- [X] No, I don't use the wayland display server protocol

### I've checked if the issue exists in the latest stable release

- [X] Yes, I have checked the problem exists in the latest stable version

**Comment by DaveDavenport** [comment]
Isn't the keybinding 'kb-accept-custom'?

```
$ echo -en '11\n111\n1111' | rofi -dmenu
1
```

Works for me.

**Comment by yuki-tsubaki** [comment]
Oh yep you are right. I don't know how I didn't notice, I thought I had tried each of them, but I guess I got hyperfocused on `kb-accept-alt` and somehow missed Control+Return. Maybe because in the default keybindings it has the same binding as the right function in dmenu.

Thanks for clearing that up (and for the very fast response)
