### ISSUE TITLE
[REQUEST] pass environment variables to drun-ed apps

### ISSUE THREAD

**Issue by ildar** [davatorium/rofi#2059]
### Before opening a feature request

- [X] I checked the *next* branch to see if the feature has already been implemented
- [X] I searched existing reports to see if it is already requested.

### What is the user problem or growth opportunity you want to see solved?

as rofi is an application launcher it must have ability to pass environment variables to drun-ed apps. This is natural

### How do you know that this problem exists today? Why is this important?

this is a useful feature that's why many/most application launchers can do it. E.g. shells and (some) DEs.

### Who will benefit from it?

advanced users

### Rofi version (rofi -v)

1.7.2

### Configuration

N/A

**Comment by DaveDavenport** [comment]
I am very confused, rofi passes all environment to the program it launches.. 

I've validated this using a desktop file that does:

```ini
[Desktop Entry]
Encoding=UTF-8
Version=1.0
Type=Application
Terminal=false
Exec=env
Name=Env test
Icon=Env test
```
and launching rofi from the terminal with a set of environment variables and checking if those are printed out.

**Comment by ildar** [comment]
Sorry for the confusion. I meant *additional* env. vars. Equivalent to the
shell command:
env VAR1=val1 VAR2=val2 cmd args.

**Comment by DaveDavenport** [comment]
I don't understand what you want. 

This works fine:
```bash
MONK=a rofi -show drun | grep -i MONK
MONK=a
```

**Comment by DaveDavenport** [comment]
You claim most launchers can do this?  can you show a screenshot of how you do it?  that might clear things up?

**Comment by DaveDavenport** [comment]
There is nothing in the free desktop standard  about this.
https://specifications.freedesktop.org/desktop-entry-spec/latest/

**Comment by ildar** [comment]
On Sat, Dec 21, 2024 at 4:53 AM Dave Davenport wrote:

> You claim most launchers can do this? can you show a screenshot of how you
> do it? that might clear things up?
>

Sorry, I didn't claim **most** DEs but some DEs do this. E.g.
https://wiki.hyprland.org/Configuring/Environment-variables/ .
My core idea was quite simple: as an app launches other apps then it should
allow customizing that action. E.g. allowing to change cmd args (that's
what `rofi run` does) and environment.
BTW I ended up running some apps with `rofi run` for my purposes.
Thanks again for this great applaucher! and cudos to @lbonn for the Wayland
support patch!

**Comment by DaveDavenport** [comment]
Ok, this feels dishonest:

> Sorry, I didn't claim **most** DEs but some DEs do this. E.g.

While I said.

> You claim most launchers can do this? 

and you said in the opening post:

> this is a useful feature that's why many/most application launchers can do it.

**Comment by DaveDavenport** [comment]
I do not want to continue with this anymore.
