### ISSUE TITLE
[feature-request] -replace for overwriting current rofi session

### ISSUE THREAD

**Issue by shibumi** [davatorium/rofi#568]
Hello,
It would be nice to have a -replace trigger for rofi. This way we could implement dynamic rofi windows.
The new rofi command should simply overwrite the old rofi window.

I am thinking about something like this:"

rofi -e "|||||||||||||||||||||||| 100%" -replace
rofi -e "|||||||||||||||||||       90%" -replace

The new window will simply overwrite the old window.

if replace is not possible, what about a timeout?

**Comment by DaveDavenport** [comment]
This would result in ugly artifacts.
You can get currently by sending a signint to a running rofi to make it quit..

**Comment by DaveDavenport** [comment]
I rather implement something like this in dmenu  mode:
```
https://filebin.pw/BB5/
```

**Comment by DaveDavenport** [comment]
First implementation: [script](https://filebin.pw/aP34/)  [patch for rofi](https://filebin.pw/BY92/)

**Comment by DaveDavenport** [comment]
![progress](https://cloud.githubusercontent.com/assets/406245/23376389/2fb7fe94-fd2c-11e6-8a46-96566ab27f1d.gif)

**Comment by DaveDavenport** [comment]
![progress](https://cloud.githubusercontent.com/assets/406245/23376727/87727212-fd2d-11e6-9c31-80fd93d545d1.gif)

better quality.

**Comment by shibumi** [comment]
@DaveDavenport  This looks awesome! How can I trigger this with bash? What I want to implement via a script is more like of a audio-bar. I want to press a button and rofi shows up with changed processbar. Thats what I want to do as first project for rofi. Playing with sigint + rofi -e calls should be enough, or?

**Comment by DaveDavenport** [comment]
the above screencast is not possible (yet), you need to apply the provided patch to rofi, with this patch you can then use  it like in the example script.

I am not sure if rofi is the best tool to show an ' audio bar'  it is more an interactive menu.

**Comment by shibumi** [comment]
Here thats my current version of rofi-audio: https://github.com/shibumi/rofi-audio/blob/master/rofi-audio.sh
I tried it withour your patch, but I expected some difficulties..At the moment it's killing itself after 0.2s.. but I would really prefer some sort of stable dynamic interface that can change the output when I press a key and can timeout after a while..

**Comment by MaskRay** [comment]
I'm thinking about how to combine this with <https://github.com/DaveDavenport/rofi/issues/561>.
In Script mode (`source/dialogs/script.c`), rather than `execute_generator` and `fclose` at startup, the external process can keep running as a coroutine. The updated filter string can be fed to the coroutine whenever it changes and new output can be populated.

**Comment by DaveDavenport** [comment]
Looking at scripting mode is planned for 1.5,  for now plugins can provide a more dynamic view:
[top](https://filebin.pw/UHAd/)

**Comment by p3lim** [comment]
While the plugin support is very (!) nice, I would still like if that patch from above would be implemented so we can easily script this instead of making a whole plugin.

**Comment by DaveDavenport** [comment]
This topic is going a bit all over the place.  It starts with a --replace, then through dmenu emulation and now script mode.

I would love to have a nicer script implementation, however:
1. I don't really use it myself, I use either dmenu or c-plugins.
2. Previous requests for a decent specification have not had the desired result.
3. I don't have time to dig into this myself .

So if somebody can come up with an (backed by others) acceptable specification I am happy to get this implemented into rofi.

(Maybe a separate 'view' for displaying dynamic information is a nice solution? (So you can easily show progress bars, etc.) Ideas welcome.)

**Comment by p3lim** [comment]
The specific case I'm after is updating the content of a dmenu session, I've been looking at the sample plugin implementations but I'm a bit lost in the details (not too familiar with C w/GLib), even though I know I should probably be going for it (I'm making a wpa_supplicant "mode").

**Comment by owl4ce** [comment]
Launch rofi inside rofi?

**Comment by DaveDavenport** [comment]
not sure what this random 4 word jumble is supposed to ask. Locking, See guidelines.
