### ISSUE TITLE
Pango markup is matched when filtering in dmenu mode

### ISSUE THREAD

**Issue by GrumpyDave** [davatorium/rofi#597]
Using rofi version 1.3.1.  This is a duplicate of [issue #273](https://github.com/DaveDavenport/rofi/issues/273) but applies to dmenu mode.

When Pango markup such as `<span weight='light' size='small'><i></i></span>` is used in list items, the tags are matched when filtering.

**Comment by DaveDavenport** [comment]
fixed.
