### ISSUE TITLE
[Feature request] Option to highlight option under mouse

### ISSUE THREAD

**Issue by gandalf3** [davatorium/rofi#600]
When [using rofi with the mouse](https://github.com/DaveDavenport/rofi/issues/441#issuecomment-304430763), it'd be nice to have more visual feedback on which option the mouse is over, to make it easier to click fast without fear of missing. Maybe an option to select/highlight the option under the cursor?

**Comment by Kommynct** [comment]
I can't even make it clickable, am I missing something?

**Comment by oredaze** [comment]
I would also like to see this feature, it is very handy when using single click to accept. If not, alternatively make it so that before the single click activates an entry, the entry is briefly highlighted before it executes, because now it is a bit ambiguous what you have clicked.

**Comment by xlucn** [comment]
Is this already implemented by the merged PR above?

**Comment by DaveDavenport** [comment]
It sais 'merged' so yes.

**Comment by DaveDavenport** [comment]
See: https://github.com/davatorium/rofi/releases/tag/1.7.0

**Comment by Shamaoke** [comment]
So, how to configure rofi to highlight an entry under the mouse pointer?

**Comment by DaveDavenport** [comment]
See manpage. Please use discussion forum for support questions.
