### ISSUE TITLE
[Feature Request]: Copy executable path to input in drun mode

### ISSUE THREAD

**Issue by fice-t** [davatorium/rofi#603]
It would be nice if there was a way to copy the Exec key from the .desktop file in drun mode, as it would be a good way to easily provide arguments for the selected program.

Perhaps Ctrl+Space could be overridden in drun mode to copy the executable path, or perhaps a binding like Alt+Space would work.

**Comment by fogine** [comment]
Hm, I'd make use of a generic option (eg. `--print-selected`) which when enabled would set the text of currently selected item (`#window horibox listview element selected`) to the input field (`#window horibox entry`).

**Comment by DaveDavenport** [comment]
I don't really see this issue.   Desktop file has a method for adding arguments (like opening file/url) rofi does support this for passing files . 
Rofi also supports 'actions' for desktop files, that is often use for launching pre-defined variations of this applications. (see f.e. nautilus has this).

if you want to pass arguments, the 'run' browser makes more sense, as it autocompletes executables, and then the current `ctrl-space` does what you want.
