### ISSUE TITLE
[dmenu] Add ability to hide columns

### ISSUE THREAD

**Issue by carnager** [davatorium/rofi#680]
fzf has a feature that allows to hide specific columns with `--with-nth=1,2,3,5`, which would hide the 4th column. After selecting a line the complete line including hidden column is visible. A delimiter can be set with -d.

It would be nice if rofi had a similar feature, since this can help clean up lines considerably.

And while we are at it. The other way around would be equally nice. As in only spit out specific columns to stdout.

**Comment by DaveDavenport** [comment]
apparently I implemented this a while back.  Added documentation to git.
