### ISSUE TITLE
On-release binding not triggered if was pressed before Rofi launch

### ISSUE THREAD

**Issue by sergei-dyshel** [davatorium/rofi#687]
Version: 1.4.1 (tags/1.4.1)
Configuration - Default

I'm trying to simulate Alt-Tab behavior, as found in common desktop environments (e.g. Windows or Gnome), using Rofi in i3 WM.  Alt-tab is supposed to work this way: 
As soon I press Alt-Tab, Rofi window appears. While holding `Alt`, I cycle to next windows with `Tab`. When I release `Alt` I switch to currently selected window.

So far binding Alt-Tab (in i3) to this simple command does the job pretty well:
```
rofi -show window -kb-row-down 'Alt+Tab' -kb-accept-entry '!Alt_L,!Alt+Tab'
```

There is, however, an annoying issue: if I don't want to cycle at all, e.g. switch to first (currently selected) window, I'm supposed to release Alt-tab immediately after opening Rofi window, which should trigger *kb-accept-entry*.

But this doesn't happen! For some reason on-release binding is not triggered. I suspect that it happens because when Rofi started, Alt-Tab was already pressed. So it sees the release of `Alt` although `Alt` wasn't pressed. Anyway, I tried going through the relevant commit (https://github.com/DaveDavenport/rofi/commit/67b0ce036f19fa0caa95461ab213717237b279dd), but  couldn't figure it out. 

I'd like to attempt fixing this on my own so any explanations or code hints are welcome!

**Comment by sardemff7** [comment]
You are hitting a limitation of X11 here.
We get the modifiers status from the X server before the list of keys already down. That means we do not see `Alt_L` down, but `Alt+Alt_L`. It should work fine if you bind `!Alt+Alt_L` to `accept-entry`.
This is the case on Wayland too, but on X11, we never see the `Tab` key as down, because the WM (or whatever launches rofi) has grabbed `Alt-Tab`, so `Tab` is not sent as being pressed for rofi.
(On Wayland, there is no such grab, so the `Tab` key is actually sent, with the `Alt` modifier down, and it works.)

There may have been an underlying bug with `Alt` and `Super` modifiers, which I found by checking for your issue, and should be fixed by now.

**Comment by sergei-dyshel** [comment]
@sardemff7
Thanks for helping me! Unfortunately, for some reason using `-kb-accept-entry !Alt+Alt_L` doesn't seem to work always. I work with multiple monitors and tried to check this behaviour with different combinations of active monitor / active window / mouse position
However, I've noticed that this is somehow related to dual monitor setup I'm using. When I switch to some window and then move mouse to _other_ monitor and press `Alt+Tab`, Rofi works as expected but then it stops working for some reason. After doing this procedure again, Rofi starts working again. Also, the only working option is `-monitor -5` (the default). 

This is very frustrating, especially when I'm so close :disappointed: . Is there a command line switch to dump all key events so I can try debugging this issue? Where is relevant code in Rofi?

BTW, can it be connected to  the bug you've fixed?

**Comment by DaveDavenport** [comment]
> Also there some weird issue with the order of windows (when running with -show window). Usually
> active window is the first item in the list (so pressing Alt-Tab does nothing) but sometimes previous
> window is first item in the list so Alt-Tab switches it correctly.

Please don't report unrelated issues in comments of issues. Please create a new issue.

**Comment by sardemff7** [comment]
> However, I've noticed that this is somehow related to dual monitor setup I'm using.

You mean it works as expected if you use only one monitor?
To be completely clear, it works:
- if you use 1 monitor and `!Alt-Alt_L`
- if you use 2+ monitors and any on-press keybinding (e.g. `Return`)

and it does not work:
- if you use 2+ monitors and use on-release binding (one that works with 1 monitor, e.g. `!Alt-Alt_L`)

is that what you say?

**Comment by sergei-dyshel** [comment]
@sardemff7 
Ok, I've played with it a little more and it seems that `!Alt-Alt_L` binding doesn't work properly without any relation to dual monitor. I've disabled second monitor and still observe this issue. Sometimes it works, sometimes not, I see that it somehow depends on which window is active now and where is mouse cursor but can't figure out any pattern right now.

**Comment by sergei-dyshel** [comment]
on-press keybindings work flawlessly

**Comment by sardemff7** [comment]
It looks like it's related to the #38, namely the focus is following the mouse and it happens to work when the mouse is where rofi appears
Hopefully fixed with the focus steal hack
