### ISSUE TITLE
rofi -dmenu freezes if stdin is closed

### ISSUE THREAD

**Issue by miseran** [davatorium/rofi#703]
## Version

Version: 1.4.2

## Configuration

https://gist.github.com/miseran/1298ad6f7fa7cb1b23e2d8c74d1c3a2d

## Launch Command

    ( sleep 10; killall rofi; ) & rofi -dmenu <&-

## What behaviour you see

Rofi grabs mouse and keyboard, but never opens a window, so all of X becomes unresponsive. Rofi needs to be killed some other way.
This didn't happen in 1.3.

Stdin is often closed for dmenu if arbitrary input is needed, without providing options. While there are other ways to do this (e.g. `echo -n '' | rofi -dmenu`), it would be nice if this way worked as well, or at least didn't lock everything up.

**Comment by DaveDavenport** [comment]
Hmm unexpected, will need to check.
I actually tried to improve the situation by checking if stdin is a tty.

(fun, if I run in strace, it does not hang..)

**Comment by DaveDavenport** [comment]
(p.s. quick workaround: `rofi -dmenu -async-pre-read 0` )

**Comment by DaveDavenport** [comment]
Wonder if there is a way to check that it is closed.

**Comment by has2k1** [comment]
When embed in a script I had these -- `myvar=$(rofi -dmenu)` -- types of statements failing. As per the workaround, these -- `myvar=$(rofi -dmenu  -async-pre-read 0 )` -- work.

**Comment by DougBeney** [comment]
Happening to me with the `drun` option after updating today. I3-gaps, Arch, Xorg, Rofi 1.5.0-dirty.

**Comment by DaveDavenport** [comment]
@DougBeney Don't think thar is related at all, more likely this:#763

**Comment by epitron** [comment]
Another way to trigger this bug is to fill up STDIN very too slowly. eg:
```
while true; do echo hello; sleep 1; done | rofi -dmenu
```

(Side question: why is the blocking pre-read supposed to make rofi feel more snappy? Does rofi refresh the display on every line it receives in async mode or something?)

**Comment by DaveDavenport** [comment]
It is more a livelock then a lock-up and a side effect of the implementation (not really a bug). Pass the `-async-pre-read 0` to avoid it.
 
Not everytime, it tries to update the view (if changed) in idle time.. but it feels a tat slower (for smaller lists) as it only shows  the list after on first redraw, not instantly.

**Comment by DaveDavenport** [comment]
Please don't start unrelated discussions in this issue.  (see rules). This has been discussed in other issues.

**Comment by kaiec** [comment]
When I use the -async-pre-read 0 workaround, sometimes lines are not selectable (Rofi 1.7.0, Arch, KDE):

[rofi.txt](https://github.com/davatorium/rofi/files/7215646/rofi.txt)

`cat rofi.txt | rofi -dmenu -i -async-pre-read 0`

Try to select the row starting with 44. 

It works with an async-pre-read value of 1 or higher.

**Comment by DaveDavenport** [comment]
as mentioned in the [guidelines](https://github.com/davatorium/rofi/blob/next/.github/CONTRIBUTING.md): do not highjack old issues,  please make a new issue.

**Comment by DaveDavenport** [comment]
closing and locking this issue now, as it keeps being used for other things.
