### ISSUE TITLE
Hide categories?

### ISSUE THREAD

**Issue by hxss** [davatorium/rofi#724]
## Version

Version: 1.4.2

## Configuration

https://gist.github.com/hxss/454dbae7f1f66dd0578725d359caea1e

## Launch Command

rofi -show drun

## What behaviour you see

![screenshot from 2017-11-25 01-17-00](https://user-images.githubusercontent.com/17298149/33223071-6708b2f4-d17e-11e7-9594-fe86e85e152a.png)

## What behaviour you expect to see

![screenshot from 2017-11-25 01-17-00-1](https://user-images.githubusercontent.com/17298149/33223094-96551624-d17e-11e7-9f7a-4d5df5f107ac.png)

Can I hide categories from drun menu?

**Comment by DaveDavenport** [comment]
No, this is not supported.

**Comment by hxss** [comment]
It would be great if you add option for that.

**Comment by Shamaoke** [comment]
@hxss You can copy the .desktop files with “categories” from _/usr/share/applications_ to _~/.local/share/applications_ and remove the _GenericName_ field from them. (It also needs to remove _~/.cache/rofi-3.runchache_ and _~/.cache/rofi2.druncache_ in order the changes to take effect.) That way the categories won't be displayed at the list. Moreover, by using this approach you can hide only specific categories or create your own (by modifying the field).

**Comment by CadaverLab** [comment]
Does this mean that `drun-match-fields` will still show the generic name in the drun list?

**Comment by JPUnD** [comment]
i also would like this feature, editing each program entry manually only to have it replaced in an update is not really a good idea and this seems like a rather good idea, is there any updates?

**Comment by JPUnD** [comment]
wait never mind, using `-drun-display-format {name}` fixes the issue

**Comment by DaveDavenport** [comment]
This is now also supported. https://github.com/davatorium/rofi/issues/817

**Comment by DaveDavenport** [comment]
https://github.com/davatorium/rofi/commit/f8961462178d81eb69d7d7f095677f7d250e653d
