### ISSUE TITLE
Do we have a list of available rofi scripts somewhere?

### ISSUE THREAD

**Issue by sandebert** [davatorium/rofi#764]
I'm a bit late to the party and just found out about rofi a couple of days ago. Looks very nice, and I like the ability to extend it with scripts. I've read the wiki, the forum, and pretty much all of the issues - but I haven't been able to find a list of scripts by the community. Regardless, I imagine there exist a lot of scripts out there, so it seems to make sense a list should also exist somewhere. Does it?

To be super clear, I'm asking if we have [something like this list of irssi scripts](https://scripts.irssi.org/).

**Comment by sandebert** [comment]
Perhaps it could simply be a page in the rofi wiki that users could update themselves?

**Comment by DaveDavenport** [comment]
Feel free to add it.

Start:
* [github rofi tag](https://github.com/topics/rofi)
* [Scripts](https://github.com/carnager/rofi-scripts)
* [Old page](https://github.com/DaveDavenport/rofi/blob/gh-pages-old/p07-Scripts.md)

**Comment by sandebert** [comment]
Done. I seeded it the best I could thanks to your links. Now we'll just hope people will add their scripts to that page.

**Comment by DaveDavenport** [comment]
Thanks!

**Comment by sandebert** [comment]
No, thank _you_ for rofi. I'm just glad to be able to pay back a little bit. :)
