### ISSUE TITLE
Feature Requst: Command-only history mode

### ISSUE THREAD

**Issue by gergesh** [davatorium/rofi#768]
A launch or config option that, when active, will only suggest comletion for commands (i.e. a single word) and not the entire phrase from the history file.

**Comment by DaveDavenport** [comment]
Please be more precise/verbose in what you want. To avoid misunderstanding.

**Comment by gergesh** [comment]
If I were to start rofi normally and type "chrom", I'd get a suggestion for
"chromium --no-proxy-server"
However, if I had launched rofi with the --command-history mode and typed
"chrom", I'd only get autocompleted to "chromium". Anything beyond that
(the program) is not suggested.

**Comment by DaveDavenport** [comment]
This one is confusing.  You can disable history to *not* see older completely commands for run, that would mostly do what been asked here.

This command would also be very difficult to implement in a generic method that works for all modes. I think its better to make a small custom script mode that does what you want.
