### ISSUE TITLE
Feature Request: combi mode custom script "catch-all" handler

### ISSUE THREAD

**Issue by karlseguin** [davatorium/rofi#813]
Hello. This is a feature request, and even if not accepted, maybe the solution I provide will be helpful to others who'd like the same behavior.

The goal is to provide a 'catch all' script when in combi mode and no items are selected. This is similar to #746 and #774 (I think), but more generalized. The current behavior is that if you hit <Enter> with no items selected, rofi exits. The new behaviour would pass the input to a script (which could then behave like any script input, causing rofi to exit on an empty stdout, or providing more entries).

My hack to make this work was to change the last line of `combi_mode_result` in `source/dialogs/combi.c` from:

```
return MODE_EXIT
```
to:
```
return mode_result ( pd->switchers[pd->num_switchers-1].mode, mretv, input, selected_line );
```

I just hard-coded the last modi, but this would obviously be better configurable/named.

A sample catch-all script:

```
#!/bin/bash

browser_tab () {
  WNDW=$(wmctrl -l -x | grep "Navigator.Firefox" | tail -1)
  if [[ -z "$WNDW" ]]; then
    ARG="--new-window"
  else
    ARG="--new-tab"
  fi
  firefox $ARG "$1" > /dev/null 2>&1 &
}

if [[ -z "$@" ]]; then
  # I actually just echo "", but some people might prefer to see a list of possible keywords / prefixes
  echo "github"
  echo "otp"
elif [[ $@ == "otp "* ]]; then
  # typing 'otp github' will execute 'pass -c otp github/otp'
  KEY=$(echo $@ | cut -f2 -d ' ')
  /usr/bin/pass otp -c $KEY/otp > /dev/null
elif [[ $@ == "github" ]]; then
  # github keyword
  browser_tab "https://github.com/"
elif [[ $@ == *".com" ]] || [[ $@ == *".net" ]]; then
  browser_tab $@
else
  # anything else does a google search
  browser_tab "https://www.google.com/search?q=$@"
fi
```

**Comment by DaveDavenport** [comment]
A default handler sounds like an interesting idea.

**Comment by DaveDavenport** [comment]
Missing information never provided. closing bug.
