### ISSUE TITLE
Sort entries when using drun

### ISSUE THREAD

**Issue by ghost** [davatorium/rofi#817]
I don't know if this is already possible or if I misunderstood the -drun-match-fields but I'd like to limit the number of .desktop entries in my menu so that I can, for example, only show the .desktop entries with the "Office" category. Is it possible to do this with -show drun or do I need an external script for the job?

## Version

1.5.1-dirty (tags/1.5.1)

## Configuration

https://paste.ubuntu.com/p/qqFGXJ9ktp/

## Launch Command

rofi -disable-history -show drun -theme ~/.cache/wal/colors-rofi-dark.rasi

**Comment by DaveDavenport** [comment]
There is currently no way to pre-filter the list.
You should however be able to type in 'Office'  to  see the office applications .
(```rofi -show drun -filter Office```)

**Comment by DaveDavenport** [comment]
Never thought about it.   Ill mark it as 'Nice to have'.

**Comment by dannycolin** [comment]
Indeed that would be nice to have that feature :). Would also be nice to have a widget that show all the categories.

**Comment by DaveDavenport** [comment]
@dannycolin  Widget? Not sure how you would see this.  Can you make a mockup?

**Comment by dannycolin** [comment]
@DaveDavenport By widget I mean something like in [Gnome Shell Activities Overview](https://en.wikipedia.org/wiki/GNOME_Shell#/media/File:GNOME_Shell_3.0_(2011,_04)_--_Applications_view.png). As you can see in that screenshot, there's a list a categories on the right that act like buttons.

**Comment by DaveDavenport** [comment]
I don't think that fits/works well with rofi.

**Comment by dannycolin** [comment]
Why not? The sidebar widget that show modes is very similar. You can select a mode and see the active one. We could definitely do something similar with a category-filter widget.

**Comment by dannycolin** [comment]
> because it is very specific to a single mode (the mode selector is not), it won't work with combi mode or full keyboard access (without making mode-specific keybindings).

Now I see your point and I totally understand (and agree) you want to keep the core code as generic as possible. Thanks for the clarifications.

**Comment by DaveDavenport** [comment]
thx for understanding.
