### ISSUE TITLE
Set x/y position

### ISSUE THREAD

**Issue by rosshadden** [davatorium/rofi#82]
I have a weird setup on my laptop where X thinks I have one giant monitor, when in fact I have four.  It's a long story involving two graphics cards and many hundreds of hours of pain.  What this means for rofi is that "60% of the screen" actually means "enormous and stretched across four monitors".  Granted I'm using the width property to make this better, though that makes the prompt lay in the middle of two screens.

What I ended up having to do with dmenu was telling it where to be placed, with the `-x` and `-y` arguments (or `-s` for screen, though that seems harder to implement).  Is this something easy to add to rofi?

By the way, awesome project!  By which I mean I am using it in AwesomeWM.  And that it's an awesome project -_-.

**Comment by MuntashirAkon** [comment]
> The -x/-y option exist in rofi. It is -xoffset and -yoffset combined with -location (defining the 'anchor')

Why doesn't this exist in the man page?

**Comment by DaveDavenport** [comment]
@MuntashirAkon feel free to provide a PR request.
