### ISSUE TITLE
Window search - can't tell rofi to search in particular property without changin window-format

### ISSUE THREAD

**Issue by pielgrzym** [davatorium/rofi#835]
:arrow_right: First read the [guidelines](https://github.com/DaveDavenport/rofi/blob/next/.github/CONTRIBUTING.md)! :arrow_left:

## Version

Version: 1.5.1

## Launch Command

rofi -terminal termite -matching fuzzy -show combi -combi-modi 'window#drun#run' -modi  combi

## What behaviour you see

I'd like rofi to search only in window class (for example) but still display window titles when doing so. When I set window-format it seems to search only in what window-format provides, but I can't see the title. Every matching algorithm is malfunctioning if I let rofi search in full format of windows (probably everyone expects something else from it, but I'm frustrated with things like: w8 should match windows from workspace 8 first, but then some magic makes a random window with long title to pop in the first place - same goes for just typing 'window' - it should show first the items from window modi, but I only get 3 results and only one is a window modi result. doh). Having control over which column rofi searches and sorts would make this behavior more predictable :)

## What behaviour you expect to see

Config option for each modi in which 'field' to search (or a --search-format to make rofi produce a second list that is parsed for searching instead the main one). This way one could specify to search windows only for modi+desktop+class and search desktop entries only in name etc.

**Comment by DaveDavenport** [comment]
I think this has been fixed. ` -window-match-fields` .
