### ISSUE TITLE
Weird transparency on Ubuntu 16

### ISSUE THREAD

**Issue by balta2ar** [davatorium/rofi#845]
Hello. Some time ago rofi on my Ubuntu 16 machine started to look really weird and became overly transparent:

![rofi-weird-transparency-ubuntu-16](https://user-images.githubusercontent.com/340676/44026184-e537b73e-9efa-11e8-938a-e24186e47c4f.gif)

rofi's text clashes with the background and colors are absolutely loathing, barely readable, depending on the background. This is the look I get when running with `-no-config` option. Also, my configuration is empty (it's a result of `-dump-configuration` option, and everything is commented out there).

I've tried switching various transparency options on and off (`-[no-]fake-transparency`, `-fake-background [string]`, `-opacity`), but it didn't have visible effect. What had an effect was changing actual colors values in themes, but that didn't help bringing back 0% transparency back.

My `~/.Xresources` is this:
```
! XTerm*cursorColor: #FF0000
! URxvt.cursorColor: green

xterm*termName: xterm-256color
XTerm*locale: true
XTerm*metaSendsEscape: true
Xterm*saveLines: 4096
xterm*faceName: Liberation Mono:size=16:antialias=false
xterm*font: 7x13
XTerm*reverseVideo: on
```
and it hasn't changed for a while. I don't really know what has changed that made rofi look like this. It's also irregardless of the version: I've tried several versions including 1.4.2, 1.5.0 and at some point from master branch -- still the same. I'm using default Ubuntu 16 environment so maybe it has something to do with compiz? On my other ArchLinux machine in OpenBox and without any compositing manager it looks fine.

I'm totally out of ideas about what else could have led to this visual effect. I could try turning off compiz, but it worked fine for a long while with it... Did anyone have anything similar?

## Version

Version: 1.5.1-52-git-4631ac7-dirty (next)

## Configuration

rofi -help: http://ix.io/1k4a
configuration: http://ix.io/1k4b

## Launch Command

```bash
ls /var/ | rofi -no-config -dmenu
```

## Steps to reproduce

Just launch rofi.

## What behaviour you see

As mentioned above, colors and transparency are weird.

## What behaviour you expect to see

Just normal colors as before.

**Comment by DaveDavenport** [comment]
Weird, haven't seen this effect in ages (like years). The no-config option should not be transparent. 


Weird thing is older version (that I assumed worked fine before) also give this problem. Any idea what changed when it broke?


Are you using X11? (no wayland with X11 layer) What is the bitdepth of the screen (8 bit per color? or 10?)

**Comment by balta2ar** [comment]
> Any idea what changed when it broke?

That's the difficult part, I have no idea, unfortunately... But it's very unlikely that it's rofi, I would have noticed immediately. Must be something in the system configuration.

> Are you using X11

It must be X11 (Ubuntu 16.04 default).

> What is the bitdepth of the screen

```
xwininfo -root | grep Depth:
  Depth: 24
```
```
less /var/log/Xorg.0.log | grep -i depth
        "Default Screen Section" for depth/fbbpp 24/32
[    10.949] (==) modeset(0): Depth 24, (==) framebuffer bpp 32
[    11.818] (==) Depth 24 pixmap format is 32 bpp
```
Full X11 log: http://ix.io/1k4F

Is there anything else I could check?

**Comment by DaveDavenport** [comment]
closing. please let me know if this still exists. 
(haven't been able to reproduce this ever).
