### ISSUE TITLE
Ability to provide runtime options as extra properties

### ISSUE THREAD

**Issue by shanedabes** [davatorium/rofi#859]
## Version

Version: 1.5.1-56-git-a99cfa56-dirty (makepkg)

## Configuration

https://gist.github.com/127e85e41838e37be0243611db4aee08

## Launch Command

rofi -modi test:"test.py" -show test

## Steps to reproduce

N/A

## What behaviour you see

At the moment it is not possible to set run time options as extra properties in rofi. 

## What behaviour you expect to see

For example, it would be very useful to set "-format i" as an extra option in rofi's output with something like:

`echo -en "\x00format\x1fi\n"`

In this case, the output can be consumed by the second rofi pass as an integer for scripts that require it. This way scripts can be written and used alongside other script/modis that expect different formats. It also means less post configuration needs to be done by the end user and the rofi command line can be reduced with hard config options kept in the script.

**Comment by DaveDavenport** [comment]
This came up a few times more, but there are some fundamental problems with allowing this from a script mode.
1.) separation of concerns. You don't want scripts to override 'random' runtime options, possibly messing up the user settings.
2.) Multiple script modes  can pass conflicting parameters.

If specific options, relevant to the script (and script alone), we should add them as an option.
The example format is a dmenu option,  a script should not override that.

If we want 'format' in a script, we should add it (And apply to that script alone).
