### ISSUE TITLE
Slow startup sometimes.

### ISSUE THREAD

**Issue by trbocode** [davatorium/rofi#898]
## Version

1.5.2

## Configuration

https://gist.github.com/trbocode/d461b10b101df6d84c232f5e15920c18

## Launch Command

rofi -show

## Steps to reproduce
Just run it

## What behaviour you see
Sometimes, the startup is very slow (5sec). Logs are in the gist. 
Usually happens if more than 30min passed after using rofi.

## What behaviour you expect to see

Consistently fast startup - Like the fast log attached.

**Comment by DaveDavenport** [comment]
It looks like it takes a very long time to walk through and parse the desktop files in the user directory.

```
0.181793 (0.000011): ../source/dialogs/drun.c:get_apps:587 Get Desktop apps (start)
2.790775 (2.608982): ../source/dialogs/drun.c:get_apps:594 Get Desktop apps (user dir)
```

This seems to take around 90% of the startup time.

Do you have a lot of files in your user directory? (often `~/.local/share/applications/`)

**Comment by trbocode** [comment]
I have about 2650 of "wine-extension-XXX".desktop files. Didn't notice that, will close if removing them helped.

**Comment by DaveDavenport** [comment]
SSD or Spinning disk.

**Comment by trbocode** [comment]
/home is on disk, but / is on ssd.
Deleting those files decreced the startup time to 3 secs but it's still somewhat annoying.
https://gist.githubusercontent.com/trbocode/d461b10b101df6d84c232f5e15920c18/raw/7b835d4f297eaf572cab3e1112bd3c0467b7e374/newnewlog

**Comment by DaveDavenport** [comment]
Linux will cache the files, after X time this might be moved out of memory again.

**Comment by trbocode** [comment]
Ah okay thanks.

**Comment by DaveDavenport** [comment]
closing for now.   There is a cache now that hopefully fixes drun.
