### ISSUE TITLE
-display-{mode} string doesn't work with custom modi

### ISSUE THREAD

**Issue by dannycolin** [davatorium/rofi#905]
## Version

1.5.2-4-git-f42cffe9

## Configuration

https://gist.github.com/dannycolin/0181f628c764c4edad704095687129d4

## Launch Command

rofi -show drun 

## Steps to reproduce

* Add a custom modi like so `modi: "drun,run,ssh,rofi-powermenu:rofi-powermenu";` in my `~/.config/rofi/config.rasi`
* Add `display-rofi-powermenu: "custom name test";` also in my config file
* Run rofi

## What behaviour you see

* Rofi use the name of my custom modi instead of the value I've setted with `display-rofi-powermenu`

## What behaviour you expect to see

* I expect rofi to use the value in `display-rofi-powermenu`

## Additional notes

Other things I've tried : 

- Set the *display* text via the command line by doing `rofi -show drun -display-rofi-powermenu "custom name test"` without any luck.
- Use a name that doesn't contain a dash symbol (e.g display-rofipowermenu).

**Comment by DaveDavenport** [comment]
Does it only fail for script modi?

**Comment by DaveDavenport** [comment]
There is a nice chicken and the egg problem here. It reads out all the config, then adds the `-display-{script}` option, so in theory i should then re-parse the configs (in the right order).

Lets see if I can do a work-around for this.

**Comment by DaveDavenport** [comment]
i think the best work-around for now is to name your script when loading:
```
rofi  -show "My Awsome Name" -modi "My Awsome Name:../Examples/rofi-file-browser.sh"
```

**Comment by DaveDavenport** [comment]
As this is gonna be a non-trivial one, bumping to later release.

**Comment by DaveDavenport** [comment]
you can now do:

```css
configuration
{
   rofi-powermenu
   {
      display-name: "PowerMenu";
   }
}
```

**Comment by dannycolin** [comment]
@DaveDavenport You rock! Thanks a lot.
