### ISSUE TITLE
Request: access the command history directly, the same way I can with bash and other shells

### ISSUE THREAD

**Issue by mrbig033** [davatorium/rofi#912]
## Version

Version: 1.3.1

## Configuration

[Output of rofi -help](https://gist.github.com/mrbig033/599d198453ee8f1bdc19a88b95efc118)

## Launch Command

`rofi -show run`

## Steps to reproduce

- Try to access the history of the last commands, like you can do on bash with `C-p` for example.

## What behaviour you see

- As far as I know, Rofi doesn't have a command to show history of previously entered commands.

## What behaviour you expect to see

- I'd like to suggest a command that let's me easily access the history of previously ran commands, like it's possible in the bash shell using `C-p` and `C-n` or the up and down arrows.

**Comment by DaveDavenport** [comment]
The top entries are normally items from history.

**Comment by mrbig033** [comment]
I'm sorry, but this is not the behavior of rofi in my machine. Is there something I can do for the items to be  arranged in this fashion?

## More about my environment

- MX Linux 17
- i3 version 4.13 (2016-11-08)

**Comment by carnager** [comment]
Well, it's not exactly like bash's history. It sorts history items by number of usage, meaning the top entry is not necessarily the command you last ran.

**Comment by DaveDavenport** [comment]
true.  Its the only history we have.

**Comment by mrbig033** [comment]
I understand. I leave that as a suggestion for possible improvements, thank. Should I close the issue? Not sure what is the etiquette here.

Anyways, thank you for the hard work ;)
