### ISSUE TITLE
Toggle ellipize

### ISSUE THREAD

**Issue by vredesbyyrd** [davatorium/rofi#917]
## Version

1.5.2

## Configuration

[gist](https://gist.github.com/vredesbyyrd/513ff6acb52ecea2742b3d4e333e03bc)

## Launch Command

`rofi -show top -modi top`

## Steps to reproduce

*  launch rofi
*  arrow right to view truncated text

## What behaviour you see

*  No change

## What behaviour you expect to see

*  Ability to view text that has been truncated by dynamically changing the ellipses. Beginning, middle(?) & end. Shift the entire view with a hotkey.   

## Further Details 

Being able to dynamically change the windows view in order to view truncated lines would be a nice feature. Basically, functioning left/right keys. I know this is a great example of something being easier said than done, and their being a lot to consider. Although I stumbled on #399 which has the same end goal and mentions this [patch](https://filebin.pw/index.php/Dbb/), which I unsuccessfully tried to apply. I am assuming it won't build since rofi's code has evolved so much since then. 

My question: if I went through line by line and manually added the contents of that patch where its needed, could i get the keybinding and behavior to "toggle ellipsis"? Or has rofi's code base changed so much that the patch is now obsolete?   

I am using rofi as a narrow sidebar that displays screen right, and with certain scripts and plugins I use having the ability to toggle between a lines _beginning and end_ could be helpful, e.g how I prefer to display _rofi_top_:   

Any thoughts on accomplishing this would be appreciated. Thanks for your time. 

![rofi-2019-02-15-1926-00000](https://user-images.githubusercontent.com/22080838/52892701-964da780-315a-11e9-8090-153223b5d9b5.png)

**Comment by DaveDavenport** [comment]
The patch won't work anymore.  Rofi code base has been in flux a lot.
I can see a use for this, will add it to the todo.

**Comment by vredesbyyrd** [comment]
That is awesome to hear. Thanks for the followup.

**Comment by DaveDavenport** [comment]
Implemented,  Should be bound to `Alt+period`.

**Comment by vredesbyyrd** [comment]
Just did some lite testing on commit 52c5592 and it seems to be working great :)
