### ISSUE TITLE
make check fails on 1.5.2

### ISSUE THREAD

**Issue by xsteadfastx** [davatorium/rofi#940]
i try to build a rofi package for alpine linux. everything works fine so far. im even using the package right now. but using `make check` in the package file fails for the keybindings.

[here](https://cloud.drone.io/alpinelinux/aports/841/1/2) is the build log.
[here](https://github.com/xsteadfastx/aports/blob/rofi/testing/rofi/APKBUILD) is the APKBUILD file ive writting.

## Version

1.5.2

## Steps to reproduce

* `./configure`
* `make`
* `make check`

## What behaviour you see

*  `FAIL: subprojects/libnkutils/tests/bindings.test `

## What behaviour you expect to see

*   `PASS: subprojects/libnkutils/tests/bindings.test `

**Comment by sardemff7** [comment]
I need the test log to know what happened, but it may be fixed in 1.5.3 already, sounds a lot like #827

**Comment by sardemff7** [comment]
Nit: you should really use the Meson build, pretty sure autotools files will disappear some day ;-)

**Comment by xsteadfastx** [comment]
meson build? are there docs about it? i used the docs from the wiki.

**Comment by sardemff7** [comment]
I will add some instructions for Meson build, but it has nothing to do with this issue (though Meson would have shown the output directly ;-) ).

Can you share the test-suite.log please?

**Comment by xsteadfastx** [comment]
this was not a bug... alpine needed to install [xkeyboard-config](https://github.com/xsteadfastx/aports/blob/16cd76781efb40955d25738c382b92385e1a4656/testing/rofi/APKBUILD#L13) to run the check. i had no idea :) but thank you
