### ISSUE TITLE
Icons with extensions but without absolute path in Icon= do not show with -show-icons

### ISSUE THREAD

**Issue by goodwillcoding** [davatorium/rofi#942]
:exclamation:
First read the [guidelines](https://github.com/DaveDavenport/rofi/blob/next/.github/CONTRIBUTING.md)!
This is not optional for any report/question. People must be able to understand the full context of the report when reading it, at any time.
If you feel like you “just have a simple question”, please consider you’re wrong and still fill the full report.
Any report missing these informations will be labeled as “Incomplete Report - Please follow the guidelines” and may not be answered in a timely fashion.
:exclamation:

## Version

Version: 1.5.1

## Configuration

Output of `rofi -help` (in a [gist](ahttps://gist.github.com/goodwillcoding/714bbdf58a240d92662cfd38a2b5e907))

## Launch Command

rofi -show-icons -show drun

## Steps to reproduce

* Create a basic .desktop launcher in 
foo.desktop:
```
[Desktop Entry]
Encoding=UTF-8
Version=1.0
Name=Foo
Comment=Bar
Type=Application
Exec=xterm
Icon=myicon
```
* Place any image as an icon into $HOME/.icons and name it myicon.png
* Run `rofi -show-icons -show drun`

## What behaviour you see

* Foo launcher will show but will be missng an incon

## What behaviour you expect to see

* Foo launcher with icon from "myicon.png" file

**Comment by sardemff7** [comment]
I just tested and checked the code too, it should be working since 6971222d070b7f797c364dba5b63ee93d89b1a4f fixing #727.
Are you sure the icon is a valid one? Did you test with the exact `.desktop` file you put here?

**Comment by sardemff7** [comment]
Btw, 1.5.1 is old. It should still work though, as the fix was in 1.5.0.

**Comment by DaveDavenport** [comment]
Weird works for me:

```
(process:6657): Helpers.IconFetcher-DEBUG: 09:04:50.614: Query: blarg(19)
(process:6657): Helpers.IconFetcher-DEBUG: 09:04:50.614: starting up icon fetching thread.
(process:6657): Helpers.IconFetcher-DEBUG: 09:04:50.619: found icon blarg(19): /home/myfancyusername/.icons/blarg.png
```

for desktop file:

```ini
[Desktop Entry]
Encoding=UTF-8
Version=1.0
Name=Foo
Comment=Bar
Type=Application
Exec=xterm
Icon=blarg
```

Can you get output of:
```
G_MESSAGES_DEBUG="Helpers.IconFetcher" rofi -show drun -filter "Foo"
```

**Comment by goodwillcoding** [comment]
@DaveDavenport SO I narrowed down the issue and it's something else. It occurs when the `Icon=` has an extension has an extension which apparently is supported from my read of this https://specifications.freedesktop.org/icon-theme-spec/icon-theme-spec-latest.html

So specifically this should be working.
```
Icon=blarg.png
```

I am going to rename the issue.

**Comment by goodwillcoding** [comment]
@DaveDavenport One thing to note is that it is nto an absolute path the `blarg.png` look up is relative. Also base on a read the PNG, XPM and SVG are supported

**Comment by sardemff7** [comment]
Actually it doesn’t seem valid. From [XDG Desktop Entry spec](https://specifications.freedesktop.org/desktop-entry-spec/latest/ar01s06.html) refers to either an absolute path or the [XDG Icon theme spec lookup algorithm](https://specifications.freedesktop.org/icon-theme-spec/icon-theme-spec-latest.html#icon_lookup). If you look closely, it **always** adds an extension to the named passed to it. So having a “relative path” (it’s not really a path, it’s a file name with an extension) is not supposed to be supported.

Please file a bug report to the upstream project that installs this `.desktop` file so they can fix it.

**Comment by sardemff7** [comment]
As a side note, from `xdg-desktop-icon --manual`:
```
Icon=Icon File
    The icon to use for the application. This can either be an absolute path to
    an image file or an icon-name. If an icon-name is provided an image lookup
    by name is done in the user's current icon theme. The xdg-icon-resource
    command can be used to install image files into icon themes. The advantage
    of using an icon-name instead of an absolute path is that with an icon-name
    the application icon can be provided in several different sizes as well as
    in several differently themed styles.
```

**Comment by goodwillcoding** [comment]
Hmmm, fair enough ... I guess some DEs just do checks outside specification (like GNOME, XFCE). Sorry I misread it and sorry to bother you.
