### ISSUE TITLE
Search Results by Frequent

### ISSUE THREAD

**Issue by mustaqimM** [davatorium/rofi#944]
## Version

Output of `rofi -v`

`Version: 1.5.2`

## Configuration

Output of `rofi -help` (in a [gist](https://gist.github.com/))

https://gist.github.com/mustaqimM/1a0707f2abc2510e1c8e1480b1449ec3
[config](https://gist.github.com/mustaqimM/a3c454a3765ea5f13d58f2be20b4f916)
[theme](https://gist.github.com/mustaqimM/cba74886f15039767db18e8aaeef6aff)
## Launch Command

The commandline used to launch **rofi**

`rofi -config ~/.config/rofi/config -show combi`
## Steps to reproduce

* [Launched Rofi shows Frequent Apps on Top: `Firefox Nightly`](https://i.imgur.com/kII6INu.png)
* [Type `Fire`](https://i.imgur.com/CW3dBKz.png)

## What behaviour you see

* Firefox isn't matched First

## What behaviour you expect to see

* Firefox isn't shown first as alphabetically or First as a Frequent App

**Comment by DaveDavenport** [comment]
History should put firefox on top. You might want to turn of sorting as that can re-order the result based on the method.

(#606 might be relevant)

**Comment by mustaqimM** [comment]
Ya that works perfectly, thanks! But just to make certain when can sort be used? Because even with history disabled, it put `Firewatch` above `Firefox`
