### ISSUE TITLE
-lines option don't work

### ISSUE THREAD

**Issue by hxss** [davatorium/rofi#945]
## Version

1.5.2

## Configuration

Output of `rofi -help` (in a [gist](https://gist.github.com/hxss/2b429fc3d73fcf5d4547e6da5c452da1))

## Launch Command

`echo "1\n2\n3\n4\n5\n6\n7\n8\n9\n0\n1\n2\n3\n4\n5\n6\n7\n8\n9\n0" | rofi -dmenu -lines 2`

`echo "1\n2\n3\n4\n5\n6\n7\n8\n9\n0\n1\n2\n3\n4\n5\n6\n7\n8\n9\n0" | rofi -dmenu -l 2`

## What behaviour you see

* I see 5 lines of items per page

## What behaviour you expect to see

* I expect 2 lines per page

I also tried rofi-git(1.5.2.r55.g855fb4e2-1) version from AUR and got same behavior.

**Comment by DaveDavenport** [comment]
I suspect your theme overrides that setting.

Try:
```
echo -e "1\n2\n3\n4\n5\n6\n7\n8\n9\n0\n1\n2\n3\n4\n5\n6\n7\n8\n9\n0" | rofi -dmenu -l 2 -no-config
```

**Comment by hxss** [comment]
You're right. Thanks.
