### ISSUE TITLE
Random crashed in rofi_view_maybe_update when running in dmenu mode

### ISSUE THREAD

**Issue by serpent7776** [davatorium/rofi#946]
Very rarely rofi crashes for me when running in dmenu mode. When I start it next time everything works correctly.
Sorry for no debugging symbols or clear steps to reproduce.

```
#0  0x0000000000420869 in rofi_view_maybe_update ()
#1  0x0000000000431fa9 in display_setup ()
#2  0x000000000043dc75 in g_water_xcb_source_get_connection ()
#3  0x00000008010a6bc7 in g_main_context_dispatch ()
   from /usr/local/lib/libglib-2.0.so.0
#4  0x00000008010a6f53 in g_main_context_pending () from /usr/local/lib/libglib-2.0.so.0
#5  0x00000008010a729f in g_main_loop_run () from /usr/local/lib/libglib-2.0.so.0
#6  0x000000000041e85c in main ()
```

## Version

Version: 1.5.2

## Configuration

https://gist.github.com/serpent7776/cdbd0459f6d2195cf086782e66107697

## Launch Command

`rofi -dmenu` started by my tool [clip-dmenu](https://github.com/serpent7776/clip-dmenu) with command `clip-dmenu.pl -b -c 'rofi -dmenu'`
[clip-dmenu config file](https://gist.github.com/serpent7776/53f1b378908e78e26fbe119e6879eeb4)

## Steps to reproduce

No clear steps to reproduce. It happens very rarely when running `clip-dmenu` which in turn starts `rofi -dmenu`

## What behaviour you see

* rofi crashed

## What behaviour you expect to see

* rofi to work without crash

**Comment by DaveDavenport** [comment]
I have not had this happen to me or got other reports.

will re-open when more info.
