### ISSUE TITLE
Add icon support to dmenu mode

### ISSUE THREAD

**Issue by IvanMalison** [davatorium/rofi#948]
#840 was closed when support for custom icons was added to script mode, but custom icons do not currently work with -dmenu mode. It would be great if they were.

**Comment by DaveDavenport** [comment]
Implemented.

**Comment by Matows** [comment]
Hello!
Sorry for bothering you, but how do we insert icon at beginning of custom menu since you implemented it?

**Comment by DaveDavenport** [comment]
I don't understand the question. For questions please use reddit/r/qtools/ or irc.
