### ISSUE TITLE
Script doesn't work

### ISSUE THREAD

**Issue by ElModdy** [davatorium/rofi#951]
## Version

Version: 1.5.2

## Configuration

[rofi -help](https://gist.github.com/ElModdy/2f75e425545d5bf9e3c6c27edf346803)

## Launch Command

**i3 config**
```
bindsym $mod+d exec "rofi -show run -modi 'run,window,Projects:project_chooser' -markup -show-icons -sidebar-mode -terminal st"
```
**Script:** [project_chooser](https://gist.github.com/ElModdy/ae1e593b390269d87271f7569c1492b2)

## Steps to reproduce

1. Press $mod+d
2. Go to the Projects tab
* type `foo +` to add a project named foo
* type `foo -` to remove the project named foo
* type `foo` to choose the project named foo

## What behaviour you see

Rofi works fine with the other modes but with mine it has some problems.
Rofi prints all the projects as you can see in the following image:

![rofi](https://user-images.githubusercontent.com/18534491/56273320-caaef700-60fc-11e9-8c28-d26f6e2877c9.png)

But it looks like Rofi can't process the input because it doesn't execute the functions ( genProject, removeProject ).
When I execute the same script from the terminal all works fine ( print, add and remove ).
To print all the projects
```
$ project_chooser
```
To remove the project "foo"
```
$ project_chooser foo -
```
To add the project "foo"
```
$ project_chooser foo +
```
To choose the project "foo"
```
$ project_chooser foo
```

**Comment by sardemff7** [comment]
rofi doesn’t split args, it passes the full input as first arg.
In your script you have:
```
# Because I don't use spaces in the name of projects
project=$1
```
Then later:
```
case $# in
```

This will make `${project}` as `foo +`, as a single string. (Please note that bash/sh do *not* split in assignments.) And `$#` will always be `1`. (Except with an unmerged feature to add history, where previous choices will be added as arguments in reverse order.)

AFAICT, there is no bug here, just wrong assumptions in the script.
