### ISSUE TITLE
Apps launched via rofi missing environment variables

### ISSUE THREAD

**Issue by jmorsecode** [davatorium/rofi#955]
## Version
Version: 1.5.2

mm## Configuration
https://gist.github.com/jmorsecode/d3a7f4df5a75f64c7195695ab368bb1a

## Launch Command
bindsym $mod+d exec --no-startup-id "rofi -i -show run -lines 6"

## Steps to reproduce
* Launch gui app, such as pycharm.
* Use feature of said app that should inherit standard env variables.

## What behaviour you see
* - Environment variables missing, such as SSH_AUTH_SOCK

## What behaviour you expect to see
* - Launching via terminal (launched directly via i3 key shortcuts) has all expected environment variables.

**Comment by sardemff7** [comment]
See the [related issues](https://github.com/davatorium/rofi/issues?q=label%3A%22Shell+environment+issue%22+is%3Aclosed). rofi will not ever fix your shell environment issues.

**Comment by jmorsecode** [comment]
This seems to be a good enough work around: 
bindsym $mod+d exec "rofi -run-command '/bin/bash -c -i {cmd}' -show run"
For those that stumble into here.

**Comment by sardemff7** [comment]
Please, don’t, anyone having this issue just has a bad environment setup that should really be fixed. Any workaround is discourage by rofi devs. You’re on your own if you chose to do that.
