### ISSUE TITLE
tty-pipe?

### ISSUE THREAD

**Issue by prankousky** [davatorium/rofi#956]
Hi everybody,

I am running `Linux archbook 5.0.9-arch1-1-ARCH #1 SMP PREEMPT Sat Apr 20 15:00:46 UTC 2019 x86_64 GNU/Linux` with `rofi 1.5.2`. Just went through `rofi.1.markdown` and found this command: `tty-pipe nmcli device wifi | out2html -p | rofi -dmenu -markup-rows`.

Where can I find `tty-pipe` so that I can try this example? `which tty-pipe` does not find it. It can neither be found in the official, nor the community repo. I could not find anything related to this via websearch, except for two programs named `ttypipe`; I tried one of them, but it was definitely something else, because the example command did not work.

I was also missing `out2html`, which I was able to install though. Sorry if this is a dumb question, but since I cannot find this program, neither was it installed with rofi, I figured I'd just ask here.

Thanks in advance for your support :)

**Comment by DaveDavenport** [comment]
Yeah, I should probably remove this or fix it.

`tty-pipe` source is included in `out2html` but I do not think it is build automagically with it.
https://github.com/DaveDavenport/out2html/blob/master/tty-pipe.c

**Comment by DaveDavenport** [comment]
What tty-pipe does is full the tool to think it is running inside a terminal (so its `isatty` call returns true) and use colors.

**Comment by prankousky** [comment]
Thank you. I have installed `out2html` from the AUR. Is there some way to get it compiled with tty-pipe from the AUR (I have no idea how I'd automatically compile it with it included)?

Do you mean `stdoutisatty`? This is the only tool I was able to find. I can replace it in the example, but then I'll get 

```
IN-USE SSID MODE CHAN RATE SIGNAL BARS SECURITY
somenetwork Infra 36 405 Mbit/s 70 ▂▄▆ WPA2
someothernetwork Infra 36 405 Mbit/s 69 ▂▄▆ WPA2
yup Infra 36 405 Mbit/s 67 ▂▄▆ WPA2
drucker Infra 36 54 Mbit/s 67 ▂▄▆ WEP
* yup Infra 6 195 Mbit/s 65 ▂▄▆ WPA2
someothernetwork Infra 6 195 Mbit/s 65 ▂▄▆ WPA2
somenetwork Infra 6 195 Mbit/s 65 ▂▄▆_ WPA2
yup Infra 36 405 Mbit/s 55 ▂▄ WPA2
-- Infra 36 405 Mbit/s 55 ▂▄ WPA2
someothernetwork Infra 36 405 Mbit/s 55 ▂▄ WPA2
drucker Infra 36 54 Mbit/s 55 ▂▄ WEP
somenetwork Infra 36 405 Mbit/s 54 ▂▄ WPA2
somenetwork Infra 6 195 Mbit/s 52 ▂▄ WPA2
drucker Infra 6 54 Mbit/s 52 ▂▄__ WEP
```
This looks correctly when posted here as code, but in rofi it will display lines like
`
<span color='#808000'> </span>       <span color='#808000'>somenetwork</span>           <span color='#808000'>Infra</span>  <span color='#808000'>36</span>    <span color='#808000'>405 Mbit/s</span>  <span color='#808000'>69</span>      <span color='#808000'>&#9602;&#9604;&#9606;_</span>  <span color='#808000'>WPA2</span>     `

I used `stdoutisatty nmcli device wifi | out2html -p | rofi -dmenu -markup-row`.

**Comment by DaveDavenport** [comment]
For network information there are some networkmanager dmenu scripts on github that will work with rofi.

**Comment by DaveDavenport** [comment]
I think there is one on this page: https://github.com/davatorium/rofi/wiki/User-scripts

**Comment by DaveDavenport** [comment]
removed entry from manpage.
