### ISSUE TITLE
Feature request: fake-background scaling

### ISSUE THREAD

**Issue by harrisonthorne** [davatorium/rofi#958]
Rofi version 1.5.2

I would really like to set a custom background for when I open rofi. I'm currently using the `fake-background` option, but scaling isn't supported/working yet. In case an image is large (like a big wallpaper), I would like for the background to be centered and to fill the screen, much like `feh`.

I'm using this to show a customized version of my desktop background. I imagine other ricers would like to have this feature too.

Thanks :) Love this project :)

*edit: clarifying that i'm using the `fake-background` option*

**Comment by DaveDavenport** [comment]
If I understand correctly you are passing an image to the ' fake-background'  option? (not screenshot or background)

In the new theme format I think we can easily add some extra options.

**Comment by DaveDavenport** [comment]
I've implemented this, but slightly different.
You can now set:
```css
window {
background-image: url("path", scale):
}
```

where scale can be `both`,`none`,`width`,`height`.

**Comment by DaveDavenport** [comment]
![image](https://user-images.githubusercontent.com/406245/122098432-1e1e4c00-ce11-11eb-87a8-b11b32395fa4.png)
example.
