### ISSUE TITLE
Rofi crashes from bindsym script

### ISSUE THREAD

**Issue by thepenguinthatwants** [davatorium/rofi#959]
Hi!

Not sure if this is a bug in rofi or i3 or something else.
So the script itself works quite well but when I try to open it by bindsym then it doesn open and rofi itself just doesnt work anymore and I have to kill it.

The error:
```
(process:24274): Helper-WARNING **: 21:59:52.297: Failed to set lock on pidfile: Rofi already running?

(process:24274): Helper-WARNING **: 21:59:52.297: Got error: -1 Socket operation on non-socket
```

The keybinding
`bindsym $mod+c exec /home/scripts/gpaste.sh`

The script (that I found and tried)
> #!/usr/bin/env bash
> 
> line=`gpaste-client --oneline | \
>       rofi -theme Adapta-Nokto -dmenu -i -p gpaste -kb-custom-1 Ctrl+x $@`
> exit_code=$?
> 
> index=`echo $line | cut -d ':' -f1`
> if ! [[ $index =~ ^[0-9]+$ ]]; then
>     exit 0
> fi
> 
> if [ $exit_code == 0 ]; then
>     gpaste-client select $index
> elif [ $exit_code == 10 ]; then
>     gpaste-client delete $index
> fi

**Comment by DaveDavenport** [comment]
Can you post the missing information, without this we cannot help debug the issue.

**Comment by thepenguinthatwants** [comment]
Hi!

Sorry for the incomplete report.

Rofi Version: 1.5.2
rofi config: https://gist.github.com/thepenguinthatwants/9c93e9305d7f960037052a31e20a7337

The behaviour I expect to see was it to show gpaste history menu. It does work if I use sh to it, but when trying to use i3wm keybinding to it then it doesnt open rofi and then it gives the error when I run rofi in terminal.

**Comment by DaveDavenport** [comment]
This is not a crash, but rofi reporting an error situation, it fails to generate a pid file.
So we need to figure out why?  

I see from the config you have not changed the PID file location. So they are obtained using XDG system (and environment variables play a role in this). It is possible I3 environment is different from your terminal (causing the different behaviour).


You can (for testing) try to change the rofi line:

```bash
rofi -theme Adapta-Nokto -dmenu -i -p gpaste -kb-custom-1 Ctrl+x -pid  ~/.rofi.pid $@
```

See if this works.

**Comment by thepenguinthatwants** [comment]
Hi!

Thanks I didn't know that u could define pid file.

Added

**Comment by DaveDavenport** [comment]
Weird.. Is there a stuck rofi running? This pid file stuff have been pretty reliable for a very very long time.

**Comment by thepenguinthatwants** [comment]
There shouldn't be any stuck rofi running.

I guess the bash script itself has a problem that for some reasons it just gets stuck when using bindsym. 

I can run rofi althought it uses different pid file than the script itself.

**Comment by thepenguinthatwants** [comment]
When I tried to run it with sudo I get

Error spawning command line ?dbus-launch --autolaunch=53014fc5e0074218800c02b5cc56edf9 --binary-syntax --close-stderr?: Child process exited with code 1

**Comment by DaveDavenport** [comment]
closing for now, if more information insights show up, will reopen.
