### ISSUE TITLE
Background Image / css gradients

### ISSUE THREAD

**Issue by vredesbyyrd** [davatorium/rofi#960]
## Version

1.5.2

## Launch Command

rofi -show combi -combi-modi "drun,window" -show -modi combi -display-combi ">>>" -window-format "{w} {n}" 

## Steps to reproduce

* In a rasi theme, try setting the selected bg color as an image.  e.g

`#element selected {  background-image:  linear-gradient(to right,  #181E21,  #37474F);  } `

## What behaviour you see

* Not currently possible.

## What behaviour you expect to see

* Just playing around with styling rofi, and wanted to set the _selected-background_ as a linear-gradient, but if I am understanding correctly the  _image data type_ is not currently supported in the rasi theme format.  I could be overlooking something as I am just now familiarizing myself with the rasi format. 

Thank you for sharing this amazing tool.

**Comment by dannycolin** [comment]
> if I am understanding correctly the image data type is not currently supported in the rasi theme format.

You're right. Gradient backgrounds aren't supported yet.

**Comment by vredesbyyrd** [comment]
Thank you for confirming that. When running rofi as a launcher/ window switcher, I started using it as a little one-liner that opens up over my panel, which uses a gradient for active items. I could not resist the urge to make rofi share the same style for selected items, haha. Maybe at some point in the future... 

https://imgur.com/a/pKKIwqJ

**Comment by DaveDavenport** [comment]
Added very very very basic support  for `background-image: url("test.png");` and `background-image: linear-gradient(start,stop);`

**Comment by DaveDavenport** [comment]
![image](https://user-images.githubusercontent.com/406245/121822063-4d13b100-cc9d-11eb-8d52-16e702807ce9.png)
