### ISSUE TITLE
Option: `drun-icon-theme` is not found

### ISSUE THREAD

**Issue by Dentrax** [davatorium/rofi#963]
## Version

`1.5.2`

## Configuration

https://0x0.st/zAsq.txt

## Launch Command

`echo $'\n\n' | rofi -theme themes/scrot.rasi -font "Font Awesome 5 Pro Solid 50" -dmenu`

## Steps to reproduce

* Step 1

**config.rasi**

```
configuration {
    drun-icon-theme:    "Paper";
    cycle:              true;
    hide-scrollbar:     true;
    disable-history:    true;
    modi:               "drun";
    show-icons:         true;
    display-drun:       "apps";
}
```

* Step 2

**themes/scrot.rasi**

```
{
    main-color:       #728cbb;
    background:       #1c1c1c;
    background-light: #1f1f1f;
    background-focus: #282828;
    foreground:       #888888;
    background-color: @background;
    text-color:       @foreground;
    font:             "Font Awesome 5 Pro Solid 50";
}
#window {
    width: 1366px;
    height: 768px;
    padding: 270px 289px;
    children: [ horibox ];
}
#horibox {
    children: [ listview ];
    padding: 0px;
}
#listview {
    layout: horizontal;
    spacing: 40px;
    lines: 3;
}
#element {
    /* top right bottom left */
    /*no space is 0px 0px -8px -81px*/
    padding: 70px 70px 62px -11px;
    border: 0px 0px 8px 0px;
    background-color: @background-light;
    border-color: @background-light;
}
#element.selected {
    background-color: @background-focus;
    text-color: @main-color;
    border-color: @main-color;
}
```

* Step 3

Run the `Launch Command`

## What behaviour you see

* - `WARNING **: 22:25:50.503: /home/dentrax/.config/rofi/config.rasi:1:16: Option: drun-icon-theme is not found.`

* - Icons won't loading.

## What behaviour you expect to see

* - https://gitlab.com/vahnrr/dots/blob/master/i3-laptop/examples/rofi_scrot.png

**P.S:** Trying to implement [this](https://gitlab.com/vahnrr/dots/tree/master) config.

**Comment by DaveDavenport** [comment]
This is correct, this option no longer exists.

Look at the option:

```
icon-theme
```
