### ISSUE TITLE
Cannot See Snap/Snapcraft Packages/Apps in Rofi

### ISSUE THREAD

**Issue by Arszilla** [davatorium/rofi#964]
## Version
`Version: 1.5.2`

## Configuration
[rofi -help](https://gist.github.com/Arszilla/50e0fc9c53e733fd1a88ff0e2c705c4e)

## Launch Command
`$mod+d exec rofi -show run -lines 3 -eh 2 -width 100 -padding 800 -opacity "85" -bw 0 -bc "$bg-color" -bg "$bg-color" -fg "$text-color" -hlbg "$bg-color" -hlfg "#9575cd" -font "Hack Nerd Font 15"`

## Steps to reproduce
Install `spotify` via `snapd` using `sudo snap install spotify`

## What behaviour you see
I don't see `spotify` in `rofi -show run`

## What behaviour you expect to see
To see `spotify` in `rofi -show run`

**Comment by DaveDavenport** [comment]
Are the snaps in your $PATH?
Can you post the content of your $PATH?

**Comment by DaveDavenport** [comment]
For `drun` mode check if your XDG_DATA_DIRS is setup correctly to include the snap desktop files:

```
XDG_DATA_DIRS=/usr/share/:/usr/local/share/:/var/lib/snapd/desktop
```

**Comment by Arszilla** [comment]
`echo $PATH` returns this: `/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl`

> For `drun` mode check if your XDG_DATA_DIRS is setup correctly to include the snap desktop files:
> 
> ```
> XDG_DATA_DIRS=/usr/share/:/usr/local/share/:/var/lib/snapd/desktop
> ```

Not sure how can I do that

**Comment by DaveDavenport** [comment]
That looks like snap (normally in `/snap/bin/` ) is not in your PATH.

You need to fix your PATH.  Best is to check with your distribution support to see what the best way to do this.
