### ISSUE TITLE
columns in dmenu mode?

### ISSUE THREAD

**Issue by prankousky** [davatorium/rofi#965]
Hi,

I am using `rofi Version: 1.5.2` on current `archlinux` with `i3gaps`. I set columns in `.Xresources` to `2`, which works.

Now I am trying to write a script that has more than two columns; it's more complex than this, but this should work as an example `ls | grep mp4 | rofi -dmenu -i -multi-select`. I tried putting `-columns 4` right after `rofi` as well as at the end (after `-multi-select`), but neither will work. Putting it at the end has no effect, while putting it right after rofi works in a way that rofi will pop up for a second, then close itself, and use **all** files that have been `ls`ed.

Is it not possible to use column like this? Or what did I do wrong in this case? Thank you for your help.

**Comment by DaveDavenport** [comment]
Cannot reproduce this issue at all.  It works for me.. Without more information (as requested) nothing we can do.
