### ISSUE TITLE
Xorg crashes when switching to to another i3 workspace

### ISSUE THREAD

**Issue by Deedone** [davatorium/rofi#968]
I dont now if this issue with rofi or i3 or xorg, but it feels very frustrating

## Version

Version: 1.5.2
Xorg version: 1.20.4-1
i3-gaps version: 4.16.1-1

## Configuration

[Gist](https://gist.github.com/Deedone/a074f0b6a0835733122cbba82f7d13a2)

## Launch Command

rofi -show run

## Steps to reproduce

* Install I3-gaps
* Open some windows on 2 different workspaces
* Open rofi on any of them
* Switch to other

## What behaviour you see

* Entire system crushing with forced reboot

## What behaviour you expect to see

* Entire system not crashing

**Comment by DaveDavenport** [comment]
How do you:
` switch to other `

rofi should grab all keys and not allow you to switch. (still xorg should not crash).

**Comment by Deedone** [comment]
As usual pressed Mod+number, i3 config is default
```
bindsym $mod+1 workspace $ws1
bindsym $mod+2 workspace $ws2
bindsym $mod+3 workspace $ws3
```

**Comment by DaveDavenport** [comment]
What is `$mod`?

**Comment by Deedone** [comment]
Mod4(Windows logo) key

**Comment by DaveDavenport** [comment]
Super+ [123]   are hotkeys to select the first,second,third entry in rofi.
Rofi should normally handle these (they keypresses should not 'reach'  I3)

This is not going to be an easy one to debug, as it is unclear what is going wrong.
Only thing I can say is that; xorg should not crash (whatever rofi/i3 does), so I think that is probably the best place to start debugging.

**Comment by Deedone** [comment]
Oh, i think i accidentally selected entry with shutdown command, thank you for helping me to understand it
