### ISSUE TITLE
Feature request: Set window title

### ISSUE THREAD

**Issue by JonnyHaystack** [davatorium/rofi#969]
It would help a lot if there was a configuration parameter that allowed you to set the window name to be something other than 'rofi'. i.e. if I could set window_name = "something" in my rofi config then that would alter the WM_NAME property of the rofi window.

The reason this would be very useful is because it allows you to use different window rules or events with different rofi configurations. For example, I mostly use the drun and ssh modi, but I have a script launched by polybar that uses rofi to select my default pulseaudio output device. For the animation of the rofi window to work nicely, I need the window to be initially invisible, and then show it when the sliding up animation starts.

The only way I know how to do this is by having a compton opacity rule to make rofi invisible and then using transset to show it when it is in position. Currently the only way I can do this is by making every rofi window initially invisible, and I have to use transset each time I use rofi, which isn't really something I want to be doing every time I use it in drun mode.

If I could set a different window name for the pulseaudio instance of rofi, then I could simply have a compton rule which only applies to that window name, which would be a lot cleaner.

## Version
Version 1.5.2

**Comment by DaveDavenport** [comment]
@sardemff7  proposes to change the window name based on the active mode. 
This sounds like a nice solution. (No extra option needed)
Would this be sufficient?

**Comment by JonnyHaystack** [comment]
@DaveDavenport I don't think that would be enough, because dmenu mode is used for so many different things. I use it for the pulseaudio script, but also for LastPass, NetworkManager, etc.

**Comment by sardemff7** [comment]
The point would be to *not* use the dmenu mode but a specific named script for each of these, so we wouldn’t need to add yet another option. :-)

**Comment by JonnyHaystack** [comment]
Ah, I didn't know about rofi userscripts until now. I was just doing things the old dmenu way :stuck_out_tongue: 

In that case if each userscript has a different window name then yes, that sounds great :smiley:
