### ISSUE TITLE
Multi monitor focus

### ISSUE THREAD

**Issue by jpldcarvalho** [davatorium/rofi#971]
**Version**: 1.5.2

**Configuration**: https://gist.github.com/jpldcarvalho/e751d991e0acd808d714699606534e24

**Launch Command**: rofi -show run

## Steps to reproduce

* Setup dual monitor environment
* Point the mouse in one screen
* With a shell in the other scree try to run rofi (or focus the other screen and press your shortcut)
* Independent of the focused monitor, rofi will open on the screen where the mouse is pointed

## What behaviour you see

* Rofi opens on the screen where the mouse is
* Rofi opens whatever I open in the screen where the mouse is

## What behaviour you expect to see

* Rofi and the software I open to be opened on the focused screen

Thank you very much !

**Comment by sardemff7** [comment]
Try `monitor` config to `-4`.

**Comment by jpldcarvalho** [comment]
It doesn't work.
But.... I tried with other options and it works changing between 0 and 1 (for the monitors id) which will help with a workaround. Between -3 and -1 I get different results but nothing good.

**Comment by jpldcarvalho** [comment]
I'm closing this issue because it needs further testing and the problem might not be with Rofi itself.
I'm using dwm and I think by default the focused window (thus screen) is the one pointed by the mouse, even if you go other windows on the same or other screen.
I'll re-open the issue if it persists after checking/changing the dwm behaviour.

Thank you very much!
