### ISSUE TITLE
.desktop files are not executed in a shell

### ISSUE THREAD

**Issue by tudurom** [davatorium/rofi#973]
## Version

```
Version: 1.5.2-88-g361ce7d6 (makepkg)
```

## Configuration

https://gist.github.com/tudurom/301fb9dfa2f47569ed6f32f1dd237560

## Launch Command

```
rofi -show drun
```

## Steps to reproduce

* Step 1: Open rofi in `drun` mode.
* Step 2: Open `.desktop` file that has environment variables in it

Example `.desktop` file:

```desktop
[Desktop Entry]
Version=1.0
Name=Firefox
# elided content
Exec=GDK_DPI_SCALE=1.2 /usr/lib/firefox/firefox --new-window %u
```

## What behaviour you see 

![screenshot](https://i.imgur.com/49oRo6a.png)

## What behaviour you expect to see

Firefox launching normally with the `GDP_DPI_SCALE` in effect.

**Comment by sardemff7** [comment]
And that’s exactly as expected by the [spec](https://specifications.freedesktop.org/desktop-entry-spec/latest/ar01s06.html). `Exec` is a program to execute, so to get the behaviour you want, use `env` as a wrappe.
