### ISSUE TITLE
Pango failed to parse font

### ISSUE THREAD

**Issue by siddbudd** [davatorium/rofi#974]
## Version

Version: 1.5.2 (installed from Arch "Community" repo)

## Configuration

[rofi -help](https://gist.github.com/siddbudd/63f22b9dfc67cdf1b6ca969f0058b5dd/)

## Launch Command

```
rofi
rofi -show run 
rofi -show window
```
etc. all produce same result

## Steps to reproduce

* Step 1: launch rofi using above commands

## What behaviour you see

* - Only an error is shown saying 

> The following errors were detected when starting rofi
> The configuration failed to validate
> Pango failed to parse font 'Liberation Mono':pixelsize=22...

I cannot select and copy the text and I will not type it all out, but you get the idea.

## What behaviour you expect to see

* - rofi launches

## Workaround

launch with explicit font as:
```
rofi -show run -font "hack 16"
rofi -show run -font "Liberation Mono 16"
```
or actually **any** character before the font size, even

> rofi -show run -font "l 16"

works just fine.

**Comment by sardemff7** [comment]
A Pango font description is **not** a fontconfig font description. In fact, your workaround is a proper Pango font description.

**Comment by siddbudd** [comment]
Hi! I have no idea what Pango is, I did a clean installation of rofi and didn’t touch anything, just launched it and got this error. Are you implying that I always need to explicitly add the font as option to launch rofi?

**Comment by sardemff7** [comment]
No, you already have a font in your Xresources (whire are to be deprecated at some point), you just need to set it with the right format. If rofi is catching some more generic font setting (`*.font` maybe? I don’t use Xresources) then you actually need to set a rofi-specific setting. I would suggest to switch to the rasi config file format now, but `rofi.font` in Xresources can be used in the meantime.
