### ISSUE TITLE
Extra pixels in selected elements

### ISSUE THREAD

**Issue by marioortizmanero** [davatorium/rofi#976]
## Version
1.5.2

## Configuration
Default

## Launch Command
Any, for example `rofi -show run`

## What behaviour you see
There are 2 extra pixels when you select the normal elements, compared to the alternate ones. Here's what it looks like for the normal ones:

![https://i.imgur.com/PXdprBR.png?1](https://i.imgur.com/PXdprBR.png?1)

Here's what it looks like for the alternate ones:

![https://i.imgur.com/A6EwqzT.png?1](https://i.imgur.com/A6EwqzT.png?1)

Here are the 2 extra pixels in the normal ones, on top and on the bottom, in red:

![https://i.imgur.com/GEutGXY.png](https://i.imgur.com/GEutGXY.png)

## What behaviour you expect to see

Both types of elements should have the same height by default and not have extra pixels on the top or bottom. When you select the normal element, only the selection color should be seen. But instead, you can see the selection color with 2 pixels on top and bottom with the background color.

**Comment by DaveDavenport** [comment]
Its identical for me (in git).

![size-rows](https://user-images.githubusercontent.com/406245/58901748-1562ed80-8702-11e9-9a6d-c248998f13eb.png)

Can you pastebin  the output of `rofi -dump-theme`

**Comment by DaveDavenport** [comment]
You can change what you see btw by removing the spacing on the listview:

```
rofi  -no-config -theme-str 'listview{ spacing : 0;}'  -show run
```
In the default theme this is set to 2px.  (it is the same for each element).

**Comment by marioortizmanero** [comment]
Okay it works perfectly with that change. Why does the default theme use 2px of spacing there then? Shouldn't it be changed?

**Comment by DaveDavenport** [comment]
imho it looks cramped without the spacing.
