### ISSUE TITLE
Rofi displays spaces wrong

### ISSUE THREAD

**Issue by vityavv** [davatorium/rofi#978]
## Launch Command

I am running rofi with a custom script I made which you can find [here](https://github.com/vityavv/dotfiles/blob/master/bin/status.sh).

## Steps to reproduce

* Step 1: Run the command. The buggy part occurs after the line `# Get memory status`.
* Step 2: Look at the output.

## What behaviour you see

* - I see that the number of spaces after the memory bar is incorrect; here:
![image](https://user-images.githubusercontent.com/4335566/59441885-3c3ab700-8dc7-11e9-8570-9d975431903a.png)

(sorry it's not cropped)

## What behaviour you expect to see

* - I expect to see something like this image here (in my terminal, after running `getoutput` from the program manually:
![image](https://user-images.githubusercontent.com/4335566/59441771-18777100-8dc7-11e9-8f16-a559100f2142.png)

## Edit

Inserting the awk code like this:

```awk
z=0;
printf "Memory: [";
while(++z < $3/200000) printf " ";
printf "]\n";
```

and replacing `$3` with `$2` and `($3 - $2)`, it prints the correct number of spaces (in rofi and in the terminal). The first instance still prints the wrong amount

**Comment by DaveDavenport** [comment]
Rofi does nothing with the string and passes it directly to pango. 
Is the alignment correct (when using same font/size) in programs like gedit?

**Comment by vityavv** [comment]
Sorry for the late response. It does not show properly in gedit.

![image](https://user-images.githubusercontent.com/4335566/59564171-95962680-9011-11e9-80d0-a057937ab725.png)

**Comment by DaveDavenport** [comment]
Then it sounds like an upstream pango bug and not a rofi issue as gedit also uses pango for rendering.

**Comment by DaveDavenport** [comment]
based on #977 assume this is fixed upstream. please let me know if not.
