### ISSUE TITLE
rofi -show crash, corrupted size vs. prev_size Aborted (core dumped)

### ISSUE THREAD

**Issue by WoollyMammal** [davatorium/rofi#980]
:exclamation:
First read the [guidelines](https://github.com/DaveDavenport/rofi/blob/next/.github/CONTRIBUTING.md)!
This is not optional for any report/question. People must be able to understand the full context of the report when reading it, at any time.
If you feel like you “just have a simple question”, please consider you’re wrong and still fill the full report.
Any report missing these informations will be labeled as “Incomplete Report - Please follow the guidelines” and may not be answered in a timely fashion.
:exclamation:

## Version

Output of `rofi -v`
Version: 1.5.3

## Configuration

Output of `rofi -help` (in a [gist](https://gist.github.com/WoollyMammal/ed4a78b32ccb6ba2fac965f4bff60995))

I did just do a system upgrade, though I just reinstalled so my system is pretty lean. 

## Launch Command

The commandline used to launch **rofi**
`rofi -show combi`

## Steps to reproduce

1. Upgrade to v1.5.3
2. Try run `rofi -show combi`, or any `rofi -show *` command.

## What behaviour you see

```
Mode combi is not enabled. I have enabled it for now.
Please consider adding combi to the list of enabled modi: modi: window,run,ssh,combi.
corrupted size vs. prev_size
Aborted (core dumped)
```
Or for `rofi -show`:
```
corrupted size vs. prev_size
Aborted (core dumped)
```

## What behaviour you expect to see

* The combi menu to appear, or for it to at least not crash.

**Comment by DaveDavenport** [comment]
can you post the coredump?

**Comment by WoollyMammal** [comment]
Sorry for the delay, this is the first time I've uploaded one.

[rofi-coredump.tar.gz](https://github.com/davatorium/rofi/files/3322303/rofi-coredump.tar.gz)

**Comment by DaveDavenport** [comment]
what distro?

**Comment by WoollyMammal** [comment]
Arch. I just built it though, so I'm probably missing a bunch of "normal" packages.

**Comment by DaveDavenport** [comment]
Can you create a coredump using:
```
coredumpctl dump
```

binary dump is not very useful for me.

**Comment by WoollyMammal** [comment]
Whenever I do that I still get a binary output. But here's the text that the tool is writing to stdout.
Username and hostname have been altered.

PID: 4324 (rofi)
           UID: 1000 (username-redacted)
           GID: 1000 (username-redacted)
        Signal: 6 (ABRT)
     Timestamp: Mon 2019-06-24 20:18:24 BST (36min ago)
  Command Line: rofi -show
    Executable: /usr/bin/rofi
 Control Group: /user.slice/user-1000.slice/user@1000.service/gnome-terminal-server.service
          Unit: user@1000.service
     User Unit: gnome-terminal-server.service
         Slice: user-1000.slice
     Owner UID: 1000 (username-redacted)
       Boot ID: 75559e91d2de4ec9b1c944a1b1bc9337
    Machine ID: 17856e51192f4b5297939ee4c0fc38c7
      Hostname: hostname-redacted
       Storage: /var/lib/systemd/coredump/core.rofi.1000.75559e91d2de4ec9b1c944a1b1bc9337.4324.1561403904000000.lz4
       Message: Process 4324 (rofi) of user 1000 dumped core.
                
                Stack trace of thread 4324:
                #0  0x00007fc250c42755 raise (libc.so.6)
                #1  0x00007fc250c2d851 abort (libc.so.6)
                #2  0x00007fc250c84a28 __libc_message (libc.so.6)
                #3  0x00007fc250c8b23a malloc_printerr (libc.so.6)
                #4  0x00007fc250c8b906 unlink_chunk.isra.0 (libc.so.6)
                #5  0x00007fc250c8efb9 _int_realloc (libc.so.6)
                #6  0x00007fc250c901ab realloc (libc.so.6)
                #7  0x00007fc251dfe8f9 g_realloc (libglib-2.0.so.0)
                #8  0x000055c0fd7709f2 n/a (rofi)
                #9  0x000055c0fd759a96 n/a (rofi)
                #10 0x000055c0fd75a397 n/a (rofi)
                #11 0x00007fc251e047b1 g_main_context_dispatch (libglib-2.0.so.0)
                #12 0x00007fc251e06869 n/a (libglib-2.0.so.0)
                #13 0x00007fc251e077f2 g_main_loop_run (libglib-2.0.so.0)
                #14 0x000055c0fd7501ff main (rofi)
                #15 0x00007fc250c2eee3 __libc_start_main (libc.so.6)
                #16 0x000055c0fd7502ee _start (rofi)
                
                Stack trace of thread 4326:
                #0  0x00007fc250cf9497 __poll (libc.so.6)
                #1  0x00007fc251e067c0 n/a (libglib-2.0.so.0)
                #2  0x00007fc251e077f2 g_main_loop_run (libglib-2.0.so.0)
                #3  0x00007fc251f7c508 n/a (libgio-2.0.so.0)
                #4  0x00007fc251de1f21 n/a (libglib-2.0.so.0)
                #5  0x00007fc250dd457f start_thread (libpthread.so.0)
                #6  0x00007fc250d03f13 __clone (libc.so.6)
                
                Stack trace of thread 4325:
                #0  0x00007fc250cf9497 __poll (libc.so.6)
                #1  0x00007fc251e067c0 n/a (libglib-2.0.so.0)
                #2  0x00007fc251e068ae g_main_context_iteration (libglib-2.0.so.0)
                #3  0x00007fc251e06902 n/a (libglib-2.0.so.0)
                #4  0x00007fc251de1f21 n/a (libglib-2.0.so.0)
                #5  0x00007fc250dd457f start_thread (libpthread.so.0)
                #6  0x00007fc250d03f13 __clone (libc.so.6)
More than one entry matches, ignoring rest.

**Comment by DaveDavenport** [comment]
thx.

**Comment by DaveDavenport** [comment]
Think I fixed it in GIT.

(can you try disabling parse-hosts entry, see if that fixes it?)

**Comment by WoollyMammal** [comment]
Ha, yeah that worked. Excellent work!
Okay, I'll work with parse-hosts disabled for now (or upgrade to the git version).
