### ISSUE TITLE
Segmentation fault on startup with 1.5.3

### ISSUE THREAD

**Issue by iwolterstorff** [davatorium/rofi#981]
## Version

Output of `rofi -v`
`Version: 1.5.3`

## Configuration
Using up-to-date Arch Linux with kernel 5.1.14.

Output of `rofi -help` (in a [gist](https://gist.github.com/))
https://gist.github.com/iwolterstorff/849d497b06af1ee0fd99979117747422

## Launch Command

`rofi -show run`

## Steps to reproduce

* run `rofi -show run` at a non-root command line.
(does work with `sudo`)

## What behaviour you see

* - Rofi instantly terminates with SIGSEGV (Address boundary error).

## What behaviour you expect to see

* - A Rofi menu should appear with a list of programs to run.

This issue appeared today after upgrading to 1.5.3. Rofi 1.5.2 still works perfectly on my machine after downgrading.

**Comment by sardemff7** [comment]
Is that a duplicate of #980 ? Please try the `next` branch (`rofi-git` from AUR).

**Comment by iwolterstorff** [comment]
Yes, it was fixed by that patch. My apologies for not checking the closed issues.
