### ISSUE TITLE
Can't open programs with termite on version 1.5.3

### ISSUE THREAD

**Issue by digitalphoton** [davatorium/rofi#982]
After updating to version 1.5.3, I am unable to open terminal-based programs with termite using rofi. Downgrading to version 1.5.2 fixes the problem.

## Version

Version: 1.5.3

## Configuration

[gist](https://gist.github.com/digitalphoton/e2a101a92cd466b8c64df0d59e488c8b)

## Launch Command

`rofi -show drun`

## Steps to reproduce

* Step 1: Ensure that termite is the only terminal emulator installed (otherwise rofi will just use something else)
* Step 2: Launch rofi
* Step 3: Attempt to launch a program that runs on a terminal (like Ranger or Neovim)

## What behaviour you see

* Rofi shows the error message "Failed to find a suitable terminal"

## What behaviour you expect to see

* The desired program opening in termite

**Comment by sardemff7** [comment]
It was intentionally removed in 2a93daec0429f0a241687e74740eb73f7f066123 as Termite doesn’t support the default `-e` command line argument, which broke the default setup when Termite was detected.

Set the `terminal` option to `termite` (instead of `rofi-sensible-terminal`) and it’ll work as expected.

**Comment by TheBabu** [comment]
I know this issue is closed but it looking the manpage for termite it does support the `-e` flag? Is it possible for the devs to check if the behavior is expected from termite?

**Comment by sardemff7** [comment]
It is not up to us to test every single terminal emulator around. If you think Termite was fixed, please test yourself (you can edit the script before installing, or copying it in a `$HOME`-based `bin` directory added to your `$PATH`) and open a Pull Request on Github *with all the information*, specifically which version of Termite is following the proper `-e` behaviour.

Reading back the issue that lead to the removal of Termite from the list, it does mention Terminator only, but it could have been a comment on IRC that made Termite go too.
