### ISSUE TITLE
Multi-line output - help

### ISSUE THREAD

**Issue by vredesbyyrd** [davatorium/rofi#983]
## Version
1.5.2-79-g4c205649

## Configuration
 [pastebin](https://pastebin.com/a2cSwD7k)

## Launch Command
` bt list | perl -pe 's#(https)#\n$1#' | rofi -dmenu -eh 2 -sep '\n'  `

## Steps to reproduce
* run rofi with above command -  [brotab](https://github.com/balta2ar/brotab) required

## What behaviour you see
 ![rofi-2019-06-27-1421-00000](https://user-images.githubusercontent.com/22080838/60294432-f281be80-98e6-11e9-97a5-037651e2bb14.png)
 
## What behaviour you expect to see
*  Using the first result in the above screenshot as an example,  **title**  - `André Simon / ansifilter · GitLab`  & accompanying **url** - `https://gitlab.com/saalen/ansifilter`, I am trying to get the _url_ to be on a new line and highlighted with the _title_, instead its on the 3rd line. 

I assume I am using the `-sep` option incorrectly, I have read through all related issues but have yet to figure it out. The `bt list` command lists the _title_ then _url_ on the same line. In the example launch command the perl section of the pipe just puts anything starting with `https` on a newline. I intend to accomplish that differently and just used it here for simplicity sake. 

Any thoughts on properly using the `-sep` +  `-eh` options for multi-line output would be very appreciated. Thanks for your time.

**Comment by DaveDavenport** [comment]
I don't follow?

You split the input data on newlines ('\n') (this will also *remove* every newline ) yet you want rofi to show newlines? 

Is something like this:
```
echo -en "a\nb\x0fc\nd" | rofi -dmenu -sep '\x0f' -eh 2
```
Not what you want?

The issue tracker is for **issues** with rofi, general questions about usage should be on either IRC or the reddit forum. See the [guidelines](https://github.com/davatorium/rofi/blob/next/.github/CONTRIBUTING.md)

**Comment by vredesbyyrd** [comment]
> Is something like this:
>  `echo -en "a\nb\x0fc\nd" | rofi -dmenu -sep '\x0f' -eh 2` 
> Not what you want? 

Yes, that is precisely the behavior I want. I just cant apply it in this case. If I just run this command on the terminal: 
`
bt list | perl -pe 's#(https)#\n$1#'  `  or  
`bt list | sed -r "s/(.+)\t(.+)\t(.+)/\1 \2\n \3/"`

Results in the output I want, which is: 

`this is some website title`
`https://somewebsite.com`

I'll close this as this is not an issue with rofi and more a reflection of my s**t programming.
