### ISSUE TITLE
parse-hosts option core dumped

### ISSUE THREAD

**Issue by deviantfero** [davatorium/rofi#984]
## Version

1.5.3

## Configuration

[pastebin](https://pastebin.com/hL3sx69m)

## Launch Command

rofi -show run -parse-hosts

## Steps to reproduce

* enable host parsing
* try to use rofi

## What behaviour you see

* [1]    7531 segmentation fault (core dumped)  rofi -show run -parse-hosts

## What behaviour you expect to see

* normal rofi run

**Comment by DaveDavenport** [comment]
duplicate of: #981, #980

**Comment by DaveDavenport** [comment]
Please update to 1.5.4, this release should have fixed the issue.
