### ISSUE TITLE
1.5.4 tarball

### ISSUE THREAD

**Issue by jubalh** [davatorium/rofi#986]
Seems like for 1.5.4 you did not upload the usual manually prepared .xz tarball. So there is only the .gz one with still needs autoreconf etc to run.

**Comment by DaveDavenport** [comment]
I did upload them:
![image](https://user-images.githubusercontent.com/406245/60436608-ae572c80-9c0c-11e9-8f8d-06b188a412b0.png)
but apparently github failed somewhere.

Will try to re-add them.

**Comment by DaveDavenport** [comment]
added again, hopefully they stick around.

**Comment by jubalh** [comment]
Worked. Thanks.
