### ISSUE TITLE
Interactive feedback during filtering

### ISSUE THREAD

**Issue by SicariusNoctis** [davatorium/rofi#987]
It would be nice to enable some way to have bidirectional communication between rofi and a script.

```bash
rofi -on_filter_query_changed script.sh
```

Then, `rofi` calls `script.sh` with its current search filter query each time there is a change in text. For instance, if the user types `"Hello!"` into the search filter bar, the following calls should be made:

```bash
script.sh "H" | rofi -dmenu
script.sh "He" | rofi -dmenu
script.sh "Hel" | rofi -dmenu
script.sh "Hell" | rofi -dmenu
script.sh "Hello" | rofi -dmenu
script.sh "Hello!" | rofi -dmenu
```

...except that the same `rofi` instance is maintained, of course.

**Motivation:** to allow the user to implement their own custom matching algorithms which account for what was typed in the search filter. There are cases (e.g. file-search) where the built-in matching algorithms aren't as intelligent as they could be.

**Comment by DaveDavenport** [comment]
closing.  was not updated with missing information.
