### ISSUE TITLE
merge run/window commands into a single command

### ISSUE THREAD

**Issue by pstephenwille** [davatorium/rofi#988]
## Version

Output of `rofi -v`
Version: 1.5.0

## Configuration

Output of `rofi -help` (in a [gist](https://gist.github.com/))
https://gist.github.com/pstephenwille/19f27cde86dfc443b9b797f203a69219

## Launch Command
rofi -show

## Steps to reproduce

* Step 1 `rofi -show run`
* Step 2 `rofi -show window`

## What behaviour you see

* - apps get focus or launch

## What behaviour you expect to see

* -  I'd like to see those commands merged into a single command.  If the app is already open, focus it's window, else launch a new instance.

**Comment by DaveDavenport** [comment]
This feature already exists. See combi mode
