### ISSUE TITLE
very difficult and inconsistent to call from i3

### ISSUE THREAD

**Issue by Araly** [davatorium/rofi#992]
## Version

Output of `rofi -v`

`Version: 1.5.3`

## Configuration

Output of `rofi -help` (in a [gist](https://gist.github.com/))
https://gist.github.com/Araly/5fae29a6aca003238413a8489acf21c9

## Launch Command

`bindsym $mod+d exec rofi -show run -font "Tamzen 16"`

## Steps to reproduce

From i3, with the command above, press the combination of keys mod (Super) and D

## What behaviour you see

rofi doesn't pop up, nothing happens, unless sometimes if I press several times, or if I stay pushed on the keys, with no apparent regularity

## What behaviour you expect to see

rofi pops up in reasonable time, consistently.

when called from the terminal, rofi behaves as expected, the issue only seems tied to i3, only with rofi. the combination itself doesn't matter, I tried several. I tried using just `rofi -show run` as a command and it doesn't change a thing. I can't find a process with "rofi" in it. if I enter the command wrong, `rofi -show ren` for example, rofi pops right out, with the expected error. I tried showing the mode "window" too, behaves as "run"

**Comment by sardemff7** [comment]
The problem can come from i3 or from your env being different between the two. Did you try the `drun` modi too?

**Comment by DaveDavenport** [comment]
Does it work more reliable if you apply the i3 hint from the manpage?

>## i3                                                                                                                   
>                                                                                                                        
>In [i3](http://i3wm.org/) you want to bind **rofi** to be launched on key release. Otherwise, it cannot >grab the keyboard.
>See also the i3 [manual](http://i3wm.org/docs/userguide.html):                                                          
 >                                                                                                                       
>Some tools (such as import or xdotool) might be unable to run upon a KeyPress event, because the keyboard/pointer is    
>still grabbed. For these situations, the `--release` flag can be used, as it will execute the command after the keys have 
>been released.

**Comment by Araly** [comment]
`bindsym --release $mod+d exec rofi -show run -font "Tamzen 16"`

behaves the same, but I have to release the key to hope having rofi pop out, if I keep it pressed long enough it works, or at least it did, and now that I'm writing this I can't seem to get it to work anymore ^^ Oh actually I hod rofi pop right now. you get the idoa

drun mode behaves exactly the same as all other modes

**Comment by DaveDavenport** [comment]
I use i3 on many machines daily. Never experience this.
What i3 version?

**Comment by Araly** [comment]
i3 version 4.16.1 (2019-01-27) © 2009 Michael Stapelberg and contributors

okay, so I found what is causing this. I use optimus manager to turn my GPU on and off on my laptop. If I'm on nvidia mode, rofi called by i3 is drunk. if I'm on intel mode, no issues, everything works fine.

I have no idea why though, again, if called form the terminal even in nvidia mode, everything is nice

**Comment by DaveDavenport** [comment]
Any new information on this?

**Comment by Araly** [comment]
I'm using rofi as a drun again, sometimes it's slow to start but it starts. I don't know what changed between when it worked and when it didn't work, and with how it works again. will let you know if I get the issue again

**Comment by DaveDavenport** [comment]
thanks for reporting back. will close for now.
