### ISSUE TITLE
#element vertical-align acts differently on last item

### ISSUE THREAD

**Issue by SevereOverfl0w** [davatorium/rofi#993]
## Version

Output of `rofi -v`: 1.5.2-dev (my package manager indicates that this is 1.5.3? Bit confused about this! I tried building 1.5.4, but hit an error that `src/git-version.c` does not exist as part of the meson build https://github.com/davatorium/rofi/compare/1.5.3...1.5.4 leads me to think 1.5.4 will exhibit the same behavior though)

## Configuration

Output of `rofi -help` https://gist.github.com/SevereOverfl0w/de49ed0ce10adb1b596bcfa160d293c9

## Launch Command

The commandline used to launch **rofi**: `echo '1|2|3' | rofi -sep '|' -theme ~/rofi-simplemenu.rasi -dmenu`

## Steps to reproduce

* Create `~/rofi-simplemenu.rasi` with:
  ```
  #element {
    vertical-align: 0.5;
  }
  ```
* Run `echo '1|2|3' | rofi -sep '|' -theme ~/src/gitlab.com/japorized/dotfiles/dotfiles/config/rofi/theme/rofi-simplemenu.rasi -dmenu`

## What behaviour you see

* Last item is vertically scrolled too far upwards and is half cut off.

## What behaviour you expect to see

* Last item is aligned the same as other items.

**Comment by DaveDavenport** [comment]
Interesting bug. can reproduce with 1.5.4.

**Comment by DaveDavenport** [comment]
Found it out..  its obvious :-D

```
echo "1|2|3"  
```

3 has a newline after it.
So the textual height of the last line is 2 heigh.  so with vertical-align: 1.0 you are aligning on the second line. with 0.5 between the 2 lines.

do:

```
echo -n '1|2|3'
```
to fix.

**Comment by SevereOverfl0w** [comment]
Haha, good catch. Thanks a lot!
