### ISSUE TITLE
Window selection only works sporadically in combi mode

### ISSUE THREAD

**Issue by telmich** [davatorium/rofi#995]
## Version

[14:35] line:~% rofi -v
Version: 1.5.1

## Configuration

Called from i3 via:

bindsym $mod+a exec "rofi -combi-modi run,window,ssh -show combi -modi combi -matching fuzzy -levenshtein-sort"

No other config

## Launch Command

rofi -combi-modi run,window,ssh -show combi -modi combi -matching fuzzy -levenshtein-sort

## Steps to reproduce

Launch, hit !w, select window. In 10% of the cases it switches to the window selected and in 90% it doesn't.

In pure window mode, it always works

## What behaviour you see

see above

## What behaviour you expect to see

Always switching to selected window

**Comment by DaveDavenport** [comment]
What window manager do you use?

**Comment by telmich** [comment]
It's i3:

```
[17:35] line:~% i3 --version
i3 version 4.16.1 (2019-01-27) © 2009 Michael Stapelberg and contributors
```

**Comment by DaveDavenport** [comment]
I3 works fine here.
But I am on an older version.. will try newer version.

**Comment by telmich** [comment]
Let me know if I can enable some debug in rofi &| attach an strace or similar

**Comment by DaveDavenport** [comment]
Is this still an issue?  For me its been working fine with latest rofi and i3.

**Comment by DaveDavenport** [comment]
please leave a note if still an issue.
