### ISSUE TITLE
Rofi not working proper with sidetab themes

### ISSUE THREAD

**Issue by TheStutterNerd** [davatorium/rofi#996]
## Version 

Output of `rofi -v`
1.5.4

## Configuration

Output of `rofi -help` (in a [gist](https://gist.github.com/))
https://gist.github.com/TheStutterNerd/6054516ea0de8c81427d47004199ca55

## Launch Command

The commandline used to launch **rofi**
rofi -show run

## Steps to reproduce

* Step 1
Keybinding for Alt+R or executing rofi -show run
* Step 2
None, just a problem with sidetab themes

## What behaviour you see

* - Its been working ace for over a year up until maybe these past 2 updates which now only shows 6 lines then theres a massive gap which is usually filled up- all other features still work fine such as opening software or cycling through the list aside from the layout issue which won't allow it to show the list to the bottom of the window.
Since editing the .rasi file and disabling and re-enabling the sidebar-mode- the sidebar doesn't seem to work proper. It's not got any of the options on the bottom like it used to do and looks exactly the same when set to false, no change happening.

## What behaviour you expect to see

* - Normal behaviour would be- the window list expands right down to the bottom of the window showing about 20 lines instead of only 6/having a massive gap. Also the sidebar used to show the names of which mode is selected which it doesn't do anymore either.

**Comment by dannycolin** [comment]
Could you also share your theme please.

**Comment by TheStutterNerd** [comment]
Had to rename from .rasi to .txt because github doesn't support the file type but sure!
[sidetab.txt](https://github.com/davatorium/rofi/files/3407533/sidetab.txt)
[sidetab-red.txt](https://github.com/davatorium/rofi/files/3407534/sidetab-red.txt)

**Comment by dannycolin** [comment]
You need to change _sidebar_ to _mode-switcher_ (line 57 in `sidebar-red.rasi`). It should looks like:

```
mainbox {
	spacing:  0.8em;
	children: [ entry,listview,mode-switcher ];
}
```

If you don't want to show the modes at the bottom, you can remove _mode_switcher_ completely.

**Comment by TheStutterNerd** [comment]
Ah yeah thats sorted it, spot on! Cheers for the help buddy.

**Comment by DaveDavenport** [comment]
Duplicate: #990 & see release notes: [here](https://github.com/davatorium/rofi/releases/tag/1.5.3)
