### ISSUE TITLE
Combi mode including run mode does not run new commands

### ISSUE THREAD

**Issue by tbrodbeck** [davatorium/rofi#998]
## Version
```
➜  ~ rofi -v
Version: 1.5.3
```

## Configuration
https://gist.github.com/tbrodbeck/9f3ed109ac94e7b086b13326fb09526b

## Steps to reproduce

* Step 1
`rofi -combi-modi window,drun,run -show combi`
* Step 2
Run a command that is not in the list. E.g (in my case): `notify-send test`

## What behaviour you see 
It will not do anything. This is unexpected, because it includes the run mode.
This would be really useful for me, since I want to search the web from rofi.

## What you want to see
Just like using the 
`rofi -show run`
option it should be able to run commands.

**Comment by sardemff7** [comment]
It can, but rofi cannot guess that you want to run a command, rofi is a filter. For it to work, maybe the `accept-custom` binding would work, not sure. However, adding a `!r` bang at the start of your command will work, as it’d tell rofi to use the run mode to process your input.

**Comment by tbrodbeck** [comment]
That's it? Now it's closed? I still think this would be a nice feature

**Comment by DaveDavenport** [comment]
I thought @sardemff7 clearly described why it works the way it does.
Again, rofi combi  mode *cannot* guess what you intent todo , so you need to specify what mode should handle the 'custom' input.

I don't want to bind a *default* action. as this will be different for everybody.

**Comment by tbrodbeck** [comment]
Isn't it obvious how the custom input should be executed? I could understand that argument if there was a conflict, but `run` and `drun` run the command and `window `does not execute custom inputs at all. So there is no conflict in this case and the command can simply be executed like `run` and `drun` promise.

**Comment by DaveDavenport** [comment]
There is more then run,drun and window going around.
What if you also have ssh in there?

**Comment by tbrodbeck** [comment]
I would not mind if it's disabled in case of conflict, or a nice solution would be to take the first named mode in the command. 
The thing right now is: 
Rofi becomes less powerful when used in combi mode, while intuitively the features of one mode should be a subset of the features of the combi mode

**Comment by DaveDavenport** [comment]
Again, combi mode (in the current implementation) , is not capable of knowing there is an conflict or even know who can execute it.

If we somehow made this information available, we need to handle this in a logic and consistent way. Disabling when there are more then one capable might not be logic. (could be solved with an error message)

But to be honest this feels like a lot change for minimal gain. I don't see this 'diminished' power when you can just simple add !r (for run) or !s (for ssh) to have it executed that way. 

If this issue gets lot of upvotes I might re-consider. (Good ) Patches are also welcome.

**Comment by danjenson** [comment]
A simple fix might be to have an opted-in default? `--combi-default-action {run,ssh,...}`, which you can set. On execution, it checks if there is a default and if so uses that to try to execute the arguments. I find this super useful because I wrote a script that allows me to type stuff like `chrome 3` and it will fuzzy match the `google-chrome-stable` binary and then run `bsprc desktop -f ^3 && google-chrome-stable`. It would be awesome to just run `chrome 3` instead of `!r chrome 3` in rofi and hand it off to this script running via `-run-command`.

**Comment by sardemff7** [comment]
Please file a new issue, or better yet, an MR directly, and not comment on an old issue where your idea will get lost.
